### ISSUE TITLE
Webanno not reading settings.properties in Ubuntu 16.04

### ISSUE THREAD

**Issue by jintrone** [webanno/webanno#1002]
I configured my installation, running via the embedded server.  Webanno runs fine, either using java -jar or as a service.  However, I cannot seem to get webanno to use my mysql DB, and I've no indication that it is actually reading the settings file or webanno.conf.  I've set the owner (as suggested) on webanno.conf to root, but this doesn't help. 

I do have a valid mysql install, with the user specified in the settings.properties; I've verified the credentials by connecting in via the console.

Here are the contents of /srv/webanno:

```
drwxr-xr-x 2 www-data root          4096 Jun 19 15:21 .
drwxr-xr-x 3 root     root          4096 Jun 14 12:54 ..
-rw-r--r-- 1 www-data root           337 Jun 14 12:55 settings.properties
-rw-r--r-- 1 root     root            84 Jun 14 12:58 webanno.conf
-rw-r--r-- 1 www-data www-data 102482336 Jun  4 13:45 webanno.jar
-rwxr-xr-x 1 www-data www-data      1061 Jun 19 15:21 webanno.sh
```
And this is what I see when I start (using java -jar):

```
  _      __    __   ___                
 | | /| / /__ / /  / _ | ___  ___  ___ 
 | |/ |/ / -_) _ \/ __ |/ _ \/ _ \/ _ \
 |__/|__/\__/_.__/_/ |_/_//_/_//_/\___/
3.4.2 (2018-06-04 19:36:56, build 756461b3251e8cfd7a086464cdc8a560479852c2)

2018-06-19 15:31:22 INFO [SYSTEM] WebAnnoApplicationContextInitializer - Authentication: database
2018-06-19 15:31:22 INFO [SYSTEM] WebAnno - Starting WebAnno on cognosis with PID 6584 (/srv/webanno/webanno.jar started by <snip> in /srv/webanno)
2018-06-19 15:31:22 INFO [SYSTEM] WebAnno - The following profiles are active: auto-mode-builtin
2018-06-19 15:32:17 INFO [SYSTEM] DocumentServiceImpl - Document repository path: <snip>/.webanno/repository
2018-06-19 15:32:20 INFO [SYSTEM] DatabaseInfoService - Database dialect: org.hibernate.dialect.HSQLDialect
2018-06-19 15:32:20 INFO [SYSTEM] DatabaseInfoService - Database driver: org.hsqldb.jdbc.JDBCDriver
2018-06-19 15:32:20 INFO [SYSTEM] DatabaseInfoService - Database URL: jdbc:hsqldb:file:<snip>/.webanno/db/webanno;hsqldb.default_table_type=cached
2018-06-19 15:32:20 INFO [SYSTEM] DatabaseInfoService - Database username: sa
```
I'm trying to set this up for my research team; I'd be very grateful for any assistance.

**Comment by reckart** [comment]
The `webanno.conf` file is read only when you let UNIX service manager run WebAnno via the startup script that is embedded in the JAR file (cf. https://webanno.github.io/webanno/releases/3.4.3/docs/admin-guide.html#_installing_webanno_as_a_service)

If you run WebAnno manually from the command line, then you need to tell it where it can find the settings.properties file, e.g.

```
java -jar webanno.jar -Dwebanno.home=/srv/webanno
```

I would recommend to use the service manager to run WebAnno.

**Comment by jintrone** [comment]
Thanks for the rapid reply!  I have been using the service manager as well, and encountered the same problem. It turns out (at least in my environment) that the -Dwebanno.home=/src/webanno is required in my service script.

Also note that properties must be passed before the -jar flag, or else they are interpreted as command line parameters.

Seems like I’m up and running now.

Thanks!


On Jun 19, 2018, at 3:45 PM, Richard Eckart de Castilho <notifications@github.com<mailto:notifications@github.com>> wrote:


The webanno.conf file is read only when you let UNIX service manager run WebAnno via the startup script that is embedded in the JAR file (cf. https://webanno.github.io/webanno/releases/3.4.3/docs/admin-guide.html#_installing_webanno_as_a_service<https://urldefense.proofpoint.com/v2/url?u=https-3A__webanno.github.io_webanno_releases_3.4.3_docs_admin-2Dguide.html-23-5Finstalling-5Fwebanno-5Fas-5Fa-5Fservice&d=DwMFaQ&c=nE__W8dFE-shTxStwXtp0A&r=NT-zDZBmNZOHIUuE1uJVSw&m=cFPjO8P23EAPEhpL1cZwU9KwYlNjmIMZgRGmHIMZVA0&s=Z0-ABjArJrLJyTbmOw59b9XMpF2YBaVPHN8e5vhMi0U&e=>)

If you run WebAnno manually from the command line, then you need to tell it where it can find the settings.properties file, e.g.

java -jar webanno.jar -Dwebanno.home=/srv/webanno


I would recommend to use the service manager to run WebAnno.

**Comment by reckart** [comment]
Great that it works for you now. I have updated my comment from before moving the `-jar` to the end.
