### ISSUE TITLE
[UX] Document status table really small on Monitoring page

### ISSUE THREAD

**Issue by j-lnaddef** [webanno/webanno#1009]
On an automation project with a lot of users, the Document status panel is extremely small. Would be nice to have to option to hide the _Features_ and _Training results /status_ panels in order to have more space to check the document status panel.

**Comment by reckart** [comment]
INCEpTION has a completely new, faster and more powerful workload management page. It also supports different workflow modes. A static mode that resembles largely the old monitoring page and a dynamic mode which is more suitable for crowd-sourcing-like scenarios.
