### ISSUE TITLE
view for bigger span relations by arcs

### ISSUE THREAD

**Issue by kleinias** [webanno/webanno#1020]
Hello,

I'm doing some annotating for wider spans and the kind of arcs between the lines is disturbing. 

![auswahl_014](https://user-images.githubusercontent.com/33533067/42524636-6c355556-8471-11e8-9874-6a305d709887.png)

It would be great, if one could overlook this more by direct arcs and textwrap in the window, then by forcing them between the lines.

**Comment by reckart** [comment]
INCEpTION supports a **brat (wrap at 120 chars)** visualization mode which removes the problem with the long lines. It also has the option of collapsing arcs with the same label in brat modes to clean up the view a little. Additionally, there are alternative editors such as the [Recogito Editor Plugin](https://github.com/inception-project/inception-recogito-editor-plugin) which could be used in cases where long spans are annotated and need to be connected using relations.
