### ISSUE TITLE
Named Entities not exported in CoNLL format

### ISSUE THREAD

**Issue by j-lnaddef** [webanno/webanno#1021]
Title says it all. I try to export a file with some Named Entities.

Exporting it in TSV works fine
```
1-1	0-4	This	ORGpart	
1-2	5-7	is	_	
1-3	8-9	a	_	
1-4	10-16	simple	LOCderiv	
1-5	17-21	test	_	
```

But CoNLL not (below is CoNLL 2000, but none of them work)
```
This _ O
is _ O
a _ O
simple _ O
test _ O
```

**Comment by reckart** [comment]
Are you using the built-in named entity layer or a custom one?

**Comment by j-lnaddef** [comment]
Built-in

**Comment by reckart** [comment]
Which version of WebAnno are you using?

**Comment by j-lnaddef** [comment]
3.4.5

**Comment by reckart** [comment]
CoNLL 2000 writes chunks. For named entities, you'd have to use the CoNLL 2002. Did you test that?

**Comment by reckart** [comment]
CoNLL 2003 should also work (NE + Chunks).

**Comment by j-lnaddef** [comment]
Guess what, I checked them all but the 2002, don't know why I assumed CoNLL2006+ would be extension from 2002. My bad, thank you!

**Comment by reckart** [comment]
**phew!** I almost thought something would be awfully broken :)
