### ISSUE TITLE
Faulty Imports

### ISSUE THREAD

**Issue by Tshimanga** [webanno/webanno#1023]
Hoping this issue is just my own ignorance.

I am entertaining usage of webanno for a project but in testing I ran into a situation where importing the document was supposedly successful; however, when going to actually view and annotate the document, the majority of it was missing. Any special considerations I need to be aware of when importing documents?

**Comment by reckart** [comment]
What kind of document? Are you aware that WebAnno only shows a configurable number of sentences when you enter the annotation screen and that you need to use the buttons in the action bar to navigate between document "pages"?

**Comment by Tshimanga** [comment]
Just a .txt file though there are quite a few escaped characters like `\n` and `\u2022`.

I actually was not aware of the 5 sentence limit. In regards to that, it looks like it implements a rather naive sentence parser that pretty much just splits on periods. For instance,  " ....  Dr. SoAndSo ..." is getting split on the period in "Dr."

Is there a way to disable the sentence splitter?

**Comment by reckart** [comment]
Depending on the WebAnno version you are using, there is a format called "Plain text (line-oriented) (experimental)". It essentially treats every line in the source file as a sentence. So if you can somehow make sure that in your input, every line corresponds to one sentence, then that format is good for you.

**Comment by reckart** [comment]
Use the "settings" from the action bar to configure the number of sentence visible at a time.

**Comment by Tshimanga** [comment]
Mmmm I'm currently playing with the 3.4.5 standalone.

Actually I just need WebAnno to capture offsets for various context scopes (negations, speculations, etc.) so it doesn't quite so much matter to me if the UI can tell where sentences begin and end.

What I ultimately do need, however, is the ability to import and export to and from .json files. I noticed a bunch of (seemingly) custom formats but no json.

Ideally being able to generate files with objects that look like 
````
{text:"example excerpts go here and not anywhere else",
 contexts:[negations:[{begin:33,end:46}],
                speculation:[],
                .
                .
               ]
}
````

Is this possible with WebAnno?

**Comment by reckart** [comment]
JSON is just the "modern" XML - it doesn't really mean anything. 

If you like a format good for machine-processing, UIMA CAS XMI (an XML dialect) should be your friend. However, you'd have to write some code to convert it to whatever JSON format you like. You can process it "by foot" with a custom XML parser, or use the Java UIMA SDK to load and transform it if you are a Java person, or try [PyCAS](https://github.com/dkpro/dkpro-pycas) if you are a Python person.

If you are more a friend of "human readable" (yet machine processable) formats, then [WebAnno TSV](https://webanno.github.io/webanno/releases/3.4.5/docs/user-guide.html#sect_webannotsv) is for you.

**Comment by Tshimanga** [comment]
Ah okay! Well, thanks for your help! I appreciate the quick responses.
