### ISSUE TITLE
Upgrade to recent MySQL driver or MariaDB driver

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#1026]
To allow using WebAnno with recent MySQL/MariaDB versions, the bundled driver should be updated to 

```
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>8.0.11</version>
</dependency>
```

or

```
<dependency>
    <groupId>org.mariadb.jdbc</groupId>
    <artifactId>mariadb-java-client</artifactId>
    <version>2.2.6</version>
</dependency>
```

**Comment by reckart** [comment]
Sticking with MySQL for the time being.

**Comment by seyyaw** [comment]
I need to append  `useLegacyDatetimeCode=false&serverTimezone=UTC` to the `database.url` in the `settings.properties` file for WebAnno to start with MySQL 5.7.22

Is there any setting other than this?

**Comment by reckart** [comment]
@seyyaw Looks indeed as if the new JDBC driver is picky about server timezone settings. Apparently, the problem can also be solved be properly configuring the server timezone in the MySQL server itself and that is probably preferable.

I'm not aware at this time of other settings that would need to be adjusted.

Any reason to keep this issue open?

**Comment by reckart** [comment]
I suppose it would probably be a good idea to adjust the `docker-compose.yml` file to either configure the MySQL server timezone or add some timezone parameter on  the JDBC string.

**Comment by seyyaw** [comment]
Well, I prefer to have the serverTimezone information in the `settings.properties` file than depending on the MySQL configuration.
