### ISSUE TITLE
Repeat Annotation very slow

### ISSUE THREAD

**Issue by j-lnaddef** [webanno/webanno#1029]
I have an automation project containing about 100 documents of about 4 sentences each, which does not seem to be excessive. 
Manually adding a tag takes **more than 10 seconds**. 
Investigation shows the culprit is the `AutomationUtil.repeateSpanAnnotation` method, which parses all documents in search of other occurences of the selected text in order to pre-tag them.

As it is, I am forced to uncheck the "Repeat annotation" option in the project settings, but it is a shame as it is a really helpful functionnality.

Is there any plan to improve performances of this method?
For now I can think of 2 possible improvements : 
- Multi-threading as I believe all other documents could be searched in parallel
- Indexing occurences of words in the different documents to improve the search efficency (would require some pre-processing when application starts or when documents are added or removed)

**Comment by reckart** [comment]
@j-lnaddef If you are only doing span annotations (or at least only need automation for span annotations) and if you don't make use of pre-annotated data for bootstrapping automation, you might try to give the "recommenders" in [INCEpTION](https://inception-project.github.io) a spin. They do their training and predictions asynchronously and should not be slowing you down so much. Mind that INCEpTION is still under heavy development at this point and you may experience it to be less stable than WebAnno.

**Comment by j-lnaddef** [comment]
Now that you mention it, having the "repeat annotation" done asynchronously seems like a nice solution too. Anything stopping you from doing so in Webanno?

**Comment by reckart** [comment]
@j-lnaddef I'm not maintaining automation support in WebAnno.

**Comment by j-lnaddef** [comment]
@reckart Oh I did not know, sorry to hear that.

FYI I got a big performance boost by indexing word occurences in all documents. This way I do not have to parse all documents and all sentences, I can directly check at the relevant positions and update if the substrings match. Now tagging a span takes less than 3 seconds, to compare with about 15 seconds before.

**Comment by seyyaw** [comment]
Hi @j-lnaddef 
I can see a quick fix by having a configuration to have `repeat annotation` either in all documents in the project or only current document. 

Can you also contribute your implementation based on indexing?

Thanks

**Comment by j-lnaddef** [comment]
What I did is way too hacky for a PR but I can give you the outlines of my implementation if someone feels like integrating it in a clean way.

So the bottleneck in `repeateSpanAnnotation` is the search for occurences of the selected text in other documents, which is done by searching through all sentences of all documents and doing a character by character comparison on a sliding window. The idea is to keep track of occurences of each word in the different documents in order to avoid wasting time during the search.

In `AutomationUtil` I keep a `private static Map<Project, Map<String, Map<SourceDocument, List<Integer>>>> wordOccurences = new HashMap<>();` : for each project, I list each word, the documents in which they appear, and the list of positions in those documents.

This map needs to be initialized at some point. Now I am initializing it the first time I call `repeateSpanAnnotation`, and it takes about 15 seconds for the 100 documents in my project.

```
private static void initIndexes(AnnotatorState aState, DocumentService aDocumentService, 			 
                CorrectionDocumentService aCorrectionDocumentService, AnnotationSchemaService aAnnotationService)
		throws UIMAException, ClassNotFoundException, IOException, AnnotationException {
	for (SourceDocument d : aDocumentService.listSourceDocuments(aState.getProject())) {
		loadDocument(d, aAnnotationService, aDocumentService, aCorrectionDocumentService, aState.getUser());
		JCas jCas = aCorrectionDocumentService.readCorrectionCas(d);
		Map<String, Map<SourceDocument, List<Integer>>> projectWordOccurences = wordOccurences.get(aState.getProject());
		for (Sentence sentence : select(jCas, Sentence.class)) {
			int index = sentence.getBegin();
			String sentenceText = sentence.getCoveredText().toLowerCase();
			StringTokenizer st = new StringTokenizer(sentenceText, " \t\r\n.,:;!?\"()", true);
			while (st.hasMoreTokens()) {
				String nextToken = st.nextToken();
				if (!" \t\r\n.,:;!?\"()".contains(nextToken)) {
					if (projectWordOccurences.get(nextToken) == null) {
						projectWordOccurences.put(nextToken, new HashMap<SourceDocument, List<Integer>>());
					}
					if (projectWordOccurences.get(nextToken).get(d) == null) {
						projectWordOccurences.get(nextToken).put(d, new ArrayList<Integer>());
					}
					projectWordOccurences.get(nextToken).get(d).add(index);
				}
				index += nextToken.length();
			}
		}
	}
}
```

The map also needs to be updated whenever you add or remove a document in a project.

Then in `repeateSpanAnnotation`, I can just jump directly to the relevant documents and positions instead of having to parse the whole documents : 

```
for (SourceDocument d : wordOccurences.get(aState.getProject()).get(selectedTextFirstToken).keySet()) {
	loadDocument(d, aAnnotationService, aDocumentService, aCorrectionDocumentService, aState.getUser());
	JCas jCas = aCorrectionDocumentService.readCorrectionCas(d);
	List<Integer> indexes = wordOccurences.get(aState.getProject()).get(selectedTextFirstToken).get(d);
	for (Integer index : indexes) {
		for (Sentence sentence : select(jCas, Sentence.class)) {
			int begin = sentence.getBegin();
			int end = sentence.getEnd();
			if (begin <= index.intValue() && end >= index.intValue()) {
				if (end < index.intValue() + selectedText.length())
				{
					break;
				}
				String sentenceText = sentence.getCoveredText().toLowerCase();
				if (sentenceText.substring(index.intValue() - begin, index.intValue() - begin + selectedText.length()).equals(selectedText)) {
					int addr = adapter.add(aState, jCas, index.intValue(),
							index.intValue() + selectedText.length());
					adapter.setFeatureValue(aState, jCas, addr, aFeature, aValue);
				}
				break;
			}
		}
	}
	aCorrectionDocumentService.writeCorrectionCas(jCas, d);
}
```

I am pretty sure this in itself can be optimized in many ways, but it already provides a huge performance boost as far as I could observe.

**Comment by seyyaw** [comment]
Dear @j-lnaddef thanks for sharing your implementation.
Once I have time, I will test and  update the AutomationUtil code. I will also include the option to have repeating per current document than the whole documents in the project.

Thanks agian

Seid M.

**Comment by reckart** [comment]
WebAnno is no longer developed and the successor INCEpTION has a completely new recommender subsystem to which this issue no longer applies.
