### ISSUE TITLE
Long-ranging relations

### ISSUE THREAD

**Issue by gpythomas** [webanno/webanno#1030]
I love webanno but I have a lot of trouble creating relations by dragging the mouse when more than 50 sentences separate the related spans. I have texts with more than 100 sentences separating coreferring expressions, and the interface doesn't handle well the scrolling down while dragging the mouse. Would it be possible to add another way to create relations (something like control click on a first mention and control click again on a second mention, or some other combination of key plus mouse click). My apologies if there already is such a function and I missed it in the docs.

**Comment by seyyaw** [comment]
@reckart We definitely need to test this one functionality. But I think need to keep also the old drag-and-drop functionality along side this new approach.

**Comment by gpythomas** [comment]
Yes, the button idea sounds like it would solve my issues. I also agree that it would be nice to keep the drag-and-drop option.

**Comment by reckart** [comment]
@seyyaw of course the drag-n-drop way should be kept - it works nicely for short-distance relations. I would expect the button to be used for primarily for long-distance relations.
