### ISSUE TITLE
Previous slot constraints remain active when removed or updated

### ISSUE THREAD

**Issue by GillesJ** [webanno/webanno#1034]
Problem:
When using [constraints for slot features](https://webanno.github.io/webanno/releases/3.4.5/docs/user-guide.html#_constraints_for_slot_features), previously loaded constraints remain active even after being removed or when loading in new constraints.

Upon making a MWE, I noticed it could be a wider problem: new slot constraints are not renewed across all projects. I tried on two different projects, the one I was prototyping constraints in and then a previous project version for testing the MWE for this issue below. The slot constraints are not loaded whether I use special operator `(!)` or not. 

Constraints on my `Primitive:String` tagset features work because they are loaded and renewed. the issue seems isolated to slot constraints.

The error happened after I tried to upload a constraints file that caused a redirect to the **Internal Error** page (Not a warning or invalid syntax parsing error). I removed that file and uploaded a previous simplified constraints file that was definitely valid. I am not sure if this was the cause.

No error is thrown by the interface (other than the Internal Error page upon uploading a file).
CAS doctor is not showing any problems.

**Expected outcome:**
Loading or removing slot constraints from a new file causes slot constraints to be updated and removed.

**Sysinfo:**
WebAnno 3.4.5. stable on Ubuntu 16.04 with embedded DB.

**MWE:**
**Note:** testing constraints files possible broke constraint loading across projects for me. It is possible this simplified instance did not cause the problem.
- use the slot feature by making two span layers (e.g., `Event` and `Participant`) and make a `Link:Participant` feature with `ParticipantTagset` for participant role types. make a `Primitive:String` feature with a kind tagset called `Type` on `Event` for event typing.
- load in constraints file in **Constraints** tab:
```
import webanno.custom.Event as Event;

Event {
  // TypeOne rules
  TypeEvent="TypeOne" ->
    Participant="ParticipantOne" (!) | Participant="ParticipantTwo" (!);
}
```
- Remove constraint file from project.
- Annotation still has the slot constraints active.

Reloading a new constraints file does not work either and previous defaults remain:
- remove old constraint file and load in constraints file in **Constraints** tab:
```
import webanno.custom.Event as Event;

Event {
  // TypeOne rules
  TypeEvent="TypeOne" ->
    Participant="ParticipantOne" (!);
}
```
- `ParticipantTwo` is still active as a default role.

**Comment by GillesJ** [comment]
It started working again as it should if I use the ".role" attribute in the rule set for slot constraints.
I didn't realize this was required syntax. Mea culpa.

MWE:
```
import webanno.custom.Event as Event;

Event {
  // TypeOne rules
  TypeEvent="TypeOne" ->
    Participant**.role**="ParticipantOne" (!) | Participant**.role**="ParticipantTwo" (!);
}
```

Problem solved!

**Comment by reckart** [comment]
@GillesJ I got a comment mail that you got the problem solved, but the comment seems to have been deleted?

**Comment by GillesJ** [comment]
I deleted the previous comment because I encountered an issue that is related so I didn't think it was solved, but after further testing it is unrelated to OP and due to commenting in constraints file. (I'll open a new issue for that one.)

Regarding OP: It is no longer a problem when using the ".role" attribute on the feature in the conditional side of the rule:

```
import webanno.custom.Event as Event;

Event {
  // TypeOne rules
  TypeEvent="TypeOne" ->
    Participant.role="ParticipantOne" (!) | Participant.role="ParticipantTwo" (!);
}

```

**Comment by reckart** [comment]
> The error happened after I tried to upload a constraints file that caused a redirect to the Internal Error page (Not a warning or invalid syntax parsing error).

In most cases, you should be able to find a stack trace related to the problem in the log file. Alternatively, you could add the line `debug.showExceptionPage=true` to the `settings.properties` file and restart WebAnno to get a stack trace shown in the browser.

Do your tagset actually contain the tags `ParticipantOne` and `ParticipantTwo`?

**Comment by reckart** [comment]
What's a "MWE" in this context?

**Comment by GillesJ** [comment]
Thank you, I will look at the log and enable in-browser log output.

A MWE is a Minimal Working Example (or in this case not working 😉) to reproduce the problem.

Yes, the tags are in the tagset and on the feature.

**Comment by reckart** [comment]
I gather the problem was the line comment (#1035 , #1036 ) then and the rest was ok.

**Comment by GillesJ** [comment]
@reckart That eliminates the Internal Error hypothesis as that was what caused it.
Can you verify if using the ".role" attribute on a slot feature is necessary for slot constraints to work?
Because the problem of not renewing constraints manifested itself until I loaded a file with .role attribute.
Requiring .role syntax is unlike other features and should probably be made more explicit in the docs.

**Comment by reckart** [comment]
@GillesJ actually, an explicit note about `.role` was added to the documentation a while back when another user stumbled over the same problem, but it turns out this amendment was only added to the master branch, not to the maintenance branch. https://github.com/webanno/webanno/pull/1039 takes care of that now :)
