### ISSUE TITLE
Unable to view imported webanno tsv3 file. Webanno version 3.3

### ISSUE THREAD

**Issue by adindabudi** [webanno/webanno#1045]
I got this error message after I successfully 
`Error: Unable to determine sentences in which the annotation starts/ends: DialogueSpeaker sofa: _InitialView begin: 2926 end: 3493 Speaker: "ADM"`

I've attached the sample of file, the layers and the tagset. 

I've created this file programmatically using python from csv file.

[attachment folder](https://drive.google.com/drive/folders/10bzppABA2_Gh8noInAM-kcY9MmJdXs6l?usp=sharing)

**Comment by reckart** [comment]
@adindabudi Please check that all your tokens are within sentences, that the sentence boundaries match the boundaries of the first and last token in the sentence, and that annotations all start/end either at token boundaries or within tokens, but not at some position between tokens or between sentences.

**Comment by reckart** [comment]
No further feedback - assuming this one has been resolved.
