### ISSUE TITLE
Confirmation popup for delete on layer change does not show up in some cases

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#107]
We have a confirmation popup displaying if the user tries to change the layer of an existing annotation and at least one of the feature values is not empty.

The same popup should also show up when the annotation has any incoming arcs (by relation layer or by slot features).

**Comment by seyyaw** [comment]
For chain and relation annotation, we cannot delete and add another arc annotation (WebAnno do not support multiple arc annotation per span layer). In stead of deleting existing annotation in this case, we clear the selection and change the layer. The user then can annotate any span annotation.
