### ISSUE TITLE
Lock to token is ignored for custom layers

### ISSUE THREAD

**Issue by lauraBaakman** [webanno/webanno#1079]
Trying to select a span of text, smaller than a token, in this layer:
![layer](https://user-images.githubusercontent.com/4301624/47024408-9ea3c080-d12f-11e8-9bc9-f4bf58be124f.png)
still results in the selection of the full token.

**Comment by reckart** [comment]
In the next release, we will have a less confusing and more convenient dropdown menu to choose the annotation granularity :) Cf. https://github.com/webanno/webanno/issues/443
