### ISSUE TITLE
Annotation view inside Curation often does not reflect perfect agreement among annotators

### ISSUE THREAD

**Issue by bustrofedico** [webanno/webanno#1101]
In several cases, while all annotators appear to agree 100% on the annotation, the curator still has to select the annotation manually. Not sure why.
![curation](https://user-images.githubusercontent.com/1271759/48080815-7c5d0a00-e1e6-11e8-967e-17d989e8d1ed.png)

**Comment by bustrofedico** [comment]
There are several issues in the curation part of the tool, possibly related to what reported above.

Something I am struggling with at the moment is that the Annotation pane reports tagging which differs from that of all annotators. I wonder if there is any sort of partial string matching going on. The task is character annotation in fiction and two characters are 'Rita Raco' and 'Sergeant Greg Raco'. The Annotation pane in many cases reports 'Rita Raco' when all annotators agreed on 'Sergeant Greg Raco'.

**Comment by reckart** [comment]
The curation code operates based on layer type, offsets, and feature values - as far as I remember, the actual text of the annotations is not taken into account.

It seems there are indeed some bugs. I still have data from a user lying here since a while waiting for debugging. I'll try to up to prio on this.

**Comment by reckart** [comment]
If you have not yet curated data in the document: could you please check if the agreement remains undetected if you use the "re-merge" button?

**Comment by reckart** [comment]
You might want to export the project as a backup before trying the re-merge.

**Comment by bustrofedico** [comment]
a-ha! That did help a whole lot with both issues, thanks for the suggestion, thank you so much! (I am using your tools extensively, I am likely to report more issues, as I proceed). 

I admit I don't fully understand what re-merge actually does and when I should use it. I am guessing it is generally a good idea to try re-merging when I stumble into issues such as those described in this ticket.

**Comment by bustrofedico** [comment]
Thanks for the explanation, that's exactly what happened. I did start curation way before everyone was done. Re-merging is saving me a ton of time, thanks again for the tip!
