### ISSUE TITLE
Document Export under Windows breaks UTF8

### ISSUE THREAD

**Issue by daxenberger** [webanno/webanno#112]
A document containing non ASCII characters exported as Plain Text (Document > Export) ends up with broken encoding ("??????"). This can be reproduced under Windows with Chrome. Richard suggests this might be related to settings of the servlet container (communication between browser and tomcat).

**Comment by daxenberger** [comment]
WebAnno Version: 2.3.0

**Comment by reckart** [comment]
I have tried exporting a document in Arabic script from a developer instance running on my laptop as well as from our test VM and cannot reproduce the problem.

VM: WebAnno -- 3.0.0-SNAPSHOT (2016-09-19 21:40:09, build 103072c06f24fbcd06bb3155e62fabd0d9a94973)

Local: WebAnno -- 3.0.0-SNAPSHOT (2016-10-08 23:18:09, build 346cefd9e20ae9e15eda456e86a075bed1b5bfb9)

**Comment by reckart** [comment]
Need to re-check because I actually checked on OS X, not Windows....

**Comment by reckart** [comment]
Checked with Chrome 54.0.2840.99 m on Windows 7 against WebAnno 3.0.0-SNAPSHOT (2016-12-05 20:57:52, build a3582fdec85645161196d86fe23209c1619275a9) -- cannot reproduce.
