### ISSUE TITLE
Cannot create users

### ISSUE THREAD

**Issue by rjalexa** [webanno/webanno#1137]
Webanno 3.4.6 standalone Jar on MacOS via Safari.
New installation. ~/.webanno created with embedded database.
Logged in as admin/admin
Created new annotation project.
Imported a couple of text files.
Clicked on users tab.
Only see admin with the admin, curator and user roles.
Click on Add does not produce any visible effect other than the automatic logout time being reset to 30 minutes.
Tried writing a new name (bob) and then clicking add. Tried clicking add without any prior input. Nothing appears. No popup blockers as far as I understand.
Help please. Thank you.

**Comment by rjalexa** [comment]
As I type "bob" the new user I wish to add there's a dropdown appearing but
as expected is empty.
New instance with only the builtin admin/admin user.
Thanks for any clarification.

**Comment by rjalexa** [comment]
Ahhhhj that might be the problem. Will try thank you. :)

**Comment by reckart** [comment]
I'm closing the issue assuming that the answer works for you. If you still have trouble adding users to projects, let me know.
