### ISSUE TITLE
When stacking is not allowed, display messaged when trying to add another annotation of the same layer

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#114]
For annotation types where stacking is not set, new annotation deletes the old annotation. It should preserved the annotation.

**Comment by reckart** [comment]
What do you mean by "it should preserve the annotation"? When the type of an existing annotation is changed, it should be replaced with an annotation of the new type - I do not think it should make a difference if stacking is allowed or not.

**Comment by seyyaw** [comment]
In stead of open existing annotation for new annotation selection, display an error message "Cannot create another annotation of layer X at this location - stacking is not enabled for this layer."

**Comment by mmev** [comment]
I get the following message:

"Cannot create another annotation of layer [Lemma at this location - stacking is not enabled for this layer."

Please close the opened bracket in the message.
