### ISSUE TITLE
Internal Error when importing training target layer file for automation

### ISSUE THREAD

**Issue by zhh210** [webanno/webanno#1143]
In 3.4.6, I was trying to import a file for training in the automation panel. However, regardless of the file format (CoNLL2000 or WebAnno TSV3), I always got the internal error msg. The error ends with logging 

[tomcat-embed-core-8.5.27.jar!/:8.5.27] at java.lang.Thread.run(Thread.java:745)[?:1.8.0_152_release]

**Comment by seyyaw** [comment]
@zhh210 Can you send me or share me the file? My email is yimam@informatik.uni-hamburg.de

**Comment by reckart** [comment]
Closing as there was no further reaction.
