### ISSUE TITLE
add clear button to Editor panel to clear selection

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#116]
Add a "clear" button to clear the existing annotation. The clear button should not change the selected layer type

**Comment by mmev** [comment]
What does "clear" mean? 
Is it the same as "deselect" the currently activated instance?  If yes, I would not call them "clear" but rather "deselect".
Or does it mean that the content (t.i. set features) of the currently annotated (activated) instance should be cleared?

**Comment by mmev** [comment]
I like the "Clear" button -- actually, I still would like to call it "Deselect", but the functionality is appropriate.

(Clear means for me "clear the content" (clearing the instance means for me, clearing its content)
Deselect means for me "deselect the instance" -- and this is the sense the user assume here.
But my english is maybe not appropriate enough.)
