### ISSUE TITLE
No scrollbar in tagset dropdown menu when creating feature

### ISSUE THREAD

**Issue by mssammon** [webanno/webanno#1183]
I am creating custom annotation layers using WebAnno current github release, using 'google-chrome' on ubuntu 16.04. I have about 20 tagsets defined so far including the standard layers that ship preinstalled. 

When I try to create a feature with one of these tagsets, the pop-up menu shows only the last 15 or so tagsets and has no scrollbar.  In the end I found a workaround by resizing the description pane but this was not intuitive; scrollbar, or having the menu open as a floating pane, or some other behavior seems preferable.

**Comment by reckart** [comment]
@mssammon Which hexadecimal commit ID is displayed behind the version in the footer of the WebAnno page? What is your screen size?

**Comment by reckart** [comment]
This is related to https://github.com/twbs/bootstrap/issues/7160 - the problem can be alleviated by limiting the size of the popup menu e.g. to 10 items. I'm checking if there is a better solution.
