### ISSUE TITLE
problems implementing cross-layer/slot constraints

### ISSUE THREAD

**Issue by mssammon** [webanno/webanno#1184]
I am trying to implement constraints of predicates on roles, and of lemmas on predicates, but so far have not been able to replicate the behaviors described in the WebAnno documentation. 

I have a toy document:

*dummyDoc.txt:*
```
Jeff is a great laywer. He sues everyone, even his own family.
```

I have created two tagsets:

1.  Name: 'SemPred senseId', values: {'being', 'printing', 'legal'}
2.  Name: 'SemArg roles', values: {'Place', 'Time', 'defendant', 'litigant'}

The internal layer names for Lemma, SemPred, and SemArg are the defaults:

```
de.tudarmstadt.ukp.dkpro.core.api.semantics.type.SemPred
de.tudarmstadt.ukp.dkpro.core.api.semantics.type.SemArg
de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Lemma
```

I have added two features to the SemPred layer:

1. Internal Name: 'category'; type 'Primitive:String'; TagSet: 'SemPred senseId'
2. Internal Name: 'arguments'; type 'Link: SemArg'; TagSet: 'SemArg roles'

The SemArg layer has no features.

The Lemma layer has one feature, which is unchanged from the WebAnno default:

1. Internal Name: 'value'; type 'Primitive:String', Tagset: NONE

I have created two constraint files:

*SemPredDummy.txt:*
```
import de.tudarmstadt.ukp.dkpro.core.api.semantics.type.SemPred as SemPred;

SemPred {
category = "legal" -> arguments.role = "litigant" (!) | arguments.role = "defendant" (!);
}
```

*SemPredDummyLemma.txt:*
```
import de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Lemma as Lemma;
import de.tudarmstadt.ukp.dkpro.core.api.semantics.type.SemPred as SemPred;

SemPred {
@Lemma.value = "sues" -> senseId = "legal";
}
```

I perform the following steps:

1. I open the document 'dummy.txt'. I select layer 'Lemma'. I highlight the word 'sues'. 
I enter the value 'sues'. I click the button 'clear'. There is now a corresponding annotation marked in the 'Annotation' pane.

2. I select the layer 'SemPred'.  I highlight the word 'sues'. At this point, an 'arguments'
dropdown and a 'category' dropdown are displayed. The 'arguments' dropdown slot has 
the text 'select role' displayed. 

3. I click the dropdown for 'category'. I see a list of values corresponding to the 
TagSet 'SemPred senseId'; none is in bold, and the value 'legal' is not at the top.

4. I select 'legal'.  I click on the 'arguments' dropdown. I see a list of values 
corresponding to the TagSet 'SemArg roles'; none is in bold, and the values marked
as core are not at the top.

======================================

I expected the constraints to result in the indicated values being in bold, and at the
top of the lists revealed by the dropdown menus. 

I did successfully replicate the WebAnno documentation's simple example for Event
features (conditional display of one feature based on the value chosen for another.

What I have not specified/performed correctly?

**Comment by reckart** [comment]
It appears you have a mismatch between the feature names defined on SemPred and the names you use in the constraints:

> 1) Internal Name: 'category'; type 'Primitive:String'; TagSet: 'SemPred senseId'
> 2) @Lemma.value = "sues" -> senseId = "legal";

Try `@Lemma.value = "sues" -> category = "legal";`

**Comment by mssammon** [comment]
Thanks for catching that. However, after deleting that import file and replacing it with the corrected one, I see exactly the same behavior.
'''
import de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Lemma as Lemma;
import de.tudarmstadt.ukp.dkpro.core.api.semantics.type.SemPred as SemPred;

SemPred {
@Lemma.value = "sues" -> category = "legal";
}

**Comment by reckart** [comment]
Hm - have you tried putting both rules into the same file? I guess it should work if they are in two separate files - but honestly, I have no idea if anybody has tested that so far.

```
import de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Lemma as Lemma;
import de.tudarmstadt.ukp.dkpro.core.api.semantics.type.SemPred as SemPred;

SemPred {
  @Lemma.value = "sues" -> category = "legal";
  category = "legal" -> arguments.role = "litigant" (!) | arguments.role = "defendant" (!);
}
```

Could you provide me with an export of your project for close inspection. Best, export the project, re-import it, remove all documents (maybe keep one there if the documents are not confidential) from the copy, and export the copy again.

**Comment by mssammon** [comment]
It turns out that exporting and reimporting solves the problem.  It appears that some errors in constraints persist after correction (i.e., deletion of an import file and import of an updated/replacement file). 
Thank you for helping me work through this.

**Comment by reckart** [comment]
Cool :) Happy to help.
