### ISSUE TITLE
changing background color of text/annotation pane

### ISSUE THREAD

**Issue by mssammon** [webanno/webanno#1189]
I'd like to experiment with changing the colors of the text and background. After looking at possibly related issues and perusing classes like `ColoringStrategy` and `BratAnnotationEditor` I am still having a hard time working out how to change color behaviors (other issues make it pretty clear that there is no external way to configure this behavior via e.g. a config file, though I'd be happy to be told I'm wrong about this). 
Ideally, I'd also like to modify the relation coloring behavior but that is a lower priority.  
Is there a single place I can experiment with hard-coding colors for text and background in the annotation pane?

**Comment by reckart** [comment]
Relevant issues:
* https://github.com/webanno/webanno/issues/782
* https://github.com/webanno/webanno/issues/383

If you want to hard-code coloring, you could change the code of `de.tudarmstadt.ukp.clarin.webanno.api.annotation.coloring.ColoringStrategy.labelHashBasedColor(...).new ColoringStrategy() {...}` to do whatever you want. E.g. add "if (aVID.getLayerId() = XXX) user color blah)".

Admittedly, this should be refactored and modularized in a better way because in the current way it is really hard to implement smarter custom coloring strategies.

**Comment by mssammon** [comment]
The method you name is called from `BratRenderer.render(...)`: 
```
      for (AnnotationLayer layer : aAnnotationService.listAnnotationLayer(aState.getProject())) {
            ColoringStrategy coloringStrategy = aColoringStrategy != null ? aColoringStrategy
                    : ColoringStrategy.getStrategy(aAnnotationService, layer,
                            aState.getPreferences(), colorQueues);
 ``` 
This code -- and the comment in the actual method you name -- makes it look like the `ColorStrategy` only affects an annotation layer -- NOT the underlying document background and text colors.  It seems like that selection must happen somewhere else (maybe even in a .css file?)

**Comment by reckart** [comment]
Ah, ok. If you really want to change the coloring of the "canvas", you'd go to `webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/style-vis.less` - the CSS file that is there is just for history reference. The LESS file is the one that is actually used.

If you use Eclipse, I recommend you run WebAnno in the way described [here](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/WebAnno%20(GitHub)%20(master)/de.tudarmstadt.ukp.clarin.webanno$webanno-webapp/doclinks/3/#_eclipse_tomcat_integration). This way you can edit the LESS file and then simply reload the page in the browser (clearing caches) to see the changes immediately.

**Comment by reckart** [comment]
I think the styles you look for are `.background0` and `.background1` - but I didn't verify.

**Comment by mssammon** [comment]
That is extremely helpful -- thank you!

**Comment by mssammon** [comment]
BG colors are as you indicated in the .less file. However, I'm still struggling to modify the basic document text color.  Experimenting with .less files has not yielded a change to text color; and looking at the java code (e.g. `BratRenderer.java`) it's not clear to me how the text color would be programmatically set via `ColoringStrategy` because the BratRenderer calls `renderTokenAndSentence(...)` without the `ColoringStrategy` argument.  So, I'm assuming there is a default set somewhere for this...

**Comment by reckart** [comment]
According to the CSS inspector in my browser, the text color is inherited from the body element of the page.

**Comment by reckart** [comment]
I assume this has been resolved.
