### ISSUE TITLE
Admin Guide Extension

### ISSUE THREAD

**Issue by Quadrocompile** [webanno/webanno#1193]
We managed to setup WebAnno with a separate Tomcat instance with NGINX as reverse proxy webserver secured with Let's Encrypt certificates and could provide to you the working configurations neccessary in addition to the WebAnno Administration Guide if you'd like to add additional information about this topic. Especially the configuration of the server.xml file to achieve the reverse proxy with https was not easy to find.
Cheers, Phil

**Comment by Quadrocompile** [comment]
I have created a draft for the admin guide (see #1204 ). Feel free to edit the contents (e.g. add license) as you see fit. I do not fully understand how to add the files to the main documentation, so maybe you could do that for me.

**Comment by reckart** [comment]
I'll reopen the issue - we close issues along with the PRs.
