### ISSUE TITLE
Word Wrap

### ISSUE THREAD

**Issue by gajal123** [webanno/webanno#1194]
The text on webanno has no word wrap. To view the entire line, I have to scroll left and right. This causes issues while highlighting as well, mainly coz once the cursor is released, the text gets selected.
A good word wrap, with text spanning from top to bottom and no left/right scroll could really make my life easier.

**Comment by reckart** [comment]
The brat-based visualization is unable to word-wrap text that is covered by an annotation. If you have long annotations, you'll get scrolling.

**Comment by reckart** [comment]
See upstream issue: https://github.com/nlplab/brat/issues/1101

**Comment by reckart** [comment]
There is an option now to switch between a sentence-oriented display and a line-oriented display (https://github.com/webanno/webanno/issues/1266). The line-oriented display uses the line breaks from the original text. This may alleviate your issues if your original texts contain line breaks (i.e. if there are not just breaks between paragraphs).

**Comment by reckart** [comment]
INCEpTION provides a `brat @ 120 characters` visualization mode which pre-wraps the text at 120 characters respecting token boundaries. Additionally, there is the `line-oriented` mode already mentioned above.
