### ISSUE TITLE
Multiple highlight on a single span of text

### ISSUE THREAD

**Issue by gajal123** [webanno/webanno#1195]
While annotating over an already highlighted span of text, the cursor remains at the beginning of the text being highlighted and no change is seen until the cursor gets released. The color of the highlight remains the same as the color of the highlight in the background. At first look, it almost looks like nothing is getting selected. Seems like a minor CSS issue.

**Comment by gajal123** [comment]
While annotating over an already highlighted span of text, the cursor remains at the beginning of the text being highlighted and no change is seen until the cursor gets released. The color of the highlight remains the same as the color of the highlight in the background. At first look, it almost looks like nothing is getting selected. Seems like a minor CSS issue.

**Comment by reckart** [comment]
Can you provide a screenshot or small video which illustrates the problem?

**Comment by gajal123** [comment]
@reckart sure

**Comment by gajal123** [comment]
@reckart sure

https://drive.google.com/open?id=1a8gDhS4_1sAAoy_6KvXrIE97gNMAeEIb

As you can see in the video, the first time it selects properly and highlights. The second time it only shows that the first letter is getting highlighted. However once i release the cursor, the entire portion i had hovered over shows up as an annotation

**Comment by reckart** [comment]
Are you using Chrome? Could it be you are affected by this issue: https://github.com/nlplab/brat/issues/1288 (https://github.com/webanno/webanno/issues/1109)?

**Comment by gajal123** [comment]
yeah i am using chrome

**Comment by reckart** [comment]
Which version?

**Comment by gajal123** [comment]
71.0.3578.98

**Comment by reckart** [comment]
According to the [Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=897752) it seems that the fix will be available in Chrome 72. According to the [Chrome release schedule](https://www.chromestatus.com/features/schedule), Chrome 72 should be released end of January. So with a little luck, the issue will resolve itself in a couple of days when your Chrome auto-updates itself.

**Comment by reckart** [comment]
I have tried on WebAnno 3.6.2 with Chrome 78.0.3904.70 (OS X) and it seems to be working ok.
