### ISSUE TITLE
Deleting a span referenced by an arc should also delete the arc

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#121]
The CasDoctor AllAnnotationsIndexedCheck barks when a span is deleted that is used by a relation. 

Not deleting it causes an inconsistent state where a relation refers to a deleted span. The relation cannot be rendered anymore. The data in the CAS is inconsistent.

The correct fix would be to also delete the relation. 

See also #120.

**Comment by mmev** [comment]
I actually like the current behaviour (CasDoctor pretend the user from deleting the span if a relation arc is pointing on it or a relation arc is drown from this span to another), as the span instance and the arc instance are two independent instances.

On the other hand, if a span instance with a "slot"-arc on it will be deleted, I rather prefer the behaviour reckart describes as intended (span and slot both should be deleted)

**Comment by reckart** [comment]
> I actually like the current behaviour (CasDoctor pretend the user from deleting the span if a relation arc is pointing on it or a relation arc is drown from this span to another), as the span instance and the arc instance are two independent instances.

So you want to have a message saying that a span cannot be deleted unless all relations pointing to it have been deleted before? If yes, then it should properly implemented in that way as an message and it should not be caught by CasDoctor. 

CasDoctor is meant as a debugging device. It is not efficient and can slow down the use of the application quite a bit.

> On the other hand, if a span instance with a "slot"-arc on it will be deleted, I rather prefer the behaviour reckart describes as intended (span and slot both should be deleted)

That should already be the case for spans referenced through slots. When a span is deleted, the corresponding slot is removed.

**Comment by reckart** [comment]
I'm looking into this. Appears to happen only on custom relation types (i.e. not on the Dependency layer).
