### ISSUE TITLE
Offset for fireRender method of AnnotationEditorExtensionRegistry

### ISSUE THREAD

**Issue by wpmp** [webanno/webanno#1212]
**Is your feature request related to a problem? Please describe.**
Some editors might want to fire render requests for a specific offset or the whole document.
Currently the offset is taken from the `AnnotatorState`.

**Describe the solution you'd like**
`AnnotationEditorExtensionRegistry.fireRender()` should also take the offset begin and end as arguments.

**Additional context**
Required as the annotation editor extensions are triggered via `protected VDocument render(JCas aJCas, int windowBeginOffset, int windowEndOffset)` in `AnnotationEditorBase` but the window offsets are not passed down to the extensions - instead, extensions have to look up the window information in the `AnnotatorState` which may contain different information.

**Comment by reckart** [comment]
I expect that eventually we'll need another solution because there is lots of other code which relies on the *visible window* information from the `AnnotatorState` - but lets go with the passing the offsets explicitly for the moment.
