### ISSUE TITLE
Dockerhub not up to date

### ISSUE THREAD

**Issue by jnothman** [webanno/webanno#1217]
**Describe the bug**

The latest release on [dockerhub](https://hub.docker.com/r/webanno/webanno/tags) is 3.4.5. https://webanno.github.io documents v3.5.2 and suggests you run `docker run -it --name webanno -p8080:8080 webanno/webanno:3.5.2`. Docker cowardly refuses this command.

**To Reproduce**
1. Go to https://webanno.github.io/webanno/releases/3.5.2/docs/admin-guide.html#_running_via_docker
2. Follow its instructions

**Expected behavior**

WebAnno launched

**Comment by reckart** [comment]
Thanks for the reminder. I'll add this to the release todo list since I usually forget it...
