### ISSUE TITLE
Exporting a document: empty dialog window shown

### ISSUE THREAD

**Issue by mmev** [webanno/webanno#122]
(Experimental)
If I try to export a document, and click on "Export" in the "Document" box in the annotation bar on the top, an empty window will be displayed. --> no export possible

(tried in several projects; Settings are set appropriate; annotations are there)

**Comment by reckart** [comment]
Please provide the full version string (including the build SHA1) from the bottom of the screen do indicate which version of WebAnno you are referring to.

**Comment by mmev** [comment]
Experimental:
WebAnno -- 3.0.0-SNAPSHOT (2015-09-17 11:53:49, build e0931340beaf324f67a39d4c70ad80c2c76b091a)

**Comment by reckart** [comment]
In general: if you are working with projects that contain slot annotations, they cannot be exported in every format (in particular not in TSV).

Please try selecting "Binary" or "XMI" from the format dropdown instead of "AUTO" or "TSV".

**Comment by mmev** [comment]
Yes, this is also an important hint.
But I do not see anything. I attach the screen shot.
![screen shot 2015-09-17 at 16 03 02 pm](https://cloud.githubusercontent.com/assets/5416080/9935210/a3f657f6-5d55-11e5-9d64-c5182dec7385.png)

**Comment by reckart** [comment]
Ah, I thought you were talking about "project export" in the project settings - but this is document export in the annotation - sorry! ;)

**Comment by seyyaw** [comment]
Changing the ExportPanelPage from Wicket Page to Wicket Panel solves this. Similarly, GuideLineModalWindowPage also do not display components. something changed may be after upgrading to latest wicket. I think changing these two ModalPages to ModalPanel is also a good idea. we don't have any other Modal Pages.

**Comment by reckart** [comment]
+1 :)
