### ISSUE TITLE
CoNLL-U version 2 import-export is not available

### ISSUE THREAD

**Issue by rueter** [webanno/webanno#1220]
**CoNLL-U import is out-dated**
There are several versions of CoNLL import but only one for CoNLL-U, which, apparently, is version one. Upon uploading valid CoNLL-U v2 sentences, the import accesses column 5 (the XPOS column). It should access column 4 (the UPOS, i.e. UniversalDependencies POS column). 
When the Webanno tool is used to annotate using the proper POS tags, columns 4 and 5 are identical, which means that any initial XPOS values have been lost. Column 10 values in addition to the feature "SpaceAfter=No" have been stripped.

**To Reproduce**
1. Go to 'Projects/Documents'
2. Select 'Formatt type ConLL-U'
3. Select 'Choose files'
4. Select 'Import'
5. After successful import, go to Annotation and open file.

**Expected behavior**
Column 4 (UPOS) should have been imported
see: [https://universaldependencies.org/format.html]

**Please complete the following information:**
 - OS: [OS X 10.13]
 - Browser: [ chrome]

**Additional context**
Unable to provide example file in .conllu

[myv_Dubinka-2013.conllu.txt](https://github.com/webanno/webanno/files/2840565/myv_Dubinka-2013.conllu.txt)

**Comment by reckart** [comment]
@rueter Which WebAnno version are you using?

**Comment by reckart** [comment]
@rueter actually: yes, the CoNLL-U support in WebAnno is on a relatively old/basic level still. The reason is that WebAnno is still based on an old version of DKPro Core. I will look into switching to a more recent version.

**Comment by rueter** [comment]
@reckart I have tried working with two different versions of Webanno:
(1) https://webanno.multilingua.uni-hamburg.de/webanno/
(2) https://webanno.sfs.uni-tuebingen.de/webanno/projectsetting.html?0

I was informed by Hanna Hedeland that the Webanno available through uni-hamburg.de was an older version and that I should try out the sfs.uni-tuebingen.de first before filing an issue.

**Comment by reckart** [comment]
As much as presently possible, this should be addressed by https://github.com/webanno/webanno/issues/1221.
