### ISSUE TITLE
aliases for boolean features

### ISSUE THREAD

**Issue by jnothman** [webanno/webanno#1228]
**Is your feature request related to a problem? Please describe.**
A layer with several boolean features is displayed in annotation as `false | false | false | false` for example, and changed to `false | true | false | false` after ticking a checkbox. It is hard to distinguish visually which features are `true` and which are `false`.

**Describe the solution you'd like**
Each attribute could have an alias for display. A common pattern might be `-feat` vs `+feat` so that I might see `-voc | +cons | -son | +ant` instead of `false | true | false | true`.

**Describe alternatives you've considered**

One could develop a tagset which produces all possible combinations of the boolean features...

**Comment by reckart** [comment]
Great idea ;) I think it should be rather straightforward to do .
