### ISSUE TITLE
how to enable remote API in the standalone version from a docker environment

### ISSUE THREAD

**Issue by WilsonPang** [webanno/webanno#1229]
Hi There,

I installed the standalone version of webanno in my docker environment. The location of the installment is /opt/webanno in the docker shell, and webanno-standalone.jar is in that directory. Then i created the new file as "settings.properties" with "emote-api.enabled=true" in it.

I tried to create a new user but can't find the role of "ROLE_REMOTE". I got "access denied" error when access http://localhost:8080/swagger-ui.html. 

Any clue?

thanks,
Wilson

**Comment by reckart** [comment]
Given there was no further feedback, I'll assume that the issue has been resolved by adding the missing `r`.
