### ISSUE TITLE
Inconsistent way of how tooltips are shown

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#123]
The topbar/ "top set of buttons" have already defined list of tooltips for them. For this case consider, "Open" button on Annotation page.

If you hover over it, you'll see 
![tooltips - first time after loading](https://cloud.githubusercontent.com/assets/1897100/9946253/5d72667a-5d92-11e5-8da3-05edb25bea44.png)

However, after you load any annotation, the functionality for showing tooltips for slot(s)/tags takes over and shows up weird tooltip for "Open" button at bottom.

![tooltips - after opening an annotation](https://cloud.githubusercontent.com/assets/1897100/9946245/53a54ffe-5d92-11e5-93e3-6e1f1143d81e.png)

I am not sure if this was intended. This stays afterwards. The jquery tooltip shows for some objects. 

Additionally, it shows "no title" for some. And for "Go to" it doesn't show any. It only shows "press Enter" with "no title" if you hover over the page number.

**Comment by reckart** [comment]
That was not intended. The JQuery tooltips should only have affected the detail editor panel, not the toolbar. I'm not sure why they "leak".

**Comment by aakashysharma** [comment]
Found the cause, it has been applied on document level.

It may have the following usages:
on document level:
this.add(new TooltipBehavior());

on a specific html element:
this.add(new TooltipBehavior("#mySelector"));

on a specific wicket component:
this.add(new TooltipBehavior(JQueryWidget.getSelector(myComponent)));

source: http://www.7thweb.net/wicket-jquery-ui/tooltip/DefaultTooltipPage

**Comment by reckart** [comment]
Cool :) Can you fix it?

**Comment by aakashysharma** [comment]
Refer: http://www.7thweb.net/wicket-jquery-ui/tooltip/DefaultTooltipPage
