### ISSUE TITLE
Tokenizer of Text document for Named Entity

### ISSUE THREAD

**Issue by tahirahmad2030** [webanno/webanno#1249]
**Is your feature request related to a problem? Please describe.**
A) I have a text file which I want to annotate using webanno. I also want to tokenize the same file separately. However I am not able to mimic tokenizer of Webanno as it may be useing some rules which I am not aware of. 

**Describe the solution you'd like**
A) I need a funtion of tokenizer where I would give text as input and it would tokenize and give me offset of each token as output. 

**Describe alternatives you've considered**
A) I am trying to build the rules by which I can mimic the tokenizer used for Webanno NamedEntity. However you can make my task easier if you build it.

**Additional context**

**Comment by reckart** [comment]
Here is the tokenizer and segmentation code currently used in WebAnno. Feel free to adapt to your needs:

https://github.com/webanno/webanno/blob/4ee09d55e59aebdc96ffeea72554ba457128d61a/webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/ImportExportServiceImpl.java#L297-L333
