### ISSUE TITLE
Cannot annotate custom layer unless first select existing annotation

### ISSUE THREAD

**Issue by cyplas** [webanno/webanno#1252]
**Describe the bug**
Upon upgrading from 3.4.8 to 3.5.0 (or other 3.5.x), I cannot annotate anything (in certain projects with custom layers) unless I first select or edit existing annotations in one of the documents of the same project (but this workaround is not available if I'm doing my very first annotations in the project). Then I can annotate in normally on different documents of the same project, although the problem reappears if, for example, I close my browser tab and open another one and proceed from there.

**To Reproduce**

I haven't tried recreating this from scratch, but maybe the following would work.
1. Create a new project, disabling all built-in layers and adding two custom layers, a span and a relation (on those spans) (see screenshot).
2. Import some documents for it (we use TSV).
3. Open a document and try to annotate it.
4. Import a document which already has at least one annotation of the custom layer.
5. Open it and annotate unannotated text in the document.
6. Double click on an existing annotation.
7. Annotate other text in the document (and other documents).

**Expected behavior**
3 and 5 fail for us, but after workaround 6, 7 works.

**Screenshots**

Settings for our project and layer:
![settings](https://user-images.githubusercontent.com/3684636/54019828-825ef980-418c-11e9-9510-6aa4c8e516c9.png)

Error when selecting multiple words:
![stacking_not_enabled](https://user-images.githubusercontent.com/3684636/54019826-825ef980-418c-11e9-88c9-89cee664eccc.png)

Error when clicking on a single word:
![unsupported_lemma](https://user-images.githubusercontent.com/3684636/54019827-825ef980-418c-11e9-9b03-ca447d89c5ae.png)

**Please complete the following information:**
 - Version and build ID: included in screenshot
 - OS: Ubuntu
 - Browser: Chrome, Firefox

**Additional context**
Was working fine with 3.4.8, and also works there if I downgrade back to 3.4.8 from 3.5.0.

**Comment by reckart** [comment]
@cyplas Does CASDoctor report anything on your project? Could you provide an example project to reproduce this?

**Comment by cyplas** [comment]
I was getting relation errors in CASDoctor during upgrades, but in line I think with what your release notes suggest, and I successfully ran the repairs on them.
Here's our test project:
[test-kas-biterm_2019-03-08_1037.zip](https://github.com/webanno/webanno/files/2945206/test-kas-biterm_2019-03-08_1037.zip)

**Comment by reckart** [comment]
@cyplas thanks, I can reproduce it. Another workaround should be to enable the "Remember layer" option in the settings dialog of the annotation page.

**Comment by cyplas** [comment]
>  Another workaround should be to enable the "Remember layer" option in the settings dialog of the annotation page.

Thanks, that seems to work too, although it seems I have to redo it (open settings and save, even though it's already checked) if I go to another browser tab.

**Comment by reckart** [comment]
You mean the setting is not saved? Opening a document in multiple tabs is not supported. To check if the settings is properly saved, go back to the main menu and open the document from there again.

**Comment by cyplas** [comment]
The setting "claims" to be saved (i.e., the checkbox is checked if I reopen settings), but it doesn't seem to help unless I click on Save again.

I'm testing in another tab not in order to annotate in multiple tabs concurrently (that sounds like hell :) ), but rather to verify that the setting is working if I'm not in the same "session". I get the same result if I close the single tab, open a new single one, and work in there.

**Comment by reckart** [comment]
Ok, fixed. Will be in the next bugfix release.

Here another more convenient workaround: rename your layer such that it starts with a capital letter that comes before "T" in the alphabet. ;)

**Comment by cyplas** [comment]
> Ok, fixed. Will be in the next bugfix release.

Thanks, that was quick.

> Here another more convenient workaround: rename your layer such that it starts with a capital letter that comes before "T" in the alphabet. ;)

Hehe, if we're desperate, we may try that. :)

**Comment by reckart** [comment]
wrt renaming: it is just cosmetics. The internal type name used in the TSV doesn't change if you change the name in the layer settings - it is only the label in the UI which changes - and this is what matters at this point. You can simply rename it back when upgrading to WebAnno 3.5.4.

**Comment by cyplas** [comment]
Aha, ok!
