### ISSUE TITLE
CSRF protections are disabled, HTTP400 with invalid origin

### ISSUE THREAD

**Issue by drspangle** [webanno/webanno#1255]
**Describe the bug**
I'm running the Docker version of the application. Because there's a shared server running this, I've got nginx running as a reverse proxy to the Docker container which is hosting webanno. I get the following error after I log in:

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Mon Mar 11 18:53:13 UTC 2019
There was an unexpected error (type=Bad Request, status=400).
Origin does not correspond to request
```

I think the problem here is that the CSRF protections have been disabled, cross-origin resource sharing isn't configured correctly, and the app is vulnerable to XSS attacks by default.

I've made sure that the nginx proxy preserves the origin of all requests, and also forwards all request headers. Something internally is misconfigured and is either binding to an invalid domain, but I can't be sure since there's no way to configure this outside of modifying the source and recompiling the .jar file.

The CSRF token is clearly seen in the request headers.

**To Reproduce**
1. Follow the normal documentation, and put the Docker version of the tool online.
2. Configure an nginx reverse proxy to forward requests to the container. Here is an example:

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 443 ssl http2;
        access_log /var/log/nginx/access.log vhost;
        return 503;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/default.crt;
        ssl_certificate_key /etc/nginx/certs/default.key;
}
# my server
upstream <censored domainname> {
                                ## Can be connect with "nginx-proxy" network
                        # webanno-annotation-tool_webanno_1
                        server <censored docker internal IP>:80;
}
server {
        server_name <censored domainname>;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name <censored>;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/<mycert>.crt;
        ssl_certificate_key /etc/nginx/certs/<mycert>.key;
        ssl_dhparam /etc/nginx/certs/<mycert>.pem;
        add_header Strict-Transport-Security "max-age=31536000";
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass <censored domainname>;
        }
}
```

**Expected behavior**
I should be able to log in. I expected a HTTP403 not HTTP400 if there is an attempt to break the authentication system.

 - Version and build ID: latest tag on Docker as of 3/11/2019
 - OS: Ubuntu 16.04, running Docker version 18.09.3, build 774a1f4
 - Browser: Doesn't matter.

**Comment by reckart** [comment]
Could this be related to https://github.com/webanno/webanno/issues/968 ?

CSRF is indeed disabled - mainly because I did not yet (try sufficiently to) figure out how to how CSRF properly set up in a Wicket + Spring + Spring Security application. Any help is welcome.

**Comment by reckart** [comment]
@Quadrocompile recently contributed a description of how to run WebAnno behind nginx: https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/WebAnno%20(GitHub)%20(master)/de.tudarmstadt.ukp.clarin.webanno$webanno-webapp/doclinks/2/#_putting_it_all_together

Maybe that helps you?

**Comment by Quadrocompile** [comment]
I'd recommend that you check out the section regarding the /opt/webanno/conf/server.xml file and try to announce the additional header fields from NGINX to WebAnno. This resolved a similar error in my setup.

**Comment by drspangle** [comment]
I'll give this a try and report back. Unfortunately, I don't have any
suggestions on how to enable CSRF protections properly for your stack. I
was initially concerned that the CSRF protections were causing the error in
the OP, but evidently that's not the case...

**Comment by drspangle** [comment]
@Quadrocompile I added the recommended lines to my nginx configuration file and still no luck. It's worth mentioning that I'm running the Docker version of the tool and proxying to that, so I don't see an obvious way to modify the `/opt/webanno/conf/server.xml` file since it doesn't exist in this version. In fact, there's no obvious way that I can see to set any of the parameters other than those specifiable through the `JAVA_OPTS` environment variable.

What I'm going to try next is to just create my own Docker image which doesn't include everything jammed into a single `.jar` file, and hopefully I can gain traction that way. If you know of a way I can fix this issue by modifying the config for the Docker version, I'd be very interested to know about it.

**Comment by reckart** [comment]
Many of the Tomcat parameters should be configurable via the `settings.properties` file. Any of the parameters documented [here](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) should work in the file (despite the documentation saying that they should go to `application.properties`).

**Comment by reckart** [comment]
Also note the information about running the standalone JAR version [here](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/WebAnno%20(GitHub)%20(master)/de.tudarmstadt.ukp.clarin.webanno$webanno-webapp/doclinks/2/#_running_the_standalone_behind_httpd) - in particular about adding these lines to the `settings.properties` file:

```
tomcat.ajp.port=18009
server.contextPath=/webanno
server.use-forward-headers=true
```

**Comment by drspangle** [comment]
@reckart The Docker image doesn't seem to have the `settings.properties` file anywhere, certainly not at `/srv/webanno/settings.properties`. Are you saying that if I create that file in there, that it will be read by whatever the `.jar` file is doing internally? If so, why not add some lines to the `Dockerfile` that creates these files by default? I could do that and create a PR if it turns out that it works.

**Comment by reckart** [comment]
When you use Docker, you should mount the "home" directory where WebAnno stores its data to your host system. You place a text file called `settings.properties` into that folder and WebAnno in the Docker image should pick it up. You can verify if it does by checking the log messages during startup. 

See: https://webanno.github.io/webanno/releases/3.5.5/docs/admin-guide.html#_storing_data_on_the_host

**Comment by drspangle** [comment]
I was able to get this working with nginx, using the recommended settings from @Quadrocompile. This allowed me to host using HTTP only, and I was planning to use a second proxy in front of the nginx which is proxying to the webanno container which provides HTTPS proxying. This way I can keep all of the actual web containers (i.e. the "inner" nginx proxy, webanno, and it's SQL database") inside my Docker network, and only expose the one "outer" nginx proxy to the Internet. This doesn't seem to work. While there is a small difference in the error message I'm getting (the CSS on the HTTP 400 page from Tomcat works, so there's some nice blue colors instead of just plain HTML) the error is the same.

I'm at my wit's end here. I'm using the exact same directives in my nginx config for the outer proxy as I am the inner proxy. This should be entirely transparent to webanno, and this arrangement has worked for dozens of other applications and webpages that my group has developed and currently host. I wish there was some way to get more detailed information about what is causing the HTTP400, such as perhaps what header is missing or whatever else, but I can't seem to get any messages from the catalina log files that give any insight beyond what I already have.

**Comment by reckart** [comment]
Sorry for the inconvenience...

There are some additional settings from the Spring Boot / Wicket integration that you might care to try out (they also go into the `settings.properties` file):

https://github.com/MarcGiffing/wicket-spring-boot#core---prevention-of-csrf-attacks

It seems the message you are seeing might come from there.

**Comment by drspangle** [comment]
@reckart Thanks for the great support. We picked the webanno tool because of how good you folks are at maintaining this repo.

I'll go through these extra parameters and see if I can't coax this into working.

**Comment by drspangle** [comment]
I've actually had success, once I added the extra params from your link to my settings.properties file. Here's how it looks now:

```
warnings.embeddedDatabase=false
server.port=80
wicket.core.csrf.enabled=false
wicket.core.csrf.no-origin-action=allow
wicket.core.csrf.conflicting-origin-action=allow
```

I decided to use the embedded database to keep this test simpler, but for some reason the `warnings.embeddedDatabase=false` directive doesn't work. I still see the warning on the UI in the actual tool. But at least I can log in and the tool works, with HTTPS. Great success! I'll make a separate issue for this remaining problem.

**Comment by reckart** [comment]
This is probably a conflict between Wicket/Springboot and the legacy XML-based Spring Security settings that we are still using. I'll try removing these legacy settings...

**Comment by reckart** [comment]
Some more links relevant to CSRF in Spring/Wicket:

* http://apache-wicket.1842946.n4.nabble.com/Wicket-Spring-4-integration-td4672031.html
* https://jira.evolveum.com/browse/MID-2886
* https://github.com/Evolveum/midpoint/commit/95f4de551ea1b663006e5dc736059d5f6ce69688#diff-43e2cbcf10434fbc532789a99aea6889

**Comment by peterstory** [comment]
Since CSRF protection isn't being used, this bug could be probably be resolved if the following lines were added to [application.properties](https://github.com/webanno/webanno/blob/2dbc603c8909426aa12892e2f3ee0f8b7ae9fde4/webanno-webapp/src/main/resources/application.properties). 

```
wicket.core.csrf.enabled=false
wicket.core.csrf.no-origin-action=allow
wicket.core.csrf.conflicting-origin-action=allow
```
@reckart If I tested this and opened a PR for this change, would you accept it?

**Comment by reckart** [comment]
@peterstory - I don't know - I did try to git a bit more and my impression is that there are two CSRF protections at work, one by Wicket and one by Spring Security. 

WebAnno disables the one by Spring Security because it would require quite a few changes to make that interoperable with Spring (cf. what [Evolveum](https://github.com/Evolveum/midpoint/commit/95f4de551ea1b663006e5dc736059d5f6ce69688#diff-43e2cbcf10434fbc532789a99aea6889) did).

But WebAnno doees not disable the Wicket CSRF because frankly it seems to me that few people have issues with it. I never faced any problem, but I'm using Apache HTTPD with AJP for the reverse proxy, not nginx. 

For the moment, it seems to me that the Wicket CSRF isn't broken per-se but only in combination with nginx. So rather than disabling CSRF entirely I think it makes more sense to document the settings that need to be made specifically with nginx.

If somebody is more versed with CSRF and can provide some deeper insight into this, I'd appreciate it.

**Comment by peterstory** [comment]
In that case, I think you could simply add the following to `application.properties`:
```
wicket.core.csrf.enabled=
wicket.core.csrf.no-origin-action=
wicket.core.csrf.conflicting-origin-action=
```
This will leave the defaults as they are now (leaving CSRF enabled), but will allow these options to be changed by the user's `settings.properties` file.

**Comment by reckart** [comment]
The user can add these lines to the settings.properties file no matter if I add the empty lines into application.properties or not. Try it :)

**Comment by peterstory** [comment]
I tried creating `/srv/webanno/settings.properties` with those lines in a container running image `webanno/webanno:3.5.3`, but those settings did not seem to be used. Those settings only worked when using the non-standalone jar file. 

My understanding is that settings need to be exposed in `application.properties` for them to be configurable. If that's not the case, I'm not sure why my `settings.properties` isn't working.

**Comment by reckart** [comment]
> EDIT: Perhaps the standalone jar is looking in a place other than /srv/webanno/settings.properties ?

The dockerfile sets the `webanno.home` to `/srv/export`:

```
CMD java ${JAVA_OPTS} -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -Dwebanno.home=/export -jar webanno-standalone.jar
```

So if you want to use a custom `settings.properties` you should mount `/export` to a folder on your host and place the file there. I see this information is missing from the documentation so far.

**Comment by reckart** [comment]
Adding this to the documentation: 

> The dockerized WebAnno expects the `settings.properties` file in the `/export` folder. Instead of
injecting a custom `settings.properties` file into the container, it is strongly recommender to
use the instructions above (Storing data on the host) to mount a folder from the host system to 
`/export` then to place the into the mounted folder `settings.properties`. Thus, if you follow
the instructions above, the settings file would go to `/srv/webanno/settings.properties` on the host
system.

**Comment by peterstory** [comment]
Success! After adding `settings.properties` to `/export`, I am able to log in! Thank you for your help! 

I'm still seeing some strange behavior, but it's easy to workaround. 

1. Open a new private browsing window to https://my_hostname.org/
2. Logging in gives this error: 
![image](https://user-images.githubusercontent.com/1322135/55588458-d0b7d780-56fb-11e9-9edb-ec6cdb009bd9.png)
3. Load https://my_hostname.org/, and I am logged in! 
4. In the same private browsing window, if I log out and log back in, things work without any errors.

**Comment by reckart** [comment]
Hm - I don't know why this happens. I do not know if a private session can access the cache of the outside non-private session - in that case it might be a caching issue from before when it was not working. Is it correct that there is no difference in the URL between points 1. and 3. or a copy-paste mistake?

**Comment by peterstory** [comment]
Looking at things with a fresh set of eyes revealed the problem: I was using a bookmark for https://my_hostname.org/webanno/login.html -- the problem was that I didn't need the `/webanno` portion of the URL (that came from an earlier setup I'd tried out). This is what was happening:

1. Submit a request to: https://my_hostname.org/webanno/login.html
2. I get redirected to: https://my_hostname.org/login.html
3. Logging in redirects to: https://my_hostname.org/webanno/login.html, which has an error, likely due to the `/webanno` in the URL
4. Issuing a request to https://my_hostname.org/login.html (using the back button of my browser) redirects to a page showing that I'm logged in.

Thanks again for your help!

**Comment by reckart** [comment]
@peterstory thanks for letting us know that it wasn't a bug after all :)
