### ISSUE TITLE
Export each document to TSV3.

### ISSUE THREAD

**Issue by ducalpha** [webanno/webanno#1256]
**Problem**
I am trying to export a document to TSV3 but current version does not support it (while other formats are supported like CoNLL 2000/2002). Therefore, I have to export the whole project to get the TSV3 file of an annotated document, but exporting the whole projects 10 times longer than exporting a single document.

**Describe the solution you'd like**
I believe it is doable to re-use the code from project export feature to export each document to TSV3.

**Comment by reckart** [comment]
@ducalpha Actually the project export feature and the export from the annotation page already use the same code. If a format is available in one it should also be available in the other. Which version of WebAnno are you using?

**Comment by ducalpha** [comment]
Oh, the option for selecting TSV3 appeared after I scrolled down the menu. Thanks!
