### ISSUE TITLE
Example of the TEI CPH XML format?

### ISSUE THREAD

**Issue by zwurgl** [webanno/webanno#1260]
One of the import options of annotated corpora into WebAnno is "TEI CPH dialect". 

I tried with a few sample TEI files, but the import failed. Apparently TEI is not enough, but I was unable to find a definition or a sample of "TEI CPH", neither in the WebAnno documentation nor anywhere else. 

I have some preannotated corpora here and would love to see how to continue working on them in WebAnno. Translation them into Conll2002 for instance works. The import retains my annotations but all the formatting is lost (newline, new paragraph ...) which makes it very hard to find your way in a lengthy document. 

I was hoping TEI CPH could be a way out.  

A sample or a definition what "TEI CPH" is and what it looks like would be great. 

Thanks!

**Comment by reckart** [comment]
In any case, WebAnno is currently only able to display texts in a sentence-oriented way. It does not preserve layout - even if you import from TEI.

**Comment by reckart** [comment]
I'm not aware of any sample of that particular format either - but you might glean some information fro the source code of the reader: https://github.com/webanno/webanno/blob/master/webanno-io-tei/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tei/TeiReader.java

**Comment by reckart** [comment]
Closing as there were no further comments.
