### ISSUE TITLE
Importing CONLL-U losing UPOS tags

### ISSUE THREAD

**Issue by lmompela** [webanno/webanno#1270]
**Describe the bug**
When importing a [CONLL-U file](https://github.com/lmompela/UD_CreoleMartinique/blob/master/gcf_dep-ud-test.conllu) with lemma and POS, the POS is lost.

**To Reproduce**
1. Go to 'home/ projects/Documents.'
2. Click on '/import file in the CONLL-U format'
3. Go to "home/annotation/open document"

**Expected behavior**
Expected to see POS tags

**Screenshots**
![screenshot1](https://user-images.githubusercontent.com/49000319/55831095-582c8e80-5ae0-11e9-93db-5ef24440c73d.png)

**Please complete the following information:**
 - Version and build ID: WebAnno -- 3.5.5 (2019-03-13 17:09:53, build 2c80308b4627f28d8a75d3e29bcc07becd0a33b0) 
 - OS: Linux
 - Browser: Mozilla

**Additional context**

**Comment by reckart** [comment]
In WebAnno 3.5.x,  CoNLL-U files must have the POS tags in the `POSTAG` column (column 5) and not in the  `CPOSTAG` column (column 4). If there are in column 4, they won't get imported.

**Comment by reckart** [comment]
You could try out the latest [3.6.0 beta](https://webanno.github.io/webanno/downloads-beta/) version which has better CoNLL-U support.

**Comment by ftyers** [comment]
@reckart Does that mean the `UPOS` tag should be in the `XPOSTAG` column and not in the `UPOSTAG` column with WebAnno 3.5.x but with 3.6.0 beta the `UPOS` tag should be in the `UPOSTAG` column?

**Comment by reckart** [comment]
@ftyers The column names I am using refer to a version of the [CoNLL-U format from 2015](https://github.com/UniversalDependencies/docs/blob/afa93afd6f1008c12edd9f7d21d789975361cbfb/format.md).

The reader that is being used in the latest WebAnno 3.6.0 beta is able to read both columns. However, I just noticed that the POS annotation layer still only exposes the value of the `POSTAG` (now `XPOSTAG`) column. I'll look into exposing the value of the `CPOSTAG` (now `UPOSTAG`) column as well.

**Comment by ftyers** [comment]
Would it be worth adding both a UD v2 CoNLL-U reader and a 2015 CoNLL-U reader ? Alternatively it might be less confusing to people if you put that CoNLL-U refers to the 2015 version and not the up to date version? Perhaps with instructions on how to get around the problem for current (post-2015) UD treebanks.

**Comment by reckart** [comment]
I think the proper fix for this will be to 

* use the ConLL-U reader from DKPro Core 1.11.0 (when it is released) which reads the two columns independently of each other and stores their values into two different features
* expose both of these features in the WebAnno POS layer

Meanwhile people can get around the issue by shifting the POS values from column 4 to column 5 e.g using this command: 

> `awk -F $'\t' 'BEGIN {OFS="\t";} { t = $4; $4 = $5; $5 = t; print; }' gcf_dep-ud-test.conllu > gcf_dep-ud-test-swapped.conllu`

**Comment by ftyers** [comment]
Thanks! I've updated the script that generates the CoNLL-U to put UPOS in both UPOS and XPOS columns. Btw, does this mean that the import/export of CoNLL-U is lossy? or will all the information be maintained, even if it is not exposed?

**Comment by reckart** [comment]
The import/export is lossy. In general you should assume that any information that is not accessible isn't imported and consequently missing on export.

**Comment by ftyers** [comment]
Good to know! Are there any plans for lossless import/export of CoNLL-U ?

**Comment by reckart** [comment]
In general, the 3.6.0 betas should retain more information and be a bit closer to CoNLL-U v2. If you lack/lose something specific, please let me know.

**Comment by reckart** [comment]
> Are there any plans for lossless import/export of CoNLL-U ?

If it had been easy to support full lossless conversion, I'd be already there. I'm trying to improve the support whenever somebody points me to something that hurts in particular (given time and opportunity).
