### ISSUE TITLE
Tokenization in conll2002 format

### ISSUE THREAD

**Issue by nipunsadvilkar** [webanno/webanno#1271]
I am trying to mimic the behavior of WebAnno tokenizer in Python. But I am unable to get the expected result. I tried going through the source code and even going through the documentation but unable to find an ideal solution.

First I thought it's splitting on every word and punctuation but that's not the case.

Here are some edge cases where above logic fails:
> text -> WebAnno tokens

1. In floating values within text

   `price is 0.99 USD` -> `['price', 'is', '0.99', 'USD']`
   > Doesn't tokenize on floating values?

2. WebAnno tokenizer preserves hyphenated terms as one token. 
e.g. `close-up`

3. Preserves stopwords as a single token.
e.g. `don't`

4. Preserves hashtags as a single token.
e.g. `#GitHub`

It would be great if I can get any inputs on how should I mimic tokenizer and which more edge cases I should consider. Thanks in advance

**Comment by reckart** [comment]
WebAnno uses the Java `BreakIterator` - if you really want to know how that works, your best bet might be to start looking [here](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/sun/text/resources/BreakIteratorRules.java). Note that the linked file is part of a specific version of the Java 8 JDK and may change in other Java versions or for other Java vendors.

I realize that WebAnno should probably offer some way of configuring the tokenization scheme.

Why do you want to replicate the tokenization in Python?

**Comment by nipunsadvilkar** [comment]
Since during training of NER model, I'm feeding conll files exported from WebAnno as an input (which is already tokenized) so want to keep tokenization consistent during prediction also.

What are your thoughts on it? Any workaround this?

**Comment by reckart** [comment]
Ok, I see. The optimal solution would have been to tokenizer your texts with the tokenizer you also want to use during prediction and then import the already tokenizer texts into WebAnno for annotation. 

Well, the [link](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/sun/text/resources/BreakIteratorRules.java) I posted before points to what I believe to be the set of rules used by the BreakIterator that Java uses. The rules are well-commented, so I hope you'll find them helpful in figuring out how to replicate their behavior in Python.

**Comment by reckart** [comment]
@nipunsadvilkar you could probably also implement a Python script which projects the annotations you made in WebAnno to a version of the text tokenized with whatever tokenizer you already have in Python. I would expect that to be less work. Also if you ever wanted to switch to yet another tokenizer, it wouldn't be any problem to you.

**Comment by nipunsadvilkar** [comment]
Yes since WebAnno `ctsv3` format gives offsets so, will map it to the new tokenizer.

Thanks for your inputs 👍 Closing the issue

**Comment by sonu-gupta** [comment]
@nipunsadvilkar Hi, I am facing the same issue. Were you able to re-create the same logic of tokenization in python?

**Comment by nipunsadvilkar** [comment]
No we used webanno TSV format to get offset and doing tokenization offline.

**Comment by sonu-gupta** [comment]
I am not sure if I get this. How do you convert your test documents into TSV format to get the offsets?

**Comment by nipunsadvilkar** [comment]
Check the webanno documentation to see how to export annotated doc into
WebAnno TSV format and what all information it provides.

**Comment by sonu-gupta** [comment]
Ah, okay! so basically you are passing every test document from webanno to get off-sets. But I am looking something completely separate, as in that does not include webanno into it in real-time application. Thanks for your help.

**Comment by reckart** [comment]
Why do you need the "WebAnno tokenization" (which is at this point actually simply the Java BreakIterator) if you are not using WebAnno? ;)
