### ISSUE TITLE
Text Search Option

### ISSUE THREAD

**Issue by iniadu** [webanno/webanno#1274]
When we need to find a certain type of sentences, containing particular words/phrases (e.g. sentences with "intraday") to review them later when the final solution how to annotate them is taken, it appears to be impossible with the existing webanno functionality.  A very simple text search would be great.

**Comment by reckart** [comment]
Try out [INCEpTION](https://inception-project.github.io) which comes with search functionality accessibly via a sidebar on the annotation page. If you have a project in WebAnno, you can usually export it and import it into INCEpTION.
