### ISSUE TITLE
Show progress information for curation

### ISSUE THREAD

**Issue by iniadu** [webanno/webanno#1275]
The Current monitoring page provides statistics on percentage of documents finished, although the definite quantity, not quantity spans (such as 0-500)  is not available. Is there any chance to get that data?
![image](https://user-images.githubusercontent.com/49755568/56363601-4ab88800-61f5-11e9-84a8-59a476a2305b.png)

**Comment by reckart** [comment]
How would you measure progress in terms of spans? I mean, there is no way to tell the maximum number of spans there could be, right?

**Comment by iniadu** [comment]
No, I mean actual number of curated docs  would be great. Smth like 572

**Comment by reckart** [comment]
Ok, I see. Yes, the "curator" is lacking a row in the charts, that is true.
