### ISSUE TITLE
Display of layers with sequential features 

### ISSUE THREAD

**Issue by cyplas** [webanno/webanno#128]
For layers with several "sequential" features (e.g., a custom MultipleLemmas layer with features lemma1, lemma2, lemma3, lemma4), but where in most cases only the first feature is set, it's visually jarring to have several trailing | characters in every annotation, as in the attachment. It would be nice to be able to somehow set up such a layer so that it does not show these when features are empty.

![webanno](https://cloud.githubusercontent.com/assets/3684636/10014453/9d616f3a-6119-11e5-86d7-818b591adde7.png)

**Comment by cyplas** [comment]
Note: part of this problem would be solved by "Lock to token offsets", but this is not supported by the format we want to use (TSV).

**Comment by reckart** [comment]
Currently, WebAnno does not allow to explicitly set the order of features (well, they are usually sorted alphabetically). Therefore, I think having a display option that depends on the order (i.e. "remove trailing separators") may not be the best option.

Another way to put this would be "Conflate empty features" to remove not only trailing separators but any immediately adjacent separators. It would solve your problem as well.

**Comment by reckart** [comment]
https://github.com/webanno/webanno/issues/128#issuecomment-142220819 - you mean that TSV does not support sub-token annotations?

**Comment by ChrisBieTUDA** [comment]
As far as I am aware, the current TSV in fact does not support subtoken annotations. We hope to attend this in the course of this calendar year . in the meanwhile, you'd have to rely on a different format, e.g. XMI, sorry.

**Comment by cyplas** [comment]
I've successfully incorporated our wish into my local test installation with the following tiny patch (relative to tag webanno-2.3.0):

--- a/webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/controller/TypeUtil.java
+++ b/webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/controller/TypeUtil.java
@@ -98,5 +98,5 @@ public final class TypeUtil
             Feature labelFeature = aFs.getType().getFeatureByBaseName(feature.getName());
 
-            if (bratLabelText.length() > 0) {
+            if (bratLabelText.length() > 0 && StringUtils.defaultString(aFs.getFeatureValueAsString(labelFeature)).length() > 0) {
                 bratLabelText.append(TypeAdapter.FEATURE_SEPARATOR);
             }

In playing with this, I realised and tested that, in fact, your previous condition (bratLabelText.length()>0) implies that you do not show any "|" until after the first non-empty feature, which is effectively the mirror of our requested feature. I'm not sure if this a bug or a design feature.

In any case, please let me know whether you would incorporate this patch or something like it (with or without a layer-level "Conflate empty features" option or the like).

Thanks for your help!

**Comment by cyplas** [comment]
Actually, I was inaccurate there: this patch does "conflate empty features", not "remove trailing separators", as we liked your idea. :)

**Comment by reckart** [comment]
> In playing with this, I realised and tested that, in fact, your previous condition (bratLabelText.length()>0) implies that you do not show any "|" until after the first non-empty feature, which is effectively the mirror of our requested feature. I'm not sure if this a bug or a design feature.

Hm, thinking of it, more a bug than a feature. I'd personally tend towards making the conflated the default and then wait if anybody asks for having the non-conflated display back (I can hardly imagine that).

**Comment by TomazErjavec** [comment]
Great, so I take it we can count on this becoming implemented in a future version?
In the meantime we would survive with the local patch.
(we plan to seriously start using WebAnno in October)

**Comment by reckart** [comment]
I'm marking it for the next major version - will certainly not be released before October though.
