### ISSUE TITLE
Missing comments on export to CONLL-U 

### ISSUE THREAD

**Issue by lmompela** [webanno/webanno#1282]
**Describe the bug**
Missing comments when exporting CONLL-U file
When exporting it gives me a ".conll" file and not a ".conllu" file

**To Reproduce**
1. Go to home/annotation
2. Click on export
3. Click on format
3. Scroll down to CONLL-U
5. Click on export

**Expected behavior**
Expected to see comments and to have a .conllu file
**Screenshots**

**Please complete the following information:**
 - Version and build ID: WebAnno -- 3.6.0-beta-4 (2019-03-13 18:08:33, build fd3e9bf9e24a363fe839751bba24d3f501862064) 
 - OS: Linux
 - Browser: Mozilla

**Additional context**

**Comment by reckart** [comment]
What do you mean by "comments"?

**Comment by ftyers** [comment]
From the [docs](http://universaldependencies.org/format.html), comments are introduced with a `#` as the first character of the line (see '3').

**Comment by reckart** [comment]
We can only export data that is known in WebAnno. WebAnno knows about sentences, tokens, pos, lemma, and dependencies (and a little about morphological features) - and of course the text itself. The sentence text (`text`) and sentence IDs (`sent_id`) are exported as "comments", but there is no support for "any kind of comments". Sentence IDs can presently not be edited in WebAnno, but if they are present in an imported CoNLL-U file, they should also be present when this file is again exported as CoNLL-U. 

Other types of "comments" such as paragraph or document boundary markers are presently not supported.

Which types of comments exactly do you need?

**Comment by ftyers** [comment]
@reckart well, basically just the original text and the sentence ID. When we select "CoNLL-U" format they are not in the exported file. Would it be possible to include them?

**Comment by reckart** [comment]
Ok, I see. WebAnno 3.6.0-SNAPSHOT currently uses DKPro Core 1.10.0 which indeed does not write the sentence ID and text comment. However, they will be included latest when the next DKPro Core version is released and WebAnno is upgraded to use it.

**Comment by ftyers** [comment]
@reckart is there an ETA on that? (just for planning purposes), e.g. two months, I'll write a script to readd the comments, two weeks and we'll probably just wait :)

**Comment by reckart** [comment]
If you need it urgently, I could temporarily backport the code from DKPro Core master to WebAnno master - I'm planning to do a new WebAnno 3.6.0 beta release anyway.

**Comment by reckart** [comment]
@ftyers https://github.com/webanno/webanno/pull/1283 - I didn't test it yet, but since the unit tests are good, I guess it should work.

**Comment by ftyers** [comment]
thanks @reckart ... @lmompela could you try the version @reckart has just made?

**Comment by reckart** [comment]
You'll have to build this from source (master branch) yourself atm - I'm still looking into including a few other changes before running a proper release process for the next 3.6.0 beta.

**Comment by reckart** [comment]
WebAnno 3.6.0-beta-5 is available now.
