### ISSUE TITLE
page up, page down jumps randomly

### ISSUE THREAD

**Issue by userfsc** [webanno/webanno#1288]
I am working with Webanno Version 3.5.5. When annotating, I use the page up/down buttons to move to the next sentences (instead of clicking page->next). It doesn't work properly anymore in this version. It randomly skips pages. Instead of going from sentences 1-20 to 21-39 it goes to 41-59. If there are 5 sentences per page, it even skips like 5-10 pages.

**Comment by reckart** [comment]
Thanks - I'll have a look at it.

**Comment by reckart** [comment]
Interesting - this doesn't seem to happen on the current development branch but I can reproduce it on the 3.5.x branch.

**Comment by reckart** [comment]
Interesting - this doesn't seem to happen on the current development branch but I can reproduce it on the 3.5.x branch.
