### ISSUE TITLE
Automation of Annotation 

### ISSUE THREAD

**Issue by Alaa-j** [webanno/webanno#1307]
Hi

I’m doing research with customised NER for the Arabic Language. I have done the annotation using the Webanno tool, and my files are saved in Webanno TSV3 format. However, I want to use the automation section for this task for the remaining records in my dataset.

So, I downloaded the tagset I created as TAP-SEP txt file (tagset_loc.txt) and then I download the Layer that I customised to use my tagset in JSON format (layer.json). Then, I created a NEW project and select the type as ‘automation’.

1. I uploaded the customised tagset_loc.txt  in the Tagset section of the project
2. Then, I did the same for the layer section, and I uploaded the layer.json file.
3. I uploaded plain text documents (the remaining dataset) in the Documents section
4. Finally, I selected my customised  layer in the automation section, then save
5. I uploaded the training documents, which I previously annotated in Webanno, in webanno TSV3 format.

My issue is that when I press start automation button I got this message [Unsupported anchoring mode: [tokens]] that stop the automation process, please could you advise in this issue.

Please find attached examples of my dataset, the tagset_loc.txt, and layer.json

P.S. All my work is done in the custom layer.

Webanno version 3.5.6
1- Dataset: https://i.postimg.cc/hG1r6GSW/dataset.png
2- tagset_loc.txt: https://i.postimg.cc/6QWR7fNg/tagset-loc.png
3- layer.json: https://i.postimg.cc/YqFPrYkQ/layer-json.png

**Comment by reckart** [comment]
Looking into it...

**Comment by reckart** [comment]
There's a whole bunch of things that needed to be fixed. I have prepared a pull request, but it would be great if you could test that before I merge the changes to make sure they actually fix your issues. Do you know how to build WebAnno from the sources so you could test my changes?

That said: if you are looking for an automation solution, I'd suggest you have a look at INCEpTION. You will find most features from WebAnno there as well and the data format is compatible - but the automation is called "recommender" in [INCEpTION](https://inception-project.github.io) and it is directly integrated into the annotation page. If you configure recommenders, they always learn in the background and make suggestions as you go - no need to explicitly trigger them. Here is a [video](https://www.youtube.com/watch?v=Xz3Hs8Lyoeg&list=PL5Hz5pttaj96SlXHGRZf8KzlYvpVHIoL-&index=3) with a short introduction to the recommenders.

**Comment by Alaa-j** [comment]
Do you know how to build WebAnno from the sources so you could test my changes? No
It works with INCEpTION

Thanks
