### ISSUE TITLE
Tooltips are shown as "alternative text" and not as "pretty windows"

### ISSUE THREAD

**Issue by mmev** [webanno/webanno#132]
related:
https://github.com/webanno/webanno/issues/123

The tooltips are now shown for tagset values like alternative texts in html-sites instead of in the pretty windows we had before already.

See attachment.
![tooltip_normaltag_alttext](https://cloud.githubusercontent.com/assets/5416080/10215971/1ad97b3e-6826-11e5-8d36-4d85f993016a.png)
![tooltip_normaltagname_ok](https://cloud.githubusercontent.com/assets/5416080/10215972/1adade52-6826-11e5-856f-1caa64416164.png)
![tooltip_slottag_alttext](https://cloud.githubusercontent.com/assets/5416080/10215973/1adb78b2-6826-11e5-8b2a-d82d44c3fd10.png)
![tooltip_slottagname_ok](https://cloud.githubusercontent.com/assets/5416080/10215974/1adb7c68-6826-11e5-8e54-4c1c8a8aa7c1.png)

**Comment by reckart** [comment]
The dropdown box creates the value lists not under the elements of the dropdown box in the DOM but rather at a different location (search DOM for elements with IDs like "value143-list").

**Comment by reckart** [comment]
Asked for a better solution than adding the TooltopBehavior to the parent of the Combobox instead of adding it to the Combobox itself... for future reference:

https://groups.google.com/d/msg/wicket-jquery-ui/MplPnTHt1m8/pHBc7TMYBQAJ

**Comment by reckart** [comment]
Sigh... this one is back again...

3.0.0-SNAPSHOT (2016-03-28 18:42:27, build c868352dbd1e6032379f267a875191e3dffb8d11)

**Comment by reckart** [comment]
Downgrading again to Wicket 6.20 and wicket-jquery-ui 6.20.1 - higher versions for some reason break the tooltips.

See also: https://groups.google.com/d/msg/wicket-jquery-ui/MplPnTHt1m8/xaGEgOsXCQAJ

**Comment by reckart** [comment]
Problem appears again in WebAnno -- 3.0.0-beta-4 (2016-05-26 10:45:55, build 5c588cbbd8eb26e5b8e10ec8df88e90cadc85e1b).

**Comment by aakashysharma** [comment]
Could it be related to recent upgrade of dependencies?

**Comment by reckart** [comment]
Downgrading to Wicket 6.20.0 and Wicket JQuery UI 6.20.1 solves the problem - but I have still no idea what causes it.
