### ISSUE TITLE
Modularization of Action Bar

### ISSUE THREAD

**Issue by wpmp** [webanno/webanno#1339]
**Describe the refactoring action**
The action bar in the editor view should be split up into different modules that are integrated into other GUI elements.
The action bar itself will disappear.

**Expected benefit**
This results in a cleaner GUI and enables the possibility to enable/disable certain action bar modules.
For example the PDF editor does not require the pagination par of the current action bar.

**Comment by wpmp** [comment]
@reckart  #1449 is merged, can this be closed?

**Comment by reckart** [comment]
The action bar has a new look and the code has been very much consolidated, but it is not yet possible to "plug" stuff into it - there is no extension point yet for action bar items - so we're not quite done here.

**Comment by reckart** [comment]
Marking this as closed. Further modularization can happen later on.
