### ISSUE TITLE
Export curated documents runs into Auto Logout after 30 minutes on larger projects

### ISSUE THREAD

**Issue by rgsol** [webanno/webanno#1344]
**Describe the bug**
When exporting curated documents on larger projects the export is aborted after 30 minutes by being logged out. The Auto Logout time is not reset periodically to 30 min as it is when exporting the whole project. 

**To Reproduce**
1. Choose the Project.
2. Go to the export tab.
3. Choose WebannoTSV3 format
4. Click "export curated"
5. Wait for being logged out after 30 minutes.

**Expected behavior**
You should never be logged out when exporting. Exporting curated documents should work as it does for the whole project.

**Screenshots**

**Please complete the following information:**
 - Version and build ID: 3.5.7 (2019-05-30 10:48:28, build d929963a33e0bea6075a1f8b1699877718ac97b0) 
 - OS: Linux (Debian 9) on the server, Linux/Windows on the clients
 - Browser: Chrome, Firefox, Opera

**Additional context**

**Comment by reckart** [comment]
This has been fixed as part of https://github.com/webanno/webanno/pull/1556
