### ISSUE TITLE
Viewing documents changes state

### ISSUE THREAD

**Issue by UWinch** [webanno/webanno#1345]
**Describe the bug**
When a manager views the document of another user for the first time, the document changes state to IN_PROGRESS i.e. its name is now marked in blue.

**To Reproduce**
* Add a user to a project that has not annotated any documents yet
* Open this users document from the annotation page as a manager
* Open the document again and see that it is marked blue.

**Expected behavior**
Only the user owning the document should be able to change the documents state.

**Comment by reckart** [comment]
Moved this to 3.6.0 since 3.5.x doesn't include the feature to view other user's annotations.
