### ISSUE TITLE
Directories for running commands for Docker setup aren't specified in the README

### ISSUE THREAD

**Issue by TristanDLM** [webanno/webanno#1348]
In the README for setting up the WebAnno Docker image, commands must be run from different directories, which are not explicitely specified.

**Comment by reckart** [comment]
Would you like to submit a PR to address this issue?

**Comment by TristanDLM** [comment]
Yes, I have addressed it in a local branch. How would I go about doing that?

**Comment by reckart** [comment]
We use the procedure described [here](https://dkpro.github.io/contributing/) at the end of the page under the heading "Preparing a pull request".

**Comment by reckart** [comment]
Ping?

**Comment by reckart** [comment]
No further reaction - closing.
