### ISSUE TITLE
Add a setting to hide the usernames from the dropdown list

### ISSUE THREAD

**Issue by DimitrisGk-iel** [webanno/webanno#1355]
**Is your feature request related to a problem? Please describe.**
In order to add a user as annotator/manager/curator  in a project you have to select her username from a dropdown list that shows  all the available usernames in the system.
There are cases that this is not desirable. We should have an option not to reveal the usernames of the users

**Describe the solution you'd like**
Add some configuration settings to the `settings.properties` file which controls how the auto-complete field behaves. 

In particular the configuration settings ‘hideusernames’ will take a Boolean (true/false) value that will control the behavior of the auto-complete field.

When the ‘hideusernames’ is set to true in order for the Project manager to add a user into an annotation project she has to write into the same text Field the annotator’s full username.  When there is a full match this username is displayed in the dropdown list where the Project Manager can select it and add it to her project.

**Comment by reckart** [comment]
@DimitrisGk-iel I'm afraid the current implementation is not effective. There are two issues:

* clicking into the field, starting to write something and then pressing backspace deleting everything written so far shows all options in the dropdown
* looking at the page source still shows all the users

I'm looking into doing server-side filtering...
