### ISSUE TITLE
Import document to a project

### ISSUE THREAD

**Issue by vaskonov** [webanno/webanno#136]
Hi,

I am trying to import a document in Project settings. The document is just a list of sentences in plain text. The problem is I don't know how to separate the sentences. It seems like webanno loads the entire document as a text and I need to annotate the text sentence by sentence.

**Comment by reckart** [comment]
WebAnno presents a document as a sequence of sentences. It uses a basic heuristic to detect sentence boundaries based on punctuation. Does your document contain punctuation?

**Comment by vaskonov** [comment]
Thank you very much for fast response.
I do have punctuation.
But why I cannot split the text into chunks by myself (for example, with new line)?

**Comment by mmev** [comment]
Is the format one sentence per line?
The new line character matters!

**Comment by reckart** [comment]
If you import plain text (or any other format that does not contain sentence boundaries), then WebAnno will apply a punctuation-based sentence detector (Java BreakIterator). The same for tokens if there are no tokens.

If you do not wish WebAnno to apply this BreakIterator, then you currently have to import using a format that already contains token/sentence annotations (basically every format except plain text).

**Comment by vaskonov** [comment]
Thank you very much for you help.
Where I can find examples of TSV format?

**Comment by reckart** [comment]
I'm afraid it's not very well documented at this time. The easiest way is probably to import a plain text file, then go to the annotation view and there export it as TSV. That could serve as a template for you creating a TSV file.

**Comment by vaskonov** [comment]
This might help me. Thank you very much.
