### ISSUE TITLE
Support relations across layers

### ISSUE THREAD

**Issue by YuhanunC** [webanno/webanno#1365]
Hello developers,

Today I stumbled upon an application (https://github.com/inception-project/inception) that uses this repository for their internal BRAT handling, now, don't get me wrong, it's a great application, but I quickly stumbled into an issue where a relation can only be connected to a single layer type, whereas the official BRAT repository allows this.

Is there any way that we can use a more recent BRAT version with your webanno repo?

Thank you in advance.

**Comment by reckart** [comment]
We only use the brat visualization. The backend works differently. This is not about updating brat, it's about old decisions in the WebAnno code that need to be revised. 

Most of the time you can just work around the issue. Let's say for named entity annotation in brat you would create two annotation, one for "Person" and one for "Location" - and in brat you could make relations between them.

If you create two layers "Person" and "Location" in WebAnno, you cannot create relations between them. What you do instead is create a layer "Entity" and add a feature "category" which can be "Person" or "Location". Then you can nicely define a relation layer on "Entity" and are a happy camper. Doesn't cover all cases, but works often enough.

**Comment by reckart** [comment]
Issue has moved here in INCEpTION: https://github.com/inception-project/inception/issues/1319
