### ISSUE TITLE
Installing webanno on Ubuntu

### ISSUE THREAD

**Issue by vaskonov** [webanno/webanno#137]
Hello,

I read the guideline and it says "This guide assumes Debian 6.0.0 (Squeeze). It may also work on Ubuntu with some modifications, but we do not test this." I am trying to install webanno on Ubuntu, unfortunately I don't have a lot of experience with tomcat settings.

    service webanno start

runs without any error message.

    http://localhost:18080/webanno/

HTTP Status 503 - This application is not currently available

    service webanno stop

runs with error message

Oct 6, 2015 1:10:17 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat6/server/classes], exists: [false], isDirectory: [false], canRead: [false]
Oct 6, 2015 1:10:17 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat6/server], exists: [false], isDirectory: [false], canRead: [false]
Oct 6, 2015 1:10:17 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat6/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
Oct 6, 2015 1:10:17 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat6/shared], exists: [false], isDirectory: [false], canRead: [false]

Do you know how I can fix it?

**Comment by reckart** [comment]
What version of WebAnno are you trying to run?

**Comment by vaskonov** [comment]
WebAnno -- 2.3.0 (2015-07-26 23:34:28, build 4eb3114b375d038ca3b0860cc1fb473ef203b472)

**Comment by reckart** [comment]
Please make sure that you have a Java 7 or higher installed on your machine. You can check on the command line using
  
    java -version

If it is 7 or higher, please check the `catalina.out` file in the folder of the Tomcat instance (probably `/opt/webanno/log` if you followed the installation instructions).

**Comment by vaskonov** [comment]
You are right, I had java 6, after upgrade it started to work. Thank you!
