### ISSUE TITLE
Extend VID for use in editor-extensions

### ISSUE THREAD

**Issue by UWinch** [webanno/webanno#1370]
**Is your feature request related to a problem? Please describe.**
I would like to extend the VID with extension-specific contents and have the extension be automatically set during the rendering process. I hope this will allow me to add several annotations for rendering in an editor extension without re-implementing all rendering code that currently creates VIDs.

**Describe alternatives you've considered**
I thought about re-implementing part of the rendering process similar to the RecommenderEditorExtension and the RecommendationRenderer. However, this requires also implementing element-specific renderers like the SpanRenderer (cf. RecommendationSpanRenderer).

**Additional context**
Will use this for this PR https://github.com/inception-project/inception/issues/1256

**Comment by reckart** [comment]
The VID is already pretty heavy as it is. What do you want to add to it?

Why can't we simply use the existing pre-renderer and then post-process it's output?

**Comment by UWinch** [comment]
I would like to distinguish between annotations of different users when I add all of them for curation. My understanding is that if these annotations are at the same place, they will not be rendered because they have the same VID. It also looks to me that the extensionID which can already be added via VID constructor is only set for VObjects that are explicitly created by the extension, so if I just want to use the existing pre-rendering process, this is not done.

I also thought about post-processing the VDocument after pre-rendering, but I could only come up with changing all VIDs for all elements that are added during one pre-rendering run.
What were your ideas for this?

**Comment by reckart** [comment]
I understand the need to improve the VID. I would suggest to redesign it in such a way that when it contains an extension ID, the format of the rest is actually not defined, i.e. an extension has to parse out the contents itself, potentially even by parsing it again as a VID (e.g. `VID.parse(VID.parse("ext:1@POS`).getExtensionPayload()) == VID.parse("1@POS`)`. That would allow an extension to pack in any additional information into the payload. Does that make sense to you?

So you want to extend the `PreRenderer.render()` method such that you can pass an optional extension ID or even some kind of `VIDFactory` in?

> I also thought about post-processing the VDocument after pre-rendering, but I could only come up with changing all VIDs for all elements that are added during one pre-rendering run.
> What were your ideas for this?

I guess the approach would involve pre-rendering into an empty VDocument for every user and then copying the information into the main VDocument - and during that process also adjust VIDs.

**Comment by UWinch** [comment]
I'm not completely sure that I understand what you're saying about the rest of the VID being undefined if an extensionID exists. My idea was to make the existing `String extensionID` into an object which can contain the name of the extension like it is currently and also additional content via subtyping. We would also need a method to parse a string representation to the specific object.

I would then pass this object to the `prerender.render` and the following render-methods. When these methods are not called from an extension the object would be empty.

Concerning post-processing: yes, I think this would involve going through all elements and adjusting the VID.

**Comment by reckart** [comment]
There is a regular expression in VID which currently defines the format. My suggestion is to change that regular expressions such that a VID can have two basic formats:

* `<EXT_ID>:<EXT_PAYLOAD>`
* or `<ID>-<SUB>.<ATTR>.<SLOT>@<LAYER>` (some elements are optional, cf. `VIDTest`)

When the first format is used, the `<EXT_PAYLOAD>` can be anything the extensions wants. The current INCEpTION recommender extension would use a VID of the second format as the payload.

For https://github.com/inception-project/inception/issues/1256 you could use e.g. `<USERNAME>:<VID>` as the payload where `<VID>` would again be according to the second format given above.
