### ISSUE TITLE
Fix a few typos in the documentation

### ISSUE THREAD

**Issue by bansp** [webanno/webanno#1376]
**Describe the bug**
Found a few typos in the documentation. PR #1375 summarizes the proposed changes.

**Please complete the following information:**
 - Version and build ID:  0.10.2 (2019-07-15 12:40:06, build 473575ebd94f22dcd61bdec3d41c2d816aabd17c)
 - OS: Linux
 - Browser: Chromium

**Comment by bansp** [comment]
Ah, the version ID is INCEpTION's -- I got a bit lost in the documentation dependencies and wondered from there all the way to browsing WebAnno's sources. Will see later if the INCEpTION docs merely duplicate these or 'physically' transclude them.

**Comment by reckart** [comment]
@bansp thanks for the fixes!
