### ISSUE TITLE
JSON I/O mangled Unicode characters

### ISSUE THREAD

**Issue by TomazErjavec** [webanno/webanno#138]
Using WebAnno 2.3.0 some non-ASCII characters (in particular, 'č',) are changed into question marks in Layer / Tagset JSON import or export. We use them not in the tags / features themselves, but in their descriptions in Slovene.

**Comment by reckart** [comment]
This issue might a duplicate of #112.

**Comment by reckart** [comment]
I just tried this with Safari (7.1.8 / OS X) and cannot reproduce it. The exported JSON file contains the non-ASCII chars that I put into the description:

    "tag_description":"çaªaã"

The same with Chrome (45.0.2454.101 / OS X) 

    "tag_description":"çaªaã"

The OS system encoding we use on the server is `en_US.UTF-8`.

The WebAnno version is  3.0.0-SNAPSHOT (2015-09-28 16:45:40, build d27759e452b7cdb7b79cfbbae5bc5f2f0661465e) running on a Java 8 in Apache Tomcat/7.0.28.

What browser, server OS encoding, WebAnno version are you using?

**Comment by reckart** [comment]
Also tried again with Safari (7.1.8 / OS X) against WebAnno 2.3.0 (2015-07-26 23:34:28, build 4eb3114b375d038ca3b0860cc1fb473ef203b472) - also no problem (same server config as above):

    "tag_description":"Öööö çãªan"}

**Comment by reckart** [comment]
Another test explicitly with the character you report problems with against WebAnno 3.0.0-SNAPSHOT (2015-09-28 16:45:40, build d27759e452b7cdb7b79cfbbae5bc5f2f0661465e) with Safari (same as above):

    "tag_description":"çaªaã čč"

**Comment by TomazErjavec** [comment]
I use Chrome 45.0.2454.101 and attach the screenshot below, the "občno_ime" is mangled - but note that (so far) I found only č misbehaving - š, ž are ok (and we don't use other non-ascii chars..)

<img width="960" alt="capture" src="https://cloud.githubusercontent.com/assets/5927714/10320653/db7433fa-6c74-11e5-8686-e8655ce004c3.PNG">

**Comment by reckart** [comment]
I've tried it on Windows 7 with Chrome 45.0.2454.101 m again. No problem.

Could it be that this is no export problem but rather a database problem? Is your MySQL server set up to use UTF-8 encoding / is the database WebAnno uses set up for UTF-8 encoding?

```
mysql> SELECT @@character_set_database;
+--------------------------+
| @@character_set_database |
+--------------------------+
| utf8                     |
+--------------------------+
1 row in set (0.00 sec)
```

And also check your tables:

```
mysql> show create table tag;
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                                                                                                                                                                                                                           |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tag   | CREATE TABLE `tag` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `description` longtext COLLATE utf8_bin,
  `name` varchar(255) COLLATE utf8_bin NOT NULL,
  `tagset` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK1BF9AD2EF8118` (`tagset`),
  CONSTRAINT `FK1BF9AD2EF8118` FOREIGN KEY (`tagset`) REFERENCES `tag_set` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=52650 DEFAULT CHARSET=utf8 COLLATE=utf8_bin |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

See also: http://stackoverflow.com/questions/6115612/how-to-convert-an-entire-mysql-database-characterset-and-collation-to-utf-8

**Comment by TomazErjavec** [comment]
Thanks, v. good suggestions - we'll look into it and report!

**Comment by cyplas** [comment]
I've reproduced this problem now on my local (laptop) installation: WebAnno 2.3.0, Chrome 44.0.2403.155, Ubuntu 14.04.

I get exactly the same output as you from the two MySQL commands you list (except for the AUTO_INCREMENT value).

My locale settings:

```
~ $ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=sl_SI.UTF-8
LC_TIME=sl_SI.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=sl_SI.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=sl_SI.UTF-8
LC_NAME=sl_SI.UTF-8
LC_ADDRESS=sl_SI.UTF-8
LC_TELEPHONE=sl_SI.UTF-8
LC_MEASUREMENT=sl_SI.UTF-8
LC_IDENTIFICATION=sl_SI.UTF-8
LC_ALL=
```

Hmmm ... To be clear how I reproduced this:

1. In Project Settings, I (arbitrarily) selected the STTS tagset and the ADV tag.
2. In its "Tag details" "Description" field, I deleted the default, typed "test čšž", clicked "Save tag".
3. I then selected a different tag and then the ADV tag, and its description now looked like "test ?šž".

So I didn't even have to import or export to reproduce the problem. I checked in the database directly and also found "test ?šž" for that tag's description. I could fix this manually:

```
> update tag set description = 'test čšž' where id = 4;
```

If I do this, the tag description also appears correctly in WebAnno again ...

**Comment by TomazErjavec** [comment]
I stand corrected: same here, i.e. it is not necessary to export or import JSON, it is enought to enter a "č" in the description, save the tagset and re-open, and the 'č' is turned into '?'.

**Comment by reckart** [comment]
I think the details of how MySQL negotiates the encoding of the connection to the database depends on the server version (and probably on the driver version). We use *MySQL 5.5.41-0+wheezy1* on our server side. Additionally, we set the server character set in `/etc/mysql/my.cnf`

    character-set-server = utf8

**Comment by TomazErjavec** [comment]
The above solved our problem, thanks!
I might be a nice to insert this advice into the installation manual in the mySQL section.
