### ISSUE TITLE
Option to disable input fields for Feature Editors

### ISSUE THREAD

**Issue by wpmp** [webanno/webanno#1382]
**Is your feature request related to a problem? Please describe.**
Currently there is no possibility to render features in a read only mode.

**Describe the solution you'd like**
To enable rendering of features in a read only manner an `enabled` flag could be used when creating feature editors.
When set to false the values cannot be modified.

**Additional context**
Required for inception-project/inception#1218

**Comment by reckart** [comment]
Can't you just call `.setEnabled(false)` on the feature editor?

**Comment by wpmp** [comment]
Well, seems like it :(
