### ISSUE TITLE
Navigation loss when importing many documents

### ISSUE THREAD

**Issue by TomazErjavec** [webanno/webanno#139]
I import 89 documents into a project - the import log then swamps the screen, so that no navigation remains. Back button works, so it's a minor usability issue. 
However, pressing back and then forward causes an Internal error (separate issue)

![image](https://cloud.githubusercontent.com/assets/5927714/10323705/1eb4bb3e-6c85-11e5-8768-2673ba51d1f9.png)

**Comment by reckart** [comment]
I *think* the CSS should define a maximum height for the info area. But obviously this is not working (if it is in place). Need to check...
