### ISSUE TITLE
Visualization for long annotations

### ISSUE THREAD

**Issue by Wolkenstein** [webanno/webanno#1393]
Webanno is great for the annotation of small entities like tokens or phrases. Annotating longer passages i.e. in linguistic discourse analysis is a tedious process.
It would be great, if you could provide an annotation view which does not visualize a longer annotation in a single line, but allows line breaks within an annotation.
Thank you and keep up the good work!

**Comment by reckart** [comment]
Current beta versions offer to switch to a "line oriented" mode via the "Settings" dialog on the annotation page. It requires that the original text file contains line breaks.

**Comment by reckart** [comment]
INCEpTION provides a `brat @ 120 characters` visualization mode which pre-wraps the text at 120 characters respecting token boundaries. Additionally, there is the `line-oriented` mode already mentioned above.
