### ISSUE TITLE
Include annotation address in CasMerge result

### ISSUE THREAD

**Issue by UWinch** [webanno/webanno#1401]
**Is your feature request related to a problem? Please describe.**
After merging, I would like to open the inserted or updated annotation in the annotation details editor panel. 

**Describe the solution you'd like**
The annotation is merged using CasMerge, I would like to adapt its result to also return the address of the annotation (or annotations in the case of arcs). I can then use it to set the annotatorstate.selection to the new annotation, calling actionSelect should then open the details editor panel to the annotation.

**Additional context**
For https://github.com/inception-project/inception/pull/1257

**Comment by reckart** [comment]
Sounds good 👍
