### ISSUE TITLE
Reading .ser files

### ISSUE THREAD

**Issue by sonu-gupta** [webanno/webanno#1409]
Hi

I am using webanno. But I am not a java pro. It would be great help to many people like me if you could upload the mechanism to read the .ser files. (annotated_files.)

**Comment by reckart** [comment]
Normally, you shouldn't have to bother with the `.ser` files as WebAnno supports various other more easily accessible formats, e.g. TSV3 and XMI. Why do you need to work directly with the `.ser` files?

**Comment by sonu-gupta** [comment]
Hi, when I export the whole project as TSV, I get the following error message. And the project export fails.
Unexpected error during project export: IllegalArgumentException: End offset must be larger or equal to begin offset: [begin: 9869, end: 9820]

**Comment by reckart** [comment]
Which version of WebAnno are you using?

**Comment by sonu-gupta** [comment]
WebAnno -- 3.5.7

**Comment by reckart** [comment]
Please try WebAnno 3.5.8.
