### ISSUE TITLE
Link feature name inconsistency between project config and xmi file

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#1445]
**Is your feature request related to a problem? Please describe.**
If a project has layer name "hello" lower cased, and if the link feature name (slot feature name) has "world" in lower case, the first character of each gets capitalized when exported to xmi file, as ```custom:HelloWorldLink```

```
    <custom:Hello xmi:id="963" sofa="12" begin="274" end="282" world="975"/>
    <custom:Hello xmi:id="968" sofa="12" begin="331" end="341" world=""/>
    <type2:TagsetDescription xmi:id="981" sofa="12" begin="0" end="0" layer="webanno.custom.Hello" name="tagset1"/>
    <cas:Sofa xmi:id="12" sofaNum="1" sofaID="_InitialView" mimeType="text" sofaString="What is Lorem Ipsum?&#10;Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."/>
    <custom:HelloWorldLink xmi:id="975" role="tag1" target="968"/>
```

**Describe the solution you'd like**
Is it possible to have the slot feature name in xmi (or other exported format) to have excatly the same characters as they are configured in the project settings? If the users want to see the first letter being capitalized, then they can certainly do so in the project settings, but the system shouldn't change the casing of characters.

So, it will end up with below:
```
<custom:helloworldLink xmi:id="975" role="tag1" target="968"/>
```

**Comment by reckart** [comment]
UIMA type names are generated conforming to the UIMA/Java naming conventions for classes. Class names start with capital letters and are written in CamelCase.

**Comment by reckart** [comment]
Mind that `HelloWorldLink` is not a feature name. It is the name of a type (class) which is the element type of the array that the feature `world` of type `Hello` represents.
