### ISSUE TITLE
No highlight over agreed sentences on the annotation panel.

### ISSUE THREAD

**Issue by Alrahabi** [webanno/webanno#1448]
Hi,
I am doing a curation for a document annotated by 3 different annotators.
It works well for the first 68 pages, but starting on page 69, agreed annotations do not appear in the ANNOTATION panel :
![curation](https://user-images.githubusercontent.com/9264660/64820742-51cfa080-d5b1-11e9-8634-7e05b2f44536.JPG)
Could you help me please?

Thanks.

**Comment by Alrahabi** [comment]
Thank you for your answer!
Please find attached the project in UIMA Binary CAS format.
Regards
[Arabic_2019-09-13_0954.zip](https://github.com/webanno/webanno/files/3608962/Arabic_2019-09-13_0954.zip)

**Comment by seyyaw** [comment]
@Alrahabi I have observed the same behavior as you have described. However, If I `Re-Merge` the curation, they are available. See below. 
![image](https://user-images.githubusercontent.com/1056051/64892411-f9240480-d691-11e9-8c30-74cd1237cfab.png)
![image](https://user-images.githubusercontent.com/1056051/64892437-0d680180-d692-11e9-85ef-e484e2763e93.png)

Do you ever re-open documents for annotation once the curation was started? In that case, maybe the automatic curation is performed and the initial curation document is created. You can see also, for example in Sentence 7 `المسجد الحرام` is annotated as `LOC-Build` but it is not available in the annotation pane.

**Comment by Alrahabi** [comment]
> Do you ever re-open documents for annotation once the curation was started? In that case, maybe the automatic curation is performed and the initial curation document is created. You can see also, for example in Sentence 7 المسجد الحرام is annotated as LOC-Build but it is not available in the annotation pane.

**Yes I did that. Do you mean that if I do the Curation I will not be able to continue the Annotation process again? I there a solution to delete such file?
Thanks.**

**Comment by seyyaw** [comment]
In this case, you have two options

1. Continue curation but the user should manually verify those new annotations (past as well future from the point new annotation document joins the curation). This important when the curator already addressed have a lot of progress on the curation.
1. `Re-Merge` the curation document but then if there are manually verified annotations, they will be lost.

**Comment by Alrahabi** [comment]
Ok, I choosed option1: 
>Continue curation but the user should manually verify those new annotations (past as well future from the point new annotation document joins the curation). This important when the curator already addressed have a lot of progress on the curation.

Now I obtain this agreement.csv file (attached), but the problem is that I get annotations that I did not validate during the curation. Please see screenshot.
Thank you again for your help.

[Desktop.zip](https://github.com/webanno/webanno/files/3618051/Desktop.zip)

**Comment by seyyaw** [comment]
@Alrahabi This is strange. Unless the user validated those annotations, I do not think they are automatically obtained ones. You can see at least that the first annotation (`LOC-Build`) is on different span annotation as far as I can see.
@reckart Do you have any idea why those annotations appear there without the user validation?

**Comment by reckart** [comment]
@Alrahabi was that screenshot taken directly after pressing "Re-merge" (without enabling the "Merge incomplete annotations" option and without changing the state of documents between the remerge and the screenshot)?

**Comment by Alrahabi** [comment]
>@Alrahabi was that screenshot taken directly after pressing "Re-merge" (without enabling the "Merge incomplete annotations" option and without changing the state of documents between the remerge and the screenshot)?

@reckart That screenshot was taken after changing the state of documents in the "Monitoring" page, and without pressing "Re-merge" in the "Curation" page.
I don't know really where we can enable the "Merge incomplete annotations" option?

>You can see at least that the first annotation (LOC-Build) is on different span annotation as far as I can see.

@seyyaw That is the problem: all the suggestions appear in the agreement file (please see the scrrenshot2).
![screenshot2](https://user-images.githubusercontent.com/9264660/65033906-403a2000-d946-11e9-9045-41692a100408.png)

Is there any way to fix all these issues without restarting the whole work?

Thank you for your help!

**Comment by reckart** [comment]
The annotation you marked as `I didn't validate this entity...` appears in the agreement file in the column of the use who created this annotation. The "CURATION" (i.e. what you see in the upper part of the screen on the Curation page) does not appear in the agreement file at all.

The agreement file is meant to provide you with all the data from all the annotators such that you can calculate your own agreement measures outside of WebAnno.

If you want instead to export the data from the upper part of the curation page, then you need to do this via the "export" tab in the project settings and selecting "Export curated documents" there. Mind that the respective documents need to have been marked as "Finished" on the curation page before they are included in the export.

**Comment by seyyaw** [comment]
@Alrahabi And the issue I guess here is that you re-open the documents for annotation after curation is started. That creates these inconsistencies, curation should be started once all annotators are doone with the annotation. As @reckart  said, either export the curated document and manually merge the incomplete annotations from the individual files, or manually verify in the curation page for such inconsistencies, or do `Re-Merge`.

**Comment by Alrahabi** [comment]
Ok, it's very clear now!
Thank you for your answers and explanations !
