### ISSUE TITLE
Missing tags in CONLL format.

### ISSUE THREAD

**Issue by sonu-gupta** [webanno/webanno#1451]
Hi, 

I have enabled multiple/overlapping tags for a token, But when I export the output data in CONLL2002 file format, I get only one tag per token. Other tags are simply omitted from the output file. It would be great if you could fix this issue. 

Thanks.

**Comment by reckart** [comment]
The CONLL 2002 format does not permit multiple tags per token. Cf. https://www.clips.uantwerpen.be/conll2002/ner/

**Comment by reckart** [comment]
If you want to export overlapping NER annotations, you need to use e.g. TSV3 or XMI.
