### ISSUE TITLE
Inconsistent export results

### ISSUE THREAD

**Issue by sonu-gupta** [webanno/webanno#1456]
Hi

If I export a project in UMI CAS JSON format, I get inconsistent results. Below are the few instances: 
- sometimes end/begin key are not present.
- even though there are annotations for a particular document, I don't get 'NamedEntity' key and the corresponding tags from the exported json. If I go back to the document and manually export the particular document, I am able to get the 'NamedEntity' tags. Not sure why this inconsistency occurs. Any help would be great.

Thanks.

**Comment by reckart** [comment]
Can you post a snippet of the JSON where the begin/end keys are missing?

When you export the entire project as a ZIP archive, in which folder are you looking for the JSON files with the named entity tags?

**Comment by reckart** [comment]
Closing this issue since there was no further input provided by the user.
