### ISSUE TITLE
setting focus to the first input element of the editor

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#146]
The existing DefaultFocusBehavior fails for combobox elements (those with tagset) to set focus on the first input element. This is because the combobox element with markup ID (obtained  **component.getMarkupId()**) is hidden (*style display:none*).

Solution: Get the first non hidden, non button input element and set focus there.

**Comment by reckart** [comment]
The getFocusComponent() of the different feature editors (including the combo with tagset) should return the correct ID to put the focus on. Scanning the dialog for non-button elements should not be necessary.

**Comment by seyyaw** [comment]
Correct, it returns the correct id but the implementation of the  combobox from com.googlecode.wicket.kendo.ui.form.combobox.ComboBox is  hidden (style display:none) for some reason, hence can't catch the focus.

**Comment by reckart** [comment]
Wow, that's wierd! Looks like kendo hides the original input (the one with the ID) and then creates a second input which then doesn't have the ID of course...

**Comment by seyyaw** [comment]
I think so,
I tried forcing *display:inline* in the style, then what happened?
Two elements are displayed, one is the real combobox, the other looks a textfield. But both display the same value.

**Comment by reckart** [comment]
I have filed an issue with the Wicket JQuery/Kendo guy Sebastien: https://github.com/sebfz1/wicket-jquery-ui/issues/211

Let's see what he says.

**Comment by reckart** [comment]
As far as I understand Sebastien and the link to the Kendo documentation that he posted in his reply to the issue above, it should be possible to obtain a pointer to the new input from a "wrapper" attribute on the old input. Maybe you want to have a look. Or at least we have a point to pick up from if the current fix to the focus problem has unwanted side effects.

**Comment by reckart** [comment]
@seyyaw so what is the final verdict on this issue and the reason for closing it?

**Comment by seyyaw** [comment]
related to #243 yes? Should be closed

**Comment by reckart** [comment]
Yep, should have been covered as part of #243. :)
