### ISSUE TITLE
Radio choice editor for number features triggers error

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#1479]
**Describe the bug**
When the radio buttons editor is active, the Wicket AJAX console reports that the editor component cannot be found for setting the focus

**To Reproduce**
1. Set the editor of a numeric feature to radio choices
2. Enable the Wicket debug mode
3. Edit the numeric feature on some annotation
4. See how the AJAX debug widget flashes red

**Expected behavior**
Optimally, it should be possible to navigate the radio-choices using the keyboard. At least, there should not be an error.

**Please complete the following information:**
 - Version and build ID: 72a1b327b0844369a492b348bc9d0f3fbd395ce6

**Comment by reckart** [comment]
@wpmp Have we fixed this along with #1496 ?

**Comment by wpmp** [comment]
@reckart Yes, this is fixed with #1496
