### ISSUE TITLE
Automatic codebook merge broken

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#1486]
**Describe the bug**
When there are agreements between different annotators, codebooks should be copied automatically. It . is not anymore merging the annotation even for single annotator

**To Reproduce**
Finish a codebook annotation document and open it in curation page

**Expected behavior**
Agreed codebook annotation should appear to the codebook editor automatically.

**Please complete the following information:**
 - Version and build ID: [Codebook PR]
 - OS: [eAll]
 - Browser: [ALL]

**Additional context**
Probably, it is broken due to the recent refactoring o the agreement model. Check the related changes

**Comment by reckart** [comment]
Closing as it has already been merged into the codebook branch
