### ISSUE TITLE
Default curation selects union and not overlap of annotators

### ISSUE THREAD

**Issue by MeDarina** [webanno/webanno#149]
In curation, all annotations made by the annotators are shown in "Annotation" (Upper field that shows the curation) by default. In the older versions, it was always the overlap that was shown (only annotations that all annotators made).

**Comment by reckart** [comment]
I haven't seen this actually happening. In which WebAnno version did you observe this behavior?

**Comment by seyyaw** [comment]
Is this still a bug @MeDarina ?

**Comment by sholschneider** [comment]
Using WebAnno -- 3.0.0-beta-5 (2016-06-05 16:13:47, build 4e88794ca674a2c793e90d27156361f9a51a8957) on Chrome, I don't see the bug described by @MeDarina. Instead, I don't see any annotations at all.

**Comment by reckart** [comment]
@sholschneider Please go to the settings dialog on the curation page and ensure that all the layers you expect to see are actually enabled/visible.

**Comment by sholschneider** [comment]
Oops! Sorry! Though, it isn't the overlap that is shown (as described by @MeDarina ).

**Comment by seyyaw** [comment]
which project and file?

**Comment by sholschneider** [comment]
Sentiment DB/15_09_05_d1441422303009_predictions_dataset_tokenized_01.tsv

**Comment by seyyaw** [comment]
That seems the user already merge them.
I tried two options after exporting it to my local installation
1. click re-merge --> Only the agreed one are copied to the annotation pane
2. delete manually the curation CAS file to re-create the merge case --> Only the agreed one are copied to the annotation pane

Are you sure the curator do not click in one of the user's annotatipn?

**Comment by MeDarina** [comment]
It is the default I got before recreating the merge. When recreating the merge, everything was fine. At least it was like that when I reported the bug. If there is some project (with data)  I can test in, please tell me, I will try. I just don't want to break existing projects and I don't have "fresh" data.

**Comment by seyyaw** [comment]
Ok, I try doing it from scratch and can not reproduce. 
I ask you just to upload new documents, make annotation with different user and see if the default merge is as expected.

**Comment by seyyaw** [comment]
@MeDarina @sholschneider please re-open and describe how to reproduce the error. I tried to reproduce but I do not see the error (tried two times with the same project @sholschneider indicated already)
