### ISSUE TITLE
Put document text outside of annotation CAS

### ISSUE THREAD

**Issue by jcklie** [webanno/webanno#1493]
**Is your feature request related to a problem? Please describe.**
Right now, the text to annotate is saved for every user in his own Cas. It would be nice to deduplicate that.

**Describe the solution you'd like**
Maybe use sofaUri.

**Describe alternatives you've considered**

**Additional context**

**Comment by reckart** [comment]
For the time being, we'll stay with the text in the CAS. In particular, if we may want to consider in the future to allow edits to text, having separate texts for every user is important. For the most part, loading the text as part of loading/saving the annotations is not a major impact to speed either. So let's table this one until it might crop up again as part of some greater scenario.
