### ISSUE TITLE
Project creation:Jump to tagset creation source from current project

### ISSUE THREAD

**Issue by MeDarina** [webanno/webanno#150]
After importing a tagset (from another project) to the current project, WebAnno jumps to the (original) other project when clicking on the tagset. However, it should stay in the current project.

**Comment by MeDarina** [comment]
Same happens for the features (when selecting the features of a label that was created in another project, WebAnno jumps to the other project).

**Comment by aakashysharma** [comment]
I can confirm that this happens. However, this happens only if tagset is exported as json and imported into other project without going back to homepage. Actually, if you export tagset as json, the (other) project will show tagsets which even don't belong to that project. Somehow the tab is not refreshing for this currently selected (other) project.

If tagset is exported as tab separated file and imported, this doesn't happen. I'll investigate further and fix this.

**Comment by aakashysharma** [comment]
@reckart Why in AnnotationService API 
```void createTagSet(TagSet aTagSet, User aUser)``` is not linked to a project, 

while getting a TagSet has no involvement of user.
```public TagSet getTagSet(String aName, Project aProject)```

**Comment by reckart** [comment]
@aakashysharma the project is a field inside TagSet and needs to be set before calling createTagSet. 

The user is actually just passed to createTagSet for logging and we do not generate a log-message with the username in getTagSet().

**Comment by reckart** [comment]
@aakashysharma are you still working on this one?

**Comment by aakashysharma** [comment]
Not at the moment, but see my first comment.

**Comment by reckart** [comment]
@aakashysharma It says "I'll investigate further and fix this." right? ;)

**Comment by aakashysharma** [comment]
_"If tagset is exported as tab separated file and imported, this doesn't happen."_

**Comment by reckart** [comment]
@aakashysharma I read that as 1) a workaround and 2) an indication where to debug the code in order to understand why it happens for JSON (but not for tab-separated). But I don't see how it relates to my question if this is still being worked on.

**Comment by reckart** [comment]
Cannot reproduce this in 3.4.5-SNAPSHOT (2018-07-08 21:33:52, build b483c04774de4623400014802c7799decf83b333). Assuming that it has been fixed as part of the big refactoring of the project settings some time back.
