### ISSUE TITLE
Labels are exported together with tagset

### ISSUE THREAD

**Issue by MeDarina** [webanno/webanno#151]
After importing a tagset (from another project) to the current project, WebAnno exports the layer (and if available, also the "relating" layer) to the current project. 
Not completely sure, whether that is what is intended, because if one exports the tagset, one probably needs the tagset only.

**Comment by aakashysharma** [comment]
Hi @MeDarina 

Which version are you using?
I checked exported tagset file, it only contains the tags (and their descriptions). 

I think what you might be seeing is when that the tab (Project/Layer/Tagsets/Constraints) in "project settings" doesn't refresh completely.

Could you confirm the following in your instance of Webanno

After importing a tagset from some other project_A to project_B, click on "Home" on the top-left bar. Click on project settings again. Go to another project which is not project_A. Do you still see any layer from project_A?

Thanks

**Comment by aakashysharma** [comment]
Looks like this is related to #150. Closing this for now, will test this after #150 is fixed. If it's still not fixed, I'll re-open.
