### ISSUE TITLE
Unable to access curation page

### ISSUE THREAD

**Issue by sonu-gupta** [webanno/webanno#1517]
Hi

When I try to open curation page, I get the following error. I am not a Java expert. It would be great if anyone could help debug this. I am using webanno 3.5.7. 

**Error: org.hibernate.exception.GenericJDBCException: could not extract ResultSet**

Thanks.

**Comment by reckart** [comment]
Can you log at the console/server log and post the full stack trace of this exception?

Are you using MySQL or the embedded DB?

**Comment by sonu-gupta** [comment]
I am using MySQL. And I get this error on WebAnno console.

**Comment by reckart** [comment]
Do you see any list of class names (i.e. a stack trace) close to the message similar to what you can find in the issue description of https://github.com/inception-project/inception/issues/346 ?

**Comment by sonu-gupta** [comment]
I accidentally deleted logs. :| Anyways, I removed some files from the disk just to make more space. Now I am able to access the curation page. Not sure what went wrong in the first place. Thanks.
