### ISSUE TITLE
Upgrade to UDv2 POS and dependency tagsets

### ISSUE THREAD

**Issue by bguil** [webanno/webanno#1521]
In the UD tagset, there is no `CONJ` tag but `CCONJ` (https://universaldependencies.org/u/pos/index.html).
The following line should be changed:

https://github.com/webanno/webanno/blob/2dbc603c8909426aa12892e2f3ee0f8b7ae9fde4/webanno-api-dao/src/main/resources/tagsets/mul-pos-ud.json#L22

**Comment by reckart** [comment]
Looks like this is something they changed for UD POS V2: https://universaldependencies.org/v2/postags.html
