### ISSUE TITLE
Cannot log via AAI; no CLARIN help desk button found

### ISSUE THREAD

**Issue by florianschiel** [webanno/webanno#1527]
I could not log in via AAI. I tried FF and Chrome and always got stuck on this page (no content shown) after logging in:
https://lmuidp.lrz.de/idp/profile/SAML2/Redirect/SSO?execution=e1s1
I then looked for a link to the CLARIN help desk to open a ticket, but I could not find one on the WebAnno start page.
That's why I try it here. Since this is more of a user problem, you might forward me to the appropriate CLARIN help desk queue.

Best regards,

Florian Schiel

**Comment by reckart** [comment]
You can send a message to the CLARIN helpdesk here: 

https://support.clarin-d.de/mail/

I've also just tried to log in to the Tübingen CLARIN-D WebAnno and I also get stuck at an empty page with the browser trying to load `https://webanno.sfs.uni-tuebingen.de/webanno/`. So it looks like the Tübingen WebAnno might be down.

@ttrippel Do you know if there are currently any issues with the Tübingen WebAnno?

**Comment by reckart** [comment]
@florianschiel Did you have any luck reaching CLARIN support?

**Comment by reckart** [comment]
Closing as there was no additional feedback.
