### ISSUE TITLE
annotation issues at end of lines in plain text imports

### ISSUE THREAD

**Issue by cyplas** [webanno/webanno#154]
There seem to be several problems when importing plain text files where the end-of-lines don't correspond to sentence boundaries. WebAnno divides the text file into sentences correctly, but behaves strangely in several ways when text is selected around the end-of-lines:

1. No space is shown between the last word at line i and the first word at line i+1.
2. When double-clicking somewhere within such a pair of words, they are both selected, contrary to the normal behaviour of selecting the current token.
3. When the annotation pop-up window comes up, a space does appear between the words, contrary to point 1.
4. When an annotation is added, it is applied twice, once to each of the two words (unless the layer is a single-token layer, I think: contrast the behaviour between Lemma and Chunk).

For an example, see the automation document in project test_cyp, document test.txt, user guest on your public installation. I attach test.txt here.
[test.txt](https://github.com/webanno/webanno/files/31810/test.txt)

**Comment by reckart** [comment]
Screenshot of the phenomenon:

![2015-11-14_12-41-30](https://cloud.githubusercontent.com/assets/1410238/11163375/18bee91e-8acd-11e5-99b0-fe0794526d46.png)

**Comment by reckart** [comment]
TSV export of the first sentence - looks like the annotation is created as a single span over two tokens and rendered as two spans. 

Appears like a bug in the code that expands the selection in "lock to multiple token" mode.

```
 # de.tudarmstadt.ukp.dkpro.core.api.syntax.type.chunk.Chunk | chunkValue # de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Lemma | value
#id=1
#text=The JANES corpus of Slovene user generated content licensed to theApache Software Foundation (ASF) under one or more contributor licenseagreements.
1-1	The	O	_	
1-2	JANES	O	_	
1-3	corpus	O	_	
1-4	of	O	_	
1-5	Slovene	O	_	
1-6	user	O	_	
1-7	generated	O	_	
1-8	content	O	_	
1-9	licensed	O	_	
1-10	to	O	_	
1-11	the	B-clicked on p in theApache	_	
1-12	Apache	I-clicked on p in theApache	_	
1-13	Software	O	_	
1-14	Foundation	O	_	
1-15	(	O	_	
1-16	ASF	O	_	
1-17	)	O	_	
1-18	under	O	_	
1-19	one	O	_	
1-20	or	O	_	
1-21	more	O	_	
1-22	contributor	O	_	
1-23	license	O	_	
1-24	agreements	O	_	
1-25	.	O	_	
```

The second sentence looks like a bug in the code that expands the selection in "lock to token" mode.

```
#id=2
#text=See the NOTICE file distributed with this work foradditional information regarding copyright ownership.
2-1	See	O	_	
2-2	the	O	_	
2-3	NOTICE	O	_	
2-4	file	O	_	
2-5	distributed	O	_	
2-6	with	O	_	
2-7	this	O	_	
2-8	work	O	_	
2-9	for	O	clicked on t in foradditional	
2-10	additional	O	_	
2-11	information	O	_	
2-12	regarding	O	_	
2-13	copyright	O	_	
2-14	ownership	O	_	
2-15	.	O	_	
```

So in summary, there appears to be a problem with newline characters in the code that expands the selection in "lock to token" and "lock to multiple token" modes.

**Comment by reckart** [comment]
@seyyaw can you have a look at this one?

**Comment by seyyaw** [comment]
This is partly brat problem and partly the text reader problem. I think either the text reader might consider texts per new line as a sentence Or brat should add white space for line breaks. While there exist a line break beteween **the** and **Apache**, brat display them as a single token. On double click, it selects both tokens. WebAnno acts correctly, sending a single Annotation (for example above, it sends an Entity from offset 63 to 73 as Named Entity) but brat behaves starngely here, displaying two annotations separately (as they are still single annotation, you can modify both as same time)
I suggest we replace new lines with white spaces, only for visiualization purpose. Everything internally will not be affected, for example exporting will be as it is imported by the text reader.

Please re-open if there is a better approach

**Comment by reckart** [comment]
Sounds like an effective solution. I don't have any better idea either. A comment in the source code referring to this issue would be nice.
