### ISSUE TITLE
Span annotations that consist of several lines make the "Actions"-box disappear

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#155]
Span annotations that consist of several lines make the "Actions"-box disappear, for example when using the "translation" layer in "darina-sem-rel".

**Comment by reckart** [comment]
Which version of WebAnno are you using? (The version string is at the bottom of the screen - if you use a SNAPSHOT version, please also include the hexadecimal commit ID)

Can you post a screenshot showing the effect?

**Comment by sholschneider** [comment]
I have been using WebAnno version 3.0.0-SNAPSHOT (2015-11-12 03:41:29, build 96e6ae709389b557c37b672a1537b30bfd48d49d). 
![missingactionsbox](https://cloud.githubusercontent.com/assets/13764947/11324620/3cfec630-9137-11e5-9e15-9786d40228c2.PNG)

**Comment by sholschneider** [comment]
When continuing the annotation without the "Actions"-box, the box reoccurs after the next document has been opened via "Next". However, the buttons ("Delete", "Clear", etc.) inside this box are inactive and cannot be used. 
![inactivebox](https://cloud.githubusercontent.com/assets/13764947/11446535/77b0b630-9538-11e5-91ee-b552ccbf4319.PNG)

**Comment by MeDarina** [comment]
Annotation (New annotation and deletion) is completely impossible after this error (for this layer).

**Comment by reckart** [comment]
Duplicate of #286 which has been fixed.
