### ISSUE TITLE
FeatureEditors should handle their updates themselves

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#1561]
**Describe the refactoring action**
Instead of the ADEP registering an Ajax update behavior on every feature editor, the feature editor should internally handle its AJAX update and then just send a Wicket event when there is a new value.

**Expected benefit**
Less redundant code, more flexibility when implementing feature editors.

**Comment by wpmp** [comment]
Sounds good, this would also solve the problem of setting feature values too fast and getting reset again because not the entire sidebar but only the editor would be reloaded, right?

**Comment by reckart** [comment]
Not really. But it solves the problem that I need to be able to request additional data in the AJAX call that the frontend makes because what the frontend by default thinks is the feature value is actually not unique: https://github.com/inception-project/inception/issues/1559

**Comment by reckart** [comment]
Basically, what I am doing here is using the `FeatureEditorValueChangedEvent` that you introduced for all feature editors.

**Comment by wpmp** [comment]
Ah, ok, I misunderstood. :)
