### ISSUE TITLE
Shortcut to delete annotations

### ISSUE THREAD

**Issue by ducalpha** [webanno/webanno#1567]
Are there any shortcut keys in WebAnno for deleting annotations?

Currently, we need to use the mouse to do all the steps: double click on the annotation to select it and move the mouse to click the "Delete" button. Doing annotation will be much faster if there is some shortcut key like "dd" (double d) to delete an annotation.

**Comment by reckart** [comment]
A key combination like CTRL-BACKSPACE would IMHO make more sense because that would also work while the focus is on an input field.

**Comment by ducalpha** [comment]
That's right, I did not think of when the user was in an input field. Maybe a combination like CTRL-D is also good.

**Comment by reckart** [comment]
Letters and numbers should be unbound by default so users can bind feature values to them with the configurable keybinding support that will be introduced with WebAnno 4.0.0.

**Comment by ducalpha** [comment]
For a quick fix, I added some shortcuts by a Chrome extension: https://github.com/ducalpha/webanno_shortcuts

**Comment by reckart** [comment]
Has been added to INCEpTION 21.0.1 - https://github.com/inception-project/inception/issues/2306
