### ISSUE TITLE
I could not locate the settings.properties file 

### ISSUE THREAD

**Issue by abreal555** [webanno/webanno#158]
I deployed webanno WAR file into tomcat server I had tomcat already installed so I just skipped the installing tomcat steps from installation manual. also I do not have www-data user so I just used root user and gave it the permission to access folder under srv. the thing is I created a directory with name webanno under srv but when it  comes to this step" edit settings.properties" I could not find this file.  Is this file supposed to be installed with deployment process? 

I need to update the data source information so I just updated the databaseContext.xml and updated the "dataSource"  with this info"driverClassName" value="com.mysql.jdbc.Driver" "url" value="jdbc:mysql://localhost:3306/webanno" and "username" value="webanno" 
		and "password" value="t0t4llYSecreT" 

but unfortunately the warning msg still shown in the webanno home page "USE THIS INSTALLATION FOR TESTING ONLY -- AN EMBEDDED DATABASE IS NOT RECOMMENDED FOR PRODUCTION USE"

**Comment by reckart** [comment]
The `settings.properties` is not created automatically - it must be created manually.

**Comment by Acromonkey** [comment]
Thank you very much, that was indeed the solution!!
