### ISSUE TITLE
Wicket Ajax error when refreshing settings-page

### ISSUE THREAD

**Issue by UWinch** [webanno/webanno#1581]
**Describe the bug**
A wicket Ajax error is thrown when the settings page is refreshed in Inception. This does not hinder the execution of the application, however it interferes with additional javascript functions implemented for https://github.com/inception-project/inception/pull/1405

**To Reproduce**
1. In inception: import a new document into a project
2. Open the wicket ajax debug console and see that the sidebar component can not be found for refresh.

**Expected behavior**
The sidebar is invisible in inception and therefore does not need to be refreshed. The page is refreshed via `WicketUtil.refreshPage`. In my opinion it would make sense to only refresh those children of the page that are visible.

**Please complete the following information:**
 - Version and build ID: Inception 0.15.0
 - OS: ubuntu
 - Browser: chrome

**Comment by UWinch** [comment]
Turns out the error was not relevant after all.

**Comment by reckart** [comment]
The error is not critical, but it's still there, right? Or did you fix it?

**Comment by UWinch** [comment]
> The error is not critical, but it's still there, right? Or did you fix it?

It's still there. My fix seemed to have a side-effect on dropdowns, so I didn't push it. However, we can leave the issue open and I'll get back to it after I finish my current PRs.

**Comment by reckart** [comment]
Let's leave it open as long as it is unfixed.
