### ISSUE TITLE
Improve VIDs

### ISSUE THREAD

**Issue by UWinch** [webanno/webanno#1585]
**Is your feature request related to a problem? Please describe.**
Our VIDs are complicated to use, we should:
* re-work/check the constructors (for extension ids, layerid, subannoid exist as parameters but only the payload is used).
* document the constructors
* check if we can remove the duplicate id

**Comment by reckart** [comment]
Will do this if it comes up during a particular refactoring or performance optimization but won't be a refactoring action on its own. Thus closing.
