### ISSUE TITLE
ApplicationEvent when annopage is created

### ISSUE THREAD

**Issue by UWinch** [webanno/webanno#1598]
**Is your feature request related to a problem? Please describe.**
For one of the INCEpTION PRs, I will need to be notified when the annotationpage is created i.e. to imply that the user opened this page via dashboard or url.

**Describe the solution you'd like**
Publish an applicationevent.

**Describe alternatives you've considered**
Cannot add this as a Metadata to the annopage from INCEpTION because editorextension needs the information which has no knowledge of the page.

**Additional context**
https://github.com/inception-project/inception/pull/1257/

**Comment by reckart** [comment]
It sounds strange that the backend would need to listen to whether something in the UI was created. Can you explain this in more detail

**Comment by UWinch** [comment]
I have an annotationeditorextension that should only render some suggestions after the corresponding sidebar has been opened but not directly when the annotationpage is opened from either the dashboard or an url. This means we must somehow find out when the user leaves the page or how I want to do it here, when the user freshly opens the annotation page.
We thought about saving a state as metadata to the page, this would tell other UI elements if the suggestions should be shown but not the annotationeditorextension, because it has no knowledge of the annotation page and its metadata.

**Comment by reckart** [comment]
@UWinch is this change still on the table?
