### ISSUE TITLE
Curator unable to see which parts of a document are already curated

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#16]
Improve sentence coloring so that it depends on the "agreement" between the curated part and with each of the annotators instead of what is done currently, namely the showing the agreement between annotators.

Specifically, if for each annotation on which the annotators do disagree, the merge view agrees with at least one of the annotators, then the sentence should be shown as green. Examples.

| Anno 1 |  Anno 2 | Complete | Agree | Merged | Auto | Cur Act. | Sentence | Explanation |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| ADJ | ADJ | yes | yes | ADJ | yes | accept | GREEN | Agreement amongst annotators. Was auto-merged and curator did not change it. Nothing more to do. |
| ADJ | ADJ | yes | yes | DET | yes | change | GREEN | Agreement between annotators. Was auto-merged, but curator choose to change it. Assuming curator is correct, so nothing more to do. |
| ADJ | ADJ | yes | yes | --- | yes | remove   | GREEN | Agreement between annotators. Was auto-merged, but curator choose to delete. Assuming curator is correct, so nothing more to do. |
| DET | ADJ | yes | no | ADJ | no | accept 2 | GREEN | Annotators do not agree, so no auto-merge. Curator chose opinion from annotator 2. Assuming curators choice was correct. Nothing more to do. |
| --- | ADJ | no | yes | ADJ | no | accept 2 | GREEN | Annotations not complete, so no auto-merge. Curator chose opinion from annotator 2. Assuming curators choice was correct. Nothing more to do. |
| DET | ADJ | yes | no | --- | no | UNKNOWN   | RED | Annotators do not agree, so no auto-merge. Curator may have not want any annotation at all or may not have made a choice yet. Not sure if anything left to do. |
| --- | ADJ | no | yes | --- | no | UNKNOWN | RED | Annotations not complete, so no auto-merge. Curator may have chosen opinion from annotator 1 or may have done nothing at all yet. Not sure if anything left to do. |
| --- | --- | n/a | n/a | ADJ | n/a | added | GREEN | Annotators have no annotation at all. Curator explicitly added an annotation. Assuming curator is correct, so nothing more to do. |
| --- | --- | n/a | n/a | --- | n/a | none | GREEN | No annotations, so nothing to worry about. |

In most cases we can look at the annotations and decide whether the curator has already taken a wilful action or whether we are pretty sure that no wilful action is required. However, in two cases, we cannot decide - they will always remain RED unless we allow the curator to somehow specify that a choice has been made.

**Comment by seyyaw** [comment]
This is a major change to the curation view @reckart . What about moving it to post 3.0 release?

**Comment by reckart** [comment]
@seyyaw Indeed. I hadn't noticed this was still on 3.0.0. Moved to 3.1.0.

**Comment by reckart** [comment]
This should be handled ok now in INCEpTION: https://github.com/inception-project/inception/issues/2193
