### ISSUE TITLE
I'd like webanno to keep track of the current protocol when doing redirection.

### ISSUE THREAD

**Issue by JnMik** [webanno/webanno#1600]
Hello guys ! 

**Is your feature request related to a problem? Please describe.**
Application redirects to HTTP protocol even when accessed to HTTPS protocol

```
curl -i https://<my domain>
HTTP/2 302 
date: Tue, 04 Feb 2020 22:30:06 GMT
content-length: 0
location: http://<my domain>/login.html
```

**Describe the solution you'd like**
I would like the application to detect it's getting hit on HTTPS and keep the current protocol with the redirects.

**Describe alternatives you've considered**
Being able to specify an environment variable to the container, PROTOCOL=HTTPS

**Additional context**
Webanno application run into kubernetes, in HTTP. I put a load balancer in front of it and install the certificate in the load balancer. The application doesn't seem to be aware that the navigation is done with https and tries to redirect to port 80.

Maybe something already exist for that ? 
thanks!
jm

**Comment by reckart** [comment]
Normally, the reverse proxy would be responsible for re-writing the URLs on the way back.

Cf. https://serverfault.com/questions/551700/apache-url-rewriting-in-reverse-proxy

**Comment by reckart** [comment]
Just recently stumbled across this.

Use the standard Spring Boot configuration properties in the settings.properties file to tell it which header to look into for the remote protocol. Note that the properties may be different for WebAnno 3 (using Spring Boot 1) and WebAnno 4 (using Spring Boot 2).

Cf. e.g. `server.tomcat.protocol-header` documented in https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
