### ISSUE TITLE
Importing partial Conll-u format for automation

### ISSUE THREAD

**Issue by lmompela** [webanno/webanno#1602]
**Describe the bug**
I have a conll-u file with, per line, the token, the lemma, and the pos tag. I'm unable to upload this document for automation. When uploading it prints : 
"Error while uploading document DOMcorpuscreole.conllu: NumberFormatException: For input string: "_""

**To Reproduce**
1. Go to projects
2. Create an automation project
3. Click on Documents
4. Upload Conll-u document
5. See error

**Expected behavior**
I would like to be able to import a partial conll-u file for automation, since I did POS tagging on one software and plan on doing dependencies on Webanno.

**Screenshots**
![image](https://user-images.githubusercontent.com/49000319/74443654-8b972280-4e41-11ea-9617-c0d213f57e06.png)

The sections per line are tab-separated (it may not look like it on Atom).

**Please complete the following information:**
 - Version and build ID: [WebAnno -- 3.6.4 (2019-12-15 11:32:54, build 97e9ce7d289b6b34715e146c9e6a2782b535e43a) ]
 - OS: Windows
 - Browser: chrome

**Additional context**

**Comment by reckart** [comment]
Do you get a stack trace in the console? That might help figuring out in which column the importer chokes.

**Comment by lmompela** [comment]
This is what I get from Webanno, I'm not running the program through the powershell but from the executable jar file. 
![image](https://user-images.githubusercontent.com/49000319/74475479-805dea00-4e75-11ea-9dea-1379eb297aed.png)

**Comment by lmompela** [comment]
Here is what I get from the command panel 

![image](https://user-images.githubusercontent.com/49000319/74476037-961fdf00-4e76-11ea-89d2-97ebffc96aff.png)

**Comment by reckart** [comment]
The stack trace indicates that your file defines a dependency relation label in column 7 but the head of the dependency in column 6 is not set.

**Comment by lmompela** [comment]
I have a subsequent problem, when trying to upload my conllu file in 
Projects > Automation > [Part of Speech] > Target layer > 
I would like the program to take my annotated corpus (in the conllu format) and suggest POS tags for the tagged tokens in a document that wasn't previously annotated. 

It gives me an "Internal error" message on my browser and the message in the console is as such : 
![image](https://user-images.githubusercontent.com/49000319/79073540-42cedf00-7cb5-11ea-8f73-5d76ce2c718a.png)

**Comment by reckart** [comment]
Puh... need to look into this. If you ask me, I'd recommend using [INCEpTION](https://inception-project.github.io) for your automation tasks.
