### ISSUE TITLE
Logbar hides last line in a document

### ISSUE THREAD

**Issue by nreimers** [webanno/webanno#161]
Please see the attached image. The yellow bar at the bottom with the logging information hides the last line of my document, so that an annotator cannot really annotate tokens in it. Closing the bar is not possible, also there is no scroll bar. The only solution is to resize the window which triggers the bar to disappear.

I use Firefox 40.0 with Ubuntu 12.04

![bildschirmfoto vom 2015-11-24 14 46 16](https://cloud.githubusercontent.com/assets/10706961/11368459/3bec0634-92ba-11e5-8876-ccf9b31b6475.png)

**Comment by reckart** [comment]
Having some kind of "close" button on the notification area would be good, yes :)

**Comment by aakashysharma** [comment]
Similar to #148

**Comment by kevinappen** [comment]
We are seeing the same problem using Chrome in Windows 8.1.

**Comment by reckart** [comment]
@aakashysharma Any suggestion how we could address this issue?

**Comment by aakashysharma** [comment]
I was thinking of writing a custom notification panel like this https://github.com/apache/syncope/blob/master/client/console/src/main/java/org/apache/syncope/client/console/panels/NotificationPanel.java

**Comment by nreimers** [comment]
A simple fix would be just to increase the margin/padding at the bottom of text field.

**Comment by reckart** [comment]
The feedback panel is floating over the text and grows dynamically with the number of messages. We cannot dynamically adjust margins without hacking up Javascript.

I'd be in favor of a customized feedback panel with offers a "click to close" button.

**Comment by nreimers** [comment]
A "click to close" would be a bit annoying for the annotator, if there are alot of annotations to tag in the last line. It adds an additional click for every annotation made.

In WebAnno 2.3.0 the logbar appears to be fixed sized with scrollbars. So more messages would not increase the size of it.

**Comment by reckart** [comment]
It is not a fixed size, but often there is only one message being displayed, in particular in annotation mode. But the panel is used everywhere in the application (cf. #148). For example, during export, there can be a huge number of messages. 

In addition to a "close" button, we could try increasing the scroll area of the annotation document, so that the user can continue to scroll beyond the document end such that the last sentences don't keep on sticking at the bottom of the page. Maybe that is what you meant by "adding margin at the bottom of the text field"?

**Comment by nreimers** [comment]
Correct. Just add "padding-bottom: 30px" to the following place in HTML: 
<fieldset class="ui-widget-content ui-corner-all">
<legend>Annotation</legend>
<div class="hasSVG" style="display: block; height: 901.333px; padding-bottom: 30px;" id="id2c"><svg viewBox="0 0 1506 901.333345413208" style="width: 1506px; height: 901.333px; margin-bottom: 0px;" version="1.1">

</svg>
</div>
</fieldset>
