### ISSUE TITLE
Upgrade to Bootstrap 4

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#1612]
**Describe the refactoring action**
Upgrade from Bootstrap 3 to Bootstrap 4.

**Expected benefit**
Using a CSS framework that is actually supported... although it should be noted that the respective Wicket packages are still only available as milestone builds.

**Comment by jcklie** [comment]
When I run the jar via

`java -jar webanno-standalone-4.0.0-SNAPSHOT.jar`

, then I get

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Feb 28 14:29:25 CET 2020
There was an unexpected error (type=Not Found, status=404).
No message available
```

Log says

`Caused by: io.bit3.jsass.CompilationException: Internal Error: File to read not found or unreadable: jar:file:/home/klie/git/webanno/webanno-webapp/target/webanno-standalone-4.0.0-SNAPSHOT.jar!/WEB-INF/lib/webanno-ui-core-4.0.0-SNAPSHOT.jar!/de/tudarmstadt/ukp/clarin/webanno/ui/core/css/theme/bootstrap.scss`

**Comment by reckart** [comment]
hm, not good.

**Comment by reckart** [comment]
Works for me in Eclipse in Tomcat as well as when running as a Java application. I'll try on the command line.

**Comment by reckart** [comment]
Looks like the jsass/libsass interface does only work with resources that are available on the file system. I'll see if I can find a solution to that.

**Comment by jcklie** [comment]
In the annotation view, if you hover over the page counter, you can increment it (I dont think that makes sense). It would be maybe also better to have grey space inbetween the buttons or group left and right. The border thickness is different between the middle and left and right.

![image](https://user-images.githubusercontent.com/934600/75554920-8fc76080-5a3b-11ea-88d0-5b7ce6af3e6f.png)

The border looks too much:

![image](https://user-images.githubusercontent.com/934600/75555102-e3d24500-5a3b-11ea-9ae9-26f696badb73.png)

This looks wrong:

![image](https://user-images.githubusercontent.com/934600/75555340-53e0cb00-5a3c-11ea-9873-03fa2a5cf2c4.png)

This looks wrong:

![image](https://user-images.githubusercontent.com/934600/75555414-7b379800-5a3c-11ea-924f-e6089c160889.png)

**Comment by reckart** [comment]
Opened an upstream issue: https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/852

Although, instead of looking for a fix a the level of the `SassResourceReference` compiler setup, I'm thinking rather of precompiling the SCSS files are build time and changing the code such that it tries to use the classpath location for dynamic compilation if possible (or if the development mode is active) and otherwise use the pre-compiled files.

**Comment by jcklie** [comment]
I comment in the PR instead of the issue
