### ISSUE TITLE
Export (to CoNLL 2003) renders BIO NER tags wrong

### ISSUE THREAD

**Issue by dcavar** [webanno/webanno#1617]
When exporting to CoNLL 2003 the NER tags of a multi-word NER annotation end up being all
I-XYZ
There are missing B-XYZ, all I-XYZ etc. Expected should be B-XYZ I-XYZ

Using: OS: Linux, Java: 13

**Comment by jcklie** [comment]
Do you have an example project/file where this occurs and that you can share?

**Comment by reckart** [comment]
Can be easily reproduced:

* Import a text file
* Annotate a multi-word span as a named entity
* Export as CoNLL 2003

**Comment by reckart** [comment]
However, this is not a bug. The CoNLL 2003 format is defined as follows:

-----
The CoNLL-2003 shared task data files contain four columns separated by a single space. Each word has been put on a separate line and there is an empty line after each sentence. The first item on each line is a word, the second a part-of-speech (POS) tag, the third a syntactic chunk tag and the fourth the named entity tag. The chunk tags and the named entity tags have the format I-TYPE which means that the word is inside a phrase of type TYPE. **Only if two phrases of the same type immediately follow each other, the first word of the second phrase will have tag B-TYPE to show that it starts a new phrase.** A word with tag O is not part of a phrase. Here is an example:

```
   U.N.         NNP  I-NP  I-ORG 
   official     NN   I-NP  O 
   Ekeus        NNP  I-NP  I-PER 
   heads        VBZ  I-VP  O 
   for          IN   I-PP  O 
   Baghdad      NNP  I-NP  I-LOC 
   .            .    O     O 
```

(Source: https://www.clips.uantwerpen.be/conll2003/ner/)

-----


I tested the behavior that a `B-` is inserted if two adjacent entities have the same tag and this works:

<img width="258" alt="Screenshot 2020-03-17 at 20 51 24" src="https://user-images.githubusercontent.com/1410238/76895860-192abf80-6891-11ea-90ca-3dd342f05380.png">


```
Barack _ O I-PER
Hussein _ O I-PER
Obama _ O B-PER
II _ O I-PER
```

**Comment by jcklie** [comment]
See also https://github.com/UKPLab/emnlp2017-bilstm-cnn-crf/issues/4
