### ISSUE TITLE
Default values for features?

### ISSUE THREAD

**Issue by spaebrun** [webanno/webanno#162]
This is  feature request: Could you perhaps allow defining default values for features?

For example, a boolean feature could be "false" by default, an Integer feature could have the value "0", a String feature could have a specific tag from the associated tagset as a default. When setting up the features, one would specify these defaults and they would automatically be selected for any annotation that the annotator adds. However, the annotator would then be able to change those default values.

**Comment by reckart** [comment]
In fact, boolean features should already be false by default and integers should be 0 by default. UIMA does not allow setting boolean features or int features to "null"

**Comment by mmev** [comment]
Are there any other possibilities to set an arbitrary value as "default"? 
E.g. "NN" for all part-of-speech tags?

**Comment by seyyaw** [comment]
@mmev  Partially possible. In the project settings page, go to the Layers and then Feature values. Check the Remember checkbox and save feature.
![image](https://cloud.githubusercontent.com/assets/1056051/11466537/f257b5d6-9741-11e5-8b5b-23a4f5959320.png)
This will allow you to re-use the previous annotation without you selecting from the lists. This will be more relevant in WebAnno 3 as the Remembered Tag set to annotate automatically to the selected span (There is no annotate button anymore).

Best
Seid M.

**Comment by seyyaw** [comment]
Re-open if you think the **remember** check-box in feature settings is not enough
