### ISSUE TITLE
Exporting XMI creates two kinds of DocumentMetaData

### ISSUE THREAD

**Issue by jcklie** [webanno/webanno#1623]
**Describe the bug**
Exporting XMI creates two kinds of DocumentMetaData:

```
    <tcas:DocumentAnnotation xmi:id="158" sofa="1" begin="0" end="1261" language="x-unspecified"/>
    <type2:DocumentMetaData xmi:id="163" sofa="1" begin="0" end="1261" language="x-unspecified" documentTitle="sn82014385-1810-01-06-a-i0001%20preinception.xmi" documentId="admin" documentUri="file:/home/klie/.webanno/repository/project/4/document/16/source/admin" collectionId="file:/home/klie/.webanno/repository/project/4/document/16/source/" documentBaseUri="file:/home/klie/.webanno/repository/project/4/document/16/source/" isLastSegment="false"/>
```

Example: https://pastebin.com/rdxruC2B

**To Reproduce**
1. Import the document as XMI
2. Export the project as XMI
3. See the bad XMI

**Expected behavior**
The resulting XMI should only contain one kind of DocumentMetaData

**Please complete the following information:**
 - Version and build ID: Webanno Master, 22b2800c6ea1944e47128d82b2de6e505898871d
 - OS: Linux
 - Browser: chrome

**Comment by jcklie** [comment]
When importing (after `reader.next(cas)`, only one DocumentMetadata is in there (DocumentMeta).

**Comment by jcklie** [comment]
After the import, it upgrades the CAS somewhere and then we have two kinds of metadata in the CAS.

**Comment by jcklie** [comment]
The CAS is upgraded the first time the document is opened for annotation. Then the CAS contains one `uima.tcas.DocumentAnnotation` from the import and one `de.tudarmstadt.ukp.dkpro.core.api.metadata.type.DocumentMetaData` from the upgrade or somewhere else.

**Comment by jcklie** [comment]
@reckart I do not know how to proceed from here. I think what we need to do:

If the CAS contains a `uima.tcas.DocumentAnnotation` during upgrade, then we need to remove it and replace it with `de.tudarmstadt.ukp.dkpro.core.api.metadata.type.DocumentMetaData`. I assume that Webanno would just override and not try to merge fields.

**Comment by reckart** [comment]
Tracked it down to a UIMA bug:

https://issues.apache.org/jira/browse/UIMA-6199
