### ISSUE TITLE
Hide/Invisible Link Feature in annotation view

### ISSUE THREAD

**Issue by GillesJ** [webanno/webanno#1629]
**Is your feature request related to a problem? Please describe.**
Currently there is no option to hide a Link Feature in the text editor annotation view.

The "enable" and "visible" tick box options only apply to the Sidebar panel.
It is unclear whether continuing to show a "disabled" Link Feature in annotation view is a bug.

I am currently working on a secondary annotation stage in which these Link Features are no longer needed, but the annotation layers they connect to have to be enabled.
The unused links cause a lot of visible clutter and confuse the annotators.

**Describe the solution you'd like**
Disabled Link Features should not be drawn in annotation view.
OR
A "Invisible/Hide in annotation editor" tickbox option in the Feature Details settings to make the link invisible in the annotation editor.

**Describe alternatives you've considered**
Disabling the Link target Type layer removes both that layer and the link.
This is of course not a solution when the target Layer is still needed in the project.

**Additional context**
Issue exists in WebAnno 3.6.2 and 3.6.4

**Comment by reckart** [comment]
When "visible" is disabled, then this particular feature should not be displayed in the "annotation bubble" that represents an annotation. The features should still be visible in the sidebar when selecting the annotation

When "enable" is disabled, then the feature should not appear to users anymore at all, neither in the bubble nor in the sidebar.
