### ISSUE TITLE
Annotators can modify documents marked as "Done"

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#163]
Although documents marked as "Done" should only be processed by the curator/project manager/admin, the annotator can still modify the annotation.
I am using version 3.0.0-SNAPSHOT (2015-09-28 16:45:40, build d27759e452b7cdb7b79cfbbae5bc5f2f0661465e) with Chrome on Windows 8.1.

**Comment by MeDarina** [comment]
I have the same error. Maybe it is important, than one can only add annotations of one layer, but not delete or change any annotations or add features.

**Comment by seyyaw** [comment]
@sholschneider  and @MeDarina  Can you confirm this in the experimental instance too? Thanks

**Comment by MeDarina** [comment]
No, it works properly on experimental.

Am 17.12.2015 um 11:05 schrieb Seid Muhie Yimam:

**Comment by seyyaw** [comment]
so this is resolved!
