### ISSUE TITLE
References wrong in https://webanno.github.io/webanno/

### ISSUE THREAD

**Issue by chozelinek** [webanno/webanno#165]
The bib file for papers

> Yimam, S.M., Eckart de Castilho, R., Gurevych, I., and Biemann C. (2014): Automatic Annotation Suggestions and Custom Annotation Layers in WebAnno In: Proceedings of ACL-2014, demo session, Baltimore, MD, USA

<http://www.aclweb.org/anthology/P13-4001.bib>

and 

> Yimam, S.M., Gurevych, I., Eckart de Castilho, R., and Biemann C. (2013): WebAnno: A Flexible, Web-based and Visually Supported System for Distributed Annotations. In Proceedings of ACL-2013, demo session, Sofia, Bulgaria.

<http://www.aclweb.org/anthology/P/P14/P14-5016.bib>

are wrong.

The bib file provided for 2013's publication points to the 2014's. And the other way round.

**Comment by chozelinek** [comment]
And check also the link to the PDF files. They are also reversed.

**Comment by seyyaw** [comment]
corrected. Thanks
