### ISSUE TITLE
"Actions"-box freezes when continuing with "next"

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#166]
When the annotator marks an annotation as "Done" and continues with "Next", the "Actions"-box freezes and is not usable. I am using version 3.0.0-SNAPSHOT (2015-09-28 16:45:40, build d27759e452b7cdb7b79cfbbae5bc5f2f0661465e) on Chrome.

**Comment by reckart** [comment]
I assume you are talking about the "Done" button in the toolbar?

A user marks a document as "Done" in the toolbar. This means that no further changes to the document are allowed. It sounds as if what you are describing is desired behavior. What would have been your expectation?

**Comment by sholschneider** [comment]
It is the desired behaviour for the current file, but not for the file that opens after having clicked on "next".

**Comment by reckart** [comment]
Absolutely right! That sounds like a bug.

**Comment by aakashysharma** [comment]
Steps I tried on latest build

1. Opened first document in a project, call it A.
2. Add new annotations + change few existing annotations.
3. Mark document as "done" using the icon at toolbar. It asks for confirmation, I click yes.
4. Try to create new annotation on same document A, getting warning/errors in feedback panel (expected)
5. Click on next document (the next document B is also "Done"). Everything works as it should.
6. Click on next document again (this document C is still not "Done"). I can create annotations, edit them.
7. Click on "previous document" (this document B is "Done"), can't create/update annotations.
8. Click on "previous document" again, (this document A is "Done"), can't create/update annotations.


@sholschneider Maybe the document was already "done". Please check the status of it. While opening, it shows "done" documents in "red" in the open dialog. I'm using "demo-crowd" project. The second document "demo2" came as "done" while importing I believe.

@reckart I can't reproduce.

**Comment by reckart** [comment]
@aakashysharma can you please just add a comment agains which version of WebAnno you were checking (version string at bottom of the screen)?

**Comment by aakashysharma** [comment]
`  3.0.0-SNAPSHOT (2016-04-13 15:09:25, build c939dbcaa0cd66d3470e85cb2c223e53577f9cce) `
