### ISSUE TITLE
Ubuntu:Webanno cannot use settings.properties file

### ISSUE THREAD

**Issue by KavishBhatia** [webanno/webanno#1662]
When trying to run Webanno on Ubuntu 18.04, the application is not able to run or find settings.properties file. I tried to run it as a embedded Tomcat server it gave an error when executing `systemctl enable webanno`
![Running via embedded Tomcat (JAR)](https://user-images.githubusercontent.com/8553451/80094359-65d77980-8566-11ea-9c99-3fefbc10b484.png)
Do not know what is the issue or what I did wrong for the ubuntu OS

When running webanno - not using settings file
![starting webanno](https://user-images.githubusercontent.com/8553451/80094756-180f4100-8567-11ea-9ee4-380db4baa3cb.png)

**Comment by jcklie** [comment]
Do you run systemd or init.d? You can check it by e.g. `pidof systemd && echo "systemd" || echo "other"`

**Comment by KavishBhatia** [comment]
@jcklie its `systemd`

**Comment by jcklie** [comment]
I would remove the symlink you created and create a file in ` /etc/systemd/system/webanno.service`

```
[Unit]
Description=Webanno

[Service]
ExecStart= /srv/webanno/webanno.jar

[Install]
WantedBy=multi-user.target
```
In the `/srv/webanno` folder is then your jar, `webanno.conf` and `settings.properties`

**Comment by KavishBhatia** [comment]
@jcklie I followed your instructions but I think it's same as before. Not using settings.properties file. I added `remote-api.enabled=true` in `settings.properties` but cannot see in the roles when I run webanno.
Also I added `server.port=18080` in `settings.properties` so now webanno should run at 8080 (as in my case before) or 18080?

**Comment by jcklie** [comment]
That then looks like it does not pick up your `webanno.conf`. What is in there? In ours where it works, it would be

`JAVA_OPTS="-Djava.awt.headless=true -Xmx16g -XX:+UseConcMarkSweepGC -Dwebanno.home=/srv/webanno"`

**Comment by KavishBhatia** [comment]
`webanno.conf` has `AVA_OPTS="-Djava.awt.headless=true -Dwebanno.home=/srv/webanno"`
should I replace this with your one?

**Comment by jcklie** [comment]
Yours should be correct, but the first screenshot you posted showed that it uses the wrong home directory. Can you try and edit the service file to `ExecStart= /srv/webanno/webanno.jar -Dwebanno.home=/srv/webanno` ?

**Comment by KavishBhatia** [comment]
changed my `webanno.conf`'s content to `ExecStart= /srv/webanno/webanno.jar -Dwebanno.home=/srv/webanno` 
Also restarted webanno. Looks same to me
![Screenshot from 2020-04-23 17-40-06](https://user-images.githubusercontent.com/8553451/80119174-a2689c80-8589-11ea-825c-21c2b52ef7a2.png)

**Comment by jcklie** [comment]
@reckart Do you have an idea? I suspect that the home folder is still wrong, but I do not know why.

**Comment by reckart** [comment]
The `-Dwebanno.home=/srv/webanno` should be in `webanno.conf`.

**Comment by reckart** [comment]
The `webanno.conf` file is ignored if it has too lax permissions. Make sure it has only the following permissions:

```
-rw-r--r--  1 root     root           288 Oct 27  2019 webanno.conf
```

**Comment by KavishBhatia** [comment]
This is the permissions for webanno.conf and its content
![Screenshot from 2020-04-27 15-03-50](https://user-images.githubusercontent.com/8553451/80375581-d64d0600-8898-11ea-8fbe-190c12c8f0f3.png)
![Screenshot from 2020-04-27 15-05-41](https://user-images.githubusercontent.com/8553451/80375585-d6e59c80-8898-11ea-9010-99f0555e35a1.png)

**Comment by reckart** [comment]
The `webanno.jar` should not have root as owner - that would mean that the process is run as root. Do *not* run WebAnno as root.

**Comment by reckart** [comment]
This [page](https://docs.spring.io/spring-boot/docs/current/reference/html/deployment.html) says you can set the environment variable DEBUG to something non-empty to permit checking what the startup script does - maybe that would help.

**Comment by KavishBhatia** [comment]
> The `webanno.jar` should not have root as owner - that would mean that the process is run as root. Do _not_ run WebAnno as root.

What should be if not root? www-data as in the documentation?

**Comment by KavishBhatia** [comment]
![Screenshot from 2020-04-29 13-59-41](https://user-images.githubusercontent.com/8553451/80593608-d2002480-8a21-11ea-8474-650d3c21482e.png)
This is after `chown www-data:www-data /srv/webanno/webanno.jar` 

Also I have enabled `remote-api.enabled=true` in `settings.properties` but when creating new user I cannot see the option `ROLE_REMOTE`

**Comment by reckart** [comment]
The user to which the JAR belongs will be the user as which the process is run. If you have a www-data user on your system, it is a reasonable choice. You could also create a dedicated user for running WebAnno and use that user.

**Comment by reckart** [comment]
For curiosity. What happens if you do this:

```
$ sudo su -
$ cd /srv/webanno
$ DEBUG=true ./webanno.jar start
```

**Comment by KavishBhatia** [comment]
> For curiosity. What happens if you do this:
> 
> ```
> $ sudo su -
> $ cd /srv/webanno
> $ DEBUG=true ./webanno.jar start
> ```

It exited the `exit 1`

**Comment by KavishBhatia** [comment]
> The `webanno.jar` should not have root as owner - that would mean that the process is run as root. Do _not_ run WebAnno as root.

Still I cannot see `ROLE_REMOTE` when creating new user

**Comment by reckart** [comment]
As long as you do not see this line in the log/console below the ascii-art logo, WebAnno did not recognize your `-Dwebanno.home=/srv/webanno` parameter.

```
2020-04-30 16:23:06 [main] INFO [SYSTEM] WebAnnoApplicationContextInitializer - Settings: /srv/webanno/settings.properties
```

**Comment by KavishBhatia** [comment]
> Which command to you use to start WebAnno?

`java -jar webanno.jar`

**Comment by reckart** [comment]
Aha :) Well, that explains a lot :)

If you want to run WebAnno as a service, you should call `sudo service webanno start` to run it. Then it should also pick up your webanno.conf file etc.

If you run it directly from your user as a JAR, you would need to call it as `java -jar webanno.jar -Dwebanno.home=/srv/webanno` - also, the "/srv/webanno" and subdirectories would need to be writable by your user.

**Comment by KavishBhatia** [comment]
> As long as you do not see this line in the log/console below the ascii-art logo, WebAnno did not recognize your `-Dwebanno.home=/srv/webanno` parameter.
> 
> ```
> 2020-04-30 16:23:06 [main] INFO [SYSTEM] WebAnnoApplicationContextInitializer - Settings: /srv/webanno/settings.properties
> ```

Got this
`2020-04-30 17:25:56 INFO [SYSTEM] WebAnnoApplicationContextInitializer - Authentication: database`

**Comment by KavishBhatia** [comment]
running from `sudo service webanno start` started localhost:8080 on user root but running `java -jar webanno.jar -Dwebanno.home=/srv/webanno` ran it on my other user which has permission on `webanno.jar`

**Comment by reckart** [comment]
When you call `sudo service webanno start` and afterwards do a `ps aux | grep webanno`, you should be able to see that the service is running under the user which owns the `webanno.jar` file. So if the file is e.g. owned by `www-data`, then the process should run as `www-data`.

**Comment by KavishBhatia** [comment]
> When you call `sudo service webanno start` and afterwards do a `ps aux | grep webanno`, you should be able to see that the service is running under the user which owns the `webanno.jar` file. So if the file is e.g. owned by `www-data`, then the process should run as `www-data`.

![Screenshot from 2020-04-30 18-03-18](https://user-images.githubusercontent.com/8553451/80732754-08ff3480-8b0d-11ea-8e4c-efb7e7473d36.png)

**Comment by KavishBhatia** [comment]
> chown 500 /srv/webanno/webanno.jar

Didn't work. Still same

![Screenshot from 2020-04-30 18-19-45](https://user-images.githubusercontent.com/8553451/80734477-84fa7c00-8b0f-11ea-828e-5fcccc03454f.png)

**Comment by reckart** [comment]
```
# cd /srv/webanno-testing
# ps aux | grep "webanno"
root     10312  0.0  0.0  19788  3576 ?        Ss   Feb25   0:00 /bin/bash /srv/webanno-testing/webanno-testing.jar
root     10330  0.0  0.2 10486552 1420336 ?    Sl   Feb25  58:18 /usr/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -Djava.awt.headless=true -Xmx3g -XX:+UseConcMarkSweepGC -Dwebanno.home=/srv/webanno-testing -jar /srv/webanno-testing/webanno-testing.jar
# service webanno-testing stop
# chown 500 webanno-testing.jar
# service webanno-testing start
# ps aux | grep "webanno"
www-data 31377  0.0  0.0  19788  3360 ?        Ss   18:10   0:00 /bin/bash /srv/webanno-testing/webanno-testing.jar
www-data 31392  8.4  0.2 10208200 1080888 ?    Sl   18:10   1:31 /usr/bin/java -Dsun.misc.URLClassPath.disableJarChecking=true -Djava.awt.headless=true -Xmx3g -XX:+UseConcMarkSweepGC -Dwebanno.home=/srv/webanno-testing -jar /srv/webanno-testing/webanno-testing.jar
```

**Comment by reckart** [comment]
Hm, ok, but changing the permissions back doesn't make the service run as root again - so it must be something different...

**Comment by reckart** [comment]
You screenshot shows your webanno.jar as being owned by `500` instead of `www-data`.

**Comment by reckart** [comment]
I just got told by @jcklie that he had previously changed the owner of the JAR files but hadn't restarted the services - so looks like they picked up the new user under which they run when I restarted the services without regard of the changed permissions on the JAR file.

**Comment by KavishBhatia** [comment]
> You screenshot shows your webanno.jar as being owned by `500` instead of `www-data`.

I ran the same command as yours `sudo chown 500 /srv/webanno/webanno.jar`

**Comment by KavishBhatia** [comment]
> I just got told by @jcklie that he had previously changed the owner of the JAR files but hadn't restarted the services - so looks like they picked up the new user under which they run when I restarted the services without regard of the changed permissions on the JAR file.

I changed the user to www-data still it runs as root, changed it to 500 and back still it is running as root.

**Comment by reckart** [comment]
Please excuse the question but... are you stopping the service before changing the user owning the file and restarting it again afterwards?

**Comment by KavishBhatia** [comment]
> Please excuse the question but... are you stopping the service before changing the user owning the file and restarting it again afterwards?

Yes I did
![Screenshot from 2020-05-01 13-46-07](https://user-images.githubusercontent.com/8553451/80803303-2afec280-8bb2-11ea-959e-ba09fceacc07.png)

**Comment by KavishBhatia** [comment]
Should I remove everything and start from Zero? Can you guide me through? Maybe I did something wrong.

**Comment by jcklie** [comment]
Did you specify the user in the service file? It should have
 
```
[Service]
ExecStart= /srv/webanno/webanno.jar
User=www-data
```

**Comment by KavishBhatia** [comment]
> Did you specify the user in the service file? It should have
> 
> ```
> [Service]
> ExecStart= /srv/webanno/webanno.jar
> User=www-data
> ```

Okay. I did mention it now. Now it is running as `www-data` but now it didn't start the `localhost:8080`

**Comment by KavishBhatia** [comment]
@reckart When I have just `remote-api.enabled=true` in my `settings.properties` I can access the `ROLE_REMOTE` but when I tried to use `curl -X GET "http://localhost:8080/api/aero/v1/projects" -H  "accept: application/json;charset=UTF-8"` it gave `401:unauthorized`
Then I added these lines mentioned in the documentation in my `settings.properties`
`database.dialect=org.hibernate.dialect.MySQL5InnoDBDialect`
`database.driver=com.mysql.jdbc.Driver`
`database.url=jdbc:mysql://localhost:3306/webanno?useSSL=false&serverTimezone=UTC`
`database.username=webanno`
`database.password=t0t4llYSecreT`

After adding these lines I couldn't access `localhost:8080`. Then I removed these lines but the `curl -X GET ..` still didn't work but when I explicitly open `http://localhost:8080/api/aero/v1/projects` it gives me the json result. 
I don't know how to use the utf-8 settings here?

**Comment by reckart** [comment]
You need to send basic authentication along with the curl, e.g using `http://USERNAME:PASSWORD@localhost...` or using other methods of supplying credentials supported by curl.

Btw. did you find the Swagger UI? http://localhost:8080/inception-app-webapp/swagger-ui.html

**Comment by KavishBhatia** [comment]
> You need to send basic authentication along with the curl, e.g using `http://USERNAME:PASSWORD@localhost...` or using other methods of supplying credentials supported by curl.
> 
> Btw. did you find the Swagger UI? http://localhost:8080/inception-app-webapp/swagger-ui.html

Yes, Swagger was in the documentation I found it under `<APPLICATION_URL>/swagger-ui.html`
