### ISSUE TITLE
Error while uploading document 

### ISSUE THREAD

**Issue by Ledgrev** [webanno/webanno#1664]
Hello, I am trying to upload the files I wish to annotate in Webanno. There are 200 very small (each containing max 300 unicode characters) plain text files I wish to upload. However, when I select the files I wish to upload and click on "import", I get the following error message:
`Error while uploading document tddm-3.txt: FileNotFoundException: Source file [tddm-3.txt] not found in [/export/repository/project/63/document/9906/source/tddm-3.txt]`
Could anyone tell me how to fix this issue? 

Thank you!

**Comment by jcklie** [comment]
Do you have a stack trace or can even share the documents with us?

**Comment by Ledgrev** [comment]
What is a stack trace? (English is not my native language)
Unfortunately, I cannot share the files as the data contains personal information.

**Comment by jcklie** [comment]
When you start webanno from a terminal, it prints more information there.

**Comment by Ledgrev** [comment]
I use Webanno how it is supplied by my host institution, namely in a browser.

**Comment by jcklie** [comment]
Do you upload 300 documents at once? What happens if you upload fewer at the same time?

**Comment by Ledgrev** [comment]
Hello, I just wanted to let you know that I tried it again and it worked this time. I'm still not sure what the problem was, but it appears to work again. Thank you for your time!
