### ISSUE TITLE
Changing order of annotation layers in TSV export

### ISSUE THREAD

**Issue by kajad** [webanno/webanno#167]
I am working with a project with several documents that have all been imported in the same Webanno TSV format with the same order or layers, e.g.  # L1| value1 # L2 | value2 # L3 | value3.

After annotation, when exporting the whole project (or any of the individual files) in TSV, the order of layers/columns in annotated documents changes randomly for each document. Some documents are exported as # L1| value1 # L2 | value2 # L3 | value3, some as # L2| value2 # L1 | value1 # L3 | value3, some as  # L1| value1 # L3 | value3 # L2 | value2, etc. 

This requires additional postprocessing of exported documents before making any overall merges or comparisons. It would be useful to avoid this by preserving the imported order of layers when documents are exported, unless new layers have been added during annotation (these can be appended as additional columns).

**Comment by seyyaw** [comment]
this is now resolved in WebAnno 3.0
