### ISSUE TITLE
Fixed order of settings tabs

### ISSUE THREAD

**Issue by UWinch** [webanno/webanno#1673]
**Is your feature request related to a problem? Please describe.**
I would like the tabs on the project settings page to be in a fixed order.

**Describe the solution you'd like**
Use `@Order(n)` with n increasing for Project settings panel factories to achieve a fixed order.

**Additional context**
Relates to https://github.com/inception-project/inception/issues/1680

**Comment by reckart** [comment]
I'm pretty sure that `@Order` is already used by the code creating the tabs. What's missing?

**Comment by UWinch** [comment]
Can be fixed in inception turns out webanno tabs are already ordered, just not together with inception tabs.
