### ISSUE TITLE
Cannot see role `ROLE_REMOTE`

### ISSUE THREAD

**Issue by KavishBhatia** [webanno/webanno#1674]
After enabling `remote-api.enabled=true` in `settings.properties`, still cannot see `ROLE_REMOTE` when creating a new user.

**Comment by reckart** [comment]
Try setting it as a system property instead of adding it to the settings file

**Comment by KavishBhatia** [comment]
How is that? I just followed the administrator guide.

**Comment by reckart** [comment]
Try adding `-Dremote-api.enabled=true` where you also add `-Dwebanno.home=....`

**Comment by KavishBhatia** [comment]
Still don't have `ROLE_REMOTE`. Also did ` systemctl daemon-reload` then `service webanno start`

**Comment by reckart** [comment]
This is still about WebAnno 3.6.5, right?

**Comment by reckart** [comment]
I tried this:
```
$ sudo su -
$ mkdir /srv/webanno
$ cd /srv/webanno
$ wget https://github.com/webanno/webanno/releases/download/webanno-3.6.5/webanno-standalone-3.6.5.jar
$ chown www-data:www-data .
$ mv webanno-standalone-3.6.5.jar webanno.jar
$ chmod +x  webanno.jar
```

Edit`/etc/systemd/system/webanno.service` in a text editor:
```
[Unit]
Description=WebAnno

[Service]
ExecStart=/srv/webanno/webanno
User=www-data

[Install]
WantedBy=multi-user.target
```

Edit `/srv/webanno/webanno.conf` in a text editor:
```
JAVA_OPTS="-Djava.awt.headless=true -Dinception.home=/srv/webanno"
```

Edit `/srv/webanno/settings.conf` in a text editor:
```
remote-api.enabled=true
```

```
$ systemctl enable webanno
$ systemctl start webanno
```

Now I did this:
* opened `http://localhost:8080/
* logged in as the default admin user
* clicked on "Users" in the main menu
* selected the user "admin" on the left
* now I see `ROLE_REMOTE` as one of the roles I can choose from

**Comment by KavishBhatia** [comment]
If you do `chown www-data:www-data .` while in `/srv/webanno` it changes the owner of the folder but not on the files inside. We have to change owner for `webanno.jar` as well to `www-data` right?

**Comment by reckart** [comment]
As I understand it, the owner of the `webanno.jar` is relevant if you run via init.d because then it also determines the user under which the process is started --- but if you run via systemd, then the owner of the process is configured in `/etc/systemd/system/webanno.service` and the owner of the file has no particular effect.

**Comment by reckart** [comment]
I just noted that I had a typo in the line`ExecStart=/srv/webanno/webanno` which should be `ExecStart=/srv/webanno/webanno.jar` - I edited the comment above.

**Comment by KavishBhatia** [comment]
I tried the steps from starting, deleting `/srv/webanno` and doing it from zero. Now the service starts but I cannot access [localhost:8080](http://localhost:8080) after one minute if I do `ps aux | grep "webanno"` I cannot see the service running

**Comment by jcklie** [comment]
What does the log say?
```
systemctl status webanno
journalctl -u webanno
```

**Comment by KavishBhatia** [comment]
> What does the log say?
> 
> ```
> systemctl status webanno
> journalctl -u webanno
> ```

![Screenshot from 2020-05-13 13-43-56](https://user-images.githubusercontent.com/8553451/81808327-d64b3800-951f-11ea-86d1-dc444ecb73e2.png)
![Screenshot from 2020-05-13 13-45-57](https://user-images.githubusercontent.com/8553451/81808524-1f02f100-9520-11ea-941d-491cd53d4a69.png)

**Comment by KavishBhatia** [comment]
> What does the log say?
> 
> ```
> systemctl status webanno
> journalctl -u webanno
> ```
![Screenshot from 2020-05-13 13-51-48](https://user-images.githubusercontent.com/8553451/81809044-f6c7c200-9520-11ea-82a2-662ebd6ca2e2.png)
![Screenshot from 2020-05-13 13-53-11](https://user-images.githubusercontent.com/8553451/81809175-37bfd680-9521-11ea-9d1e-9598199d5d2d.png)

**Comment by KavishBhatia** [comment]
Ran the service again with `systemctl daemon-reload`, can access the localhost now but still can't see `ROLE_REMOTE`. Followed steps suggested by @reckart

**Comment by reckart** [comment]
To be honest, I don't know what is going on on your machine. I tried on a linux here, and it worked. Worst case, you could try running on the command line with `java -jar -Dremote-api.enabled=true -Dwebanno.home...blah...` and see if you can force it somehow in this way.

**Comment by KavishBhatia** [comment]
It should be a problem in a VirtualBox? Right? Can you replicate the issue in a Vbox?

**Comment by reckart** [comment]
Well, what I reported in the [comment above](https://github.com/webanno/webanno/issues/1674#issuecomment-627285182), I did in fact try on Ubuntu in VirtualBox.

**Comment by KavishBhatia** [comment]
Now this is confusing. I will try from zero again.

**Comment by reckart** [comment]
I'm sorry for the fuss. We really try to make the setup as straight-forward as possible... and as far as I can tell, most people have no issue. If you can figure out what's going wrong, let us know - maybe we could add a hint in the documentation to help others not stumble over the same issue.

**Comment by KavishBhatia** [comment]
> I'm sorry for the fuss. We really try to make the setup as straight-forward as possible... and as far as I can tell, most people have no issue. If you can figure out what's going wrong, let us know - maybe we could add a hint in the documentation to help others not stumble over the same issue.

Yes sure. Thank You for the help.

**Comment by KavishBhatia** [comment]
> Edit `/srv/webanno/settings.conf` in a text editor:
> 
> ```
> remote-api.enabled=true
> ```
> 
The documentation doesn't mention `settings.conf` but `settings.properties` are these same? And if not what is the difference? Which one should I have in `/srv/webanno`

**Comment by reckart** [comment]
> The documentation doesn't mention settings.conf but settings.properties are these same? And if not what is the difference? Which one should I have in /srv/webanno

Ah, once a again a copy-paste bug in my comment. There is no `settings.conf` - it should have been `settings.properties`. I have updated my comment above.

**Comment by KavishBhatia** [comment]
[In this comment](https://github.com/webanno/webanno/issues/1674#issuecomment-627285182) under `webanno.conf` it should be `-Dwebanno=...` instead of `-Dinception=..` 
I think this is also a copy paste error from Inception.

**Comment by KavishBhatia** [comment]
I was also just copy pasting. Silly me. Now I can see the `ROLE_REMOTE`. Thank You @reckart for all the help. Appreciate it. 
I will close the issue now.

**Comment by reckart** [comment]
:D
