### ISSUE TITLE
Turning pages not possible

### ISSUE THREAD

**Issue by MeDarina** [webanno/webanno#168]
Sometimes going to the next or previous page is not possible. Annotators told me that this happens sometimes and works again after re-opening the document (so I do not know whether the way I  could reproduce it is the only case in which this happens).
I could reproduce it in the following way: 
1) Change number of displayed sentences (in settings) to a small number (less than the document has)
2) Go to "next" page
3) Change number of displayed sentences (in settings) to a big number (more than the document has)
4) Go to "prev." page --> Error message: this is the first page

**Comment by aakashysharma** [comment]
Only happens for previous page. Working on it.
