### ISSUE TITLE
Invalid Zip File while Importing tsv File

### ISSUE THREAD

**Issue by ashikrafi** [webanno/webanno#1686]
Dear Team,

Thank you very much for all the efforts. However, I am facing a problem right now while importing tsv file. It shows **"Error importing project: IOException: Invalid ZIP file"**. For your information, this tsv file was generated by Tensorflow. 

I have attached a screenshot for your consideration. Please have a look into it.

![Capture](https://user-images.githubusercontent.com/6106868/82443667-ae317b00-9ac3-11ea-9141-c165ecbee64f.PNG)

Thank you,
Ashikur

**Comment by jcklie** [comment]
What are you trying to import? This is the project import and needs a Webanno project that you exported before, not a generic zip file.

**Comment by reckart** [comment]
TSV files need to be imported by selecting "WebAnno TSV 3" from the format dropdown and then clicking the Documents "Choose files" button to select which files to upload. The import projects panel only accepts ZIP files that were generated via the export tab in the project settings.

**Comment by ashikrafi** [comment]
Hi,

I would like to import the output file generated by NeuroNER. 

- How to import the output file ?
- How to display the output file?
- Another thing is that- do I need to manually annotate the texts in file? Any other option?

Thank you
Ashikur

**Comment by jcklie** [comment]
What file format does NeuroNER give you as output? Webanno supports many file formats, see [here](https://webanno.github.io/webanno/releases/3.4.0/docs/user-guide.html#sect_formats). You might need to write a conversion script though.

**Comment by jcklie** [comment]
CoNLL 2002 looks good

**Comment by ashikrafi** [comment]
Thanks.

One more thing. How to convert JSON to WebAnno TSV 3? Could you please tell me?

**Comment by seyyaw** [comment]
@ashikrafi for the first issue, we do not have an automatic JSON to TSV converter. Maybe you need to write your own script to do so. You also make sure you have created the types in the WebAnno project.

The second issue is underspecified, what is the error? Are you creating an automation project?

**Comment by ashikrafi** [comment]
@seyyaw 
The first issue has been resolved. 

Actually, I have been trying to upload a tsv file to WebAnno where the project type is Automation or Annotation. But when the tsv file is uploaded, I am unable to visualize named entity recognition automatically.

What should I do after I upload the file? Do I need to do anything else? I am just stuck.

**Comment by seyyaw** [comment]
@ashikrafi, Strange! If you have properly converted the JSON to TSV and you have the annotation types in WebAnno, they should be visible. If you want, you can share the TSV files and we can try it.

**Comment by ashikrafi** [comment]
@seyyaw 

Thank you very much for your cooperation. 

- **Please find the attachment and unzip it in order to get the TSV file.** 
[tensorboard_metadata_tokens.zip](https://github.com/webanno/webanno/files/4682957/tensorboard_metadata_tokens.zip)

- **Below I have shared the screenshots of how I tried to do the job. But the last screenshot shows no outcome**

**Step: 01**

![W_001](https://user-images.githubusercontent.com/6106868/82915177-3e733280-9f92-11ea-8d97-b8316c4bc3d7.PNG)

**Step: 02**

![W_002](https://user-images.githubusercontent.com/6106868/82915204-459a4080-9f92-11ea-9f6f-913b388fa67b.PNG)

**Step: 03**

![W_003](https://user-images.githubusercontent.com/6106868/82915216-492dc780-9f92-11ea-83ef-9934ceca4b99.PNG)

**Step: 04**

![W_004](https://user-images.githubusercontent.com/6106868/82915227-4cc14e80-9f92-11ea-8eb5-822cfe52f66b.PNG)

**Comment by ashikrafi** [comment]
@seyyaw 

I look forward to hearing from you soon.
Thank you

**Comment by seyyaw** [comment]
HI @ashikrafi 
I look into your file
Two things 1) the file is not a proper TSV file. Please check [here](https://webanno.github.io/webanno/releases/3.6.5/docs/user-guide.html#sect_webannotsv) to see how the TSV file should look like. 2) You also import the file as a plain text file (from the screenshot above).

**Comment by ashikrafi** [comment]
Hi @seyyaw 

Thank you. It helped me a lot. However, I have a new issue now. **Could you please tell me in what format the below file is?** I have been trying to convert this file into CoNLL format.  

![Format](https://user-images.githubusercontent.com/6106868/83236345-32b38600-a1b5-11ea-87a5-e830251843c2.PNG)

I look forward to hearing from you.

**Comment by seyyaw** [comment]
@ashikrafi Please continue referring this [link](https://webanno.github.io/webanno/releases/3.6.5/docs/user-guide.html#sect_webannotsv). You need to add also the header information for the annotation types.

**Comment by reckart** [comment]
Import a plain text file, make a few annotations, then export as TSV3 to see an example of the format. The specification of the format is given at the location @seyyaw has already provided above: https://webanno.github.io/webanno/releases/3.6.5/docs/user-guide.html#sect_webannotsv

You can also find lots of snippets we use in unit testing here: https://github.com/webanno/webanno/tree/master/webanno-io-tsv/src/test/resources/tsv3-suite

**Comment by reckart** [comment]
Closing the issue as there was no more feedback.
