### ISSUE TITLE
Shortcut to select entity type while annotating NE

### ISSUE THREAD

**Issue by matthieus** [webanno/webanno#169]
To my knowledge, there is no shortcut to choose an entity type (i.e. Location vs Organization vs Person). Brat has it and it significantly speeds up the annotation job.

**Comment by seyyaw** [comment]
Hi @matthieus 
If you mean key binding, we are working to have it in WebAnno 3

**Comment by seyyaw** [comment]
Now available in [WebAnno 3.0.0 beta 1](https://github.com/webanno/webanno/releases/tag/webanno-3.0.0-beta-1)
