### ISSUE TITLE
Allow remote api via API token

### ISSUE THREAD

**Issue by jcklie** [webanno/webanno#1696]
**Is your feature request related to a problem? Please describe.**
Using an API token instead of user/password is nice, as you do not risking leaking the password and it would maybe allow Shibboleth.

**Describe the solution you'd like**
Generate an API token in user settings for remote api access.

**Comment by reckart** [comment]
The remote API in INCEpTION now supports OAuth. Note that INCEpTION does not issue the tokens - a separate OAuth server such as Keycloak is required to use this functionality.

See https://inception-project.github.io/releases/26.6/docs/admin-guide.html#_oauth2_authentication
