### ISSUE TITLE
More explicit UI for accepting/rejecting recommender suggestions - feature for INCEpTION 

### ISSUE THREAD

**Issue by waleedabdeen** [webanno/webanno#1697]
**Is your feature request related to a problem? Please describe.**
The current UI for accepting/rejecting the recommended annotation request via single/double is error-prone. This is an extension for a feature request in INCEpTION application

Issue in INCEpTION [inception-project/inception/issues#1634](https://github.com/inception-project/inception/issues/1634)

**Describe the solution you'd like**
I plan to add two buttons on top of the recommended annotation span to accept/reject suggestions, that are shown when mouse is over the annotation and hidden/removed when mouse it out.

**Comment by reckart** [comment]
Move downstream: https://github.com/inception-project/inception/issues/1634
