### ISSUE TITLE
replacing a tagset causes Runtime Exception

### ISSUE THREAD

**Issue by mmev** [webanno/webanno#170]
Replacing a custom tagset causes Runtime Exception in a project.

See:
[Unexpected RuntimeException.webarchive.zip](https://github.com/webanno/webanno/files/103422/Unexpected.RuntimeException.webarchive.zip)

**Comment by aakashysharma** [comment]
Hi @mmev could you please tell us what steps did you perform in order to replace a tagset?

After #76 importing a tagset file twice would add a new tagset with "Copy of" as prefix. So, I'm curious about the steps you performed to replace tagset.

**Comment by mmev** [comment]
Hi Aakash,

steps I have done:
- open the project
- go to Tagsets
- click on the tagset name (the tagset will be activated)
- within the box 'Import tagset':  choose Format (TAB-separated for me), and Files (one txt-file with the same format I originally used for this tagset; thus, it should work -- and it works for a new project)
- click on Import tagset
= crash

What should I do another way?

**Comment by aakashysharma** [comment]
If you just import, without the intent of replacing tagset, does it work? Also, could you send me the text file in email?

**Comment by mmev** [comment]
I am sorry, I edited my previous comment in the meantime.

**Comment by mmev** [comment]
[SemAnnoRoleInventory_20160125_WA.txt](https://github.com/webanno/webanno/files/103529/SemAnnoRoleInventory_20160125_WA.txt)

**Comment by mmev** [comment]
Dear Aakash,

please find the tagset-file for issue #170 attached.

I am using it on Testing with
WebAnno -- 3.0.0-SNAPSHOT (2015-12-14 18:54:52, build 
c602bd968037e46f66b56986ba3f52b1c7d026f1)
for the projects kp3_role_reA and kp3_role_reB.

Best regards,
Eva


Éva Mújdricza-Maydt
Institut für Computerlinguistik, Ruprecht-Karls-Universität Heidelberg
Raum 122, Im Neuenheimer Feld 325, 69120 Heidelberg
Tel: 06221-54-3483
E-Mail: mujdricz@cl.uni-heidelberg.de
Studienberatung (BA): studienberatung@cl.uni-heidelberg.de
Webseite: http://www.cl.uni-heidelberg.de/~mujdricz/

Am 1/25/16 um 17:48 PM schrieb Aakash Sharma:
> If you just import, without the intent of replacing tagset, does it
> work? Also, could you send me the text file in email?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webanno/webanno/issues/170#issuecomment-174577905>.
>

Role	semantische Rolle
de	 
Agent	~ Ausführender, Handelnder\n\nDef: (Actor) führt ein Ereignis *intentional* und *bewusst* aus und existiert *unabhängig* von diesem Ereignis; typischerweise lebendig, muss aber nicht menschlich sein; das Prädikat drückt keine Emotion oder Sinneswahrnehmung aus\n\nTest: _Handelt der Partizipant bewusst/mit Intention/mit Absicht?_
Attribute	~ Eigenschaft eines Partizipanten\n\nDef: (Circumstance) das Ereignis referiert auf/involviert die *Charakterisierung oder Eigenschaft eines Partizipanten* ; bevorzugt ein identifizierender, beschreibender, *charakterisierender Ausdruck*\n\nTest: _Leistet das Argument eine Charakterisierung eines Partizipanten im Ereignis?_
Beneficiary	~ Profitierender, Benachteiligter\n\nDef: (Undergoer) ein Beteiligter am Ereignis, der einen *Vor- oder Nachteil* aus dem Ereignis erleidet (mit oder ohne Absicht); der Vor- oder Nachteil wird *durch die Verbbedeutung* impliziert; *existiert unabhängig* vom Ereignis; tendenziell belebt\n\nTest: _Impliziert das Prädikat einen Vor- oder Nachteil für den Partizipanten?_
Cause	~ Auslöser, Ursache, Voraussetzung\n\nDef: (Actor) *nicht intentionaler*, *nicht bewusster* *Auslöser oder Ursache* eines Ereignisses; kann sowohl belebt, als auch unbelebt sein; wie ein Agent existiert Cause vom Ereignis *unabhängig* ; tendenziell abstrakt\n\nTest: _Ist der Partizipant die Voraussetzung oder Ursache für das Ereignis?_ ; _Verursacht der Partizipant das Ereignis ohne eigene Willenskraft?_
Co-Agent	~ gleichwertiger Mithandelnder\n\nDef: (Actor) *gleichgestellter* Teilnehmer *neben dem Agent* in einem Ereignis, wobei die Bedeutung des *Prädikats* eine gleichzeitige Teilnahme mehrerer Partizipanten *erfordert* , das Ereignis basiert typischerweise auf Gegenseitigkeit; trägt die gleichen Eigenschaften wie der Partizipant mit der Agent-Rolle\n\nTest: _Wäre der Satz ohne diesen weiteren Agent-Partizipanten ungrammatisch?_
Co-Patient	~ gleichwertiger Mitbetroffener\n\nDef: (Undergoer) ein *Patiens* , der *mit einem anderen zusammen* in einem Ereignis verändert wird, wobei die Teilnahme von der Verbsemantik aus *erforderlich* ist; trägt die gleichen Eigenschaften wie der Partizipant mit der Patient-Rolle\n\nTest: _Wäre der Satz ohne diesen weiteren Patient-Partizipanten ungrammatisch oder semantisch unvollständig?_
Co-Theme	~ gleichwertiges Theme\n\nDef: (Undergoer) ein *Theme* , das sich in einem Ereignis *gleichwertig* und *erforderlicherweise mit einem anderen Theme* beteiligt; trägt die gleichen Eigenschaften wie der Partizipant mit der Theme-Rolle\n\nTest: _Wäre der Satz ohne diesen weiteren Theme-Partizipanten ungrammatisch oder semantisch unvollständig?_ ; _Beteiligen sich beide Theme-Partizipanten auf gleiche Weise am Ereignis?_ (wenn nicht: Pivot)
Destination	~ Endpunkt, Zielort\n\nDef: (Undergoer) ein *tendenziell konkreter* , *physikalisch beschreibbarer Zielort* des Ereignisses, der *unabhängig* vom Ereignis existiert; *tendenziell nicht belebt* ; zum Teil auch abstrakt wie Organisationen\n\nTest: _Führt das Ereignis zum Partizipanten als Zielort, Endpunkt?_
Duration	~ Dauer\n\nDef: (Time) eine *zeitlich* bestimmte Angabe, die die Länge, *Dauer* des Ereignisses hervorhebt\n\nTest: _Drückt die Angabe eine zeitliche Länge, Dauer des Ereignisses aus?_
Experiencer	~ Fühlender, Wahrnehmender\n\nDef: (Undergoer) ein Patient, wenn er am Ereignis *bewusst wahrnehmend* teilnimmt; die Wahrnehmung bezieht sich auf *Emotionen* oder *Sinneseindrücke* ; existiert *unabhängig* vom Ereignis; kommt typischerweise zusammen mit Stimulus vor\n\nTest: _Erlebt der Partizipant etwas emotional?_ (wenn nicht: Agent oder Theme) ; _Nimmt der Partizipant etwas bewusst wahr?_
Extent	~ Wertänderung\n\nDef: (Undergoer/Quantity) eine *Änderung eines Werts* während des Ereignisses\n\nTest: _Drückt der Partizipant eine Wertänderung während des Ereignisses / durch das Ereignis aus?_
Frequency	~ Häufigkeit\n\nDef: (Time) *Häufigkeit* , Angabe über die *Wiederholung eines Ereignisses*\n\nTest: _Drückt das Argument eine repetitive Wiederkehr des Ereignisses aus?_
Goal	~ Ziel, Zielsetzung\n\nDef: (Place) der *Endpunkt* oder *Ziel* eines Ereignisses (evtl. im Sinne vom Zweck), *bevorzugt abstrakt* ; existiert *unabhängig* vom Ereignis; das Ziel ist *beabsichtigt oder gewollt*\n\nTest: _Ist das Argument ein beabsichtigtes Ziel des Ereignisses?_
Initial_Location	~ Ausgangspunkt\n\nDef: (Place) ein *konkreter, physischer Ort* als *Ausgangspunkt* für das Ereignis\n\nTest: _Drückt das Argument einen konkreten Ausgangspunkt für das Ereignis aus?_
Instrument	~ Werkzeug\n\nDef: (Undergoer) ein *Instrument, Werkzeug* , womit das Ereignis ausgeführt wird; das Werkzeug ist *typischerweise nicht belebt* , aber es *kann auch eine Maschine oder ein belebtes Wesen sein* ; ein Instrument hat *keine Willenskraft* , ist *nicht bewusst* ; *existiert unabhängig* vom Ereignis; der Agens, der die Handlung mithilfe des Instruments ausführt, muss nicht explizit erwähnt werden\n\nTest: _Wird das Ereignis mithilfe des Arguments ausgeführt?_
Location	~ Ort\n\nDef: (Place) ein primär *konkreter Ort* , an dem das Ereignis situiert ist oder stattfindet; *existiert unabhängig* vom Ereignis\n\nTest: _Beschreibt das Argument den konkreten Ort, an dem das Ereignis situiert ist oder stattfindet?_
Locus	~ Verortung\n\nDef: (Place) *abstrakte Verortung* des Ereignisses; *existiert unabhängig* vom Ereignis\n\nTest: Beschreibt das Argument die abstrakte Verortung des Ereignisses?
Manner	~ Art und Weise der Handlung\n\nDef: (Circumstance) beschreibt die *Art und Weise* einer *Handlung*, oder die Eigenschaft eines Zustands; (oft ein Adjunkt)\n\nTest: _Wie ist etwas passiert?_
Material	~ Material\n\nDef: (Place) Ein Patiens, der am Anfangspunkt eines transformierenden Ereignisses steht (Source), und der *durch das Ereignis zu einer anderen Entität geformt wird* ; das Ereignis ist typischerweise beabsichtigt; kann konkret oder abstrakt sein\n\nTest: _Wird aus dem Argument etwas Neues geformt oder gebildet?_
Path	~ Weg\n\nDef: (Place) *Weg zu etwas* , ein *abstrakter* Weg, *Bereich* ; Das Ereignis drückt typischerweise eine *Bewegung*  (in konkretem oder übertragenem Sinne) aus, diese Bewegung verläuft entlang des Weges/durch den Bereich.\n\nTest: _Drückt das Argument einen abstrakten Weg oder Bereich aus, durch den das Ereignis verläuft?_
Patient	~ Patiens, Betroffener, Veränderter\n\nDef: (Undergoer) ein Beteiligter, Betroffener an der Handlung, der *vor dem Ereignis unabhängig* vom genannten Ereignis existiert, der aber durch das Ereignis in bestimmter Weise *ohne eine eigene Intention* *verändert wird (typischerweise in Form, Struktur, Zustand)* ; die Änderung kann auch den Entzug der Existenz mit einbeziehen; kann *belebt oder unbelebt* sein, tendenziell jedoch ein belebter Partizipant; kann abstrakt oder konkret sein, *tendenziell* jedoch ein *konkreter* Partizipant\n\nTest: _Wird der Partizipant durch das Ereignis oder durch einen anderen Partizipanten verändert, ohne zu einer neuen Entität geformt zu werden?_
Pivot	~ betontes Theme\n\nDef: (Undergoer) eine *themeartige* Rolle, die zu wählen ist, *wenn bereits ein Theme als Gegenstand des Ereignisses eindeutig zugewiesen werden muss* . Pivot wird als *zentraler, wichtiger, mehr betont* im Ereignis empfunden als das weitere Theme. Das Prädikat erfordert typischerweise ein (logisches) Subjekt mit themeartigen statt agentartigen Eigenschaften, dieses Subjekt wird tendenziell als Pivot annotiert. Oft realisiert die Pivot-Rolle zusätzliche Bedeutungsaspekte eines Themes.\n\nTest: _Beteiligt sich das Argument am Ereignis neben einem Theme-Argument als Gegenstand des Ereignisses, spielt jedoch eine mehr zentrale Rolle im Ereignis als das andere Theme?_ (wenn gleichwertige Partizipanten: Co-Theme)
Product	~ Erzeugtes, Produkt\n\nDef: (Place) ein *konkretes* Resultat: ein spezieller, *objektartiger Endpunkt* (Goal, Resultat) eines Ereignisses, der *durch das Ereignis erzeugt* wird oder durch das Ereignis *zustande kommt*; existiert nicht vor dem Ereignis; mit dem Ereignis kommt es zur Existenz\n\nTest: _Entsteht das konkrete Argument durch das Ereignis?_
Recipient	~ Empfänger\n\nDef: (Undergoer; früher Place) ein *typischerweise belebter* Partizipant, der in der Situation etwas *empfängt, aufnimmt, bekommt* ;  das Prädikat drückt typischerweise einen Besitzwechsel oder 'Transfer' aus, dessen Endpunkt, Ziel der Partizipant ist -- *Endpunkt eines Besitzwechsels/Transfer-Events* ; der Gegenstand (ausgedrückt durch ein weiteres Argument) kann auch abstrakt sein wie z.B. in einem kommunikativen Event ; existiert *unabhängig* vom Ereignis\n\nTest: _Wird im Ereignis etwas zum aktuellen Argument transferiert?_
Result	~ Resultat, Ergebnis\n\nDef: (Place) *Folge* , *Resultat* ; ein spezieller, *bevorzugt abstrakter Endpunkt* (Goal) eines Ereignisses, der durch das Ereignis *erzeugt wird/zustande kommt* ; existiert nicht vor dem Ereignis\n\nTest: _Entsteht die abstrakte Entität, das durch das Argument ausgedrückt wird, durch das Ereignis?_
Source	~ Quelle, Ursprung\n\nDef: (Place) *Quelle, Ursprung* ; ein *nicht örtlich* aufgefasster *Ausgangspunkt* für das Ereignis, kein physikalischer Ort; *tendenziell abstrakt* und *tendenziell unbelebt* ; existiert *unabhängig* vom Ereignis, eine Veränderung des Arguments durch das Ereignis ist nicht relevant\n\nTest: _Steht das Argument für einen nicht örtlich aufgefassten Ausgangspunkt des Ereignisses, wobei es während des Ereignisses nicht verändert oder umgeformt wird?_
Stimulus	~ Wahrgenommenes, Erlebtes\n\nDef: (Actor) eine spezielle Cause-Rolle für *Wahrgenommenes, Erlebtes* in Ereignissen, die eine emotionale oder wahrnehmende Haltung einbeziehen; kann konkret oder abstrakt sein; typischerweise kommt eine Stimulus-Rolle mit einer Experiencer-Rolle zusammen vor\n\nTest: _Steht das Argument für den auslösenden Gegenstand der Emotion bzw. des Sinneseindrucks?_
Theme	~ Objekt, Gegenstand des Ereignisses, Thema\n\nDef: (Undergoer) ein allgemeiner, abstrakter oder konkreter *Partizipant* , der durch das Ereignis *betroffen* ist, der jedoch in Gegensatz zu einem Patient *nicht verändert* wird, und der *keine Kontrolle* über das Ereignis hat wie ein Agens.; existiert *unabhängig* vom Ereignis; kann belebt oder unbelebt sein; kann abstrakt oder konkret sein; Das Prädikat drückt keine Emotion, Wahrnehmung eines Sinneseindruckes oder Kommunikation aus. Bei gleichgesetzten themeartigen Partizipanten ist der weitere als Co-Theme zu annotieren. Sind mehrere themeartige Partizipanten am Ereignis beteiligt, wobei diese nicht gleichgesetzt werden können, ist der zentralere als Pivot zu annotieren.\n\nTest: _Drückt das Argument das grundsätzliche Thema/den grundsätzlichen Gegenstand des Ereignisses aus?_
Time	~ Zeitpunkt\n\nDef: (Time) Angabe über den *einmaligen* *Zeitpunkt* oder *Intervall* , zu dem das Ereigniss stattfindet, abläuft;\n\nTest: _Drückt das Argument aus, wann das Ereignis passiert?_
Topic	~ Kommuniziertes\n\nDef: (Undergoer) beschreibt den *Inhalt einer Informationsübergabe*\n\nTest: _Drückt das Argument den Gegenstand eines kommunikativen Ereignisses aus?_
Trajectory	~ konkreter Weg\n\nDef: (Place) ein *konkreter Weg* (Path) zu etwas; Das Ereignis drückt typischerweise eine *Bewegung*  (in konkretem oder übertragenem Sinne) aus, diese Bewegung verläuft entlang des Weges/durch den Bereich.\n\nTest: _Drückt das Argument einen konkreten Weg oder Bereich aus, durch den das Ereignis verläuft?_
Value	~ messbarer Wert\n\nDef: (Place/Quality) ein *messbarer, aber typischerweise abstrakter Wert auf einer Skala* , dessen Angabe als skalarer Wert für die Prädikatbedeutung wesentlich ist\n\nTest: _Drückt das Argument einen Wert als wesentliche Bedeutungskomponente des Ereignisses/Zustands aus?_

**Comment by aakashysharma** [comment]
Looks like we'll have to change how #76 was fixed.

**Comment by reckart** [comment]
Then let's reopen #76.

**Comment by aakashysharma** [comment]
Closing this for now. I'll test after fixing #76. If if it still not fixed, will re-open this.
