### ISSUE TITLE
More tooltips

### ISSUE THREAD

**Issue by An-Feli** [webanno/webanno#1716]
**Is your feature request related to a problem? Please describe.**
Sometimes, I do not know what a button is for.

**Describe the solution you'd like**
Would be nice to get a helpful tooltip when hovering the mouse cursor over the button.

**Additional context**
See also: https://github.com/inception-project/inception/issues/1620

**Comment by UWinch** [comment]
@An-Feli Are there more tooltips you want to add or can this issue be closed?

**Comment by An-Feli** [comment]
I think it's fine for now. We can close it.
