### ISSUE TITLE
AnnotationDetailEditorPanel rendered way too often

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#172]
The AnnotationDetailEditorPanel is rendered way too often. This can be observed e.g. by adding a print statement to de.tudarmstadt.ukp.clarin.webanno.brat.annotation.component.AnnotationDetailEditorPanel.FeatureEditorPanelContent.populateItem(Item<FeatureModel>).

E.g. when simply reloading a page, we get the AnnotationDetailEditorPanel rendered four times!

```
Adding tooltip behavior to #valuea9_listbox
2016-02-15 22:46:14  INFO [http-bio-8080-exec-7] [admin] (BratAnnotator) - AJAX-RPC CALLED: [whoami]
2016-02-15 22:46:14  INFO [http-bio-8080-exec-7] [admin] (BratAnnotator) - AJAX-RPC DONE: [whoami]
Adding tooltip behavior to #valueb0_listbox
2016-02-15 22:46:14  INFO [http-bio-8080-exec-5] [admin] (BratAnnotator) - AJAX-RPC CALLED: [getCollectionInformation]
2016-02-15 22:46:14  INFO [http-bio-8080-exec-5] [admin] (BratAnnotator) - AJAX-RPC DONE: [getCollectionInformation]
Adding tooltip behavior to #valueb6_listbox
2016-02-15 22:46:15  INFO [http-bio-8080-exec-5] [admin] (BratAnnotator) - AJAX-RPC CALLED: [getDocument]
2016-02-15 22:46:15  INFO [http-bio-8080-exec-5] [admin] (BratAnnotator) - AJAX-RPC DONE: [getDocument]
Adding tooltip behavior to #valuebc_listbox
```

Every time `Adding tooltip behavior to...` appears in the output above, the AnnotationDetailEditorPanel is rerendered and in that case that means about 500k of data being sent from server to client because there is a link feature with a large number of selections.

The first rendering is a normal page render, the others are triggered by AJAX requests - and the latter (whoami, getCollectionInformation, getDocument) should **not** trigger a re-rendering.

**Comment by reckart** [comment]
Culprit seems to be an unconditional reload of the editor panel on every request!

https://github.com/webanno/webanno/blob/master/webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotator.java#L394

**Comment by reckart** [comment]
@seyyaw Looks like you added this unconditional reload. Any specific reason why?

**Comment by reckart** [comment]
@seyyaw If you don't see any immediate problem, I'd suggest to move the reload into the condition where I think it should belong:

```
 if (getModelObject().getSelection().getAnnotation().isNotSet()) {
                    editor.setAnnotationLayers(getModelObject());
                    editor.reload(aTarget); // Add here
                }
                editor.reload(aTarget); // Remove here
```

**Comment by seyyaw** [comment]
It seems it is added during forward annotation and cursor loading debug but I found it safe to remove it totally. I run some test and it doesn't cause any problem

**Comment by reckart** [comment]
Ok, thanks!
