### ISSUE TITLE
adding login message from settings property

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#173]
Adding a simple message with style at login page. 
In settings.properties file

`login.message=` add custom message to appear at login page
`style.login.message=` add simple style such as color and font to this message

**Comment by reckart** [comment]
New setting should be documented in admin guide: https://github.com/webanno/webanno/blob/master/webanno-doc/src/main/asciidoc/admin-guide/settings.adoc

**Comment by reckart** [comment]
How about allowing HTML code including style for this message. That would also allow users to add a link to some page, e.g. with terms and conditions. We'd not need the 'style.login.message' property then.

**Comment by reckart** [comment]
This seems to be not in the documentation yet - at least I see no commit for it.

**Comment by reckart** [comment]
@seyyaw please use asciidoc syntax in the documentation, not HTML fragements.
