### ISSUE TITLE
Make a hint for 'invisible annotation in other pages' in the Annotation interface, too

### ISSUE THREAD

**Issue by mujdricza** [webanno/webanno#174]
If an annotation instance is going over sentences, and the page is not showing all of the affected sentences with the long annotation, then this annotation instance is not shown at all.

In Curation, there is a hint "Invisible annotation in other pages" -- the same would be great for the Annotation interface, too.

**Comment by reckart** [comment]
INCEpTION provides this for spans now: https://github.com/inception-project/inception/issues/2342
