### ISSUE TITLE
Export issue for CoNLL formats

### ISSUE THREAD

**Issue by floschne** [webanno/webanno#1742]
**Describe the bug**
I created a test document and added a single NE annotation that consists of only one token.
When exporting the document with the following CoNLL formats, the annotation was not reflected in the exported file.

- CoNLL 2000
- CoNLL 2006
- CoNLL 2009
- CoNLL-U

The other CoNLL formats (2002, 2003, 2012, CoreNLP) included the annotation.

_I haven't tested with other annotation layers or other export formats - so maybe you want to check them as well._

**To Reproduce**
1. Create a test document and create a NE-Pers span annotation consisting of one Token
2. Export with the CoNLL formats listed above
3. Open the exported file and see that you see nothing ;-) at least from the NE-PER annotation

**Expected behavior**
The exported file should reflect the annotation

**Please complete the following information:**
 - Version and build ID: 4.0.0-SNAPSHOT - current master branch from 22.07.2020
 - OS: Ubuntu 18.04 LTS
 - Browser: latest chrome dev browser

**Comment by jcklie** [comment]
I think that is intended behaviour, as the Conll formats not only define how they are serialized, but also which layers are:

The CoNLL 2000 format represents POS and Chunk tags. 
The CoNLL 2006 (aka CoNLL-X) format targets dependency parsing.
The CoNLL 2009 format targets semantic role labeling. 
The CoNLL 2012 format targets semantic role labeling and coreference. 

You can find an overview at e.g. the [DKPro File Format Documentation](https://dkpro.github.io/dkpro-core/releases/1.9.2/docs/format-reference.html#format-de.tudarmstadt.ukp.dkpro.core.io.conll-asl).

**Comment by reckart** [comment]
As @jcklie said: NEs do not appear in formats which do not support NEs - that is expected behavior.

**Comment by floschne** [comment]
Alright, thanks for the info. Didn't know this :-)
