### ISSUE TITLE
Codebook export doesn't work when exporting a whole project

### ISSUE THREAD

**Issue by floschne** [webanno/webanno#1747]
**Describe the bug**
Exporting a project with Codebooks throws an error because the Codebooks cannot be exported.
This is because of the "new" CASStorageService, which requires a CAS storage session for the CASes that include the Codebook annotations. In theory, this could be easily fixed by simply creating those sessions BUT would introduce a cyclic dependency between `webanno.api.dao` and `webanno.api.codebook`. In practice, this requires to refactor the architecture of codebook export but can also be done. 

(Pruned) Error-log:
`ERROR [admin] de.tudarmstadt.ukp.clarin.webanno.ui.core.page.ApplicationPageBase - admin: Unexpected error during project export: CasSessionException: No CAS storage session available
ERROR [admin] de.tudarmstadt.ukp.clarin.webanno.ui.core.page.ApplicationPageBase - admin: Project export failed`

**To Reproduce**
1. Create a project with codebooks and annotate some documents with those codebooks
2. Go to Project Settings > Export
3. Select Format: AUTO and click the export button
4. See the error messages in the UI as well as in the debug log

**Expected behavior**
No error messages and successful export of the project

**Please complete the following information:**
 - Version and build ID: 4.0.0-SNAPSHOT (2020-07-28 22:14:51, build 2d09f9d064556e52d0ee5dd7c49271a42766472e)
 - OS: Ubuntu 18.04 LTS
 - Browser: latest chrome dev.

**Comment by reckart** [comment]
Closing as it has been merged into the codebook branch already
