### ISSUE TITLE
Really destroy cas when deleting cas

### ISSUE THREAD

**Issue by UWinch** [webanno/webanno#1749]
**Describe the bug**
In `CasStorageServiceImpl.deleteCas(SourceDocument aDocument, String aUsername)` the object pool for the Cas is not deleted. However, we are deleting the associated file, so the cas object should also be deleted from the pool.

**Additional context**
For https://github.com/inception-project/inception/issues/1796. For re-merge, the cas state is re-set by deleting it (on disk) and then re-creating and saving a newly merged cas. However the cas is retained in the pool and taken as a basis for the re-merged one.

**Comment by reckart** [comment]
Should we not keep it checked out from the pool so we keep a lock on it to prevent a concurrent thread from doing something with that cas while e we are not done re-merging yet?

**Comment by reckart** [comment]
Would it make sense to overwrite the CAS in the pool with the remerged CAS? Since we must have exclusive access to the CAS during remerge that should probably be fine?

**Comment by UWinch** [comment]
Currently we have exclusive access for the deletion of the cas. Then for getting the mergecas, we try `readCas` which will give us an exception because the file is no longer on disk, then we use `createCurationCas` which uses `readAnnotationCas(aRandomAnnotationDocument,UNMANAGED_ACCESS)`. Not sure if this can be dangerous.

**Comment by reckart** [comment]
We use `readAnnotationCas(aRandomAnnotationDocument,UNMANAGED_ACCESS)` because we read some user's annotation file and then store it under the name of another user (i.e the CURATION user). That must be done unmanaged so the CAS storage doesn't complain that we try to save the data under another user.
