### ISSUE TITLE
[Curation] 'Invisible annotation in other pages' does not work for simple span annotation

### ISSUE THREAD

**Issue by mmev** [webanno/webanno#175]
In Curation, the 'Invisible annotation in other pages' does not work. 
See the attached files with a span annotation example (green color) which spans over the sentences 120 and 121. 

![annotationbeyondsentences_s120-s121_notshownmissinginvisibleannotationhint](https://cloud.githubusercontent.com/assets/5416080/13248544/3235194e-da1f-11e5-8ed4-938fbe307025.png)
![annotationbeyondsentences_s120-s121_shownwithinthesamepage](https://cloud.githubusercontent.com/assets/5416080/13248543/3233f186-da1f-11e5-8804-a4162b3918f2.png)

**Comment by seyyaw** [comment]
It works. Look the following:
![image](https://cloud.githubusercontent.com/assets/1056051/13855563/57cdadb0-ec71-11e5-9870-9144bb654cb1.png)

The annotation is as follows:
![image](https://cloud.githubusercontent.com/assets/1056051/13855606/91e2af1e-ec71-11e5-891b-cfbd27557f45.png)

**Comment by seyyaw** [comment]
re-open if you still have the issue, with some examples (or indicate the project and files in experimental using internal email)
