### ISSUE TITLE
escape special characters for TSV import/Export

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#176]
We use the **|** character as multiple annotation character and the **_** character for empty annotations.
Escape them if they are used in the annotation.
Reported by @ChrisBieTUDA

**Comment by reckart** [comment]
```
	// If | is used as annotation, escape it with `|` and replace it with WEBANNO_BAR for processing
	// WEBANNO_BAR will be a reserved word, the same for [, ],  and _
	private static String WEBANNO_BAR = "WEBANNOBAR";
	private static String WEBANNO_RBR = "WEBANNORBR";
	private static String WEBANNO_LBR = "WEBANNOLBR";
	private static String WEBANNO_UNDERSCORE = "WEBANNOUNDERSCORE";
```

This is a very ugly solution and it introduces new "reserved words".

I'd very much vote for a backslash based escaping, e.g `|` should become `\|` and to the `\` itself should become `\\`. This is a very typical escaping, much less verbose, and does not create new "magic words".

@ChrisBieTUDA

**Comment by reckart** [comment]
This should definitely be fixed before the release.

Backslash-based escaping is simple:

* when writing put a backslash in front of all special characters including the backslash itself
* when parsing a line for special characters during reading, ignore them if they are preceded by a backslash
* after the input format has been parsed just remove all remaining backslashes in the content

**Comment by seyyaw** [comment]
why put backslash before backslash? We just need to escape the special characters (backslash is not special character and hence not ambiguous for parsing) we use internally in WebAnno.

**Comment by reckart** [comment]
The WEBANNO_BAR etc. constants are still there...?

**Comment by reckart** [comment]
@seyyaw if the backslash is used for escaping then it has a special function (escaping) and thus if a backslash appears literally in an annotation or token it needs to be escaped.

**Comment by reckart** [comment]
@seyyaw Btw. the TAB character is also a special character in a TSV format.

**Comment by seyyaw** [comment]
the WEBANNO_BAR is there because we use the **|** in the regex to split multiple/stacked annotations. 
242.... `mAnnos.split("\\|"))`

**Comment by seyyaw** [comment]
I can't imagine the TAB char used as annotation in WebAnno. May be  **\t** is used, which is ok

**Comment by seyyaw** [comment]
And, the special characters in WebAnno are the **|**, **[**, **]**, and** _ **which do have special meanings. Other **special characters** such as <, !, .... do not require escaping.

**Comment by reckart** [comment]
Sure, \t is ok, but make sure that if somebody uses "\t" as an annotation, that will also still work
so \t should be `\\t` then in the TSV:

**Comment by reckart** [comment]
I would recommend having some unit test(s) to cover for all these situations.

**Comment by reckart** [comment]
> the WEBANNO_BAR is there because we use the | in the regex to split multiple/stacked annotations. 
242.... mAnnos.split("\\|"))

Sure, but then why is `WEBANNO_BAR = "WEBANNOBAR"` and not `WEBANNO_BAR = "|"`? This looks to me like a magic word. So if an annotation text would include the string "WEBANNO_BAR" I think it would break.

**Comment by seyyaw** [comment]
If **WEBANNO_BAR = "|"**, the parsing will fail, that is why we have this issue.

Yes, **WEBANNOBAR**, **WEBANNORBR**, **WEBANNOLBR**,and  **WEBANNOUNDERSCORE** are reserved words. WebAnno will not allow annotating with them. Any better approach?

**Comment by reckart** [comment]
@seyyaw Well, the idea of escaping is that it allows to use characters or words that would otherwise be reserved. While parsing the data, the escaping respected when encountering special characters and otherwise is removed from it. While writing, it is added. It is never replaced with some other magic strings.

The parsing code needs to be change. The "split by tab" does work if you represent tabs as `\t`. But then e.g. spliting by dash does no longer work because you need to check if the dash is escaped. But you could e.g. try using a negative look-behind in your split expression to only split by `-` but never by `\-` (so split by - only if it is not preceded by the escape character).

Cf. http://stackoverflow.com/questions/18677762/handling-delimiter-with-escape-characters-in-java-string-split-method

**Comment by ChrisBieTUDA** [comment]
Hm, I don't quite get the current state of the escaping. What I know is that we should avoid 'magic strings' of any kind. Eventually, people will manage to 'find' them (Imagine someone walks into a WEBANNOBAR ...) . Please re-assess this; aren't there suitable escaping libraries that could help? Negative look-behind sounds awful :)

**Comment by seyyaw** [comment]
Thank you both for the suggestion. @reckart the answer in the link of sof helps for splitting.
@ChrisBieTUDA yes, there is unescape function in the Apache StringEscapeUtils package. Now possible to walk to **WEBANNOBAR**  =)

**Comment by reckart** [comment]
Special characters are still not sufficiently escaped. E.g. using tabs or newline characters in feature values causes broken TSV:

Current:

```
#FORMAT=WebAnno TSV 3
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity|value


#Text=0-16#This is a test .
1-1	0-4	This	#*'"`´	:{}\|\[ \]()\§$%?=&\_
	
1-2	5-7	is	#*'"`´	:{}\|\[ \]()\§$%?=&\_
	
1-3	8-9	a	#*'"`´	:{}\|\[ \]()\§$%?=&\_
	
1-4	10-14	test	#*'"`´	:{}\|\[ \]()\§$%?=&\_
	
1-5	15-16	.	#*'"`´	:{}\|\[ \]()\§$%?=&\_
	
```

Expected:

```
#FORMAT=WebAnno TSV 3
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity|value


#Text=0-16#This is a test .
1-1	0-4	This	#\*'"`´\t:{}\|\[ \]()\\§$%?=&\_\n	
1-2	5-7	is	#\*'"`´\t:{}\|\[ \]()\\§$%?=&\_\n	
1-3	8-9	a	#\*'"`´\t:{}\|\[ \]()\\§$%?=&\_\n	
1-4	10-14	test	#\*'"`´\t:{}\|\[ \]()\\§$%?=&\_\n	
1-5	15-16	.	#\*'"`´\t:{}\|\[ \]()\\§$%?=&\_\n
	
```

The following special characters must be escaped in feature values:

* `\` - this is the escape character
* `[`, `]` and `|` - these have a special meaning for stacked annotations
* `tab` - this is the TSV column separator character
* `newline` - this is the TSV token separator character
* `_` - this character means "no annotation" and should IMHO for consistency always be escaped
* `*` - this character means "no value" and should IMHO for consistency always be escaped (#240)
