### ISSUE TITLE
Get Projects for Roles

### ISSUE THREAD

**Issue by UWinch** [webanno/webanno#1763]
**Is your feature request related to a problem? Please describe.**
Follow up to https://github.com/webanno/webanno/pull/1743. In `ProjectService`: Would be good to have a method where we can provide the roles and get back the matching projects instead of having a single method for every combination of roles a user can have on a project.

**Comment by reckart** [comment]
Will do this if it comes up during a particular refactoring or performance optimization but won't be a refactoring action on its own. Thus closing.
