### ISSUE TITLE
Memory leak in Export operation

### ISSUE THREAD

**Issue by maciej-brochocki** [webanno/webanno#1788]
**Describe the bug**
Seems like there is a memory leak somewhere during export operation. When memory usage increaseses from usual ~20% to 30% the service starts to work very slowly.

**To Reproduce**
1. Check memory usage in linux with ps
2. Perform multiple export operations
3. Check memory usage in linux with ps

**Expected behavior**
No memory usage increase, no slow down as a result.

**Screenshots**
-

**Please complete the following information:**
 - WebAnno -- 3.6.5 (2020-04-05 20:33:52, build c0bb5da9c28fe6dd328d3bdad738635dcebe992f)
 - Linux
 - any

**Additional context**
-

**Comment by reckart** [comment]
The WebAnno 4 branch has many optimizations for import/export. You could check out the [latest beta release](https://github.com/webanno/webanno/releases/tag/webanno-4.0.0-beta-16). Alternatively, try the new [INCEpTION 0.17.0](https://inception-project.github.io) which also includes these improvements.

**Comment by reckart** [comment]
I should also mention that the `ps` tool is not suitable for measuring memory usage of JVMs. Depending on the JVM you use, it can be that memory once allocated by the JVM is permanently becoming part of its heap and is never again released to the OS. The JVM will internally garbage collect data on this heap and it becomes available for new Java objects, but it is never given back to the OS (for a few pointers, see e.g. [this post](https://stackoverflow.com/questions/30458195/does-gc-release-back-memory-to-os) on StackOverflow).

If you want to diagnose a memory leak, you'd need to check the internal memory usage of the JVM itself, e.g. using tools such as [VisualVM](https://visualvm.github.io) or [Java Mission Control](https://adoptopenjdk.net/jmc.html).

**Comment by reckart** [comment]
Closing as the way that memory usage was measured is not sufficient for JVMs.

**Comment by reckart** [comment]
@maciej-brochocki If you have further evidence of a leak, please let us know.
