### ISSUE TITLE
How can I tag two words separated by apostrophe independently? 

### ISSUE THREAD

**Issue by Ema82** [webanno/webanno#1789]
Hello,
noting some text in Italian, there are cases in which the first of two words has an elision, an apostrophe and then the second word. When I annotate cases like this, it happens that the two words are considered together, when I need them to be considered separately.
For example, in the following text: "_dell'ascensore_" I need to select and tag only "_ascensore_" for the annotation, but when I try to do that, Webanno also includes "_dell'_ " in the selection. 
How can I handle these situations?
I'm using WebAnno 3.6.5.

Thank you

**Comment by seyyaw** [comment]
@Ema82 what is your annotation type? You can decide the annotation type to support "sub-token" annotation in the project settings.

**Comment by Ema82** [comment]
Thanks for the answer seyyaw, 
I tried to set "single tokens only"in Project Settings->Behaviors->Granularity, but it continued to consider the two words together.
I finally solved by setting the granularity to "Character-level". 

Thanks for your suggestion!
