### ISSUE TITLE
Easy to accidentally delete annotations

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#18]
It is possible to accidentally delete an annotation, e.g.:

* select an existing annotation with at least one text feature
* change the value of the text feature
* press enter

Expected: value will change and the brat part re-renders, possibly cursor jumps to the next feature - or in the worst case - simply nothing should happen

Actual: annotation is deleted.

The "create" button is disable because the annotation already existed. Pressing enter thus activates the "delete" button of the form. Delete should never be a default action in the annotation detail editor.

3.0.0-SNAPSHOT (2015-06-11 21:04:37, build 8423c03d340eb33a8d60953b14925e10869097ac)

**Comment by seyyaw** [comment]
It seems disabling "create" Button is not interesting.

**Comment by reckart** [comment]
Why is disabling the "create" button not interesting? I'm actually thinking of completely removing the create button and the ghost and immediately create annotations upon selection. This is actually a request I got from users.

**Comment by seyyaw** [comment]
For example, auto-ghosting is not possible after modifying an existing annotation.

**Comment by reckart** [comment]
Ok - let's leave it at that for now. I cannot see a fix for this though, so why is the issue closed?

**Comment by seyyaw** [comment]
sorry, i took close for closing the editor, not the issue.

**Comment by reckart** [comment]
Sorry, restless mind here ;)

So assuming auto-ghosting is turned off, I as a used expect this:

* open existing annotation
* change some feature value
* press enter
* -> annotation view is re-rendered with updated (optionally jumps to the next feature value as if pressing tab)

Assuming auto-ghosting is turned on, I gather you expect this

* open existing annotation
* change some feature value
* press enter
* -> annotation view is re-rendered with updated
* -> next token is auto-ghosted and opened in the detail editor with the feature values from the previously selected annotation being pre-loaded

Do you agree with my expectations when auto-ghosting is off?
Did I correctly describe your expectations when auto-ghosting is on?

**Comment by seyyaw** [comment]
Yes, this is nice solution for me.

**Comment by reckart** [comment]
So that means that actually, in auto-ghosting mode we'd need a button called "save" or "next" and that would be the default action, but not one that is called "create". And when auto-ghosting is turned off, then we don't need the "create" button, but we also need to make sure that "delete" is not the default action.

**Comment by reckart** [comment]
I have investigated on how to fix this. Basically I found two options

1. instead of disabling the button, it could be hidden using "style: hidden; position: absolute" - however, in some browsers that does not work
2. prevent the "enter keypress" event from leaving the form field and hitting the form

The second option can be implemented by extending the addAnnotateActionBehavior() method to attach a Javascript to suppress this event to each relevant component. What's left is implementing that. 

A naive approach using InputBehavior didn't work out - it generates a Javascript syntax error during evaluation. So a custom solution is probably in order. The accepted answer here should help http://stackoverflow.com/questions/19728494/wicket-preventing-form-submission-by-a-textfield-within-a-wizard-step

**Comment by seyyaw** [comment]
Without forward annotation support, solution is as follows (based on the following suggestion of the accepted answer:   [so link] (http://stackoverflow.com/questions/2335553/jquery-how-to-catch-enter-key-and-change-event-to-tab)


1. For every input element, **Enter** saves the current feature value and move focus to next input field
2. Focus will be lost from all input fields once **Enter** is pressed to the last input element
