### ISSUE TITLE
[TSV]Slot target to a generic Annotation type fails

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#180]
Importing TSV file with a slot feature where the target is generic annotation type, i.e **uima.tcas.Annotation**,  fails. This is because it is ambiguous to which annotation type the target belongs. 
Solution: For generic types, add the actual annotation type along side the target address while exporting.
example: 
`1-3-de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity` indicates that this goes to the Named Entity annotation a token **1-3**
`2-5-de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink` indicates that this goes to the CoreferenceLink annotation at token **2-5**

The TSV file is less readable but unambiguous for the reader. Is this ok @reckart @ChrisBieTUDA

**Comment by reckart** [comment]
Sounds like this will still fail if stacking is enabled.

**Comment by reckart** [comment]
Also, I agree with you that the TSV format would really suffer from that in terms of readability. I don't really like it.

You *could* use something like

```
<sentence>-<token>-<columnnumber>-<in-column-entry>
```

The `<columnnumber>` instead of the full name would make it shorter and more readable.

The `<in-column-entry>` would disambiguate in case of a stacked annotation - e.g. if you wish to address the second Named Entity in the NE column.

**Comment by seyyaw** [comment]
No, stacking will not fail. We numbered stacked annotations.
But the second suggestion seems a lot re-write

**Comment by seyyaw** [comment]
Also, I expect people will use very rarely  the generic Annotation type as a target

**Comment by reckart** [comment]
How would your example from above look if stacking was enabled for named entities?

> `1-3-de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity` indicates that this goes to the Named Entity annotation a token 1-3

**Comment by seyyaw** [comment]
We have it in the TSV documentation

> Multiple span annotation on a token/sub-token will have a numbered reference enclosed by brackets as [N] where N refers to the nth annotation on this token/sub-token

**Comment by reckart** [comment]
Ok. So if you use the column number instead of the type name (as in my suggestion) and combine it with the way you currently handle stacking, I guess it would look like this:

```
<sentence>-<token>-<columnnumber>-[<in-column-entry>]
```

For example:

``
1-3-5[1]
```

Where `5` is the column which is for named entities. I assume that for every column in the TSV, there can only be a single type, so using the column number instead of the full type name has the same level of information but is much shorter.

**Comment by seyyaw** [comment]
ok
