### ISSUE TITLE
Cannot build the project

### ISSUE THREAD

**Issue by seba174** [webanno/webanno#1819]
**Describe the bug**
Cannot build the project.

**To Reproduce**

- Pull the repository from Github.
- Open project in IntelliJ.
- Try to build the project.

**Expected behavior**
Build should succeed.

**Additional Context**
First error:
```
(...)\webanno\webanno-api\src\test\java\de\tudarmstadt\ukp\clarin\webanno\api\type\CASMetadataTest.java:33:32
java: cannot find symbol
  symbol:   class CASMetadata
  location: class de.tudarmstadt.ukp.clarin.webanno.api.type.CASMetadataTest

```
**Please complete the following information:**
 - Master branch, commit e26d1ac
 - OS: Windows
 - Java version (11 and 15)

**Comment by jcklie** [comment]
Can you run "mvn clean install -DskipTests=true -D "checkstyle.skip=true" in the inception root folder on the command line once and then try again?

**Comment by reckart** [comment]
Try refreshing the Maven project in IntelliJ.

**Comment by seba174** [comment]
> 
> 
> Can you run "mvn clean install -DskipTests=true -D "checkstyle.skip=true" in the inception root folder on the command line once and then try again?

After doing that following error shows up:
`[ERROR] Failed to execute goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute (read-notice) on project webanno: Execution read-notice of goal org.codehaus.gmaven:groovy-maven-plugin:2.1.1:execute failed: Plugin org.codehaus.gmaven:groovy-maven-plugin:2.1.1 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:1.8.0 at specified path C:\Program Files\Java\jre1.8.0_271/../lib/tools.jar -> [Help 1]`

**Comment by jcklie** [comment]
You need java 11 for webanno master.

**Comment by seba174** [comment]
Yeah sorry, issue is resolved after running `mvn clean install -DskipTests=true -D "checkstyle.skip=true"` inside IntelliJ's 'Execute Maven goal' window instead of just command line (so it uses not global Java but this specified in IntelliJ).

Thanks for your quick help!

**Comment by jcklie** [comment]
Thanks! We will update the documentation to include this.
