### ISSUE TITLE
Organizing documents

### ISSUE THREAD

**Issue by floschne** [webanno/webanno#1820]
**Is your feature request related to a problem? Please describe.**
This is a feature request coming from a meeting with researchers from the [CLICCS project.](https://www.uni-hamburg.de/forschung/forschungsprofil/exzellenzcluster/cliccs.html). 
They use WebAnno (with Codebooks) to annotate climate-research-related documents and have a couple of hundred documents in the project.

**Describe the solution you'd like**
- It would be nice if we'd had a feature to organize documents into packages/folders in the Project Settings.
- Compute agreement metrics only on a selected and predefined subset of all documents of a project, i.e., select a package/folder of documents created in the project settings for which the metrics get computed

**Comment by floschne** [comment]
@seyyaw @reckart  you can assign me for this issue

**Comment by reckart** [comment]
Duplicate of https://github.com/webanno/webanno/issues/498
