### ISSUE TITLE
Searching for documents in the Open Document Dialog

### ISSUE THREAD

**Issue by floschne** [webanno/webanno#1821]
**Is your feature request related to a problem? Please describe.**
This is a feature request coming from a meeting with researchers from the [CLICCS project.](https://www.uni-hamburg.de/forschung/forschungsprofil/exzellenzcluster/cliccs.html). 
They use WebAnno (with Codebooks) to annotate climate-research-related documents and have a couple of hundred documents in the project.

**Describe the solution you'd like**
It would be helpful to have an option to search for annotations, words, etc. in the Open Documents Dialog to reduce the list of proposed documents to open.
If Issue #1820 gets implemented, it would also be convenient to show the packages in the list of documents.

**Additional context**
This is related to Issue #1820

**Comment by floschne** [comment]
@seyyaw @reckart you can assign me to this issue

**Comment by reckart** [comment]
There is a functionality for searching for annotations in INCEpTION based on Lucene/MTAS. If you want to add this, I would suggest you consider doing it there. What you are looking for could reasonably easy be implemented on top of it.

**Comment by seyyaw** [comment]
@reckart no this is not searching for annotation. This is functionality to "Filter" documents based on keyword/s in the `open documents` dialog box before selecting one of the documents. This is a requirement from the social science document coding annotation project. And it is needed in WebAnno

**Comment by reckart** [comment]
Well the description said to filter by annotations. If you only care to filter by document name, that is fairly easy to do in WebAnno.

**Comment by reckart** [comment]
Implemented in INCEpTION: https://github.com/inception-project/inception/pull/3289
