### ISSUE TITLE
Annotation disabled for curator

### ISSUE THREAD

**Issue by UWinch** [webanno/webanno#1822]
**Describe the bug**
There are two cases in which the user in the annotator state is not the current user. The annotation should only be disabled in one of them:

- The admin (current user) is viewing another annotator's work -> the annotation should be disabled
- The current user is acting as the curation user -> the annotation should not be disabled

**To Reproduce**
Relevant for https://github.com/inception-project/inception/pull/1872.

**Describe the solution you'd like**
Revert to the previous functionality of  `isUserViewingOthersWork`, move checks for curation to `editable`-methods.

**Comment by reckart** [comment]
The check was before using the user object instead of the user name to check access. This required an additional DB access to fetch the user object which slowed down things. So we should not revert but fix without reintroducing the DB access.
