### ISSUE TITLE
A simple import of already tokenized text to which no further tokenization is applied.  Also, clearer token identification on GUI.

### ISSUE THREAD

**Issue by nlgcat** [webanno/webanno#1828]
**Is your feature request related to a problem? Please describe.**
I a corpus in a tokenized-by-whitespace plain text format.  When I uploaded this to webanno, it at first appeared to work as I expected.  However, webanno further tokenized some of the tokens.  For example [He , 's] became [He , ' , s].  This causes a discrepancy between my input tokens and the output I get from webanno after annotation.

**Describe the solution you'd like**
Having an option to either use the existing process, or instead, split tokens by whitespace and lines by newline would allow for an easy solution for those performing simple annotations and not wanting to get bogged down in some of the more complex input formats which are designed to do more detailed linguistic work than I am here.

**Describe alternatives you've considered**
I looked at some of the other file formats, but some of them look like overkill to convert what I have (an ordered list of sentences, each containing an ordered list of tokens).

**Additional context**
For me, the current implementation went against the principle of least surprise.  When I view the _He 's_ on the interface, it looks like only two tokens, there is no space in between.  I had assumed the text would be split by whitespace on the interface where there is a token boundary.  It is only when I try to highlight a single character, or view the tsv output that I see otherwise.

I might of missed something here, and the functionality may exist, but what I am trying to do is upload as a document, an ordered list of tokens.

Thanks

**Comment by reckart** [comment]
I have opened a PR for the format. Making token boundaries more explicit in the UI would take more work. The rendering code tries to reproduce whitespace true to the original, not true to the tokens. But if you import pre-tokenized text where tokens are space-separated, it will also look ... well ... more tokenized in the UI.

**Comment by nlgcat** [comment]
Appologies for the delayed response.  Just wanted to thank you for the work making this change.  We did not migrate mid-project on our previous work, but doing a new project now and this change is so helpful.  Thanks!

**Comment by reckart** [comment]
@nlgcat Thanks for the feedback :) If you start a new project now, it would also be a good time to look at [INCEpTION](https://inception-project.github.io) as a replacement for WebAnno.
