### ISSUE TITLE
[Questions] Adding suggestions to annotation project

### ISSUE THREAD

**Issue by saboof** [webanno/webanno#1829]
Hi, 

I looked for the right place to post questions, found the google group but I can't publish questions there at the moment.

Regarding the question: 
we have a kind of SRL annotation project, we want to help users find possible predicate in the text fast. 
So we want to add suggestions for such possible predicates (only for the predicates and not for the additional arguments), my question is how can we add these suggestions in an annotation project? 

The suggestions which are span in the documents come from a different heuristic model. This model is saved on different sever, potentially we could upload it to the same server where the WebAnno is installed.  
we want to pre-process the text so we would add these suggestions as part of the documents in the project.

**Comment by jcklie** [comment]
We recommend you to use [INCEpTION](https://github.com/inception-project/inception) which is a extension of Webanno. There you can define external recommender that give you suggestions using your own model. 

You can refer to our [video about external videos](https://www.youtube.com/watch?v=Xz3Hs8Lyoeg&list=PL5Hz5pttaj96SlXHGRZf8KzlYvpVHIoL-&index=3), the [documentation about external recommender](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/INCEpTION%20(GitHub)%20(master)/de.tudarmstadt.ukp.inception.app$inception-app-webapp/doclinks/3/#_external_recommender) and [the Python framework](https://github.com/inception-project/inception-external-recommender) I built to easily add recommender to INCEpTION .

If you want to stay with Webanno and just preprocess, then I recommend you to generate documents using XMI and [DKPro cassis](https://github.com/dkpro/dkpro-cassis) or [UIMAj and Java](https://uima.apache.org/d/uimaj-current/). You would annotate a document a bit, then export it to see the structure that Webanno uses for SRL and then use XMI to generate your own.

**Comment by seyyaw** [comment]
@saboof and if the suggestion comes as a form of pre-annotation, the `correction` component of WebAnno might be an option. The suggestion will be displayed at the bottom and the users will have an option wither to accept the suggestion or modify/newly annotate in the `annotation` pabel.

**Comment by ofersabo** [comment]
@jcklie Thanks for your feedback I moved to use INCEpTION. 
But I'm still in the process of considering both as I suspect that some things are not as stable in INCEpTION as they at in WebAnno. 
Anyway, I wanted to know if I could export INCEpTION projects into WebAnno? obviously keeping only features that the two programs have, i.e. WebAnno won't have the Knowledge-base feature. I tried that a few times and couldn't manage to do so. The other way around, from WebAnno to INCEpTION does work.

**Comment by reckart** [comment]
WebAnno 3.6.x is pretty stable (because it isn't really changed much anymore). However, it also doesn't include many optimizations and some fixes that are part of the WebAnno 4 beta series which is developed as part of INCEpTION.

INCEpTION essentially uses the WebAnno import/export API. This API was modularized in order to support INCEpTION being able to build on it. In principle, the import/export mechanism "should" be able to skip over data in an exported project that it does not understand - therefore, it should in theory be possible for WebAnno to import an INCEpTION project albeit losing all INCEpTION-specific features in the process. However, I believe that nobody has ever really tested it.

**Comment by reckart** [comment]
Actually, the modularization of the import/export in WebAnno has already been mainly done prior to INCEpTION for [WebAnno 3.5.0](https://github.com/webanno/webanno/pull/938) - so one more reason why even importing an INCEpTION project into WebAnno 3.6.x should theoretically be possible.

**Comment by ofersabo** [comment]
Hi, 

So according to my testing, it does work, I was able to create projects in one and move them to the other and vice versa. 
However, it seems that once a project has more than dozens of documents, WebAnno can't import it.
I'm going to look if this is a known issue.

**Comment by reckart** [comment]
Assuming this topic has resolved itself.
