### ISSUE TITLE
Many images fail to load in user-guide

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#183]
After clicking on help link available in webanno, a popup open up with user-guide. Upon inspecting, you can see that many images/resources fail to load.

![helperrors](https://cloud.githubusercontent.com/assets/1897100/13724695/ee365ca8-e88d-11e5-91eb-9e58bb53f423.png)

**Comment by reckart** [comment]
Can you please check if the images also fail to load in the 3.0.0-SNAPSHOT documentation linked here:

https://webanno.github.io/webanno/documentation/

**Comment by aakashysharma** [comment]
@reckart There it works. I'm curious why most of them are related to version 3. 

Also, earlier images were .jpg, now all those which failed are PNG. 

I'm not sure what could be the problem here.

**Comment by reckart** [comment]
Which files are included in the online docs is controlled at the following location:

https://github.com/webanno/webanno/blob/master/webanno-doc/pom.xml#L132

Presently, this is configured for ".jpg", ".png" and ".html" (all lowercase). If you fix the capitalization of the image file names, it should work.

@sholschneider When you include new images, please use lower-case file extensions.
