### ISSUE TITLE
[Question] exporting all documents

### ISSUE THREAD

**Issue by ofersabo** [webanno/webanno#1830]
Hi,

Let's say we've 1000 documents in a project and only a single annotator. 
Since there is only a single annotator there is no need for a curation process, or at least we decide that there is no need for that.
So by the time that the annotator is done with the documents we as project managers would want to export all the documents. 
Is there a way to export all documents after the annotator is done? e.g. without the curation user goes over all the documents and marks each of them separately as finished.   

This question could also be extended to the case where we have multiple users.
Assuming multiple annotators for a project with 1000 documents. Is there a way to export all documents annotated by a particular user?

**Comment by reckart** [comment]
You just export the whole project from the "export" pane in the project settings - it contains everything including the annotations made by the one user.
