### ISSUE TITLE
Annotation page doesn't clear up if you open a faulty document after opening up a normal document

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#184]
Steps to reproduce
1. From home page of webanno, launch Annotation and open a normal document.
2. While document is opened, click on "Open" icon from top and open a "faulty" document (sentences01 (1).tsv here). Faulty here means a document which doesn't load due to IO or some other error.
3. The "faulty" document  won't load and you'll get an error message in bottom feedback panel.
   ![f1](https://cloud.githubusercontent.com/assets/1897100/13725496/baa8f1a0-e8a3-11e5-8ed6-ec5fac87720a.png)
4. Any further action on opened document (which is actually not) would result in Unexpected error: null.
   ![f2](https://cloud.githubusercontent.com/assets/1897100/13725502/dfa9fb20-e8a3-11e5-8b54-a1ffd3b864d5.png)
5. The issue can be resolved by resizing the window which forces webanno to redraw and that clear up.
   ![f3](https://cloud.githubusercontent.com/assets/1897100/13725510/fccc09aa-e8a3-11e5-9e24-b8bdd10e0d13.png)

**Comment by reckart** [comment]
The question is, what should happen when a faulty document is opened. I guess probably in addition to showing the error message WebAnno should open the "Open Document" dialog again.

**Comment by aakashysharma** [comment]
Wouldn't error message appear in background and ignored by user?

**Comment by reckart** [comment]
Probably yes. But if only the annotation area is cleared, I fear that pressing other buttons in the toolbar or in the annotation detail panel may trigger further errors.

**Comment by aakashysharma** [comment]
Yes, but blank page with some error messages would convince user to understand that it failed and would try to open a document first. Even if there are subsequent actions, they would probably resulted in caught exceptions.

We can get feedback on this from actual users by asking them what happens if they open a document in Annotation and the document is blank. I still think, they would try to open another document.

**Comment by reckart** [comment]
If the code is changed to blank out the annotation area, maybe it can be done in such a way that some "broken document" notice is shown not only on the bottom of the screen but actually directly within the area that would usually be occupied by the text+annotations.
