### ISSUE TITLE
Exported typesystem from layer settings has duplicate type definitions

### ISSUE THREAD

**Issue by jcklie** [webanno/webanno#1849]
**Describe the bug**

Exported typesystem from layer settings has duplicate type definitions

**To Reproduce**
1. Go to Layer Settings
2. Click on "Export UIMA all"
3. See duplicates in the "typesystem.xml"

Duplicate are e.g.

```
de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.morph.MorphologicalFeatures
de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink
de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS
de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Token
```

**Expected behavior**
No duplicates

**Comment by reckart** [comment]
Interesting. I can reproduce it on INCEpTION 0.17.3 on a fresh project. Cannot imagine though how this would be a bug on our side. I'm pretty sure this happens somewhere in the upstream UIMA framework code...

**Comment by jcklie** [comment]
It would be also nice if token and sentence type were in this typesystem.
