### ISSUE TITLE
Improve ordering in auto-complete string feature editor

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#1855]
**Is your feature request related to a problem? Please describe.**
The auto-complete string feature editor matches using "tag contains case insensitive" and then displays all matches in alphabetical order. That means e.g. when entering "line", there can be a lot of hits which contain "line" somewhere in the tag before we actually arrive at tags starting with "line" or even at an exact match.

**Describe the solution you'd like**
Introduce a better ranking with sorts approximately as follows:
- reordered (by constraints) frist
- exact match
- starting with
- containing

**Comment by skatje-myers** [comment]
This issue re-surfaces once the '.' character is added to the string being typed in. In the attached example, "sit.01" and such should appear first, not babysit.01

![image](https://user-images.githubusercontent.com/5782965/107840746-a3fe8d80-6d72-11eb-9fb0-916509e86a49.png)

**Comment by reckart** [comment]
@skatje-myers since you are using INCEpTION - which version of INCEpTION are you using?

**Comment by skatje-myers** [comment]
0.17.4.

**Comment by reckart** [comment]
It is only in 0.18.0 and higher. Please go directly to 0.18.1 because there is a memory leak in 0.18.0.
