### ISSUE TITLE
After filling a slot, the annotation detail panel is not updated

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#186]
To reproduce:

* create an annotation that can act as a slot filler
* create an annotation with a slot feature
* add a slot
* double click on the slot filler annotation

Expected
* arc is drawn in the annotation area: OK
* annotation detail area is updated and the target span text appears in the slot: **not ok**

What happens
* the slot continues to display `"<select to fill>"`

WebAnno -- 3.0.0-beta-1 (2016-03-12 18:10:26, build 17c92399feb85cf0bb41ea82af74d99469b22186)

**Comment by mmeva** [comment]
The problem is still there (including the issue #209) 
[3.0.0-SNAPSHOT (2016-03-28)]

**Comment by reckart** [comment]
Yes I know - we are working on it.

**Comment by reckart** [comment]
Unfixed by https://github.com/webanno/webanno/commit/47b3242ae2711f0feb23e50fbbf40113fc6872f0
