### ISSUE TITLE
Cannot view annotation details on closed document

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#188]
If a document is closed, it is no longer possible to double-click on an annotation to inspect it. Even for closed documents, it should still be possible to load the details of annotations in the annotation detail editor panel - it should only no longer be possible to make any changes!

3.0.0-beta-1 (2016-03-12 18:03:28, build f3410cc6aa5c0a09df68a5b77cf560d06c50ac42)

**Comment by reckart** [comment]
@seyyaw I believe you worked last on issue related to preventing changes to closed documents, right?

**Comment by seyyaw** [comment]
I think so,it was possible to edit closed documents. I will investigate.
