### ISSUE TITLE
Ugly empty space

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#190]
We have some ugly empty space in the annotation detail editor panel below the selected text. The element ID hints that this is somehow part of the auto-forwarding code ( @seyyaw, @ChrisBieTUDA ). This space should be removed.

![2016-03-13_20-09-57](https://cloud.githubusercontent.com/assets/1410238/13730733/c8e674ae-e957-11e5-8105-ef3cbe561131.png)

WebAnno -- 3.0.0-beta-1 (2016-03-12 18:03:28, build f3410cc6aa5c0a09df68a5b77cf560d06c50ac42)

**Comment by seyyaw** [comment]
Until we have a better approach, we keep on using the hidden input text for auto-forward annotation.

**Comment by reckart** [comment]
Ok - just make it not use vertical space - or at max 1 px.

**Comment by reckart** [comment]
@seyyaw any reason for using ".1em" (which is a relative size depending on the screen resolution) vs "1px" (which is always 1px)?
