### ISSUE TITLE
java developer

### ISSUE THREAD

**Issue by zionraync** [webanno/webanno#1908]
**Describe the bug**

While building the current version of WebAnno as a project with IntelliJ Idea 2021 Community Edition, compile errors appeared. I used JDK 11. Lack of classes, such as ASTPath, SimpleNode, ConstrainsParser, etc.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Version and build ID: [see bottom of the browser screen]
 - OS: [e.g. Windows, Linux, OS X] Windows 10
 - Browser: [e.g. chrome, safari] chrome 

**Additional context**

**Comment by reckart** [comment]
IntelliJ may not properly execute the Maven plugins that are part of the build and which generate the respective classes. Try building on the command line and see if IntelliJ finds the classes then.

**Comment by zionraync** [comment]
Couldn't build the project from the source code.

**Comment by zionraync** [comment]
@reckart thanks. I will try and keep you posted.

**Comment by jcklie** [comment]
We have a guide about [Intellij and INCEpTION](https://inception-project.github.io/releases/0.19.6/docs/developer-guide.html#_setting_up_for_the_development_in_intellij_idea), which is similar to webanno. I would guess that you would need one run of `mvn clean install -DskipTests=true -D checkstyle.skip=true` (which is not in the guide yet, but added in the next INCEpTION release).

**Comment by zionraync** [comment]
@reckart It was built successfully in another pc with windows os. Thanks a lot!

@jcklie Thanks for your info. I will try it soon.

**Comment by reckart** [comment]
No further feedback. Assuming issue was resolved.
