### ISSUE TITLE
Button line wraps despite ample space

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#191]
Despite ample space in the annotation detail editor panel, the "clear" button wraps into the next line.

![2016-03-13_20-13-46](https://cloud.githubusercontent.com/assets/1410238/13730741/40226078-e958-11e5-9846-2cc068b90cb3.png)

WebAnno -- 3.0.0-beta-1 (2016-03-12 18:03:28, build f3410cc6aa5c0a09df68a5b77cf560d06c50ac42)

**Comment by reckart** [comment]
This seems to be related to an element that is hidden using a CSS style:

```
<td>
  <button type="button" name="delete" id="deletebc7">Delete</button>
  <button id="reversebb5" style="display:none"></button>
  <button class="buttons" name="clear" id="clearbc8">Clear</button>
</td>
```

If I remember right, an element that is set to be invisible in Wicket should not appear at all in the DOM - so I guess this used of the CSS style attribute is some kind of hack here.

**Comment by reckart** [comment]
@seyyaw do you have any insight on this?

**Comment by seyyaw** [comment]
Looks like the problem is due to the table's td property. If I replace the table with div and span, we don't have the problem but not sure the look and feel is better. see how it looks like with div/span
![image](https://cloud.githubusercontent.com/assets/1056051/13730906/29ce304a-e95d-11e5-9e47-14653a58cdb4.png)

**Comment by reckart** [comment]
Ah. Well, the buttons should either not be in the table or the cell should have a colspan. 
I think we should keep the "Layer" label in front of the dropdown.
However, for the "Forward annotation", I think also a colspan should be used or the line should be out of the table. The label is very long and wraps too early.

**Comment by seyyaw** [comment]
use colspan of 3 for the buttons and 2 for the forward annotation rows
