### ISSUE TITLE
Information about tokenizer used during import plaintext (one sentence per-line)

### ISSUE THREAD

**Issue by MaviccPRP** [webanno/webanno#1912]
**Is your feature request related to a problem? Please describe.**

I am using WebAnno with a great pleasure but have troubles checking the tokenization method of WebAnno,
If I choose import plain text files into a project and choose 'one sentence per-line' format.
The text will be tokenized, but I do not see which algorithm is tokenizing the text.

**Describe the solution you'd like**

It would be very helpful, if WebAnno shows tokenizer information directly in the GUI during import or as meta data in exported tsv files.

**Describe alternatives you've considered**

I currently do not have alternatives.

**Additional context**

My current use case is:
1. Import plain text files into WebAnno *3.6.7 (2021-02-27 22:35:18, build _afd15dd9ef6da4b4e37713caf06ebd2699cad2ef)* into a token annotation project (e.g. NER)
2. Export the annotated data using tsv3 format
3. Train a machine learning model on the annotations
4. Use the model to automatically annotate unseen text data

In the last step, I do not know how to check, which algorithm to use to tokenize the data.

Thank you for your work on this great tool!

**Comment by seyyaw** [comment]
Hi @MaviccPRP 
The default tokenizer in WebAnno is the Java [BreakIterator](https://docs.oracle.com/javase/tutorial/i18n/text/about.html) which is based on some punctuations.

**Comment by reckart** [comment]
For best effect, pre-tokenizer your text using a tokenizer you know, then import the pre-tokenized text, then annotate.

You might want to consider looking at the [INCEpTION](https://inception-project.github.io/) annotation tool which takes WebAnno technology to the next level. It also includes a ["Text (pretokenized)"](https://inception-project.github.io/releases/20.3/docs/user-guide.html#sect_formats_text_pretokenized) import mode.

**Comment by MaviccPRP** [comment]
Great, thanks for the Info. Helped alot.
