### ISSUE TITLE
Documentation of the "WebAnno TSV 3" format

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#193]
Documentation of the "WebAnno TSV 3" format.
- [x] add to the list of supported formats in the documentation
- [x] describe the file format itself

---
- [x] header structure
- [x] text - how raw text is encoded in the file
- [x] sentences and tokens - how sentence boundaries and tokens are encoded
- [x] special characters and escaping - what special characters exist and how they are escaped
- [x] features
- [x] -- single features - _how is a single feature represented if it has a value/does not have a value_
- [x] -- multiple features
- [x] -- no features at all
- [x] -- slot features
- [x] span layers
- [x] -- single-token span annotations
- [x] -- sub-token span annotations - within a single token / across token/sentence boundaries
- [x] relation layers
- [x] chain layers
- [x] stacked annotations

**Comment by seyyaw** [comment]
@sholschneider How far are you in the TSV file format documentation. I can take a final look into it if you are done with the basic documentations

**Comment by reckart** [comment]
@seyyaw Having worked myself on the unit tests for TSV, I am not sure if a person not familiar with the TSV implementation is very able to write such a documentation. Even coming up with the unit test cases, I had to be quite creative and there were quite a few subsequent discussions. Also, I think there is at least one more issue open which may entail changes to TSV, e.g. #313.

I think the TSV documentation should contain headings such as these

* header structure
* text - how raw text is encoded in the file
* sentences and tokens - how sentence boundaries and tokens are encoded
* special characters and escaping - what special characters exist and how they are escaped
* features - encoding of annotations with one features, multiple features, no features at all
  * slot features - encoding of slot features
* span layers
  * zero-length span annotations
  * multi-token span annotations
* relation annotations
  * cross-sentence relation annotations
* chain annotations
* stacked span/relation annotations

**Comment by seyyaw** [comment]
OK,
Probably I takeover the documentation once I clean remaining issues. By the way, #313 should be closed
