### ISSUE TITLE
Improve documentation of constraints

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#194]
- [x] the documentation of constraints should use asciidoc _source blocks_ `----`, not _example blocks_ `====`
- [ ] example constraint rule on a normal string feature + explanation 
- [ ] example constraint rule on a (dependency) relation + explanation

**Comment by reckart** [comment]
@aakashysharma Can you provide the examples?

**Comment by aakashysharma** [comment]
@reckart Yes. I'll.

**Comment by reckart** [comment]
For dependency should be something along the lines of

```
Dependency {
Governor.@POS.posValue = "XX" & Dependent.@POS.posValue = "XX" -> dependencyType = "XX"
}
```

... but I didn't test it.

**Comment by reckart** [comment]
-> https://github.com/inception-project/inception/pull/4721
