### ISSUE TITLE
Annotation of whitespace

### ISSUE THREAD

**Issue by rbawden** [webanno/webanno#1943]
**Describe the bug**
I would like to do text normalisation by annotating spans of text with the normalised version and a label/comment. I would like to be able to annotate whitespace too, either as part of a span or by itself, but webanno does not currently allow me to do this, even though I have selected the annotation layer to apply to characters rather than tokens (I have checked and I can annotate parts of words and parts of several words in a single span).

**Expected behavior**
I would like to be able to select whitespace for annotation or select a span of text containing whitespace at the beginning of the end: e.g. in `Gonna take awhile , `, I would like to be able to select the space after 'awhile' as well as be able to select the space and the following comma.

**Screenshots**
When I try to select the comma and the preceding whitespace, only the comma is selected:
<img width="174" alt="image" src="https://user-images.githubusercontent.com/6254922/146412199-ca132c43-73cc-4017-8a84-ed528bd85c2f.png">

**Please complete the following information:**
 - Version and build ID: 3.6.7, afd15dd9ef6da4b4e37713caf06ebd2699cad2ef
 - OS: OS X
 - Browser: Safari

Thank you in advance for your help!

**Comment by reckart** [comment]
The annotation of whitespace is not supported in WebAnno. The brat-based visualization would have problems with that.

The new tool [INCEpTION](https://inception-project.github.io) supports alternative editors, but there also the annotation of whitespace is not (yet) tested. Feel free to copy your feature request there - WebAnno won't get features anymore.

**Comment by rbawden** [comment]
Thank you - I'll check it out!
