### ISSUE TITLE
Cannot curate sentence starting with double hyphen

### ISSUE THREAD

**Issue by YoannDupont** [webanno/webanno#1956]
# bug description
Sentences starting with double hyphen do not show up in the curation UI.

# To Reproduce
Create a corpus with a sentence starting with a double hyphen and annotate, then try to curate.

# Expected behavior
Sentence should show up in curation

# Additional information
 - Version and build ID: 3.6.1
 - OS: Linux
 - Browser: Vivaldi

**Comment by reckart** [comment]
I have tried reproducing this with INCEpTION 22.2 but I had no problems there with sentences starting with a double-hyphen. If you can reproduce the issue with [INCEpTION](https://inception-project.github.io), please open an issue in its [issue tracker](https://github.com/inception-project/inception/issues/new/choose).
