### ISSUE TITLE
"typeUiName" in tagset JSON export unnecessary (?)

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#196]
I believe the "typeUiName" in the JSON export of tagsets is no longer relevant. I believe this comes from _very_ old versions of WebAnno where a tagset could only be assigned to a single feature. Since then tagsets and features have been decoupled. A tagset can be referenced by multiple features. So I believe "typeUiName" should be removed. Probably the same for
- "type"
- "type_name"
- "type_description"

**Comment by seyyaw** [comment]
I think we have it for back compatibility

> // back compatibility
>  @JsonProperty("typeUiName")
>  String typeUiName;

**Comment by reckart** [comment]
But if it is not used anymore, then we can remove it, no? I would assume that any key/values that are present in the JSON but not mapped into Java are simply ignored on import.
