### ISSUE TITLE
'Project Export failed' happened when the relation between character level 'Named Entities' is annotated.

### ISSUE THREAD

**Issue by HoJang** [webanno/webanno#1966]
First of all, thank you for sharing the great annotation tool!
I think it's a minor but important bug that has to be reported.

**Describe the bug**

'Project Export failed' happened when the relation between character level 'Named Entities' is annotated.

![2022-08-16 17 14 13](https://user-images.githubusercontent.com/4926612/184831476-41f000b3-2c50-4343-86c5-6c3b2116ef05.png)

**To Reproduce**
1. Set the Granularity of Named entity layer to 'Character-level'

![2022-08-16 17 13 44](https://user-images.githubusercontent.com/4926612/184831975-85efd795-792f-4c11-9265-e8711228a2cd.png)

2. Add 'Relation' layer to annotate relation between two Named entities.

![2022-08-16 17 18 56](https://user-images.githubusercontent.com/4926612/184832397-4d1d06ad-ea8f-41a2-ac26-28681b75b83d.png)

3. 'Project Export failed' happened If the relation is as follows. (kidney -> treating)

![2022-08-16 17 24 34](https://user-images.githubusercontent.com/4926612/184833685-b4f94ff5-1e4c-4d34-a987-0d720b55a8e8.png)

4. Project Export succeed If the relation is as follows. (treating -> kidney)

![image](https://user-images.githubusercontent.com/4926612/184833985-f2b4aa96-0e95-4340-8bd9-3f61f79352bd.png)

**Please complete the following information:**
 - Version and build ID:  WebAnno -- 3.6.11 (2021-12-23 15:23:37, build 1a06196f017e26545447da984d66e63a5d67a2d0)
 - OS: Centos 7.8
 - Browser: chrome, edge

**Additional context**

I assume the export error happened when the relation annotation started to prefix of a token such as 'kidney' in 'kidney-deficiency'

I attached the project export file. The error can be reproduced when you set the relation from kidney to treating.

[test_project_2022-08-16_1738.zip](https://github.com/webanno/webanno/files/9349138/test_project_2022-08-16_1738.zip)

Best regards,

Jang

**Comment by reckart** [comment]
Thank you for the report. There will not be any fix in WebAnno anymore. The successor to WebAnno is [INCEpTION](https://inception-project.github.io). You can export your annotation projects from WebAnno and import them into INCEpTION. It would be great if you could try that and see if the issue can be reproduced in the latest INCEpTION version - and if so open an issue in the INCEpTION repository.

**Comment by HoJang** [comment]
> Thank you for the report. There will not be any fix in WebAnno anymore. The successor to WebAnno is [INCEpTION](https://inception-project.github.io). You can export your annotation projects from WebAnno and import them into INCEpTION. It would be great if you could try that and see if the issue can be reproduced in the latest INCEpTION version - and if so open an issue in the INCEpTION repository.

Thank you for your prompt reply. 
I'm sorry there is no later version of WebAnno, but I'm greatful that there is a better service.

Many thanks,
Jang

**Comment by reckart** [comment]
Your problem might be related to these issues which have been fixed in INCEpTION:

* https://github.com/inception-project/inception/issues/3066
* https://github.com/inception-project/inception/issues/3092

**Comment by HoJang** [comment]
> Your problem might be related to these issues which have been fixed in INCEpTION:
> 
> * [WebAnno TSV 3 export fails with certain subtoken annotations inception-project/inception#3066](https://github.com/inception-project/inception/issues/3066)
> * [Export doesn't work inception-project/inception#3092](https://github.com/inception-project/inception/issues/3092)

Thank you for letting me know that the bug has been fixed in INCEpTION
Although our annotation task is underway now, I will seriously consider the change of the annotation tool.
I appreciate your help again.

Sincerely,
Jang
