### ISSUE TITLE
Line spaces while importing a document in plain text

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#197]
I imported eclipse.ini file into webanno using Import option under documents tab in project settings. While importing I chose format "plain text".

In Annotation, I don't see any line breaks. 
![importedeclipse](https://cloud.githubusercontent.com/assets/1897100/13755511/e3bd8d52-ea1b-11e5-818a-29444db3d4f4.png)

I am not sure if this is an issue. Should I've done something else to get those line breaks?

**Comment by reckart** [comment]
WebAnno does not have a concept of line breaks - quite as much as HTML doesn't have it. It has a concept of sentences and tokens. One "line" in  WebAnno corresponds to one sentences. This "line" is then wrapped according to the available space on screen.
