### ISSUE TITLE
Named Entities layer lock to token offsets behaviour not saved

### ISSUE THREAD

**Issue by chozelinek** [webanno/webanno#198]
I am using WebAnno standalone 2.3.0. in a Mac OS X El Capitan and I am using Chrome.

I try to add mark the behaviour "Lock to token offsets" for the already existing Named Entity layer.

Then I click on Save layer button, and the box is unchecked. If I try to annotate a file, the annotation is not locked to token offsets.

I've also tried to create a custom layer but it happens the same.

**Comment by reckart** [comment]
Problem exists also in WebAnno -- 3.0.0-beta-1 (2016-03-12 18:10:26, build 17c92399feb85cf0bb41ea82af74d99469b22186)

**Comment by reckart** [comment]
If **lock to multiple tokens** is enabled, then **lock to token** as no effect and cannot be enabled. The two are mutually exclusive. To enable **lock to token**, first disable **lock to multiple tokens**. Btw. if you disable both options, then you can do sub-token annotations (effectively *lock to character*).

I am still leaving this issue open for the moment as we should have a more intuitive solution for setting the lock mode.

**Comment by chozelinek** [comment]
I've tried **lock to token offset** enabled and **lock to multiple tokens** disabled and viceversa. And I have always sub-token annotation. Also disabling both behaviours.

By the way, **allow multiple tokens** just means that my annotation span can be more than one token long, doesn't it?

Anyway, I think both options shouldn't be exclusive. But maybe you have scenarios where it has to be in this way.

**Comment by reckart** [comment]
There are basically three modes that WebAnno supports

| Mode | Lock to token | Allow multiple tokens |
| --- | --- | --- |
| character-based annotation | off  | off  |
| token-based annotation | on  | off  |
| multi-token annotation | off  | on  |

Maybe we can replace the two confusing checkboxes with a drop-down menu.

**Comment by chozelinek** [comment]
Thanks for the pointer. I agree that a drop-down menu or radio button allowing only one choice would be better, if behaviours had to be exclusive. Still, I remember that in previous versions one could have token-based annotation and simultaneously multi-token annotation.

In my case, no matter which combination of behaviours I switch on or off (from the three you have just illustrated), I always have character-based annotation.

**Comment by reckart** [comment]
Ok, that's definitely a bug then - we'll look into it!

**Comment by seyyaw** [comment]
I tried in WebAnno 3 and I cannot observe this problem. 
Do you have this problem still?

**Comment by reckart** [comment]
Assuming this has been fixed since there was no further feedback and nobody could observe this anymore.
