### ISSUE TITLE
Empty lines in text cause sentence numbering to be off

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#20]
If we have empty lines in the document text, it can cause the sentence numbering to be off.

![2015-06-13_16-38-55](https://cloud.githubusercontent.com/assets/1410238/8144699/b5f87fda-11ea-11e5-8913-7cd7982a1e86.png)

This is a general problem with the brat visualization, not only a problem in curation. However, in curation is becomes most obvious as the numbers of the sentences in the overview no longer match with the numbers in the annotation view. In annotation/correction/etc, we only notice the empty lines and the numbers incrementing by more than one.

3.0.0-SNAPSHOT (2015-06-11 21:04:37, build 8423c03d340eb33a8d60953b14925e10869097ac)

**Comment by seyyaw** [comment]
This mainly happens when we have empty lines while importing plain text files. We can make the reader to trim empty lines, but the original file will be changed. what is recommended here?

**Comment by reckart** [comment]
It is recommended:
* to check if this issue has already been reported to the brat people
* whether they have been working on it already
* if not, we should try to fix it in the brat Javascript code

Please do not modify the output of the readers and please do not change any reader to remove empty lines.

**Comment by reckart** [comment]
Reported issue upstream: https://github.com/nlplab/brat/issues/1148

However, I'm not clear yet on what the numbering actually means: should it be **line numbers** or **sentence numbers**?

**Comment by reckart** [comment]
Replacing `\n` and `\r` with a simple space during the brat rendering process. This avoids having do modify the readers/original files.
