### ISSUE TITLE
Type of coreference features set wrong

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#200]
The "type" of the features "referenceType" and "referenceRelation" is wrongly set to "de.tudarmstadt.ukp.dkpro.core.api.coref.type.Coreference" - it should be "uima.cas.String".
This means that all current WebAnno databases have a wrong setting here!

* [X]  migration step that kicks in on start to fix the features.
* [X] fix on layer creation also.
* [x] layer types should also be fixed on project import - otherwise fixing them would require a server restart.

Previous commits may reference issue 1325 (chili).

**Comment by aakashysharma** [comment]
@reckart In webanno 3 and later, is there any feature whose type will be
`de.tudarmstadt.ukp.dkpro.core.api.coref.type.Coreference ` ?

**Comment by reckart** [comment]
That is theoretically possible, yes, but highly unlikely for the two features COREFERENCE_RELATION_FEATURE, COREFERENCE_TYPE_FEATURE (these are constant names - see below).

See: https://github.com/webanno/webanno/blob/master/webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/migration/FixCoreferenceFeatures.java

**Comment by reckart** [comment]
During import, it may also be possible to apply the additional check for the layer type that had to be commented out in the FixCoreferenceFeatures class (again see source code).

**Comment by aakashysharma** [comment]
@reckart Do you have a project archive to test fix? I tried some old projects but in those it's set to uima.cas.String. 

Please send over email.

**Comment by aakashysharma** [comment]
@reckart Also, coming back to earlier comment, in Webanno 3 when creating a new feature for custom layer, I don't see an option to create a feature of type ` de.tudarmstadt.ukp.dkpro.core.api.coref.type.Coreference `

So, should I remove any additional checks other than the type of feature?

**Comment by reckart** [comment]
I have sent you an export of a minimal WebAnno 2.3.0 project with a custom chain layer.

For completeness, here an except from the JSON file in that export that illustrates the problem:

```
    {
      "name": "webanno.custom.MyChains",
      "features": [
        {
          "name": "referenceRelation",
          "uiName": "Reference Relation",
          "type": "webanno.custom.MyChains",
          "enabled": true,
          "visible": true,
          "remember": false,
          "description": null,
          "tag_set": null,
          "project_name": "BrokenChains"
        },
        {
          "name": "referenceType",
          "uiName": "Reference Type",
          "type": "webanno.custom.MyChains",
          "enabled": true,
          "visible": true,
          "remember": false,
          "description": null,
          "tag_set": null,
          "project_name": "BrokenChains"
        }
      ],
      "uiName": "MyChains",
      "type": "chain",
      "description": null,
      "enabled": true,
      "built_in": false,
      "attach_type": null,
      "attach_feature": null,
      "lock_to_token_offset": true,
      "allow_stacking": false,
      "cross_sentence": false,
      "multiple_tokens": false,
      "project_name": "BrokenChains",
      "linked_list_behavior": false
    },
```

**Comment by reckart** [comment]
> @reckart Also, coming back to earlier comment, in Webanno 3 when creating a new feature for custom layer, I don't see an option to create a feature of type `de.tudarmstadt.ukp.dkpro.core.api.coref.type.Coreference`

> So, should I remove any additional checks other than the type of feature?

Does the example above and the project I sent you answer that question? People may have created broken custom chain layers in older versions of WebAnno.

**Comment by aakashysharma** [comment]
Should the fix only address if feature name is referenceType and referenceRelation?

**Comment by reckart** [comment]
@aakashysharma optimally the fix should trigger if the feature names are that *plus* if the layer type is a chain layer. In the DB migration code, I had to comment out the check for the layer type due to technical reasons. On import, that should not be a problem though.

**Comment by aakashysharma** [comment]
So, in this case **type** of those features will change to `uima.cas.String` ?

**Comment by reckart** [comment]
Yes, these features are actually the labels of the chain element span and of the arc pointing to the next element in the chain. These are string labels.

**Comment by reckart** [comment]
@aakashysharma Please use constant names, not literal strings. See class WebAnnoConst.
