### ISSUE TITLE
"Features" frame should be hidden if no annotation is selected

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#203]
"Features" frame should be hidden if no annotation is selected (in brush mode) or if no annotation is selected or ghosted (in select-then-save mode).

![2016-03-15_14-36-54](https://cloud.githubusercontent.com/assets/1410238/13779472/697105f6-eabb-11e5-8ffe-5e98417f0a2c.png)

WebAnno -- 3.0.0-SNAPSHOT (2016-03-15 14:25:51, build 7abca6b01f995d76d0a602870447c7f7b11bc2e0)

**Comment by aakashysharma** [comment]
Should I slight yellow background color to the warning text?

![screenshot at 2016-04-19 15 24 54](https://cloud.githubusercontent.com/assets/1897100/14640686/fdf2413e-0642-11e6-9e68-56d72a44ff7e.png)

**Comment by reckart** [comment]
No. Coloring (in particular area coloring) should be used sparsely. I like it in the present way.
