### ISSUE TITLE
Problem with null in tagset

### ISSUE THREAD

**Issue by TomazErjavec** [webanno/webanno#207]
We have the situation where we have a fixed list of tags for a multi-feature layer, yet these tags can often be empty (in feature2, feature3). 
When importing TSV this causes no problem, but it is impossible to annotate only the first feature yet leave the rest empty, as WA complains:
[null] is not in the tag list. Please choose form (sic!) the existing tags
I tried adding "[null]" and "null" to the set of tags, but this isn't the "null" WA wants. I also cannot give it a tag with no name (WA won't let me), nor can I import the JSON tagset definition with null as the name of the tag (internal error).
Is there any way to allow for a null tag in a tagset?

**Comment by reckart** [comment]
Questions should best go to the users mailing list: https://webanno.github.io/webanno/mailinglists/

Hm. What you describe sounds almost as if a feature that has a tagset cannot have an empty value.

WebAnno should not make a difference between an empty feature value and an actual `null` feature value (`null` is not the string `[null]` but actually a null value).

@aakashysharma can you reproduce this? 

If a feature value is "null", then I think the tagset check should simply be skipped. We normally do *not* support mandatory features atm (features that *must* have a value).

**Comment by reckart** [comment]
@TomazErjavec can you post the webanno version string from the bottom of the screen please?

**Comment by aakashysharma** [comment]
@reckart In current build, I can add and use a tag named `null`

**Comment by aakashysharma** [comment]
@TomazErjavec Could you type `null` in the dropdown which you get in Annotation and press "Enter" to save it? It'll save it even if the tag `null` is not defined in the tagset.

@reckart correct me if I'm wrong.

**Comment by reckart** [comment]
Sure, the problem is not if the tag is called "null".

The problem as I understand it is occurring under the following conditions:

* there is a layer in the project that has two features, each of which is bound to a tagset
* the tagset does not allow adding tags (closed tagset)
* a document is imported into that document in TSV format with an annotation where both of the features are unset

**Comment by TomazErjavec** [comment]
- sorry I formulated it as a question, it's really a bug report
- version is 2.3.1-SNAPSHOT (2015-11-10 11:53:22), build 897ff54f514aabd7d8aae8615b0f1f0866a8efc5)
- yes, the problem isn't a tag "null" but that, (under the conditions that @reckart notes), the moment you want to enter or change Tag1, you are forced to insert some tag in Tag2, Tag3, even if you don't want to (which we typically don't, as we use the other tags only in cases where a non-standard word is normalised into several words, and we want to assign a tag to each of them).

**Comment by reckart** [comment]
Not performing check whether tag is in tagset if user didn't enter a value.

**Comment by sholschneider** [comment]
The problem still ocurrs a few times during the day when trying to switch layers.

**Comment by reckart** [comment]
@sholschneider which version of WebAnno (version string on bottom including longish hexadecimal number) are you using?

**Comment by sholschneider** [comment]
I'm using WebAnno -- 3.0.0-beta-2 (2016-04-05 22:19:45, build b07b2897193cb8add658f0d3a6cb1008e490afc1) on Chrome.

**Comment by reckart** [comment]
@sholschneider the version you are using does not yet include the fix for this issue.
