### ISSUE TITLE
Agreement may be wrongly detected as disagreement

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#21]
The new CasDiff2 may detect the following situation as a DISAGREE/COMPLETE while it should be detected as an AGREE/COMPLETE:

```
Annotator 1: Lemma[0,0,"one"]
Annotator 2: Lemma[0,0,"one"], Lemma[0,0,"two"]
```

**Comment by reckart** [comment]
The reason is that agreement is defined by having only a single configuration in a configuration set. In the case above, we have two configurations in the configuration set:

```
CfgSet [position=(0,0)
  Cfg ["one", ["Annotator 1", "Annotator 2"]]
  Cfg ["two", ["Annotator 2"]]
]
```

I guess the agreement should also be asserted if there is at least one complete configuration in the set - although this removes the orthogonality between agreement and completeness.

**Comment by reckart** [comment]
On  a second thought, I'm not actually sure if this should be called an agreement. If there are two interpretations and one has only been found by one annotator, then there is at least disagreement on the other interpretation.

**Comment by reckart** [comment]
@mmev do you have any opinion on this issue?

**Comment by mmeva** [comment]
There are - as you write - several interpretations of AGREE for an annotated layer in consideration:
a) all annotated units on the same offsets are the same;
b) at least one unit on the same offsets is the same;
+) weighted proportion of the overlapping units.

This issue affects only settings which allow stacked (multiple) annotations. One could merge all these options if the calculation uses different distance/weighting functions. 

A starting point could be e.g. in the DKPro framework the org.dkpro.statistics.agreement.distance.SetAnnotation with different distance functions (NominalDistanceFunction, SetAnnotationDistanceFunction, MASISetAnnotationDistanceFunction) for Cohen's Kappa (WeightedKappaAgreement) of for Krippendorff's Alpa (KrippendorffAlphaAgreement).

I do not really know how COMPLETENESS is implemented currently, but it could be, that allowing a set annotation would also affect the interpretation of COMPLETENESS.

**Comment by reckart** [comment]
Thanks for the comment.

Hm...

So for agreement (not diff), the code currently doesn't take stacked annotations into account anyway (cf. `AgreementUtils.makeStudy(DiffResult, Collection<String>, String, String, boolean, Map<String, List<JCas>>)`):

```
                // Make sure a single user didn't do multiple alternative annotations at a single
                // position. So there is currently no support for calculating agreement on stacking
                // annotations.
```

Need to think again about this and about the boundary between "diff" and "agreement".

**Comment by reckart** [comment]
For coding-based agreement, we do not support stacking and in fact ignore any stacked annotations entirely.

For unitizing agreements, stacked annotations are passed on to the agreement measure and are covered there.
