### ISSUE TITLE
Span layers appear in feature types dropdown only after switching projects

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#215]
Reproduce:

* add a span layer "X" to a project
* add a second span layer "Y" to the project
* add a feature to layer "Y" and try selecting "X" as the feature type

Expected:
* "X" is available from the feature type dropdown list

Actual
* "X" is not available

Workaround
* switch to a different project, then switch back. Now "X" can be selected.

WebAnno -- 3.0.0-SNAPSHOT (2016-03-28 18:42:27, build c868352dbd1e6032379f267a875191e3dffb8d11)

**Comment by aakashysharma** [comment]
Found source of problem. 

The values for dropdown in featureDetailForm are generated as soon as you reach the ProjectLayers tab/page. 
List 'spanTypes' is not getting updated, so 'featureType` doesn't get updated in `FeatureDetailForm`

**Comment by aakashysharma** [comment]
@reckart While fixing this, I've implemented it in such a way that X can have a feature of type X (if X is of type _span_). Is it ok? Can a layer have feature which has itself (span) as type?

**Comment by reckart** [comment]
Span layer can have a link feature that points to itself, yes.
