### ISSUE TITLE
"Delete all relations" popup showing up even if there are no relations

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#216]
Reproduce:
- create annotation on some layer (e.g. POS)
- change layer of current annotation to some other layer (e.g. Lemma) using the dropdown field in the annotation detail editor panel

Actual:
- dialog "Are you sure you like to delete all attached relations to this span" pops up **unconditionally**

Expected
- dialog **only** pops up if the current span **actually** has attached relations or links from link features.
- if there are no attached relations or links from link features on the current span, then there should be **no dialog**

WebAnno -- 3.0.0-SNAPSHOT (2016-03-28 18:42:27, build c868352dbd1e6032379f267a875191e3dffb8d11)

**Comment by TristanDLM** [comment]
I would like to fix this issue, but I am not a Tomcat expert. Could someone help me understand what I would need to change, in which class(es), in order to do this please? Thanks.

**Comment by reckart** [comment]
The relevant code is in `de.tudarmstadt.ukp.clarin.webanno.ui.annotation.detail.AnnotationFeatureForm.actionReplace(AjaxRequestTarget)`. You probably need to add another condition which checks the `AttachStatus` to see whether popping up the dialog is necessary.

**Comment by sdabhi23** [comment]
Hey @reckart is this issue still relevant? I have located the file on the 3.6.x branch of the repo, and would like to take this up

**Comment by reckart** [comment]
@sdabhi23 if it is a thing that is annoying you, then it's still relevant ;) Btw. the relevant location in the master branch should be `de.tudarmstadt.ukp.clarin.webanno.ui.annotation.detail.AnnotationDetailEditorPanel.actionReplace(AjaxRequestTarget)`. The code was refactored quite a bit between the 3.6.x and the master branch. So unless you have a strong reason to fix it on the 3.6.x branch, it would probably make more sense to investigate it on master because merging these changes in master will probably not be straightforward.

**Comment by sdabhi23** [comment]
> So unless you have a strong reason to fix it on the 3.6.x branch, it would probably make more sense to investigate it on master because merging these changes in master will probably not be straightforward.

The only reason I looked it up on 3.6.x was because I was not able to locate the class you mentioned earlier on master! I will fix it on master now

**Comment by reckart** [comment]
INCEpTION does not have this bug.
