### ISSUE TITLE
Annotation user preferences deleted on exit

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#219]
For some reason that I do not understand, we have code that deletes all user preferences files on exit.

@seyyaw @ChrisBieTUDA Why do we have that? I would find it much more convenient to have them persistent across server restarts.

In `de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.saveUserSettings(String, Project, Mode, T)`

```
        FileUtils
                .forceDeleteOnExit(new File(propertiesPath, annotationPreferencePropertiesFileName));
```

**Comment by ChrisBieTUDA** [comment]
I agree they should be persistent.
