### ISSUE TITLE
Parameter setting for number of sentences to be displayed by default

### ISSUE THREAD

**Issue by nilsreiter** [webanno/webanno#22]
Please add a parameter that can be set to define the number of sentences to be displayed by default, so that not every annotator has to change that setting manually.

**Comment by seyyaw** [comment]
The new behaviour
 - The first time a user opens a document, the number of sentences to be displayed will be read from global settings (from settings.properties file or, if this file do not contain the setting, it will load from the applicationContext.xml file, a default of 5)
- If the user changes the number of sentences to display from the annotation settings dialog window, the user's setting will have a precedence.

**Comment by reckart** [comment]
The naming of the properties doesn't align with the other property names. We typically use something like: 

   topic.subtopic = value

e.g.

   database.username = ...
   backup.interval = ...

The property should be renamed from `number.of.sentences` to something like that. I would suggest like

   ui.brat.sentences.number

**Comment by reckart** [comment]
Has been implemented ages ago.
