### ISSUE TITLE
Keyboard-based annotation/forward annotation slow

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#223]
I find the keyboard-based annotation that is activated by checking the "forward annotation" checkbox a bit slow. The problem seems to be that for every key-press, a round-trip with the server is initiated - and that even though the annotation view is not updated, only the checkbox. Pressing a key quickly and repeatedly often runs into a "hang" where the server does take a few seconds to respond. It would be much better if the tag cycling could be handled in JavaScript. @ChrisBieTUDA @seyyaw 

WebAnno -- 3.0.0-SNAPSHOT (2016-04-02 19:12:19, build 119c196ab0cb67cffb3dc89550e2d1357fda3eea)

**Comment by ChrisBieTUDA** [comment]
absolutely, I agree with this and talked with @seyyaw about it. Seid, please investigate REC's proposal regarding cycling inside JS.

**Comment by reckart** [comment]
This will not be fixed anymore in WebAnno. In INCEpTION, the whole forward-annotation mode has been removed.
