### ISSUE TITLE
Forward annotation does not seem to work

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#224]
Forward annotation does not seem to work @seyyaw @ChrisBieTUDA .

* enable forward annotation mode.
* select POS layer
* double-click on a token
* press V (some verb tag is selected)
* press enter

Expected

* current annotation is assigned the verb tag
* POS annotation created at next token and opened

Actual

* current annotation becomes unselected without being updated

WebAnno -- 3.0.0-SNAPSHOT (2016-04-02 19:12:19, build 119c196ab0cb67cffb3dc89550e2d1357fda3eea)

**Comment by ChrisBieTUDA** [comment]
what browser are you testing, REC? try 'space' instead of 'enter' ?

**Comment by reckart** [comment]
Using Safari 9.1. Space seems to work. So the key is space, not enter? Or is this browser-specific?

**Comment by sholschneider** [comment]
Using Chrome 49.0.2623.110, the space key works for going to the next token. But how can I choose the tag now?

**Comment by reckart** [comment]
For me, the space key completes the current annotation and creates one with the same tag on the next token. Pressing any key then selects a tag starting with the letter of the key pressed.

**Comment by sholschneider** [comment]
Ah okay, I found it. However, both g, d, and h-key lead to tags starting with "$". It seems to me that "$" is the default beginning for keys whose letters do not represent the beginning of any tag. Am I right?

**Comment by reckart** [comment]
@sholschneider yes - it appears as if pressing a key that has no tag associated with it simply selects the first tag.

**Comment by seyyaw** [comment]
for Safari, **Enter** is not working. for chrome both **Enter** and **Space** key should work. closing...

**Comment by reckart** [comment]
This should be reflected in the documentation. Reopening for the documentation to be updated with a respective notice.

**Comment by seyyaw** [comment]
annotation.adoc is updated
