### ISSUE TITLE
How to delete a layer?

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#227]
For fixing some issue, I created some additional layers in a project. However, they are not needed as I ended up creating many. The only option I see is to disable them.

Why is there no option to delete a layer? I understand that it could (potentially) break webanno at many places if you delete a layer which is being used. Is it by design?

**Comment by reckart** [comment]
I don't think there are technical reasons beyond our control anymore that would prevent the deletion of layers.

But it would require checking where layers are used (e.g. span layers may act as targets for a relation or of link features) and prevent them from being deleted if still in use (also displaying a notice to the user that respective using layers need to be deleted first or offering to delete these layers as well).

It may also be a good idea to immediately "upgrade" all the CASes in a project when a layer is deleted to remove all annotations from this layer... that would avoid problems if a new layer with the same name but incompatible features is created (e.g. if "x" was a string before and now is a boolean).
