### ISSUE TITLE
Inconsistencies when applying German browser settings

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#229]
When applying German browser settings, some of the buttons are translated, some are not. I am working with WebAnno -- 3.0.0-beta-2 (2016-04-05 22:19:45, build b07b2897193cb8add658f0d3a6cb1008e490afc1) on Chrome.
![inconsistency](https://cloud.githubusercontent.com/assets/13764947/14377187/b798c9c4-fd6e-11e5-8e1a-73cb511bf74d.PNG)

**Comment by reckart** [comment]
That is correct. Some parts of WebAnno are translated/translatable - but many parts are not.

We could consider adding a configuration setting on the server that to explicitly enable i18n - and leave that off by default.

**Comment by sholschneider** [comment]
The inconistencies reoccur in the documentation (s #195).

**Comment by reckart** [comment]
Language is now set to English by default.
