### ISSUE TITLE
Training files for automation should not be stored as SourceDocument

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#23]
Training files for automation should not be stored as SourceDocument. The automation module should maintain a separate table for these training files. This will simplify the code elsewhere because the TAB_SEP files do not need to be specially handled. It will improve the overall separation of concerns.

- [x] move trainingDocument property out of SourceDocument
- [x] move WebAnnoConst back to `webanno-api`
- [x] export training documents
- [x] import Training documents
- [x] move automation implementation out of `webanno-api-automation`
- [x] move all automation-related calls out of CasStorageService/CasStorageServiceImpl and into `webanno-automation`
- [ ] implement automatic migration code (if feasible)
- [ ] document upgrade procedure (if necessary)

**Comment by reckart** [comment]
@seyyaw can you fix this?

**Comment by seyyaw** [comment]
@reckart fixing this is easy. But it needs to change the structure of the database. Again, what about doing this early phase of next WebAnno version? I don't see the benefit doing it now.

**Comment by reckart** [comment]
Why does this required changes to the database?

**Comment by seyyaw** [comment]
Because, for example the field **isTrainingDocument** is not required anymmore

**Comment by reckart** [comment]
@seyyaw please stick to the usual commit message format

```
#<issue number> - <issue title>
- <change 1>
- <change 2>
- ...
```

**Comment by reckart** [comment]
This commit contains *many* changes not related to the issue. It makes it very hard to see what is going on.

**Comment by seyyaw** [comment]
yes, mainly
1) I commit all after checking the whole refactoring is working
2) While working on the automation refactoring, there were a lot of continuous changes (This week was busiest of commits I think)

**Comment by reckart** [comment]
Thanks for moving the training document property out of the SourceDocument. Does it completely address the issue? Can it be closed?

**Comment by reckart** [comment]
It would be useful if GitHub provided a feature to compare a commit against the the latest master state instead of simply showing everything in a commit.

**Comment by seyyaw** [comment]
I need to write upgrade procedures. There are many options to upgrade, the most important is to 1) delete the old training documents (which will be source document now, which is false), 2) removing some fields from the SourceDocument table. Do we have a place for upgrading to WebAnno (3x or 4)?

**Comment by reckart** [comment]
So far, we have a single automatic migration step which is `FixCoreferenceFeatures`. It runs when the application starts up. You could do something like that.

If you just want to document the procedure, you could add a section

```
=== Version <3.3.0 to 3.3.0

...
```

in `webanno-doc/src/main/asciidoc/common/migration.adoc`.

**Comment by reckart** [comment]
Mind that manual upgrade instructions will mostly help people that use MySQL. For people using the standalone JAR version, I believe, it will not be much help. I can hardly imagine them to look up how to connect to an HSQLDB to manually fix its contents.

**Comment by seyyaw** [comment]
Nice, I will try to add another auto migration for Automation. We can close this issue and open the migration issue for automation then.

**Comment by reckart** [comment]
Let's treat the migration as part of this issue. I think it is a completing step for the refactoring.

**Comment by reckart** [comment]
Comparing the changes in 4627bb8 via my local git client, I noticed that you moved `WebAnnoConst` from the `webanno-api` module to `webanno-support`. `webanno-support` should only contain stuff that is not specific to WebAnno and `webanno-api` should be the lowest common ground for WebAnno-specific things like `WebAnnoConst`. Can we move it back?

**Comment by seyyaw** [comment]
ok, I will do that

**Comment by reckart** [comment]
You have move the automation code from `webanno-automation` into a module called `webanno-api-automation`. If there is an `api` module, then that module should only contain interfaces, data classes, enumerations, etc. but no actual implementation. So the `MiraAutomationServiceImpl` and related code should remain in `webanno-automation` or if you like e.g. in `webanno-mira`, but in any case it should be moved out of `webanno-api-annotation` because it is implementation - not API.

**Comment by reckart** [comment]
`CasStorageService/CasStorageServiceImpl` must not have automation-related calls. It is a low-level task-agnostic serice. Please move these methods into `webanno-automation`.

**Comment by seyyaw** [comment]
Ahh! I found the problem about adding issue number, the vim is removing when staff started with #?

**Comment by reckart** [comment]
I don't think it is vim - rather the git command line tool that reads the file saved by vim. I can recommend the SourceTree git client if you are on Windows or OS X. On Linux the git support in Eclipse or SmartGit should work well.
