### ISSUE TITLE
Problem with subtoken span annotation without a feature

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#231]
I have created a TSV file with all kinds of annotations

* POS (single-token span)
* Named Entity (multi-token span)
* Coreference chains
* Span with slot feature
* Subtoken span
* Dependency relation

There seems to be a problem here with the first type declared in the header.

```
#T_SP=webanno.custom.Inflection|
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS|PosValue
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity|value
#T_SP=webanno.custom.SemanticPredicate|ROLE_webanno.custom.SemanticPredicate:arguments_webanno.custom.SemanticPredicateArgumentsLink|webanno.custom.SemanticArgument
#T_SP=webanno.custom.SemanticArgument|
#T_CH=de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink|referenceType|referenceRelation
#T_RL=de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency|DependencyType|BT_de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS


#Text=0-20#Jack loves Mary Ann.
1-1	0-4	Jack	NNP	Person	_	_	de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceType[2]	de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceRelation->2-1	nsubj	1-2	
1-2	5-10	loves	VBZ	_	Content|Experiencer	1-3[1]|1-1	_	_	_	_	
-->1-2.1	9-10	s	_	_	_	_	_	_	_	_	
1-3	11-15	Mary	NNP	B-Person[1]	_	_	B-de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceType[1]	de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceRelation->1-1	dobj	1-2	
1-4	16-19	Ann	NNP	I-Person[1]	_	_	I-de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceType[1]	de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceRelation->1-1	compound	1-3	
1-5	19-20	.	.	_	_	_	_	_	_	_	

#Text=21-39#She loves him not.
2-1	21-24	She	PRP	_	_	_	de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceType[1]	de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceRelation->1-2	nsubj	2-2	
2-2	25-30	loves	VBZ	_	_	_	_	_	_	_	
-->2-2.1	29-30	s	_	_	_	_	_	_	_	_	
2-3	31-34	him	PRP	_	_	_	de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceType[2]	de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceRelation->2-2	dobj	2-2	
2-4	35-38	not	RB	_	_	_	_	_	neg	2-2	
2-5	38-39	.	.	_	_	_	_	_	_	_	
``` 

According to the header, the first column after the token column should be for the "Inflection" type. But it appears that the first column is for POS. 

Only in the two subtoken likes, the first column contains offsets for the Inflection annotations (they are on the "s" of "loves"). How does the reader know that for subtokens, the first column is Inflection but for all other normal token rows, the first column in POS?

**Comment by reckart** [comment]
@ChrisBieTUDA ping

**Comment by seyyaw** [comment]
`#T_SP=webanno.custom.Inflection|` 
does not have a feature. That is why it is missed. And the **s** is not an inf annotation, it is a token (annotation unit) like **loves**. I see two way out here

1. If layer do not have at least one feature, ignore from the export OR

1. Add the layer name (so add one more column)

Yes, the current format is broken

**Comment by reckart** [comment]
The layer should be in the export even if there is no feature.

I do not think the layer name needs to be added anywhere else then in the header - where it already is. But there needs to be an additional column to indicate where spans on this layer start and end. Since you know from the header that the span has no features, you can use a dummy value like `*` and for multi-token span layers that do not have a feature, you can use the regular BIO encoding like: `B-*`, `I-*`. I think you also normally also have some number in parentheses in case of overlaps.
