### ISSUE TITLE
Include offsets in TSV3 format

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#234]
I think it would be good to include offsets into the original text in TSV3 format, even though the original text is not fully stored in the file. Having the offsets of annotations in there would allow to map the content of a TSV3 file to easily relate it to other potentially existing stand-off annotations on the same underlying text, e.g. if there are stand-off annotations.

Since it is very cheap to add the offsets as two additional columns, e.g. after the initial ID column, I think we should really do that. The reader can safely ignore this information. If would only be relevant for the writer.

**Comment by reckart** [comment]
@ChrisBieTUDA ping

**Comment by ChrisBieTUDA** [comment]
PRO
it's reasonably cheap. the information is available. 
CON
makes it more complicated, and larger.. Also, as opposed to all other columns, the contents are 'ignored' when reading it back in, which could cause confusion. 

Can you please give a concrete example where this would be useful and where offset info could not be reconstructed rather easily, given that the format gives the tokens in linear order? 
I am looking for examples where people with little skills have a big advantage from this. Skilled people, like ones that can handle CASes, don't seriously need that. 

So far, I am not convinced..

**Comment by reckart** [comment]
Discussed this again with @ChrisBieTUDA today with the conclusion that he's still not convinced but also not opposed and that the offsets should be included.

**Comment by seyyaw** [comment]
what do you mean by **include offsets into the original text**? We have already the following

1. offsets of all annotations (second column)

1. offsets of the sentences (next to ext=)

example (from $230)

```
#Text=0-20#Jack loves Mary Ann.
1-1 0-4 Jack    NNP Person  _   _   de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceType[2]   de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceRelation->2-1 nsubj   1-2 
1-2 5-10    loves   VBZ _   Content|Experiencer 1-3[1]|1-1  _   _   _   _   
-->1-2.1    9-10    s   _   _   _   _   _   _   _   _   
1-3 11-15   Mary    NNP B-Person[1] _   _   B-de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceType[1] de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceRelation->1-1 dobj    1-2 
1-4 16-19   Ann NNP I-Person[1] _   _   I-de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceType[1] de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceRelation->1-1 compound    1-3 
1-5 19-20   .   .   _   _   _   _   _   _   _   

#Text=21-39#She loves him not.
2-1 21-24   She PRP _   _   _   de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceType[1]   de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceRelation->1-2 nsubj   2-2 
2-2 25-30   loves   VBZ _   _   _   _   _   _   _   
-->2-2.1    29-30   s   _   _   _   _   _   _   _   _   
2-3 31-34   him PRP _   _   _   de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceType[2]   de.tudarmstadt.ukp.dkpro.core.api.coref.type.CoreferenceLink:referenceRelation->2-2 dobj    2-2 
2-4 35-38   not RB  _   _   _   _   _   neg 2-2 
2-5 38-39   .   .   _   _   _   _   _   _   _   
```

**Comment by reckart** [comment]
Offsets for each token/subtoken (second column). I would say that the sentence offsets can be derived from these, so the sentences do IMHO not need to have an additional offsets info.
