### ISSUE TITLE
RuntimeException in Curation if changing the project

### ISSUE THREAD

**Issue by mmeva** [webanno/webanno#235]
Observed in Curation on Testing 3.0.0-beta-2 (2016-04-05) for projects kp3_main_role_(train|devel|test): 
1. Curate a document A of project X
2. Try to open another document B of project Y (thus, change the project)
Effect: RuntimeException

Independent of:
- whether the document A or B were opened before
- whether the document A or B were closed ("done") before or after opening
- whether the project X or Y were opened before in the current log-in setting

The "back" button in the browser opens the selected document B correctly.

[RuntimeExc_ChangingProj.txt](https://github.com/webanno/webanno/files/212928/RuntimeExc_ChangingProj.txt)

**Comment by seyyaw** [comment]
@mmeva I tried random files in two different projects and it works for me. May be send me exact projects and document names (by email). Thanks

**Comment by seyyaw** [comment]
can't repro
