### ISSUE TITLE
"New Annotation" window pops up at the bottom of the page (where you do not see it)

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#236]
When choosing a large number of sentences in "settings" during the annotation process, the "new annotation" window pops up at the bottom of the page is not visible while working on sentences at the beginning of the file.
I am using WebAnno -- 2.3.1 (2016-04-07 10:40:53, build 6c4cc8b8483131e47e2b7f2b9fbe94b8c1b720df) on Chrome

**Comment by sholschneider** [comment]
Same thing occurs vice versa when you annotate at the bottom of the page. You have to scroll up to find the "Annotation"-box.

**Comment by reckart** [comment]
This is related to the feature request "Remember size of annotation dialog" addressed in commit
2a123c69dcb03885725d30249b2592e18018ecd5.

I think the easiest thing would be to add a user-configurable preference whether to remember the dialog position/size or not.

**Comment by reckart** [comment]
Won't be fixed anymore since we have v3 now.
