### ISSUE TITLE
Confusing question when stacking span annotations

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#237]
When selecting a token which is already assigned to a tag in order to assign a second tag, the moment the annotator changes the layer, the/she is asked "Are you sure you want to delete the existing annotation?". Clicking on "yes" does not delete any tags and only changes the layer of the second tag. However, this might cause confused annotators.
I am working with WebAnno -- 3.0.0-beta-2 (2016-04-05 22:19:45, build b07b2897193cb8add658f0d3a6cb1008e490afc1) on Chrome.

**Comment by reckart** [comment]
Sounds similar to https://github.com/webanno/webanno/issues/216

IMHO the popup should **only** appear if any of the feature values have been set in the span annotation.  If all features are unset, then the changing of the layer should be possible without this extra confirmation.

**Comment by reckart** [comment]
The confirmation dialogs have been improved as part of #555. I believe this also addresses the issue described here... at least I don't seem to manage reproducing this on WebAnno 3.3.0-SNAPSHOT (0e0d107518b077741b4b8d5b606187f881f89432).

If this issue still exists, please re-open the issue or create a new issue and provide additional information on how to reproduce it step-by-step.
