### ISSUE TITLE
No way to discern between (non-)BIO encoded columns

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#238]
There is no way to discern between BIO and non-BIO-encoded columns.

This is a "real" multi-token annotation which was BIO-encoded by the TSV3 writer:

```
#FORMAT=WebAnno TSV 3
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity|value


#Text=0-16#This is a test .
1-1	0-4	This	B-PERSON[1]	
1-2	5-7	is	I-PERSON[1]	
1-3	8-9	a	I-PERSON[1]	
1-4	10-14	test	I-PERSON[1]	
1-5	15-16	.	I-PERSON[1]	
```

In this one, I simply set the feature values manually to `B-NOTBIO!` and `I-NOTBIO!`. 

```
#FORMAT=WebAnno TSV 3
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity|value


#Text=0-16#This is a test .
1-1	0-4	This	B-NOTBIO!	
1-2	5-7	is	I-NOTBIO!	
1-3	8-9	a	I-NOTBIO!	
1-4	10-14	test	I-NOTBIO!	
1-5	15-16	.	I-NOTBIO!	
```

The TSV3 reader has no way to tell that one is fake and the other is real.

I suggest we add a flag in the header when BIO encoding is used:

```
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity|value[BIO]
```

**Comment by reckart** [comment]
@seyyaw Btw, since we have a special syntax to disambiguate stacked annotations, I wonder if we actually need the BIO encoding at all. I don't really see at the moment what the BIO encoding adds that the `[<number>]` suffix does not already cover. Maybe we can completely remove the BIO encoding? @ChrisBieTUDA

**Comment by seyyaw** [comment]
No, the number just tell if there are multiple annotation on same position or not, and if the annotation spans multiple tokens. But it does not tell if this is the **B** or the **I**
Example:
```
1-1	0-4	This	B-ORG[1]	
1-2	5-7	is	I-ORG[1]||B-OTH[2]	
```

**Comment by reckart** [comment]
The first one with a given number is the B and the others are I. The BIO encoding is used to tell if two adjacent annotations with the same label are one or two labels:

```
B-LALA 
I-LALA 
= one annotation spanning two tokens

B-LALA 
B-LALA 
= two single-token annotations
```

But since this information is already included in the number suffix, I think we don't need the BIO encoding anymore:

```
LALA[1]
LALA[1]
= one annotation spanning two tokens

LALA[1]
LALA[2]
= two single-token annotations
```

**Comment by seyyaw** [comment]
How do decode the following? No way to tell if they are stacked or multiple annotation without the prefixes. 
```
B-LALA[1]|B-LALA[2]
I-LALA[1]|B-LALA[2]
```
I will check how to add the BIO in the header.

**Comment by reckart** [comment]
I would suggest this:

```
B-LALA[1]|B-LALA[2]
I-LALA[1]|B-LALA[3]
```

**Comment by reckart** [comment]
Or rather this:

```
LALA[1]|LALA[2]
LALA[1]|LALA[3]
```

**Comment by reckart** [comment]
Also like this for example. Numbers are added when

* stacked or
* multi-token

Numbers are increased continuously.

Here we have 5 annotations:
* two stacked on the first token
* one multi-token on the 2nd and 3rd token
* two single token annotations which do not get a number

```
#Text=This is a test .
1-1	0-4	This	PERSON[1]|PERSON[2]	
1-2	5-7	is	PERSON[3]	
1-3	8-9	a	PERSON[3]	
1-4	10-14	test	PERSON
1-5	15-16	.	PERSON
```

```
1-1 0-4 This    PERSON[1] 
1-2 5-7 is  PERSON[1] 
1-3 8-9 a   PERSON[2]|PERSON[3] 
1-4 10-14   test    PERSON[2]|PERSON[3] 
1-5 15-16   .   PERSON[2] 
```

**Comment by seyyaw** [comment]
Done --Referencing is incremental
Done --References added only when it is ambiguous
Todo -- documentation

**Comment by reckart** [comment]
Closing this issue. The documentation of the whole TSV is still open -> #193.
