### ISSUE TITLE
Stacked annotations should be separated by a single `|` (pipe symbol)

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#241]
Stacked annotations should be separated by a single `|` (pipe symbol), not by two of them.

Current:

```
#FORMAT=WebAnno TSV 3
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity|value


#Text=0-16#This is a test .
1-1	0-4	This	B-PERSON[1]||B-LOCATION[2]	
1-2	5-7	is	I-PERSON[1]||I-LOCATION[2]	
1-3	8-9	a	I-PERSON[1]||I-LOCATION[2]	
1-4	10-14	test	I-PERSON[1]||I-LOCATION[2]	
1-5	15-16	.	I-PERSON[1]||I-LOCATION[2]	
```

Expected:

```
#FORMAT=WebAnno TSV 3
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity|value


#Text=0-16#This is a test .
1-1	0-4	This	B-PERSON[1]|B-LOCATION[2]	
1-2	5-7	is	I-PERSON[1]|I-LOCATION[2]	
1-3	8-9	a	I-PERSON[1]|I-LOCATION[2]	
1-4	10-14	test	I-PERSON[1]|I-LOCATION[2]	
1-5	15-16	.	I-PERSON[1]|I-LOCATION[2]	
```

**Comment by seyyaw** [comment]
From TSV documentation
```
Stacked annotations are separated by a two | character, i.e ||

Multiple slot features, on a single base annotation are separated by a single | charter. 
```

**Comment by reckart** [comment]
Let's use a different character then. It is unusual that a character has different meanings depending on if it occurs once or twice in such a file format.

**Comment by reckart** [comment]
I would suggest to use the pipe `|` as separator for stacked annotations and the semi-colon `;` as separator if there is a slot feature with multiple fillers.

**Comment by reckart** [comment]
@seyyaw btw, where do I find the TSV documentation?

**Comment by seyyaw** [comment]
**;** is used for slot feature separation
TSV doc: I sent once to all the group and @sholschneider might be working on it. We have another Issue for the docs anyways, closing
