### ISSUE TITLE
Exceptions that happen during project export are not displayed in UI

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#244]
Exceptions that happen during project export are not displayed in UI. Instead of the export process failing with an error message, the export simply gets stuck. 

The process should abort properly:

- progress bar is reset
- buttons become active again
- error message is displayed
- stack trace should go to the logs

We often have users hitting this problem and always have to ask them to look for some stack trace in the logs (and sometimes not even these are there).

**Comment by aakashysharma** [comment]
@reckart So would you like to display all exceptions's cause to the user in feedback panel and all stack traces in log?

**Comment by reckart** [comment]
@aakashysharma once the first exception is hit, it should about the export, display the message for *that* exception to the used and log the stack. It should not even be permitted to continue the export after the first exception has been hit.

**Comment by aakashysharma** [comment]
Any hint on how to test this? How to deliberately make a project export fail which is not of type `FileNotFoundException`?

**Comment by aakashysharma** [comment]
Should it continue on following warning messages? It happens if you export a project which was taken from quite old version of WebAnno.

`[example2.tsv] No writer found for format [ctsv] - exporting as WebAnno TSV instead.`

**Comment by reckart** [comment]
Warnings are not exceptions. The abort should only happen when exceptions are thrown.

**Comment by aakashysharma** [comment]
Should progress bar go to 0?

Currently, if user cancels an export, progress bar is set to 100.

**Comment by reckart** [comment]
0 sounds good.

**Comment by aakashysharma** [comment]
@reckart I'm not sure how to cause project crashes now. I feel the Even after making repository's project directory completely empty (zipping all files in 1 and delete other files)
![repository](https://cloud.githubusercontent.com/assets/1897100/16999583/02ce5a20-4ebf-11e6-8360-744943ee5a2e.png) , the project export succeeds!

![exportcomplete](https://cloud.githubusercontent.com/assets/1897100/16999571/f428a58e-4ebe-11e6-97c3-87ab7696fd72.png)

There's not much in console log!

```
2016-07-20 21:15:55 ERROR [Thread-15] [admin] (ProjectPage) - null
2016-07-20 21:15:55 ERROR [Thread-15] [admin] (ProjectPage) - null
2016-07-20 21:15:55 ERROR [Thread-15] [admin] (ProjectPage) - null
2016-07-20 21:15:56  INFO [http-bio-8080-exec-5] [admin] (ApplicationPageBase) - admin: Project export complete
```

**Comment by reckart** [comment]
@aakashysharma Then let's consider this issue as resolved. If we hit problems again, we can open a new one (or reopen).
