### ISSUE TITLE
WebAnno allows to import xmls if xmi is specified as import format

### ISSUE THREAD

**Issue by muchafel** [webanno/webanno#245]
When uploading documents using the import functionalities of the UI (project settings/project/documents) one can upload xmls if one specifies xmi as import format. This will cause troubles when exporting the project as the xml cannot be annotated etc.
It would be great if webanno would warn in such cases (or prohibit them)

(if one transforms documents in xmis using dkpro an typesystem.xml is created automatically that might be uploaded accidentally)  

WebAnno -- 2.3.0 (2015-07-26 23:34:28, build 4eb3114b375d038ca3b0860cc1fb473ef203b472)

**Comment by reckart** [comment]
Maybe this problem affects all documents imported with the wrong type... I thought we had at some point in the past introduced a check on import - basically trying to pass all documents through the respective reader and fail if the reader throws any exception (or at least skip the problematic documents).

**Comment by reckart** [comment]
That should no longer be happening. Cf. https://github.com/webanno/webanno/issues/416#issuecomment-320522576
