### ISSUE TITLE
Highlighting in curation confused

### ISSUE THREAD

**Issue by mmeva** [webanno/webanno#246]
During Curation, the highlighting function seems to be confused.
Example (see attached picture):
Pointing at a SemArg instance of role2 annotation causes the highligthing of a non-correspondent SemArg-Instance of role4 annotation.
![highlightingproblems](https://cloud.githubusercontent.com/assets/2294086/14602941/12adc234-056b-11e6-8f12-b13abae3e468.png)

(Project and file name as well as WebAnno version see attached picture.)

I am using Safari.

Note that the described behaviour is not deterministic. (That is, you probably cannot reproduce the very same picture, but only similar ones.)

**Comment by reckart** [comment]
This is a known issue. The highlightning is actually not intended. It is basically just random.

The first fix should be that this highlighting does not happen.

Maybe in the future, it could be changed such that it actually makes sense and tries highlighting annotations that webanno considers to be equivalent.
