### ISSUE TITLE
Switching between documents on curation page is very slow

### ISSUE THREAD

**Issue by mmeva** [webanno/webanno#249]
At least in the Curation UI, if clicking on "Next document", WebAnno takes at about half a minute to load the next document.

Observed in project kp3_dck_role_v01, WebAnno -- 3.0.0-beta-2 (2016-04-05 22:19:45) with Safari.

The documents are not really long - 300-700 sentences. They are annotated heavily, but most of the annotation layers are hidden, and are just span annotations.
Nevertheless, 30 seconds seem to be long...

**Comment by reckart** [comment]
Document loading in curation is not really optimized for speed. I believe the CASes are still loaded way more often than actually necessary.

**Comment by reckart** [comment]
#569 should improve the situation a bit.

**Comment by reckart** [comment]
The improvements in the 4.x branch should address this issue sufficiently - at least for the moment.
