### ISSUE TITLE
Documents are not marked as already opened if paging with "Next document"

### ISSUE THREAD

**Issue by mmeva** [webanno/webanno#250]
You have two possible ways to open a document for annotation or curation:
1) click "Open" in the "Document" menu frame, select project, select document name, click "Open"
2) click "Next" in the "Document" menu frame

If I take the 2. way, the document will not be marked as 'already opened' - t.i. the name of the document stays black if I go for the way 1).

Observed in Curation, WebAnno -- 3.0.0-beta-2, Testing.
See attachment: I have already opened the files with "reden" und "schauen", but both names are still black. (Files with "passieren" and "sagen" were selected via way 1).
![openeddocumentnotmarkedassuch_curation](https://cloud.githubusercontent.com/assets/2294086/14637204/1d66243a-0630-11e6-981f-c40995fb8ea3.png)
)

(Probably, this issue is only a symptom for another problems.)

**Comment by mmeva** [comment]
The overview in Monitoring does not mark the documents opened via 2) as 'opened' either.

**Comment by mmeva** [comment]
The affected documents (which are opened but are not marked as opened) are also not part of the export!
(Note that I did not marked them as "Done" in the Curation interface. But opened documents are part of the export otherwise.)

**Comment by reckart** [comment]
What export? The "Export the whole project to the file system"?

**Comment by mmeva** [comment]
Yes

**Comment by reckart** [comment]
The "Export whole project..." should include **everything** irrespective of in which state the documents are in. It is meant as an archival function.

But mind that the export contains two folders: one with the binary CAS and one with the "other format". Are the binary CAS for the respective documents also missing, or only the files for the "other format"?

**Comment by mmeva** [comment]
Also the binary CAS are affected - that is, the folder named "curation_ser" does not include the affected documents either.

One more information: I chose the format "UIMA XMI" for the export.

**Comment by aakashysharma** [comment]
Tested on WebAnno `3.0.0-SNAPSHOT (2016-04-19 14:51:32, build ef8040abe091adf44ff834586e8a11d424ad475f)`

Chrome `49.0.2623.75 (64-bit)`

1. **In Annotation**, this is not reproducible. All documents are being marked open if they are opened by method 1 or 2.
I opened first file in this project in annotation and navigated by method 2.
![all files marked blue](https://cloud.githubusercontent.com/assets/1897100/14641029/a8f0b394-0644-11e6-9f70-6f06872093a1.png)


2. However, **in Curation** mode it exists,
Before opening any document.
![beforecuration](https://cloud.githubusercontent.com/assets/1897100/14641058/bbd9d01c-0644-11e6-8dc7-f37e2a858319.png)

Even after opening documents by method 2, they are not marked 'blue' by WebAnno. (The last two documents)
![after curation](https://cloud.githubusercontent.com/assets/1897100/14641078/cf519724-0644-11e6-923f-d8bdded8d85a.png)

3. I **exported this project** in 'UIMA XMI' format and imported right back into my instance. I opened the imported copy of project in Curation and all documents are there.

**Comment by reckart** [comment]
@aakashysharma as you investigated this: what is the status of this issue? Can we reproduce it? Does it still occur?

**Comment by aakashysharma** [comment]
I didn't investigate further after verifying where it exists (posted with screenshots above). Only method 2(opening document by clicking on "next document") doesn't mark documents as opened in Curation.

**Comment by reckart** [comment]
Ok, that sounds like you have narrowed down pretty precisely when the problem occurs. This should allow to also locate the relevant part of the source code. Probably 1-2 lines of code missing there that mark the document as opened. May be an easy fix.

**Comment by aakashysharma** [comment]
Only difference I could see while comparing code for AnnotationPage and CurationPage is this line 453

`repository.upgradeCasAndSave(bModel.getDocument(), Mode.CURATION, bModel
                                .getUser().getUsername());`

This is marked depricated without providing any alternative to it. Maybe it's changing the state of document while upgrading so that it's not marked read.

**Comment by reckart** [comment]
I don't know. Try following where AnnotationDocumentState is used and see if you can somehow correlate this to your findings about when the state is not changed. Maybe that way you find the missing calls.
