### ISSUE TITLE
Monitoring: "last access" line is counted as a document

### ISSUE THREAD

**Issue by mmeva** [webanno/webanno#251]
The line for "last access" within the project overview table in the Monitoring UI is counted as a document. Thus, the number of documents is one more than it should be.

Observed on: WebAnno -- 3.0.0-beta-2, Testing

Could be this comment be placed probably as an additional information, but not as a line within the table? (or it could be placed to the header of the table)

**Comment by reckart** [comment]
*sigh* - it would be best actually to reimplement the whole table, because it is also very slow clicking on the cells when there are many documents.

**Comment by reckart** [comment]
Actually, I don't understand what you mean by "count". I don't see any number of documents being displayed on the monitoring page except in the progress indicators - and they are correct. I.e. if there are two documents, then the progress indicators go from 0 to 2.

... so not sure what the problem is.

**Comment by normundsg** [comment]
Here is a screenshot that illustrates the mismatching (+1) total number of documents in the Monitoring view (v3.2.1).

<img width="577" alt="wa-doc_count" src="https://user-images.githubusercontent.com/1726922/31316044-b9a3e37e-ac2d-11e7-8c17-06d3d7bc98e7.png">

Ok, it is not specified if this is a total doc count, or row count in the table below, but intuitively this is assumed as doc count.

**Comment by reckart** [comment]
The new workload management pages in INCEpTION do not have this issue anymore.
