### ISSUE TITLE
Pop-up window width not adjusted to the content 

### ISSUE THREAD

**Issue by mmeva** [webanno/webanno#252]
The size of some of the pop-up windows is not appropriate. 

Examples in Curation:
![popupwindowwidth_toosmall](https://cloud.githubusercontent.com/assets/2294086/14740564/3054ef2e-0890-11e6-86ec-55f5d881ec5c.png)
![popupwindowwidth_toowide](https://cloud.githubusercontent.com/assets/2294086/14740565/3055390c-0890-11e6-8ca5-c3b5af5d6475.png)

**Comment by aakashysharma** [comment]
@reckart Found this in CurationPage.java:609

It's probably set that way to adjust for the `if block` which can also end up in displaying
`Curation was finished. Are you sure you want to re-open document for curation?`

Should I change the width of modal window according to the statement it has to show OR do we have a standard size which we should use for all modal window?

**Comment by reckart** [comment]
I would suggest to:
* have a fixed size
* use a generic popup title (e.g. "Question")
* and put the actual message into the popup

**Comment by aakashysharma** [comment]
Why not use [setAutoSize(true)](https://ci.apache.org/projects/wicket/apidocs/6.x/org/apache/wicket/extensions/ajax/markup/html/modal/ModalWindow.html#setAutoSize(boolean) )

**Comment by reckart** [comment]
No objection.

**Comment by aakashysharma** [comment]
Tested setAutoSize() but it doesn't look pretty!

It re-sizes based on content, not on title's width. I'll try to implement your suggestion.

**Comment by reckart** [comment]
I was kind of expecting that the title wasn't taken into consideration, but not sure.

**Comment by aakashysharma** [comment]
@mmeva Please report if you see more such misaligned message windows.

**Comment by reckart** [comment]
@aakashysharma you mean other dialogs or you mean if the problem still appears? Mind we'd have to provide a new version for testing for the latter to be checked.

**Comment by aakashysharma** [comment]
@reckart I fixed the width for the two dialogs shown above. I'm not sure about which other dialogs are improperly sized. That's why I created #261 implementing your suggestion.

So, until #261 is done, there might be some dialogs other than the ones above which have weird size.
