### ISSUE TITLE
Export: Give a meaningful name for Curation export zip file

### ISSUE THREAD

**Issue by mmeva** [webanno/webanno#257]
If I export the whole project ("Export the whole project to the file system"), the exported zip file has a meaningful name with the project name and a time stamp which is good.

It would be appropriate, if exporting only the curated documents ("Export curated documents to the file system") also could bear a meaningful name. A proposal: The zip-file could be named with the project name, the time stamp, and maybe a hint on the content like "projectxy_2016-04-25_1114_curated-documents.zip"

Observed on WebAnno -- 3.0.0-beta-2

**Comment by aakashysharma** [comment]
Should curation export be handled like [this](https://github.com/isisaddons/isis-wicket-excel/blob/master/cpt/src/main/java/org/isisaddons/wicket/excel/cpt/ui/ExcelFileDownloadLink.java) 

I believe that will also help catching errors encountered during export such as #272

**Comment by reckart** [comment]
I think maybe you can use the three-argument constructor of DownloadLink which allows to specify a filename? Cf. `org.apache.wicket.markup.html.link.DownloadLink.DownloadLink(String, IModel<File>, IModel<String>)`

**Comment by aakashysharma** [comment]
Modified code to generate name such as 
<ProjectName>_curated_documents_<timestamp>.zip

timestamp is in format "yyyy-MM-dd_HHmm" 

Let me know if this has to be changed to some other format.

**Comment by reckart** [comment]
Sounds good.
