### ISSUE TITLE
Unnecessary special handling for Dependency type in Tsv3 writer?

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#258]
The TSV 3 write has a special handling of the DKPro Core Dependency type:

```
				if (type.getName().equals(Dependency.class.getName())) {
					depFs = ((Token) depFs).getPos();
					govFs = ((Token) govFs).getPos();
				}
```

I don't think this is necessary in the writer - and if it is not, then we should remove it.

@seyyaw Can you tell why this is necessary?

**Comment by seyyaw** [comment]
Yes this is not necessary for the writing. removed
