### ISSUE TITLE
Relation layers in TSV

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#259]
I have created a simple relation and serialized it to TSV3, but I do not understand the meaning of the generated header:

```
#FORMAT=WebAnno TSV 3
#T_RL=webanno.custom.Relation|BT_de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Token


#Text=This is a test .
1-1	0-4	This	_	
1-2	5-7	is	_	
1-3	8-9	a	_	
1-4	10-14	test	_	
1-5	15-16	.	1-1	
```

What does `BT_de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Token` mean here?

The type `webanno.custom.Relation` is defined as

```
    <typeDescription>
      <name>webanno.custom.Relation</name>
      <description/>
      <supertypeName>uima.tcas.Annotation</supertypeName>
      <features>
        <featureDescription>
          <name>Governor</name>
          <description/>
          <rangeTypeName>uima.tcas.Annotation</rangeTypeName>
        </featureDescription>
        <featureDescription>
          <name>Dependent</name>
          <description/>
          <rangeTypeName>uima.tcas.Annotation</rangeTypeName>
        </featureDescription>
      </features>
    </typeDescription>
```

The annotation is created as 

```
        List<Token> tokens = new ArrayList<>(select(jcas, Token.class));
        
        Token gov = tokens.get(0);
        Token dep = tokens.get(tokens.size()-1);

        Type relationType = cas.getTypeSystem().getType("webanno.custom.Relation");
        
        // One at the beginning
        AnnotationFS fs1 = cas.createAnnotation(relationType, dep.getBegin(), dep.getEnd());
        FSUtil.setFeature(fs1, "Governor", gov);
        FSUtil.setFeature(fs1, "Dependent", dep);
        cas.addFsToIndexes(fs1);
```

Yes, for that one specific relation, the `Governor` and `Dependent` feature values are tokens, but this doesn't have to be the case in general. The type system doesn't say anything about token.

Why do we have that reference to the token type in the header?

**Comment by reckart** [comment]
If I create a relation that uses a different annotation type for governor and dependent, the header still only shows one of them, e.g. 

```
        List<Token> tokens = new ArrayList<>(select(jcas, Token.class));
        
        Token gov = tokens.get(0);
        
        Token t2 = tokens.get(tokens.size()-1);
        NamedEntity dep =  new NamedEntity(jcas, t2.getBegin(), t2.getEnd());
        dep.addToIndexes();

        Type relationType = cas.getTypeSystem().getType("webanno.custom.Relation");
        
        // One at the beginning
        AnnotationFS fs1 = cas.createAnnotation(relationType, dep.getBegin(), dep.getEnd());
        FSUtil.setFeature(fs1, "Governor", gov);
        FSUtil.setFeature(fs1, "Dependent", dep);
        cas.addFsToIndexes(fs1);
```

Results in 

```
#FORMAT=WebAnno TSV 3
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity|value
#T_RL=webanno.custom.Relation|value|BT_de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Token


#Text=This is a test .
1-1	0-4	This	_	_	_	
1-2	5-7	is	_	_	_	
1-3	8-9	a	_	_	_	
1-4	10-14	test	_	_	_	
1-5	15-16	.	*	*	1-1	
```

Presently, mixed-type relations cannot be created in WebAnno, but I hope that will change at some point and it would good if the format already would support this right now so we don't have to invent yet another format at that point.

**Comment by seyyaw** [comment]
**BT_** is to mean the base span type for this relation, where the arcs are drawn to and from.
I create a span layer of type A and relation layer of type B in webanno. I get the following
```
#FORMAT=WebAnno TSV 3
#T_SP=webanno.custom.A|val
#T_RL=webanno.custom.B|relval|BT_webanno.custom.A


#Text=This is a simple sentence to be 
1-1	0-4	This	X	_	_	
1-2	5-7	is	Y	Z	1-1	```

I do not know how you get always the same header, should be the way the annotation is created

**Comment by reckart** [comment]
Based on offline discussion, we came up with this:

** Case relation with one feature `value`**

```
#FORMAT=WebAnno TSV 3
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity|value
#T_RL=webanno.custom.Relation|value|BT_de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity


#Text=This is a test .
1-1 0-4 This    *[1]|*[3]   _   _   
1-2 5-7 is  *[1]    _   _   
1-3 8-9 a   *[2]|*[4]    *[1]|SUBJ[2]   1-1[2_3]|1-1[4_1]   
1-4 10-14   test    *[2]    _   _   
1-5 15-16   .   _   _   _   
```

There are two relations here:
* Relation 1: FROM *NamedEntity* WITH ID *2* STARTING AT *1-3* TO *NamedEntity* WITH ID *3* STARTING AT *1-1* WITH FEATURE *value* not set
* Relation 2: FROM *NamedEntity* WITH ID *4* STARTING AT *1-3* TO *NamedEntity* WITH ID *1* STARTING AT *1-1* WITH FEATURE *value* set to *SUBJ* 

**Case with relation without any feature**

```
#FORMAT=WebAnno TSV 3
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity|value
#T_RL=webanno.custom.Relation|BT_de.tudarmstadt.ukp.dkpro.core.api.ner.type.NamedEntity


#Text=This is a test .
1-1 0-4 This    *[1]|*[3]   _   
1-2 5-7 is  *[1]    _   
1-3 8-9 a   *[2]|*[4]    1-1[2_3]|1-1[4_1]   
1-4 10-14   test    *[2]    _   
1-5 15-16   .   _   _   
```

There are two relations here:
* Relation 1: FROM *NamedEntity* WITH ID *2* STARTING AT *1-3* TO *NamedEntity* WITH ID *3* STARTING AT *1-1*
* Relation 2: FROM *NamedEntity* WITH ID *4* STARTING AT *1-3* TO *NamedEntity* WITH ID *1* STARTING AT *1-1*

**Comment by seyyaw** [comment]
Exporting relation: When the gov or the dep are not ambiguous, no need to add the the ref in the relation.

**Comment by reckart** [comment]
Please review the comments on commit c2e88f81f98f3a590d3b8901df12128a67f416e0

E.g. if a bracketed number is present in a cell it should be present on all values, not only starting on the second one. The numbers should be continuous starting at 1.
