### ISSUE TITLE
Modify how yes/no confirmation dialogs/messages are shown

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#261]
In continuation to #252 it was suggested to approach error messages with a different design. It would require modification to de.tudarmstadt.ukp.clarin.webanno.webapp.dialog.YesNoFinishModalPanel and wherever it is used to display confirmation.

They should 
1. have a fixed size
2. use a generic popup title (e.g. "Question")
3. and put the actual message into the popup

**Comment by reckart** [comment]
We now have a generic reusable confirmation dialog.
