### ISSUE TITLE
Curation: "Sentences" panel shows difference, but there is no one

### ISSUE THREAD

**Issue by mmeva** [webanno/webanno#264]
In Curation, the left panel called "Sentences" shows many times a difference in annotation (marked with red color), but I cannot see any differences in the annotations.

Examples (with WebAnno version and project/file):
![markeddifferencenotthere](https://cloud.githubusercontent.com/assets/2294086/15050678/78c343cc-12f5-11e6-92cf-4660e479dcdb.png)
![markeddifferencenotthere2](https://cloud.githubusercontent.com/assets/2294086/15050677/78c1b6a6-12f5-11e6-8764-3c8b38d308d8.png)

**Comment by seyyaw** [comment]
This is strange. Debugging shows that internally, we have different sensID, 

CasDiff:
```
[[role1:AID [addr=6274], role4:AID [addr=6274]] -> SemPred
   sofa: _InitialView
   begin: 694
   end: 699
   RoleSet: FSArray
   aFrame: "bevorstehen"
   senseId: "bevorstehen-1"
, [role1:AID [addr=6295], role4:AID [addr=6295]] -> SemPred
   sofa: _InitialView
   begin: 694
   end: 699
   RoleSet: FSArray
   aFrame: "bevorstehen"
   senseId: "bevorstehen-2"
]
```

**Comment by seyyaw** [comment]
ok, got the problem. It was due to stacked annotations. If **user1** has Annotation **A** and **B** and **user2** has Annotations **A** and **B** on the same positions, Casdiff returns differing configsets

**Comment by mmev** [comment]
I still would like to ask a question to this issue:
If we had a project curation in that time the curation panel could not display the actual annotated labels, we should consider the re-curation now (since we didn't see the differences in the annotation which were there...), don't we?

**Comment by seyyaw** [comment]
Yes you can re-curate, but you will loose the manual annotations. If you have a lot of manual annotations, it is better not to re-curate. It will not have effect on the curation result (it is only a visual issue)
