### ISSUE TITLE
Constraint rules with multiple conditions match even if only one condition is true

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#267]
Constraint rules with multiple conditions match even if only one condition is true.

Example rule:

```
import webanno.custom.Relation as RELATIONS;

RELATIONS {
    Governor.value = "Animal" & Dependent.value = "Weight" -> label = "hasWeight";
}
```

ValuesGenerator produces:

```
2016-05-12 12:23:08 TRACE [main] (ValuesGenerator) - comparing [Animal] to [[Animal]]
[PossibleValue [value=hasWeight, important=false]]
```

Looks like the second condition is maybe not even checked?

**Comment by reckart** [comment]
@aakashysharma you know the constraints best, could you have a look at it?

**Comment by aakashysharma** [comment]
Yeah sure.

**Comment by reckart** [comment]
@aakashysharma lightning fast ;) thanks 👍
