### ISSUE TITLE
Trying to draw an arc between two span layers which have no relation layer attached causes exception

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#274]
Trying to draw an arc between two span layers which have no relation layer attached causes exception

```
2016-05-18 09:32:39 ERROR [http-bio-8080-exec-1] [admin] (BratAnnotator) - ClassCastException: de.tudarmstadt.ukp.clarin.webanno.brat.controller.SpanAdapter cannot be cast to de.tudarmstadt.ukp.clarin.webanno.brat.controller.ChainAdapter
```

Tried on a custom "SemPred" layer with slots on it. Unable to reproduce on the built-in Named Entity Layer.

Something else seems to be strange in general - e.g. try changing the value of an existing POS annotation, then try drawing an arc between spans of another layer, e.g. NamedEntity.

Seems like somehow the last arc layer is remembered and not properly obtained from inspecting the spans between which the arc is actually being drawn.

**Comment by seyyaw** [comment]
Do not observe on non-slot layers so far. Re-open if the problem occurs for other span layers
