### ISSUE TITLE
Exception on 2.3.1 after trying 3.0.0-beta-2

### ISSUE THREAD

**Issue by outsideMyBox** [webanno/webanno#275]
I had downloaded webanno-standalone-2.3.1.jar and could run it without any issue. Then I downloaded webanno-standalone-3.0.0-beta-2.jar. This version didn't work, here the stacktrace: http://pastebin.com/2iTr3dj2

The stangest thing is that now I've got error when launching the version 2.3.1: http://pastebin.com/ENRMAzTV
(I deleted ~/.webanno before running both versions)

I tried the same procedure on another computer and got other errors:
2.3.1 http://pastebin.com/7S7BaQhv
3.0.0.beta http://pastebin.com/tCJ9Xi9J

**Comment by reckart** [comment]
If you are running standalone versions, WebAnno creates a temporary folder - you also need to delete that. It is a bit inconvenient but at least it is documented in the upgrade instructions:

> clean up the temporary installation before running the new version:
>
> On OS X: rm -R "$TMPDIR/winstoneEmbeddedWAR"
>
> On Linux: rm -R /tmp/winstoneEmbeddedWAR
>
> On Windows: remove the winstoneEmbeddedWAR that should be somewhere under C:\Users\<username>\AppData\Local\Temp

See also: https://webanno.github.io/webanno/releases/2.3.1/docs/user-guide.html#_upgrade_from_2_0_x_to_2_1_x

Please check if that fixes your problem

**Comment by outsideMyBox** [comment]
Oups, sorry about that. Yes, it solved the issue.
