### ISSUE TITLE
self-referencing arcs for custom layers

### ISSUE THREAD

**Issue by cyplas** [webanno/webanno#277]
As far as I understand, self-referencing arcs (to mark root-level dependencies, for example) are only available for the built in dependency annotation layer (https://groups.google.com/forum/#!msg/webanno-user/snIsIIR_aP0/K3QlPm-l7IoJ). It would be nice if this were possible for custom layers too.

**Comment by reckart** [comment]
Actually, for some reason it doesn't presently even work for dependencies anymore.

If I draw an arc from a POS tag to itself, nothing happens.

Tested on: WebAnno -- 3.0.0-SNAPSHOT (2016-05-12 20:43:29, build 57f8a1f6e93f77121d99a9dba77c1abae1c1453c)

**Comment by seyyaw** [comment]
Ok, it works but in strange way. Brat do not support drawing an arc to self, we **hack** this in such a way that if you draw an arc from the root to any gov and the label is **ROOT**, it will draw to itself.
![image](https://cloud.githubusercontent.com/assets/1056051/15404053/17c36374-1dfc-11e6-9dbf-66c8e265f545.png)

**Comment by cyplas** [comment]
Aha! Does this apply to WebAnno 3 only? And does/will it apply to custom layers too or only the built-in dependency layer?

**Comment by reckart** [comment]
I think we should try to change the brat JS code to support self-linking. Shouldn't be too difficult to do.

**Comment by reckart** [comment]
Well, so I think we resolved that this currently works as designed but a better interaction would be preferrable - in particular being actually able to draw self-referencing links by modifying the brat code. Changing this from a bug then to an enhancement.

**Comment by cyplas** [comment]
Hmm, I tried the ROOT workaround now with webanno-standalone-3.0.0-beta-5.jar, but it didn't work for me. I'm not sure if I have the wrong version or if I misunderstood the workaround. Could you please help? I tried like this: 

- import a custom span layer A and a custom relation layer B attached to A
- import and open document for annotation
- annotate layer A for tokens T1 and T2
- connect the two A annotations (it shows an arrow with (B) above it)
- type ROOT for the label field in the form on the right (the (B) gets replaced with ROOT, but the arrow remains intact)
- hmm, tried exporting to TSV 3, but relation still shows relation between T1 and T2

**Comment by reckart** [comment]
It only works for the built-in Dependency layer. Cf. https://github.com/webanno/webanno/blob/7b0928a5f4855d0f6d4004ce336d41a16c2eb416/webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/controller/ArcAdapter.java#L445

**Comment by reckart** [comment]
With the last commit, the special handling for the built-in dependency layer was remove and the ability to create looping arcs in general was added. I hope this doesn't cause lots of crazy situations with slots/chains. If that would be the case, we may have to further extend the brat type configuration with a flag indicating whether loops should be allowed for a given type or not.

**Comment by amir-zeldes** [comment]
This feature is great and I'm all for it being available, but it's also very easy to trigger by mistake: when double clicking on a markable, if your hand shakes a little, it is interpreted as a self link. The problem is that users don't notice, then just double click again to make their annotation, but there is now a self link above their node.

In many cases, e.g. coref and similar edges, self-links make no sense and should be forbidden, since they are by definition an error. I suggest to make an annotation layer-feature making self-links impossible for certain annotation layers (similar to other layer properties, like allowing stacking or limiting to sentence boundaries). This way we can completely remove this spurious error type from layers in which it doesn't make sense.

**Comment by reckart** [comment]
We need to check the JS code if this is something that can easily be added per layer or not.

I also had another idea to avoid the spurious self-linking which would not require this behavior to be configurable per layer: we could probably easily change the code such that self-linking only works when an additional key is pressed when dragging the arc starts. E.g. if you press SHIFT and drag, then the UI would allow to link to the source span. If SHIFT is not pressed, when it would only allow to link to other spans. I **think** this might be easier and faster to implement - but have again to check.

**Comment by amir-zeldes** [comment]
Either sounds fine by me

**Comment by reckart** [comment]
Creating a self-looping arc now requires pressing shift before starting to draw the arc and holding it until the mouse button is released.
