### ISSUE TITLE
Slot-feature support in TSV3 broken

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#285]
Slot-feature support in TSV3 broken:

```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoTsv3Writer.process(WebannoTsv3Writer.java:166)
	... 37 more
```

**Comment by reckart** [comment]
@seyyaw I would like to do another beta release before next week. Do you see any chance of fixing this before the next beta?

**Comment by seyyaw** [comment]
The test example is not useful. No header, no annotation.

> #FORMAT=WebAnno TSV 3
> 
> 
> #Text=This is a test .
> 1-1	0-4	This	
> 1-2	5-7	is	
> 1-3	8-9	a	
> 1-4	10-14	test	
> 1-5	15-16	.

**Comment by reckart** [comment]
As I said: the reference file is bogus. When the exception is fixed, then we get a file from the Tsv3Writer in the `target/test-output/WebAnnoTsv3ReaderWriterTest-testSimpleSlotFeature` folder. If we are happy with that, we use it as a reference file. But first the exception in the writer needs to be fixed.
