### ISSUE TITLE
Curation with RTL language

### ISSUE THREAD

**Issue by TFeige** [webanno/webanno#287]
Browser: Chromium Version 50.0.2661.102 Ubuntu 16.04 (64-bit)
WebAnno:  3.0.0-beta-4 (2016-05-26 10:45:55, build 5c588cbbd8eb26e5b8e10ec8df88e90cadc85e1b)

Today I tested the curation feature with an arabic text.  I had two annotators annotating one text differently. In the curation window, the annotation segment has the correct layout. But the two segments from annotator1 and annotator2 are LTR, not RTL. Thus resulting in a weird layout.
![curation-rtl](https://cloud.githubusercontent.com/assets/19265315/15669250/ac4d5816-271f-11e6-9468-dd258c016287.png)

Direction="rtl" is missing for the svg element.

Apart from that (or maybe not?) the differences regarding the annotation didn't result in a red sentence overview.

Edit: The bug is present in the correction feature as well. The "User: Suggestion" segment is LTR.

**Comment by reckart** [comment]
Good point - we need to add RTL support on the curation page as well (probably also on automation and correction...)

**Comment by reckart** [comment]
I don't know why the sentences list does not show... that seems like a separate bug.

**Comment by reckart** [comment]
@TFeige I made some fixes and added the RTL in curation. Could you privately mail me an export of the the project you were using here to check if your problem still occurs with my changes?

**Comment by reckart** [comment]
I loaded some data from the [Uppsala Persian Dependency Treebank](http://stp.lingfil.uu.se/~mojgan/UPDT.html) into WebAnno and looked at it in curation mode. Seems to be working now. 

![2016-06-04_14-43-45](https://cloud.githubusercontent.com/assets/1410238/15799631/045f16e8-2a63-11e6-8e7a-1828a7645040.png)
