### ISSUE TITLE
TSV3 writer fails with zero-span slot fillers

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#294]
TSV3 writer fails with zero-span slot fillers.

Test is implemented in `WebAnnoTsv3ReaderWriterTest.testZeroLengthSlotFeature2()`.

Stack

```
Caused by: java.lang.NullPointerException
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoTsv3Writer.setSpanAnnoPerFeature(WebannoTsv3Writer.java:577)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoTsv3Writer.setSpanAnnotation(WebannoTsv3Writer.java:316)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoTsv3Writer.process(WebannoTsv3Writer.java:140)
	... 37 more
```

**Comment by reckart** [comment]
@seyyaw Adding more simple TSV tests, I hit another exception. Mind, I'm no longer building my tests directly on tokens, but actually on "normal" span layers - so I hope not to be chasing stupid cases here. This test is a situation where e.g. a slot filler is annotated that is not realized in the text. It is my understanding that such cases can indeed happen and that is why we introduced zero-width annotations into WebAnno.

**Comment by seyyaw** [comment]
for TestZeroLengthSl;otFeature1 --> It means we annotate a balnk space.. very cornerish case.
I have added the file too anyways.,,,

**Comment by reckart** [comment]
We annotate a blank space? If that is the case, I made a mistake in the unit test. The zeroLength should be annotating spans of length 0, so not a space but "nothing".

**Comment by reckart** [comment]
And the "nothing" should be at the beginning of a token, at its end, or inside. We can presently not e.g. have zero-width annotations within areas of whitespace in WebAnno.

**Comment by reckart** [comment]
@seyyaw thanks for noting this. I indeed made a typo in the `testZeroLengthSlotFeature2` test (the `testZeroLengthSlotFeature1` looks correct to me). Fixed now, reference file updated, all green.
