### ISSUE TITLE
typo in error message

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#295]
There's a typo in "Unexpected error: This document is already closed. Ask your project manager to re-open it via the Montoring (sic!) page".

**Comment by aakashysharma** [comment]
@sholschneider Steps to reproduce?

The correct version only exist in AnnotationDetailEditorPanel.java: 538
_"This document is already closed. Please ask your project manager to re-open it via the Montoring page"_

**Comment by sholschneider** [comment]
I am using WebAnno -- 3.0.0-beta-4 (2016-05-26 10:45:55, build 5c588cbbd8eb26e5b8e10ec8df88e90cadc85e1b) on Chrome. The message ocurred after trying to annotate an already closed document.

**Comment by aakashysharma** [comment]
Ah I get it now. Pushing fix.
