### ISSUE TITLE
Problem with POS annotations not attached to tokens

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#298]
During a test, problems cropped up when starting to curate annotations with POS annotations that were found in the CAS but were attached to a Token but not otherwise part of the CAS - i.e. they do *not* appear as actual POS tags.

```
2016-06-07 14:48:01 ERROR [ajp-bio-127.0.0.1-18009-exec-9] [richard] (CasDoctor) - [AllAnnotationsIndexedCheck] Unindexed annotations: 2
2016-06-07 14:48:01 ERROR [ajp-bio-127.0.0.1-18009-exec-9] [richard] (CasDoctor) - [AllAnnotationsIndexedCheck] Non-index annotation [POS
   sofa: _InitialView
   begin: 0
   end: 11
   PosValue: "--"
] reachable through [Token
   sofa: _InitialView
   begin: 0
   end: 11
   parent: <null>
   lemma: <null>
   stem: <null>
   pos: POS
      sofa: _InitialView
      begin: 0
      end: 11
      PosValue: "--"
   morph: <null>
]
2016-06-07 14:48:01 ERROR [ajp-bio-127.0.0.1-18009-exec-9] [richard] (CasDoctor) - [AllAnnotationsIndexedCheck] Non-index annotation [POS
   sofa: _InitialView
   begin: 50
   end: 62
   PosValue: <null>
] reachable through [Token
   sofa: _InitialView
   begin: 50
   end: 62
   parent: <null>
   lemma: <null>
   stem: <null>
   pos: POS
      sofa: _InitialView
      begin: 50
      end: 62
      PosValue: <null>
   morph: <null>
]
```

**Maybe** the problem is somewhere in the curation code. My assumption:

* The Tokens are merged into the CAS of the CURATION_USER
* then POS annotations on these Tokens are not properly cleaned if the annotators do not agree on the POS annotations

**Comment by seyyaw** [comment]
How do you get the above? I expor/re-import the **Bloomington** project and test it my local installation. I caught no exceptions.

**Comment by reckart** [comment]
I am pretty sure that you should be able to reproduce this problem after adding the following to your settings.properties:

```
debug.showExceptionPage=true
debug.casDoctor.checks=AllAnnotationsIndexedCheck
debug.casDoctor.repairs=RemoveDanglingRelationsRepair
debug.casDoctor.fatal=true
```

**Comment by seyyaw** [comment]
Yes, this helps.

**Comment by seyyaw** [comment]
But the old  **MergedCas** should be manually deleted
