### ISSUE TITLE
 RTL, line breaks and Scrollbars

### ISSUE THREAD

**Issue by TFeige** [webanno/webanno#300]
I experienced another bug in an arabic document (doesn'nt matter if annotation or correction). If a large span annotation is made, a line break is averted. This results in scroll bars. But the scroll bars are designedfor LTR texts, thus resulting in non accessible text. See Screenshot
![scroll-bars](https://cloud.githubusercontent.com/assets/19265315/16035364/0eabbe56-3217-11e6-9c2e-721ce413ab93.png)

**Comment by reckart** [comment]
Thanks for reporting.

Btw. as a tip: you can change the width of the annotation detail sidebar in the *Settings* - if you work with very long annotations, you may want to have that a bit wider.

**Comment by TFeige** [comment]
Thank you! That is indeed helpful.

**Comment by reckart** [comment]
In RTL mode, all content in the annotation window is now shifted to the far right. Additionally, the horizontal scrollbar is sent to the far right. Scrolling is possible to the left. As in LTR mode, arcs that carry over into the next row are not drawn until the full extent, but rather to the width of the initial window size.
