### ISSUE TITLE
Monitoring page results in Internal Error when project size is zero

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#305]
A simple error when the project size is 0, and the user clicks "monitoring" page.

```
 ERROR [http-nio-8080-exec-2] [admin] (DefaultExceptionMapper) - Unexpected error occurred
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor 'public de.tudarmstadt.ukp.clarin.webanno.monitoring.page.MonitoringPage() throws org.apache.uima.UIMAException,java.io.IOException,java.lang.ClassNotFoundException'. An exception has been thrown during construction!

...

...

...

Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at de.tudarmstadt.ukp.clarin.webanno.monitoring.page.MonitoringPage.<init>(MonitoringPage.java:246)
        ... 85 more
```

**Comment by reckart** [comment]
@aakashysharma can you have a look at this one?

**Comment by aakashysharma** [comment]
@reckart What is meant by 'project size 0' here? 

Tested following on build 5c588cbbd8eb26e5b8e10ec8df88e90cadc85e1b

1. Created a new project and just gave name to it. 
2. Didn't add any documents or constraints. 
3. When I click on monitoring page, there's no such error!

![test305](https://cloud.githubusercontent.com/assets/1897100/16260602/7409d4c0-3868-11e6-9b49-576fbffc9088.png)

**Comment by reckart** [comment]
@aakashysharma check the code in the problematic line reported in the issue report. Maybe it provides a hint. Otherwise ask @GiantEnemyCrab ;)

**Comment by aakashysharma** [comment]
Ah ok. It happens if there are no project in WebAnno instance

` Project project = repository.listProjects().get(0); `

**Comment by GiantEnemyCrab** [comment]
Right, I can confirm that what I meant by "project size is 0" is when there is no project created.

**Comment by GiantEnemyCrab** [comment]
Thank you!!
