### ISSUE TITLE
Feature name starting with non-alphabets causes Annotation to crash

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#306]
Accidentally, I was able to create feature with name '1' & '2'.

However, while Annotating, it crashed giving me an error
"Invalid feature name "1".  Feature names must start with a letter and consist only of letters, digits, or underscores."

I believe that it must be stopped while creating features in project settings.

Steps to reproduce

1. Go to projects.
2. Select any project.
3. Add a new layer and then add a feature to it with name '1' or something which starts with a non-alphabet.
3. Click on save feature.
4. Go to home and open any document in that project to annotate.
5. Choose the layer to which you'd added feature with name '1'.

**Comment by reckart** [comment]
Yep, should be prohibited.

**Comment by aakashysharma** [comment]
Renaming feature doesn't resolve this. Also there's no way to delete feature.

_Invalid feature name "1". Feature names must start with a letter and consist only of letters, digits, or underscores._

**Comment by aakashysharma** [comment]
@reckart Could you confirm the requirement for feature name

It should only consist of alphanumeric characters and "_" with only letters in beginning. Is underscore "_" a strong requirement?

The current implementation seems to work in favor of removing all spaces and using that as *internal* name rather than display name.

**Comment by aakashysharma** [comment]
Also, this would require to move the check for certain feature names #255 after the whitespaces have been processed. In current build, I was able to create a feature with uiName = "  float Value" with internal name="floatValue" which shouldn't be allowed.

**Comment by reckart** [comment]
`floatValue` is a valid internal name and ` float value` is a valid UI name. The forbidden names in #255 apply to the internal names, not to the ui names. On first creation, a defined strategy of converting an invalid uiName into a valid internal name is permissable and currently being employed. The check for #255 must be applied after such a conversion procedure.
