### ISSUE TITLE
Using webanno to create an interactive sentence pair alignment visualization  

### ISSUE THREAD

**Issue by danyaljj** [webanno/webanno#311]
This is more like a question than issue: 

I have a machine learning software for aligning two sentences; there are two things I want: 

 1)  visualize the output of the alignments. How easy/hard do you think it is to connect the output of a program to your tool and visualize it (on the fly; like the use inputs two sentences, my program analyzes and outputs the alignments and then we visualize them)

 2) Let the users give feed back: let the users to add/delete some annotations, and use the new annotations for re-training/updating my learning system.

**Comment by danyaljj** [comment]
or maybe in a simpler language, what is an easy way to use your [`webanno-brat`](https://github.com/webanno/webanno/tree/master/webanno-brat) module to visualize the brat annotations?

**Comment by reckart** [comment]
If you are looking for pure visualization, better work with the brat visualization directly. The webanno-brat module quite tightly integrates with the rest of WebAnno. You could use the `visualize.js` file from WebAnno which contains some improvements compared to the one from brat, but also removed some functionality. The modifications are conspicuously marked in the code.

**Comment by danyaljj** [comment]
Thanks for clarification. 
Do you have a simple example usage of [visualize.js](https://github.com/webanno/webanno/blob/master/webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js)? 

There are many java functions in  [webanno-brat](https://github.com/webanno/webanno/tree/master/webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat).  How does it integrate with these java functions? Is it possible to make java calls to do the visualization?

**Comment by reckart** [comment]
No, we do not have any "how to program with WebAnno" material. Feel free to study the source code. As said before, the server-side part of the rendering is quite tightly integrated with the rest of WebAnno. It is in a sense extensible and modular, but for the purpose of extending WebAnno, not for the purpose of being itself used as a module separately from WebAnno.

**Comment by danyaljj** [comment]
got it thanks!

**Comment by reckart** [comment]
Btw. if you are looking for some simpler "sample" code of how to drive a brat visualization from Java, you could have a look at the DKPro Core brat module: https://github.com/dkpro/dkpro-core/issues/656
It will not give you an annotation tool with user interaction, document management, etc. but it shows how to can converter Java-based annotations (here UIMA-based) into the kind of JSON format that brat likes.

**Comment by reckart** [comment]
I am pretty sure that the DKPro Core brat module produces a slightly different JSON dialect than the one we use in WebAnno. DKPro Core still uses the original visualize.js from brat. Converting it to use the one from WebAnno could happen further down the road. If you want to annotate, you will also need other JS files from brat, e.g. visualize_ui.js, the annotate_*.js files, etc.
