### ISSUE TITLE
remote API to upload/download documents to project

### ISSUE THREAD

**Issue by dillonalaird** [webanno/webanno#312]
Background:
We have a feed of articles we want to tag that's updated regularly. Instead of manually downloading these articles and re-uploading them to the server we'd like to run a program to do this automatically.

Issue:
We need to be able to login with a remote user, access a specific project (ones the remote user has permissions for) and upload/download documents to that project.

**Comment by reckart** [comment]
I am planning on adding remote API calls for the following actions:

* list all projects that the user has access to - the list returned should include the project ID, project name, and a list of role the use has in the respective project
* delete a project that a user as admin role in
* import a new document into a project that a user has admin role in

**Comment by erikpetersonpb** [comment]
These new functions are very useful.  Thanks for adding them!  I'd like to experiment with active learning, and if I could use the API to download annotated/curated documents I could automate the process.

**Comment by reckart** [comment]
@erikpetersonpb Just keep on watching the issue for a moment. @anshul-tak will upgrade the implementation any time soon with more functions and an improved URL scheme.

**Comment by anshul-tak** [comment]
@erikpetersonpb I have committed new changes for new API calls with new schema. You can have a look. You can experiment with these functions now. Do let us know if you require some more functionality :)

**Comment by erikpetersonpb** [comment]
I look forward to testing out the new API calls as part of our annotation workflow.

**Comment by reckart** [comment]
@erikpetersonpb Will you run a build yourself or do you plan to wait for a build/beta?

**Comment by erikpetersonpb** [comment]
I've checked out the repository and have built the snapshot war file.  I'll be experimenting with that until the next build.

Thanks,
Erik

________________________________

**Comment by erikpetersonpb** [comment]
I'm testing using the latest build.  I am able to start WebAnno, and use the web interface to import an existing project and annotate documents.  I've made sure my user account has admin privileges for a particular project, confirmed the project id, and then I've tried to use the remove API, including getting a list of projects, the documents within a project, etc.  For example, I put the following in to get the list of documents for a project (after looking at the RemoteAPIController file:

http://erik:password@localhost:18080/webanno-webapp/api/projects/1/sourcedocs

Looking at the tomcat logs, this gives the error:

127.0.0.1 - - [19/Aug/2016:18:29:25 -0700] "GET /webanno-webapp/api/projects/1/sourcedocs HTTP/1.1" 404 -

Is there additional set up necessary to use the remote API beyond the regular set up for the web interface?  Anything else I should try?

Thanks.

**Comment by reckart** [comment]
You have set the system property `webanno.remote-api.enable` to `true` when starting WebAnno, e.g. by passing `-Dwebanno.remote-api.enable=true` as a command line parameter to Tomcat. After that, a new `ROLE_REMOTE` permission appears for selection in the user management. Add this role to your user.

**Comment by reckart** [comment]
Mind that the user retains that role even if it becomes invisible when you unset the system property again. So I'd recommend only playing with this on a testing instance, not on a production system.

**Comment by erikpetersonpb** [comment]
I've gotten the new API to work, mostly, and it is great so far.  Here are a few comments:

- When you upload a source file, it returns a JSON string with the new document id.  It would be useful if creating a new project also returned the id of the newly created project.  This saves a step of listing the projects and looking up the id in the list.
- The source code for the remote api uses the example url of 
http://USERNAME:PASSWORD@localhost:8080/webanno-webapp/api/projects  
though if WebAnno is set up as described in the instructions, the URL is 
http://USERNAME:PASSWORD@localhost:18080/webanno/api/projects
- When trying to get this list of annotators for a particular source document, it always returns the same single annotator name, no matter who the actual annotators are or if there are any at all.
- I get the following when I try to upload a source document.  Could I have missed setting the right permissions on a directory?

 Exception report</p><p><b>message</b> <u>article_01066.pre.xmi (Permission denied)</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>java.io.FileNotFoundException: article_01066.pre.xmi (Permission denied)
        java.io.FileOutputStream.open0(Native Method)
        java.io.FileOutputStream.open(FileOutputStream.java:270)
        java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:213)
        java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:162)
        org.apache.commons.fileupload.disk.DiskFileItem.write(DiskFileItem.java:417)        org.springframework.web.multipart.commons.CommonsMultipartFile.transferTo(CommonsMultipartFile.java:143)
 de.tudarmstadt.ukp.clarin.webanno.webapp.remoteapi.RemoteApiController.uploadDocumentFile(RemoteApiController.java:403)
        sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        java.lang.reflect.Method.invoke(Method.java:498)
 org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:817)
org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:731)
org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)

Thank you.

**Comment by reckart** [comment]
@erikpetersonpb Thanks for the extensive feedback. We're looking into it.

> The source code for the remote api uses the example url of http://USERNAME:PASSWORD@localhost:8080/webanno-webapp/api/projects
though if WebAnno is set up as described in the instructions, the URL is http://USERNAME:PASSWORD@localhost:18080/webanno/api/projects

The Javadoc says `To test when running in Eclipse...` and when running from Eclipse using a Tomcat through Eclipse WST/JST, the default for name of the context corresponds to the project name in Eclipse.

**Comment by reckart** [comment]
Moved the reported problems/requested features to new issues:

* #323
* #324
* #325

**Comment by erikpetersonpb** [comment]
Thank you for the clarification on the access url.
