### ISSUE TITLE
Bad character in visualizer.js may cause problems

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#314]
There is a non-standard Unicode space character in visualizer.js:

```
    	return t1 || t2 || t3 || t4 ||<HERE>t5;
```

That may cause problems with browsers trying to load and run the JS file.

**Comment by GiantEnemyCrab** [comment]
Thanks for fixing this.
I was encountering an issue where this was fine in Mac OSX, but not in CentOS.
In Chrome it looked like it was inserting a question mark character when I used Inspector.

Found out just now there was already a fix for this.

**Comment by reckart** [comment]
@GiantEnemyCrab I still don't understand why apparently only a few people were hit by this problem. E.g. I never stumbled over it.
