### ISSUE TITLE
Misleading error message when uploading malformed constraints

### ISSUE THREAD

**Issue by hterhors** [webanno/webanno#317]
Hi,

using the newest version from the master-branch,

I am not able to import my list of Constrains. 
Currently, there are about 7738 Constrains specified in the file.

If i click the "**Import**"-button i get the following error:

`413 Request Entity Too Large
`

Best regards,
Hendrik

**Comment by hterhors** [comment]
Fixed the problem. 
The issue was a syntax-error in the file.
 
The error message here is maybe a bit misleading?

Greetings,
Hendrik

**Comment by reckart** [comment]
@hterhors can you provide a snippet of the file with the syntax error so we have material for reproducing the problem.

@aakashysharma Is this something you can look into?

**Comment by aakashysharma** [comment]
@hterhors The error message seems to be generated by server not constraints parser which is misleading, I agree. However, when you say syntax error caused this, that's strange. Could you share the constraints file or provide more details about the syntax error?

@reckart I believe it has to do with file upload processing not constraints parser.

**Comment by hterhors** [comment]
> @hterhors can you provide a snippet of the file with the syntax error so we have material for reproducing the problem.

See attachment

> @hterhors The error message seems to be generated by server not constraints parser which is misleading, I agree. However, when you say syntax error caused this, that's strange. Could you share the constraints file or provide more details about the syntax error?

Yes. Maybe it is not a syntax error. I think you are right because I tried a different very-long file without syntax error but same result. 


[BUGGEDConstrains.txt](https://github.com/webanno/webanno/files/386074/BUGGEDConstrains.txt)

**Comment by aakashysharma** [comment]
413 errors occur when the request body is larger than the server is configured to allow. Here’s how you can fix it, depending on your web server:

**Apache**: Set the LimitRequestBody directive in either your httpd.conf file or a local .htaccess file. (http://stackoverflow.com/a/3719358/1688568)

[source](http://craftcms.stackexchange.com/questions/2328/413-request-entity-too-large-error-with-uploading-a-file)
