### ISSUE TITLE
New line in sentence should be exported as is

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#318]
Currently, the TSV export removes new lines during export and a sentence remain in a single sentence. In stead export the new line with the different start tag such as **#TextSUbSent**.

**Comment by seyyaw** [comment]
TSV3 export DONE: 
Example: Input sentence
```
This is
very good example
```
TSV3 Export

```
#FORMAT=WebAnno TSV 3


#Text=This is
#TextSUbSent=very good example
1-1	0-4	This	
1-2	5-7	is	
1-3	8-12	very	
1-4	13-17	good	
1-5	18-25	example	
```

**Comment by reckart** [comment]
IMHO special characters like newline should be escaped in the sentence representation as we also do it in tokens.

```
#Text=This is\nvery good example
```

Your solution looks... ugly/like a hack. A newline character does not introduce a "subsentence". I mean, what is that even?

@ChrisBieTUDA

**Comment by reckart** [comment]
If you consider keeping the sentence on multiple lines a better option for the sake of readability, then please at least start all the lines in the same way and using the same level of indentation, e.g. 

```
#Text=This is
#Text=very good example
```

**Comment by reckart** [comment]
Thanks :) Does the reader also require modifications to support this?

**Comment by seyyaw** [comment]
yes, I will update it

**Comment by reckart** [comment]
@seyyaw can you please push the latest changes for this issue?
