### ISSUE TITLE
Dropdown-menu with constrained tags not updated when stacking span annotations

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#319]
When stacking span annotations which contain constrained features, the dropdown-menu still shows tags that are suggested by the constraint of the previously chosen tag. 
I am using Webanno Testing (WebAnno -- 3.0.0-SNAPSHOT (2016-07-11 21:41:04, build 40bf35e3d1fae4c29b1d84e8bce738d1dde7c155)) with Chrome on Windows 8.1.

**Comment by reckart** [comment]
I'm not sure how to reproduce this. Can you provide exact instructions how to trigger this effect?

**Comment by reckart** [comment]
Deferring to 3.0.1 because user did not provide reproduction instructions so far.

**Comment by reckart** [comment]
Closing as a duplicate of #441.
