### ISSUE TITLE
Monitoring: Locking and unlocking documents very slow

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#322]
Locking and unlocking documents for users is very slow (>10 seconds per click). I am using WebAnno Testing 3.0.0-SNAPSHOT (2016-07-11 21:41:04, build 40bf35e3d1fae4c29b1d84e8bce738d1dde7c155) with Chrome on Windows 8.1.

**Comment by reckart** [comment]
Duplicate of #90.

**Comment by reckart** [comment]
Closing as being a duplicate.
