### ISSUE TITLE
Remote API should return project ID when project is created

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#325]
When you upload a source file, it returns a JSON string with the new document id. It would be useful if creating a new project also returned the id of the newly created project. This saves a step of listing the projects and looking up the id in the list.

**Comment by erikpetersonpb** [comment]
This works in my tests.  Thank you.

**Comment by reckart** [comment]
@erikpetersonpb I don't think that file is mandatory, is it? We used it to allow the uploader to store additional metadata with the project. Doing a quick scan of the code, it doesn't seem to be used anymore. I think we can just remove the remaining references to that file from the code. If you have need for such a file, I would suggest opening a new issue for it.
