### ISSUE TITLE
Curation: "Annotation"-frame shows annotations by annotator nr.1, not the merge

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#326]
I have some trouble with file "Sentiment DB/15_06_05_e01062015_05062015_predictions_dataset_tokenized_180.tsv". Using WebAnno 3.0.0-SNAPSHOT (2016-07-11 21:41:04, build 40bf35e3d1fae4c29b1d84e8bce738d1dde7c155) with Chrome on Windows 8.1, the annotation frame in the curation mode doesn't show the merge but the annotations done by the first annotator. I didn't have any problems with other files of the same project.

**Comment by sholschneider** [comment]
It occurred again. I am using WebAnno -- 3.0.0-SNAPSHOT (2016-10-09 13:33:23, build 7af062679c8da06eafdb4cf41bfb151c48629e21) with Chrome on Windows 8.1. 
![notamerge](https://cloud.githubusercontent.com/assets/13764947/19872595/ec6e4c7a-9fba-11e6-8594-986bf4157ecc.PNG)

**Comment by sholschneider** [comment]
...and it occurred again with file 15_05_21_e_2005025_21050215_classified_001.tsv of the same project. I did open the file in the curation view before both of the annotators finished the file. Could this have something to do with the described error?

**Comment by reckart** [comment]
Looking at the version of WebAnno that you are using, I suspect there may be corrupt data files. I would recommend you work with the latest beta-version which automatically performs sanity checks on the data.

**Comment by reckart** [comment]
Haven't heard anything about this for a long time. I assume it has meanwhile be fixed or was due to inconsistent data.
