### ISSUE TITLE
Extend remote API to allow access to curated documents

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#327]
Extend remote API to allow access to curated documents.

The `listAnnotationDocument` can additionally list the `CURATION_USER` (cf. de.tudarmstadt.ukp.clarin.webanno.api.WebAnnoConst.CURATION_USER) if the authenticated user has PermissionLevel.CURATOR or PermissionLevel.ADMIN in the respective project.

Likewise, the `getAnnotationDocument` can additionally allow downloading the annotations from the `CURATION_USER` for CURATOR and ADMIN users.

**Comment by reckart** [comment]
@anshul-tak @erikpetersonpb

When we currently get information about the state of annotation documents, we get no information about the state of curation. Also, we do not have any way of downloading the curated document.

Unlike for annotation documents, there is no explicit database entry for curated documents. To check the state of curation, we need to check the state of the `SourceDocument`, not of the `AnnotationDocument`. To get the data for the curated document, we have to use `RepositoryService.readCurationCas(SourceDocument)`.

The `CURATION_USER` is not an actual user in the database - it is just a name under which we store the annotations on disk. However, `RemoteApiController.getAnnotationDocument(...)` currently checks if the `annotatorName` is a user in the database.

We could change the `getAnnotationDocument` in such a way that it does a special handling of the `CURATION_USER`... or we could introduce a new `getCurationDocument` call specifically to get the curation document. Reviewing the situation, I kind of tend towards the latter.

In order to tell if a document has been curated or not, I think we should extend the `showSourceDocuments` call such that it also returns the state of each source document.

**Comment by anshul-tak** [comment]
@reckart 
Currently, `showSourceDocuments` returns "sourceDocName:id". Can you tell me the format of the returned JSON string? 

Yes creating a new call is better option. What should be the permission of this new call `PermissionLevel.CURATOR` || `PermissionLevel.ADMIN` or just `PermissionLevel.CURATOR` ? Also, is curated document always stored in CAS format and should always be downloaded with the same format?

**Comment by reckart** [comment]
I guess something like this:

```
[
{ id: 10, name: "<sourceDocumentName", state: "<sourceDocumentState>" },
{ id: 12, name: "<sourceDocumentName", state: "<sourceDocumentState>" },
...
]
```

Access for `PermissionLevel.ADMIN` - as far as I remember, we had discussed that all the Remote API calls should be limited to users that hat `ADMIN` permissions on the respective projects. The only exception is the call that creates new projects, which is should be bound to the global role `ROLE_PROJECT_CREATOR`.

**Comment by anshul-tak** [comment]
Okay, I will make these changes.

**Comment by anshul-tak** [comment]
@reckart Can you tell me about the format of the exported curated document. Should it also has option of `?format=[FORMAT]` like we have in our `getAnnotationDocument` like "format=text". For annotation document we have `exportAnnotationDocument` in `RepositoryServiceDbData.java`. However, we do not have any method for curated document. Do you want me to create a method similar to `exportAnnotationDocument` for curated document or should I restrict to download in XMI format.

We have method to `RepositoryService.readCurationCas(SourceDocument)` but it will return a CAS which could be serialized for xmi. If we want other formats we need to run pipeline like in `exportAnnotationDocument`.

**Comment by reckart** [comment]
I think you can simply call `exportAnnotationDocument` and pass WebAnnoConst.CURATION_USER as the user argument. Try it.

**Comment by anshul-tak** [comment]
@reckart yeah it worked :) I will soon commit it.

**Comment by erikpetersonpb** [comment]
It works for me.
