### ISSUE TITLE
Rendering glitch after first opening a document after login

### ISSUE THREAD

**Issue by amir-zeldes** [webanno/webanno#333]
The first time I edit a document after importing from a WebAnno 2 xmi file in V3.0.0 beta 6, the span offsets are incorrect, overflowing to the right (see image). As soon as I edit any annotation, the spans snap back to the token boundaries and the effect disappears permanently. Deleting and reimporting the document allows the effect to be reproduced.

![capture](https://cloud.githubusercontent.com/assets/2188635/18415208/235f8d1e-77b8-11e6-9ba8-729470cbe11c.PNG)

**Comment by reckart** [comment]
Hm, interesting. So what you are saying is that this somehow relates to opening a document for the first time. We need to check:

* is this the first time a user opens a document (i.e. when it is converted from source format to internal storage)
* is this the first time a user opens a document after restarting the browser
* is this the first time a user opens a document after logging in
* is this the first time a user opens a document after restarting the server

**Comment by amir-zeldes** [comment]
I just tested this - it seems to be option 2: restarting the browser and logging in will reproduce the effect. 

  * Editing any document fixes it, including one that has no spans yet, and then switching to a document with spans doesn't exhibit the effect. 
  * Logging out and in again doesn't suspend the fix - on the second login it's still fixed. 

Only restarting the browser then going into a document with spans for the first time makes this happen again, and it's gone from the first edit until the next browser restart.

**Comment by reckart** [comment]
I feel it might be due to some race condition and browser internal caching of font metrics or something like this. My first idea would be to try fixing it be delaying the rendering for a few microseconds after loading the page.... have to try it out.

**Comment by amir-zeldes** [comment]
OK, this is not a critical bug IMO though, it's just a minor distraction and disappears very quickly.

**Comment by reckart** [comment]
I also see this effect sometimes after logging out/in again.

Curiously for me this seems somehow linked to #331. When the glitch appears, then the page does not scroll up when an element is selected. When the glitch does not appear, the view jumps. Argl...

**Comment by reckart** [comment]
I also see this effect quite a bit simply going through the home screen (i.e. clicking home in the annotation screen, then entering the annotation mode again, and opening the document again).

**Comment by reckart** [comment]
It seems that removing all the font-related stuff (per #337) fixes this issue as well... just leaving this open a little more for additional testing.

**Comment by reckart** [comment]
Seems ok now for me in Firefox, Safari and Chrome.
