### ISSUE TITLE
single annotator?

### ISSUE THREAD

**Issue by asher-stern** [webanno/webanno#334]
Hi.
Is it possible to use WebAnno for annotating documents by a single annotator?
I see that if documents were annotated only by a single annotator, their annotations are not exported. Can this behavior be changed?

Thanks in advance.

**Comment by seyyaw** [comment]
Yes it is possible. What do you mean by their annotations are not exported? Is that from the annotation page or when you export the whole project? In the annotation page, click export icon, 
![image](https://cloud.githubusercontent.com/assets/1056051/18458301/3a83b732-7960-11e6-8355-5a83756b21de.png) and choose the export format.

**Comment by asher-stern** [comment]
Hi.
Thanks for the answer.
Yes, I mean when exporting the whole project.
I see that I can export annotations from the annotation page, but this has to be done separately for each document.
What I need is actually exporting the whole project (i.e., all the annotated documents) and this, if I understand correctly, cannot be done.

Thanks.

**Comment by reckart** [comment]
@asher-stern I guess you have two options.

1. mark the document as "done" in the annotation view. Then go to the curator view and mark it as "done" there as well. After that, it should be included in the export of the curated documents
2. export the whole project *not* using the "export curated" but the other button. In the ZIP file, you should be able to find the per-user annotations

**Comment by reckart** [comment]
I guess there is a third option:

3. mark the documents as done in the monitoring view in the annotator column and in the curation column and then export the curated docuemtns

**Comment by asher-stern** [comment]
@reckart Thanks for you answers.
Unfortunately, none of the options worked for me.

1. In curator view - only documents that were annotated by two annotators appear in the menu of the curator view. So I cannot mark the document as "done", since it does not appear there at all.

2. Exporting: Both ZIP files do not contain a document that was not annotated by two annotators. (I tried the two buttons).

3. In monitoring view, when I try to click on the icon in "curation" column of a document that was not annotated by two annotators I get a message-box: "the state can only be changed explicitly by the curator".

I am using the JAR file: webanno-standalone-2.3.1.jar

**Comment by reckart** [comment]
@asher-stern 

1. ok, that kind of makes sense... but might still be worth changing that behavior in WebAnno
2. the [WebAnno user manual](https://webanno.github.io/webanno/releases/2.3.1/docs/user-guide.html#_export_2) explains the structure of the project export ZIP. Are you not seeing any folder called `annotation` when you extract the ZIP? Below it, you should find a folder for each document and inside these the annotations for each user.
3. that looks like there are one or more bugs in the code.

**Comment by asher-stern** [comment]
@reckart 

Regarding 2:
I find a folder called "annotation" and below it I find a folder for each document that was annotated by two annotators. But no folder for documents that were annotated by a single annotator (even though they were marked "done" by that annotator.

**Comment by reckart** [comment]
@asher-stern do you see and files for these documents in the `annotation_ser` folder?

**Comment by reckart** [comment]
@asher-stern it might help me if you could export the whole project and send it to my privately to have a look. I believe you have may mail address.

**Comment by asher-stern** [comment]
@reckart `annotation_ser` contains only documents that were annotated by two annotators.

**Comment by asher-stern** [comment]
@reckart I'll try to send it.

**Comment by reckart** [comment]
@asher-stern thanks. Looking at the package, I suspect that the problem might be that annotations from a user that has only the "admin" role an no "user" role *within* a project might not be included in the export.

**Comment by reckart** [comment]
Looking at the code confirms my suspicion. During export, we include only annotations for users that have the `user` (annotator) in a project. 

Project `admin` users can create annotations and they can perform curation, but unless they also have the `user` permission level, their annotations do not export and neither do they show up in the monitoring view. 

It might be the time to re-think the admin permission. I think we should do two things:

* the project creator should not only get the `admin` permission, but also the `user` and `curator` permissions
* disable the ability for pure `admin` users to create annotations and perform curation and instead bind these actions exclusively to the `user` and `curator` permissions.

**Comment by asher-stern** [comment]
Hi.
Indeed. Adding "user" permission to "admin" user makes its annotations get exported.
Bottom line it seems that I will be able to use WebAnno for annotating documents by a single annotator.

Many thanks.

**Comment by reckart** [comment]
Changing the default permissions continues being tracked here: #340.

Closing this issue as the problem was resolved.
