### ISSUE TITLE
WebAnno for Entity Linking

### ISSUE THREAD

**Issue by tgalery** [webanno/webanno#335]
Hi there, I was considering using webanno as an entity linking framework, so users can click on a portion of the text and annotate it with the corresponding wikipedia id for that word. Given that there are millions of entries this would be an annotation layer very different from named entity recognition.

If I wanted to do that with webanno, would I need to write a custom class / layer for it or is this functionality supported out of the box ?

**Comment by seyyaw** [comment]
@tgalery I would go with a custom layer for the wikipedia id. You can then import the entries as a Tagset or allow user to type the ID.  But I am not sure how it will look like with a million entries (a dropdown with a million entries....)

**Comment by reckart** [comment]
A tagset with a million entries would certainly not go well. Mind that we presently load the full tagset into the dropdown when the side panel is rendered. Such a large tagset would require *at least* that the dropdown be filled dynamically with a limited set of tags, e.g. the first 100 that match the string entered into the dropdown.

**Comment by tgalery** [comment]
@seyyaw @reckart to be honest, I don't want to fully load the tagset. My idea was basically to send an http request after the span is selected to either the wikipedia or wikidata apis. This in turn would return the top n matching results for that query, so the user can select which identifier is the right one to be used. In effect, this would mimic the 'normalisation' feature of Bart 1.3 (which is broken and doesn't work well). So I guess the question would be better phrased like:

1 - Could I perform such http requests as part of a Custom Layer design ?
2 - Would there be interests from the webanno community to have such a tool (I know that it exists from the Entity Linking community, but all the solutions so far don't benefit from Webanno's integration with Mechanical Turk / Crowd Flower) ?

**Comment by seyyaw** [comment]
@tgalery I already got the same request today at [KONVENS 2016](https://www.linguistics.rub.de/konvens16/). We do not support such type of annotation yet. But I think it is doable and a nice addition to WebAnno (3+). What do you think @reckart and @ChrisBieTUDA ?

**Comment by reckart** [comment]
Technically it can be done with some investment of work. @tgalery are you suggesting that you implement this feature and contribute it to WebAnno?

**Comment by reckart** [comment]
Mind that CrowdFlower integration is a completely separate thing. I'm not even sure if it still works.

**Comment by tgalery** [comment]
I'm usually pro of unification (for maintainability's sake). Ideally, I could develop this as a feature. There are other people related to DBPedia that might be interested in this as well. But I just wanted to know how feasible it is (I don't know the class domain that well). Could you give me a rough idea on what this would entail (e.g. extend from Class x, change class Y, etc ...). 
I'm not that fussed about CrowdFlower per se, but having some way to get /pay people for annotations would be cool. Is the Mechanical Turk integration working ? Or any other integrations planned down the pipeline ?

**Comment by reckart** [comment]
I don't think we ever had MT integration and I am not aware of anything planned atm in this direction.

There are various way in which this entity linking feature could be implemented. Pointing out the classes and the necessary changes (and deciding on a strategy) is already a good deal of the work and takes some time. It is nothing done in 5 minutes. From a birds-eye view, the following areas probably need to be touched in one way or the other:

* project settings (feature configuration)
* annotation UI feature editor

**Comment by tgalery** [comment]
Cool, will look at it and have a think. Thanks for the help!

**Comment by reckart** [comment]
Regarding entity linking: the [INCEpTION text annotation platform](https://inception-project.github.io) provides this capability and it is largely compatible with WebAnno. WebAnno itself is mainly in maintenance mode, so this feature most likely won't be added or back-ported from INCEpTION. Thus, I am marking this issue as **won't fix** and would ask anybody looking here to have a look at INCEpTION instead.
