### ISSUE TITLE
Unable to select dependency relation when selected layer is named entity and "remember layer" is enabled

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#345]
Unable to select an existing dependency relation when selected layer is named entity and "remember layer" is enabled. The error message "Unexpected error: No relation annotation allowed on the selected span layer" is displayed.

Expected: just open the dependency relation in the detail panel - not try creating any new annotation.

**Comment by seyyaw** [comment]
@reckart I can not repro
![345](https://cloud.githubusercontent.com/assets/1056051/18808038/b9da21d8-8257-11e6-9ebd-bc62d0c7b891.gif)

**Comment by reckart** [comment]
Actually, with the latest changes in the code, I cannot even create any dependency relation anymore. I always get the message "Layer do not support arc annotation." now... have to look more into it...

**Comment by reckart** [comment]
Fixed along with #346 (hopefully...)

**Comment by reckart** [comment]
"Layer do not support arc annotation" now (still) displayed when "remember layer" is turned off...

**Comment by reckart** [comment]
Now selection of relations no longer updates the detail panel... *sigh*...

**Comment by reckart** [comment]
Ok... cleaned up the code, removed redundancies (and thus potential for bugs...)... did play around with annotations (creating, deleting, editing, etc.)... looks good so far, but leaving open for further testing.
