### ISSUE TITLE
Switching from closed to open documents

### ISSUE THREAD

**Issue by TFeige** [webanno/webanno#349]
Version: 3.0 beta6 build 2cbe5c0c7adf8c84bb171853f4c0d6f4464d24a4
If I open a closed document (Workflow: Done), and then click on the Button "next" to open the next document, the system doesn't permit to change annotations, although the status of the new document is "open".

It is possible to create new ones, but not to change their values nor delete annotations.
![next](https://cloud.githubusercontent.com/assets/19265315/18834151/a35d8906-83f4-11e6-994e-7a97ffc8d105.png)

I experienced this behaviour in Annotation and Automation mode.

**Comment by reckart** [comment]
Interestingly seems to happen only when opening a closed document. Does *not* seem to happen when closing an open document and then switching to another open document...

**Comment by reckart** [comment]
Fixing bug by removing code ;)
