### ISSUE TITLE
Load plain text as one-sentence-per-line

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#350]
Load plain text as one-sentence-per-line which is linguistically wrong but makes more sense for sentences with ASCII formatting. This should be considered just as a temporary solution until (someday) the WebAnno rendering code could be changed to switch between sentence-oriented and line-oriented rendering...

**Comment by GiantEnemyCrab** [comment]
Thanks for the change, and I also vote up for being able to choose line-oriented.

It might not be linguistically correct, but line-based is a compromise for free-form text that is not formatted well to begin with, especially seen widely in medical records. For this kind of text, it is challenging enough to have a good sentence segmentation model. (And behaviors may change depending on model versions of sentence segmentation). So, line-based option should exist.

**Comment by reckart** [comment]
Unfortunately, going for line-based rendering is a major code change. Might be worth doing at some point, but certainly not close to a major release.
