### ISSUE TITLE
Showing x of y documents feature

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#357]
WebAnno currently shows "showing x of y sentences" in the top right UI.

It would be great to have "showing x of y documents", as well.

The reason is more for keeping track of the progress for where I am at the project level.

**Comment by seyyaw** [comment]
This is an easy fix. But it should not be considered as indicator of progress, just index of the document

**Comment by GiantEnemyCrab** [comment]
Yes, I agree. Index should do, and users can interpret the index of the documents however they need to.
