### ISSUE TITLE
Time stamp formatting

### ISSUE THREAD

**Issue by erikpetersonpb** [webanno/webanno#364]
Original line:

SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-DD'T'hh:mm:ssZ");

The timestamp formatting in SimpleDateFormat in listAnnotationDocument in RemoteApiController.java uses 'DD' which gives the day in the year.  I think more useful would be 'dd' which is day of the month.  Also, for the time it uses 'hh' which is "Hour in am/pm (1-12)".  Since an am/pm marker is not included in the formatting, I think more useful would be 'HH' which is "Hour in day (0-23)"

My proposed change is 

SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd'T'HH:mm:ssZ");

**Comment by reckart** [comment]
Thanks. I also removed the manual override of the timezone... I think this is not required or possible even wrong.
