### ISSUE TITLE
No sentence-splitter

### ISSUE THREAD

**Issue by asher-stern** [webanno/webanno#370]
Hi.
Is it possible to use WebAnno without sentence splitting?
What I would like it to do is to display the document as is, without sentence splitting, where the document is split into lines exactly as they are in the original text (not by sentences).
Is it possible?

Perhaps replacing the default sentence-splitter by a tool that annotates "sentences" just by splitting the text according to newline (\n) characters?

**Comment by reckart** [comment]
That was implemented as https://github.com/webanno/webanno/issues/350

Duplicates https://github.com/webanno/webanno/issues/350
