### ISSUE TITLE
 Wrong tagset showing up with feature

### ISSUE THREAD

**Issue by katiePitchBook** [webanno/webanno#371]
Here's a screenshot of the admin for the feature, layer, and the associated tagset.  As you can see the Company ID feature is associated with the Company ID tagset. 
![2016-10-06_11-17-15](https://cloud.githubusercontent.com/assets/15332740/19164875/87739edc-8bb6-11e6-9d60-2eea5cdade38.jpg)

However, when annotating, the wrong associated tagset is sometimes showing up for a feature.  In the screenshot below, you can see that the date tagsets are showing up with the company id features.
![2016-10-06_11-09-15](https://cloud.githubusercontent.com/assets/15332740/19164772/3448c84a-8bb6-11e6-8770-8c9c12a66e05.jpg)

**Comment by erikpetersonpb** [comment]
This seems to have been introduced recently as older builds didn't have this issue.

**Comment by reckart** [comment]
@katiePitchBook unfortunately, your screenshot does not include the status line of WebAnno at the bottom of the browser window which includes version and build information. Can you please copy/paste it here?

**Comment by reckart** [comment]
@katiePitchBook is there any reliable way in which you can trigger this bug? Is there anything you can do to make WebAnno return to the normal behavior (e.g. reload page with F5)?

**Comment by reckart** [comment]
I think I have been able to reproduce the issue and hope to have fixed it in the latest commit (see above).

**Comment by reckart** [comment]
@katiePitchBook I interpret the thumbs up as a sign that the fix worked, so I'm closing the issue. Please leave a comment if the problem reappears.
