### ISSUE TITLE
Document-level tagsets

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#379]
I am interested in having a tagset or tagsets on the document level. For example, annotation tasks for classifying the documents into "politics", "finance", "sports", "technology".

There are work-arounds for this but would be great to this feature.

**Comment by kazukisan** [comment]
Noting that zero-width annotation at the top of document could be a decent substitute for this feature request.

**Comment by nipunsadvilkar** [comment]
Hey @kazukisan, What is the workaround you are mentioning in the first comment? How would one go about setting up document level annotation? Some insights from you would be very helpful

**Comment by seyyaw** [comment]
@kazukisan We are working on document level annotation enhancement in WebAnno - codebook based annotation. If you are interested in a test, let me know. But it is not in the public WebAnno branches yet.

**Comment by reckart** [comment]
Superseded by #923
