### ISSUE TITLE
Long span-annotations and sentences result in Browsercrash

### ISSUE THREAD

**Issue by TFeige** [webanno/webanno#380]
Webanno 3- beta6 build 2cbe5c0c7adf8c84bb171853f4c0d6f4464d24a4 on Chromium 53.0.2785.143

I have one document, that consists of only one sentence (in classical arabic, sentences are often not ended with punctuation marks).

By clicking multiple times on "Wait" – to not terminate the script – I was finally able to access the Settings and disable some Layers. That helped.

So the problem refers to multiple enabled annotation (layers?).

With beta5 the problem didn't exist.

**Comment by reckart** [comment]
Can you send me the project?

**Comment by reckart** [comment]
Thanks for the project. I'll have a look.

**Comment by reckart** [comment]
The RTL rendering code was very inefficient. In your case, there was a very long span with a large number of overlapping spans on top of it. The calculation of metrics is now improved and dramatically speeds up that case.

**Comment by reckart** [comment]
@TFeige did you already have the chance to try a recent build with this fix included?

**Comment by TFeige** [comment]
No, but I will check it later today.

**Comment by TFeige** [comment]
I just checked with build ebf51bbd12475e15e6fa8f93488dbcb3ee21f0a5 in standalone version.

The text was displayed really fast. But unfortunately it is not usable, because the page gets reloaded (on chromium) every ~8seconds.
Using Firefox the case gets even worse. The text is shown for one second, then the page reloads while showing white content and using 100% CPU.

**Comment by reckart** [comment]
Hm. I locally tested with Chrome and Safari. Are you using the same test project that you sent me before?

**Comment by TFeige** [comment]
Yes. It is the same project. I will test it on another machine.

**Comment by TFeige** [comment]
I narrowed it down to the standalone version and the auto-logout feature. The Counter is always at 00:00. Running the latest snapshot with tomcat, the bug is resolved.

**Comment by reckart** [comment]
Ok, I didn't test the auto-logout with the standalone... so that's a new issue then.
