### ISSUE TITLE
Combining spans and chains in relation layer??

### ISSUE THREAD

**Issue by Ratatam123** [webanno/webanno#381]
Hi,
I have an use case (Annotations for Opinion Mining: targets and opinions (=>many times discontinuous strings)), for which it would be useful to combine span and chain annotations in a relation layer. Do you think you can add this feature for the upcoming 3.0 release?

**Comment by reckart** [comment]
What do you mean by "combining"?

**Comment by Ratatam123** [comment]
Being able annotate that they relate to each other (idea of the relation layer). I understood that one can only connect spans via a relation layer.

**Comment by Ratatam123** [comment]
*to

**Comment by reckart** [comment]
Yes, you can only connect spans via relations. However, a chain layer consists of spans *and* links between the spans. Would simply using a chain layer not be sufficient for your case?

**Comment by Ratatam123** [comment]
Hm, in my case, some constructs that pose as one unit in my task and which i want to relate to other units are interrupted by other/irrelevant words. I'll try to find a way around it..

**Comment by reckart** [comment]
I am not sure what kind of problems we would run into if we allowed relations to connect to chain layers or if we allowed slot features to point to elements in a chain. I agree, it sounds like a good idea, but I'm afraid lots of things may break - so I don't see that coming for 3.0.0...

**Comment by Ratatam123** [comment]
ok, np

**Comment by reckart** [comment]
You can probably use the new *slot features* feature in WebAnno 3 to model this, but it will take quite a few more clicks for the annotator than the idea of using a chain layer.
