### ISSUE TITLE
Configuration of colors per tag value

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#383]
This is a feature that existed in BRAT, so it would be great to have color configurable per tag value.

**Comment by reckart** [comment]
What happens to tags where you don't explicitly set a colot?

**Comment by GiantEnemyCrab** [comment]
By default, the colors should be automatically assigned from the colorStrategy code.
Therefore, all tag values will have some colors assigned in the settings UI. So, all the colors will be shown.

Project managers can then change the colors as they wish.

Note that this idea will require some changes in the project settings UI, so that color selection can be done adjacent to each tag value. (Also, this would require an additional column in MySQL for colors)

How does it sound?

**Comment by reckart** [comment]
The ColoringStrategy is currently applied dynamically, i.e. when the annotations are rendered. That means, the color assignments can easily change e.g. when the set of visible layers is changed through the "settings" dialog in the action bar (at least in "one color per layer mode").

I assume that your suggestion would only apply in "one color per tag" mode. I would tend towards not statically pre-assigning colors to tags and allow leaving the color selection empty. If the selection is empty, then I would propose using the `labelHashBasedColor` strategy. If a color value is set, then this color should be used instead.

The tagset descriptions (at least the JSON format) would then have to be extended with a new field for the color. And as you pointed out, the UI would have in incorpora a new text field for the color code (or maybe even a color chooser widget) and the DB would need an additional column. 

One of the reasons why I would like to allow the color field to be empty is, that then the DB column can be nullable. If we would make the DB column non-null, then it would require implementing migration code that fills in sensible values for all tags that have no color during upgrade. I would like to avoid that.

**Comment by GiantEnemyCrab** [comment]
Thanks for the comment!

Originally, this request comes from another engineer who tried to configure an annotation project and noticed that same colors were used for some of the tags.

For example, both tag values of "drug" and "disease_disorder" had the same purple color. Also, both "diagnostic_test" and "response_term" has the same orange color. There are total of 8 tags in this tag set.

Actually, as long as the automatic coloring can result in these colors being different / unique, it would suffice the requirement here, without introducing complicated color configuration.

This may mean we can close this issue and open a new issue that is more specific to how auto-coloring is done and how it can be more unique per tag value, etc. Let me know how this sounds.

**Comment by reckart** [comment]
I believe the manual assignment is probably a good idea to address your need.

But if you have separate ideas for improving the ColoringStrategy (in particular `labelHashBasedColor`), feel free to open another issue. Mind that currently we use static palettes in ColoringStrategy that were generated for a reasonable contrast. Apparently the human brain requires a certain contrast between colors to work with them easily, which puts a natural limit on the number of colors that can be in a sensible palette. The current palette contains 12 colors. Probably this could be pushed a bit. Additionally, the brat JS code renders some things (e.g. arcs) in a lighter tone, so for these types of visual elements/layers, the palette is further filtered down to avoid colors becoming too light. Something that would be rather easy to do (I think) is to allow the instance administrator to specify custom palettes in the settings.properties files... anyway, that would also be a separate issue.

**Comment by GiantEnemyCrab** [comment]
Thanks. I will first experiment with labelHashBasedColor a bit and see what happens. 

And yes, ultimately, manual assignment would be nice to have, with some logic that handles null / empty value colors in DB gracefully.

For arc colors, I have seen something as crazy as light red color font surrounded by orange selection color or the arc, which made it almost impossible to read. This may be an interesting side-effect of the current palette.

**Comment by seyyaw** [comment]
+1 for manual color assignment, may be with a color chooser palette.

**Comment by reckart** [comment]
There is another problem/question: what happens when there are multiple features with tagsets defined on a layer?

**Comment by GiantEnemyCrab** [comment]
I am imaging a project settings UI, where administrators will be able to choose a color from color chooser palette per tag value row. So, this should naturally scale to be compatible with multiple tagsets on a layer. 

So, if I have multiple tagsets, for example, "drug type", and if I have 4 tag values, I could assign blue, orange, green, yellow, etc. I would then have "drug strength" tagsets and tag values are just "strong" and "weak". I could assign brown and pink colors for these two.

But I may not have understood your question, actually. So let me know.

**Comment by reckart** [comment]
If there are multiple featured on a layer then we show all of the feature values in the bubble above the text separated by a pipe symbol. Now if a layer gas two features both with a tagset and the user selects a green tag for one feature and a red tag for the other feature... What will be the color of the bubble? Green? Red?  The RBG sum of the two?

**Comment by reckart** [comment]
I see two options:

* if there are multiple features with tagsets, then coloring falls back to hash-based
* we introduce an additional setting on the layer which indicates which feature should be use to define the color

**Comment by reckart** [comment]
Closing - superseded by #1603.
