### ISSUE TITLE
Automatic sign off from WebAnno after session expiration

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#384]
When the session expires, WebAnno should automatically sign off users and send it to home screen.

I am experiencing that WebAnno stays open (even after session has expired on the server side), and if I take any action, then it finally signs me off, sending to home screen.

This is more for security reasons. There may be documents that contain sensitive data, and as an extra  cautious approach, WebAnno should automatically redirect to the home page. This is similar to these bank websites that send users to home login screen after checking account page stays open for a while without any action being done on the website.

I am not sure if "session" is technically the correct terminology in this context. But it is the logic that handles sign-off.

**Comment by reckart** [comment]
I have added a countdown on the browser-side that triggers a page reload (a few seconds) after the configured server-side session timeout has expired. It only reloads the current page, but that effectively redirects to the login page.

**Comment by GiantEnemyCrab** [comment]
Thank you for the change, confirmed that it is working

**Comment by reckart** [comment]
@TFeige reports in #380 that auto-logout has problems in the standalone version: the counter is always at 0:00. Need to check this.

**Comment by reckart** [comment]
Looks like in Winstone, the default session timeout is 0. In this case, just don't display the timer.
