### ISSUE TITLE
Confusion over annotation_feature "name" column

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#385]
It happens that a colleague of mine misspelt "NamedEntities" as "NamedEntites" on the initial tagset creation. He then corrected this in the project settings UI.

Later, he created xmi file, which is pre-annotated with some values for the custom NamedEntities tagset. But it didn't work during import. The reason is that annotation_feature table, which the Java code refers to, still kept the misspelt version as "NamedEntites". So, the spell-corrected "NamedEntities" in xmi did not work.

He found out that by writing the misspelt version in xmi, the document import worked fine.

What is happening is the once webanno users change the feature name in the UI, the change gets reflected in the uiName field of the DB, but the original value of the feature name is kept, which makes it confusing for users. 

This problem also happens when writing constraints. The java code refers to the "name" field in annotation_feature, but people who are writing constraints would normally only see the "uiName", without knowing what the original values were for those.

I am not sure what would a good solution for this.

One least-costly way, I imagine, would be to show this original value stored in DB, somewhere in the project settings UI.

**Comment by reckart** [comment]
I have added a display for the "internal name" also for features now. It is also important for people that want to build constraint rules.

**Comment by GiantEnemyCrab** [comment]
Thanks, showing the internal name sounds good. The only other thing is to add this feature info into the help section when releasing official 3.0.0, so that users know what this can be used for.

**Comment by reckart** [comment]
Added a note to the docs, although I didn't update the screenshots.

**Comment by GiantEnemyCrab** [comment]
Thank you for the change, confirmed that it is working
