### ISSUE TITLE
Importing Projects, but Tagset is not saved

### ISSUE THREAD

**Issue by katiePitchBook** [webanno/webanno#386]
When I import a webanno project, I have to select the correct tagset for each feature.  It does not import the selected tagset from the exported webanno project.

![screenshot from 2016-10-14 14 24 44](https://cloud.githubusercontent.com/assets/15332740/19403376/bfdc5e56-921b-11e6-933b-6e52935d65aa.png)

**Comment by reckart** [comment]
Somebody reported this issue before, but I cannot find it anywhere (maybe it was an oral report). 

I don't see a blatantly obvious problem in the code... this needs some debugging.

**Comment by aakashysharma** [comment]
I think I noticed it and told you. But I was unable to consistently reproduce it.

**Comment by reckart** [comment]
Need to check if #914 fixed this.

**Comment by reckart** [comment]
Cannot reproduce this anymore. Assuming that the refactoring in #914 fixed it.
