### ISSUE TITLE
Non-admin users should be able to change their own password

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#389]
Non-admin users would most likely have their own preferred password. They should be able to change their own password, at least, even if they don't have "admin" privilege.

**Comment by GiantEnemyCrab** [comment]
Whether this feature is needed or not, of course, depends on the organization and some organization or teams would be totally fine getting into user password management.

But there are also people who don't want to get into the business of user password management (manually helping users change their own preferred passwords). And the fact that only admin-rights privileged people can change any password doesn't allow self-service as much.

In order to account for these two different situations (ones that prefer to do password management, and one that prefer self-service password updates for all users), I think that:

-each user should have status of whether they can change their own password self-service. All admins would, of course, be able to change their own user password. Perhaps "Allow this user to change his/her password" checkbox can be placed below "Enable account", or so.
-For users with self-service password update enabled, when they login, they see "Manage Users", though they are not admin
-But within "Manage Users", these non-admin users would only see their account name in the username selection textarea
 -When they click their own user name, they would be able to type "password","repeat password", "email", but they are not allowed to modify any other config.

**Comment by reckart** [comment]
Looking in the code recently, I think the code is more-or-less prepared for self-service changing of user passwords. Need to look into it more.

**Comment by GiantEnemyCrab** [comment]
Great to hear!

The scenario I listed in the above comment is just one hypothesis of how it could potentially be done. I will look forward to hearing the kind of changes you have in your mind.

**Comment by reckart** [comment]
If I remember correctly, the code was written so that every user could enter into the "user management" but normal users would only see themselves and be able to change their password. I need to check if we simply have been overzealous by blocking access to the user management for all but admin users or if there is more to do.

**Comment by GiantEnemyCrab** [comment]
The idea sounds great to me. Personally, I am in favor of allowing each user to change their own password themselves.

**Comment by reckart** [comment]
Mind that not in all cases is it ok for users to change passwords. In particular when external authentication is enabled, not must not be allowed.

**Comment by GiantEnemyCrab** [comment]
Got it, so the two cases I listed (self service allowed versus not allowed) still hold true, then.

**Comment by GiantEnemyCrab** [comment]
This change incorporates one of the two scenarios. This allows non-admin users to change their password (and this suffices requirements for my organization scenario):

https://github.com/GiantEnemyCrab/webanno/commit/d7e03f9b866b4739b4971261e131f121c70f19c4

But as we mentioned, there are organizations that prefer not to allow users to change their passwords, and this change doesn't accommodate that.

In order to account for those cases, I suggest creating a new field in DB for "allow_password_change" TINYINT length 1 (basically boolean) per user. By default, this checkbox can be unchecked (so, yes, UI change is also needed). Does this sound good before I dig into this further?

**Comment by reckart** [comment]
I would have tended towards detecting whether external authentication is enabled and in that case suppress the ability of the user to change their passwords.

Additionally allowing an administrator to select per-user if the password can be changed could be desirable by some administrators. However, that setting must then also be disabled/ignored if external authentication is enabled.

The database schema is automatically updated by Hibernate. If you want to add an additional boolean to the user, then just add the field to `de.tudarmstadt.ukp.clarin.webanno.model.User`. On the next start, Hibernate will create the column. To avoid upgrade problems, this column would have to be nullable. It might be necessary to specifically handle the null case in the User class and map it to "false". The getters/setters in the User class should accept/return `boolean`, not `Boolean` to avoid NullPointerExceptions.

**Comment by reckart** [comment]
To check if external authentication is enabled, you can use `SettingsUtil.getSettings()` and check for the value of the property `auth.mode`. Cf `de.tudarmstadt.ukp.clarin.webanno.webapp.security.preauth.WebAnnoApplicationContextInitializer`:

```
        // Activate bean profile depending on authentication mode
        if (AUTH_MODE_PREAUTH.equals(aEnvironment.getProperty(PROP_AUTH_MODE))) {
            aEnvironment.setActiveProfiles(PROFILE_PREAUTH);
            log.info("Authentication: pre-auth");
        }
        else {
            aEnvironment.setActiveProfiles(PROFILE_DATABASE);
            log.info("Authentication: database");
        }
``

**Comment by reckart** [comment]
Allow non-admin users access to their profile if `user.profile.accessible` is set to `true` in the settings file. By default, this is turned off.

**Comment by reckart** [comment]
@GiantEnemyCrab feel free to grab a recent build (or build yourself) and to give it a try ;)

**Comment by GiantEnemyCrab** [comment]
Thank you. It is a great way to solve, by using a settings file's new parameter.
I will integrate all the upstream changes including this (because 3.0.1 was released) early next week.
