### ISSUE TITLE
Curation: Opening new file via "open" does not work when trying less than two times

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#391]
When a curated file is marked as "Done", clicking on "Open" in order to curate the next file leads to nothing. The page loads but the "open document" window does not open. As it opens when the curator tries again, it is not a big issue, still a bit inconvenient.

I am using WebAnno -- 3.0.0-SNAPSHOT (2016-10-09 13:33:23, build 7af062679c8da06eafdb4cf41bfb151c48629e21) with Chrome on Windows 8.1.

**Comment by reckart** [comment]
Cannot reproduce - I assume it is fixed.

WebAnno -- 3.4.5-SNAPSHOT (2018-07-08 21:33:52, build b483c04774de4623400014802c7799decf83b333)
