### ISSUE TITLE
System very slow when loaded with many documents

### ISSUE THREAD

**Issue by asher-stern** [webanno/webanno#401]
Version 2.3.1
Using tomcat, MySql.
Webanno is loaded with ~3300 documents.
When selecting "Annotation" in the home page, it takes about 30 seconds until the dialog box with the list of files is displayed.

**Comment by asher-stern** [comment]
Also when clicking the "open" (after finishing the annotation of one document), it takes again 30 seconds.
So the user has to wait 30 seconds for each document.

**Comment by reckart** [comment]
Are these long or short documents? I.e. is the second delay possibly related to the length of an individual document rather than the number of documents?

**Comment by asher-stern** [comment]
@reckart 
The delay is before selecting any document. The delay is after clicking the "open" button (or "annotation" in the home page) until the dialog box is displayed.

When selecting a document in the dialog box, it is displayed immediately.

**Comment by reckart** [comment]
Ok, I can see why this is slow... we have a loop that goes over all source documents in a project and for each of them then individually retrieves the annotation document metadata to check the state of the annotation...
