### ISSUE TITLE
Curation export: only export documents that are marked as Done

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#402]
An ability to export project with annotation documents that are marked as "Done" status only.

**Comment by reckart** [comment]
You mean non-curated but done?

**Comment by GiantEnemyCrab** [comment]
curated + done only.
I am seeing all documents that are in curation mode (whether done or not) from the export at the moment.

**Comment by GiantEnemyCrab** [comment]
I mean, when export curated documents from project export.

**Comment by reckart** [comment]
Oh, I would have assume that only documents that were curated and marked as done would be exported. If we currently export curation documents that are not marked as done, I would personally consider that as a bug. So I would tend towards fixing that and not even adding a checkbox. WDYT?

**Comment by GiantEnemyCrab** [comment]
Thanks for the response. I agree that this is a strange behavior, but wasn't sure when I created this Github Issue. So, yes, it should be fixed as a bug.

**Comment by GiantEnemyCrab** [comment]
In current codes:

https://github.com/webanno/webanno/blob/master/webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/page/ProjectExportPanel.java#L155

https://github.com/webanno/webanno/blob/master/webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/page/ProjectExportPanel.java#L205

Simply removing the condition related to:
`
sourceDocument.getState().equals(SourceDocumentState.CURATION_IN_PROGRESS`
`
, can make this work for this issue (tested locally).

Let me know how this sounds.

**Comment by reckart** [comment]
@GiantEnemyCrab sounds good.

**Comment by GiantEnemyCrab** [comment]
https://github.com/webanno/webanno/blob/master/webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/page/ProjectExportPanel.java#L151

The comment description for the if statement should be updated
```
// If the curation document is exist (either finished or in progress
```

Should be a minor change.

Re-opening

**Comment by reckart** [comment]
@GiantEnemyCrab thanks for the pointer ;)
