### ISSUE TITLE
Is there any way to hide the export button from the annotators so that only admin can export the project

### ISSUE THREAD

**Issue by snehamanickam** [webanno/webanno#405]

**Comment by aakashysharma** [comment]
@snehamanickam Not sure what you are trying to achieve here. Also, please mention the version number of WebAnno you are using.

The projects option is only visible to admins and project mangers.

> " This functionality is only available to project managers (managers of existing projects), project creators (users with the ability to create new projects), and administrators. "

See[This functionality is only available to project managers (managers of existing projects), project creators (users with the ability to create new projects), and administrators. ]( https://webanno.github.io/webanno/releases/2.3.1/docs/user-guide.html#sect_projects) for more details.

**Comment by snehamanickam** [comment]
I am using webanno 2
I created a project and assigned it to different users, so when the user logs in the user can annotate the project whatever assigned to them. In the annotation page there is the option of export, I dont want that export option visible for the user. Is their any way to achieve this.

**Comment by seyyaw** [comment]
@snehamanickam It seems you do not want users to obtain the annotated data except the admins:
I can see two solutions here
1) Allow only admins to export annotations
2) Have an option in the project to enable/disable export button for non-admin users

I prefer option 2 though

**Comment by snehamanickam** [comment]
Thank you for your response @seyyaw  and @aakashysharma .

**Comment by snehamanickam** [comment]
Thanks. For option2, Is there any built in settings available for customizing this or we have to make changes in the code.

**Comment by reckart** [comment]
There is no option for this yet. It would seem to be sensible to add this as a per-project setting "allow users to export". That would entail:

* extending the project settings page with the additional option
* adding a boolean field to the project class/entity (Hibernate then adds this to the DB)
* adding support to export/import that setting when exporting/importing a project
* extending the annotation/curation/automation/correction pages to honor that setting

**Comment by seyyaw** [comment]
done!. Note checkbox is enabled by default for new projects (so enable export), but for old projects, this option should be checked manually to allow users to export annotation documents.

**Comment by reckart** [comment]
@seyyaw as far as I can see, the setting is not yet included in the project export/import.

**Comment by reckart** [comment]
Also, can this setting please be enabled by default so that existing users are not surprised?

**Comment by seyyaw** [comment]
@reckart I think the request is on annotation page. Project export/import is already allowed only for admins. Do I miss something?

**Comment by reckart** [comment]
@seyyaw that is correct. But the admin's configure in the project settings whether users may import/export. So when an admin exports the project, the exported project must also have that setting. You changed `de.tudarmstadt.ukp.clarin.webanno.model.Project` and friends, but you did not update `de.tudarmstadt.ukp.clarin.webanno.model.export.Project`(or I am blind).

**Comment by seyyaw** [comment]
ok, got it

**Comment by reckart** [comment]
@seyyaw to fix the problem that users need to manually enable this setting on old projects, I would suggest to change the setting from **enable export for users** to **disable export for users**. Can do this and also add the project export/import? I would like to do the WebAnno 3 release before Friday.

**Comment by seyyaw** [comment]
Ok Action is reversed and project export/import updated. @snehamanickam Checking the box now means disallow the user from exporting annotation documents. Field is also changed so if the SNAPSHOT is used in the last 4 days, the column enableExport should be discarded from the database.

**Comment by GiantEnemyCrab** [comment]
@seyyaw, I am seeing that disableExport would remove the clickable link from "Export", so it is functional, but I was thinking that this change would actually hide the Export button entirely. Is there reason to keep this icon in the page, if it is not clickable? (I may have missed something in discussion here?)

**Comment by seyyaw** [comment]
Maybe it is better to show that it is possible to export (that the functionality exists) but disabled by the admin. If hiding is better, We can do that too. What do you think @snehamanickam ?
