### ISSUE TITLE
Hi, I have json files with some pre annotation. I would like to use webanno for further annotations. Since webanno doesn't support json files, How can i achieve converting json to xmi or tsv files. I tried converting them to xmi using xmiwriter but that is not working.

### ISSUE THREAD

**Issue by snehamanickam** [webanno/webanno#407]
Hi, I have json files with some pre annotation. I would like to use webanno for further annotations. Since webanno doesn't support json files, How can i achieve converting json to xmi or tsv files. I tried converting them to xmi using xmiwriter but that is not working.

**Comment by reckart** [comment]
This topic has been discussed on the mailing list: https://groups.google.com/d/msg/webanno-user/3c52rVcOtxU/tjhCeZFVDQAJ
