### ISSUE TITLE
Installation guide leaves users in a confused state

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#415]
The installation guide for WebAnno 2 strongly suggested that people should run WebAnno in Tomcat behind an Apache HTTPD and it assumes e.g. the use `www-data` to be present on the host. However, since WebAnno 3, the init script that we provide suggests to expose the Tomcat directly via authbind.

The installation instructions should be updated. I would suggest we drop the instructions for installation behind an Apache HTTPD and focus only on the authbind solution.

See this related thread on the users mailing list: https://groups.google.com/forum/#!topic/webanno-user/Oli8i6z4qLM

**Comment by nkrot** [comment]
My twopence. If irrelevant, please ignore.

I have deployed WebAnno on CentOS 7. To my knowledge, there is no authbind.

So I installed Tomcat and deployed webanno via tomcat. It was kinda pain as the WAR file is extremely big and does not get uploaded through tomcat web interface. Therefore I copied war file directly under /var/lib/tomcat/webapps/ as webanno.war. When tomcat started, it deployed webanno automagically. I am not sure this is the correct way of using Tomcat :)

I dont have init script /etc/init.d/webanno, seems that Tomcat takes care of starting the application on startup.

webanno home directory was automatically created under $CATALINA_HOME (defined in /etc/tomcat/tomcat.conf), namely, **/usr/share/tomcat/.webanno** and I created **settings.properties** under that directory. I feel this is incorrect, WebAnno home should not be under /usr/share/.

**Comment by reckart** [comment]
Deploying WebAnno by copying the WAR to the `webapps` folder is completely fine. That's actually how I do it all the time. I never use the web interface.

You should change your tomcat configuration and add `-Dwebanno.home=/some/folder/you/like` there and place your settings.properties into that folder. We usually recommend `/srv/webanno`.

**Comment by nkrot** [comment]
`JAVA_OPTS` in `tomcat.conf`?

**Comment by reckart** [comment]
Should work. I think I usually have modified some `catalina.sh` file when not using a package-installed tomcat.

**Comment by reckart** [comment]
I believe the documentation is ok now.
