### ISSUE TITLE
After session expiration, login always results in login screen again

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#419]
To reproduce:

1. log out from WebAnno
2. keep the WebAnno's browser window or tab open
3. wait until the session expires (default 30 minutes?)
4. log in
5. it will land on a login page, instead of webanno's home page with list of things to choose from

This creates confusion for users because it makes it look like their authentication was not successful. But if they successfully type username / password again, after landing on the login page, it will do fine.

**Comment by reckart** [comment]
I've already noticed that effect as well, but I have no clue what causes it. 

The session timeout actually comes from Tomcat - WebAnno just displays it: http://stackoverflow.com/questions/14433070/default-session-timeout-for-apache-tomcat-applications
