### ISSUE TITLE
Allow Project admin to set doc status to "New" from Monitoring

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#422]
Project admins are currently able to toggle doc status between "in progress" to "done", etc.
But there is no option to set it "New". In case several or more annotation documents just need to start over (likely as a result of discussion of disagreements + resolution).

Clicking the icon should result in toggling among "New", "In progress", and "Done".
When it has "New" status, it should not remove the annotation right away in case it was clicked "New" as an error in Monitoring. But next time the annotator opens the document, given the "New" status, it should start over the annotation from scratch fresh.

**Comment by reckart** [comment]
The new workload management pages in INCEpTION allow a project manager to reset the annotations of a user (or even of multiple users / documents).
