### ISSUE TITLE
Datagrid (ajax-based) for table display in Monitoring

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#424]
Clicking through different pages in monitoring (when there are more than 20 documents) can take time to go through all documents.

Instead, I think that the table feature deserves some improvement to become something faster and dynamic.

Some datatables may support a checkbox feature to select all rows for further batch action.
#412 mentions about doing such batch action for setting status to curation ready through API, but if datatable supports batch action, API would not be the only possible way to do so.

The data table should support sorting by each column, etc. And within the datatable (or some say datagrid), scrolling action can result in loading the next page of documents.

**Comment by reckart** [comment]
This is related to #90 and #322.

**Comment by reckart** [comment]
INCEpTION provides new workload management UIs which are faster and more powerful (e.g. they support batch actions). There are also different workload management modes how, e.g. static (traditional like WebAnno) and dynamic (i.e. have n annotators annotate each document, but do not care who the annotators are).
