### ISSUE TITLE
Curation cannot be opened in WebAnno 3.0.1

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#427]
When trying to access curation in WebAnno 3.0.1, an error is produced:

```
Last cause: Expression #1 of ORDER BY clause is not in SELECT list, references column 'weblab.sourcedocu2_.name' which is not in SELECT list; this is incompatible with DISTINCT
WicketMessage: Error attaching this container for rendering: [Select [Component id = documentSelection]]
```

**Comment by reckart** [comment]
@GiantEnemyCrab Looks like this may not necessarily be a WebAnno problem but rather something new introduced with MySQL 5.7.

**Comment by GiantEnemyCrab** [comment]
Thanks for the info. Good to know.

In my local environment with Mac, it is 5.7.15
The target deployment environment is using 5.1.73

I will align mysql version to the deployment target environment

**Comment by reckart** [comment]
@GiantEnemyCrab I have committed a fix. Can you please try it. If you hit this problem in other parts of WebAnno, please let me know.

**Comment by reckart** [comment]
I did a quick scan in the code for `DISTINCT` but the curation page open dialog seems to have been the only place where `DISTINCT` was combined with `ORDER BY` in a problematic way.

**Comment by reckart** [comment]
I've also locally upgraded to MySQL 5.7 recently, so if there are more of these issues, I'll probably also get bitten by them (when I get time to work on WebAnno that is...)-

**Comment by GiantEnemyCrab** [comment]
Thank you for the quick fix.
I can confirm that the issue is addressed in my local environment.
