### ISSUE TITLE
Curation: Constraints aren't updated at all

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#441]
In an earlier version of WebAnno, stacked annotations led to a merge of suggested tags as the constraints weren't updated properly. Now, using WebAnno -- 3.1.0-SNAPSHOT (2017-02-12 22:10:50, build 96280b8b14735b8574ef49310206d471eebfb2eb) with Chrome on Windows 8.1, the constraints aren't updated at all. Once you choose a tag that activates a constraint rule, the suggested sub-tags stay the same during the whole curation process, regardless of the constraint rules that should be applied afterwards.

**Comment by reckart** [comment]
Are the rules applied when you reload the page?

**Comment by sholschneider** [comment]
Yes, but I have to reload every time a constraint rule has been applied.

**Comment by reckart** [comment]
Sure - this is not supposed to be a workaround. It helps narrowing down where/why the problem occurs.

**Comment by reckart** [comment]
Does this happen only in curation or also in annotation?

**Comment by sholschneider** [comment]
It also happens in annotation.

**Comment by reckart** [comment]
Similar issue but older: #319.

**Comment by reckart** [comment]
I think this is a new variant of #376.

**Comment by reckart** [comment]
Here the relevant wicket-jquery-ui issue https://github.com/sebfz1/wicket-jquery-ui/issues/245

**Comment by sholschneider** [comment]
Now, constraints aren't applied at all.

**Comment by reckart** [comment]
It is a complex problem and will take a while to solve.

**Comment by reckart** [comment]
NPE when slot features are used without constraints

```
Caused by: java.lang.NullPointerException
        at de.tudarmstadt.ukp.clarin.webanno.ui.annotation.detail.editor.LinkFeatureEditor.autoAddImportantTags(LinkFeatureEditor.java:411)
        at de.tudarmstadt.ukp.clarin.webanno.ui.annotation.detail.editor.LinkFeatureEditor.onConfigure(LinkFeatureEditor.java:453)
        at org.apache.wicket.Component.configure(Component.java:1055)
```
