### ISSUE TITLE
Feature to reset (remove) existing from annotation document

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#442]
Would be great to have a button in Annotation mode to remove all the annotations from currently working document.

Could be implemented to reset annotation on a layer-basis. (I would think removing all existing annotations from all layers may be too excessive)

Confirmation should appear before removing all annotations.

Ensure that a reset cannot be performed if the document has been marked as "Done".

- [x] Annotation page
- [x] Correction page
- [ ] Automation page

**Comment by reckart** [comment]
With recent refactoring to the internal APIs, this is should be easy to do now. Coming soon ;)

**Comment by reckart** [comment]
Ok, we have a reset button on the annotation page now - complete with a safety dialog.
