### ISSUE TITLE
"Lock to token offsets" and "Allow multiple tokens" are hard to understand

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#443]
Would be great to improve the layer settings for "lock to token offsets" / "allow multiple tokens".

The "Help" section does describe the differences but I think that in the settings page, this can still improve.

Can this be edited as below?
"Lock to single token offsets"
"Lock to multiple token offsets"

I believe the phrase sounds more consistent, because, after all, these are about the same feature, just different offsets.

And it would also be great if these two checkbox settings are next to each other.
Currently, "Allow stacking" and "Allow crossing sentence boundary" are displayed between "Lock to token offsets" and "Allow multiple tokens".

**Comment by reckart** [comment]
Actually these two checkboxes should be removed and replaced with a a dropdown box titled "Lock to" with these options:

* characters
* single tokens
* multiple tokens

**Comment by GiantEnemyCrab** [comment]
Yep , totally agreed.
