### ISSUE TITLE
Uploading a TSV3 file into a project - broken annotation

### ISSUE THREAD

**Issue by Tiberiu17** [webanno/webanno#447]
Hi,

I have exported a TSV3 file and then imported it back into the same project, but also a new project. The annotations are completely messed up and the file look entirely unmanageable. This happened in the 3.0.0 version.
I have attached a snip to showcase my situation.
Thank you.

![image](https://cloud.githubusercontent.com/assets/25326310/23254875/d1433060-f9b9-11e6-9cc0-e8db894fec63.png)

**Comment by reckart** [comment]
Indeed, there is something bad going on here. Looks like offsets got mixed up badly. Could you privately send me an export of the project (via Main Menu -> Project -> Export (format binary cas)) for a closer look?

Did you try exporting/importing in a different format, e.g. UIMA binary CAS?

**Comment by Tiberiu17** [comment]
I tried the binary and it worked fine. The issue seems to be with the TSV3.

**Comment by Tiberiu17** [comment]
How do I send it privately? By email?

**Comment by reckart** [comment]
Yes. You can find it [here](https://www.ukp.tu-darmstadt.de/people/senior-staff/dr-richard-eckart-de-castilho/).

**Comment by reckart** [comment]
Ok, the problem were Windows newline characters that got swallowed when exporting the file as TSV3. I have now changed the code such that text is Java-escaped and then stored in the file. So the TSV format now looks like

```
#Text=This is line 1\r
#Text=and this is line 2 of a\tsentence.
```

**Comment by reckart** [comment]
@amir-zeldes this change might be relevant to you.

**Comment by reckart** [comment]
Hm, this change is not backwards compatible... if a text contained e.g. `\t` in a previously exported TSV3 file, it would now become a tab character... need to think if there is a better solution.

**Comment by reckart** [comment]
New files now written as format 3.1. The reader detects if file is 3 or 3.1. In the latter case, Java-unescaping will happen. This should provide a smooth transition.

Relevant commits

- https://github.com/webanno/webanno/commit/398518872d2430f15657392b13cd192cb58acf61
- https://github.com/webanno/webanno/commit/a9430e10774d24f5ec6fef0f6aa99f42a6f219ea

**Comment by amir-zeldes** [comment]
Windows newlines (or `\t` for that matter) probably don't appear in our data, though thanks for the heads up. Have you considered using XML or Unicode codepoint escapes? e.g. for `\r` use `&#13;` or `\u000D`? It may be more robust than Java style escapes.

**Comment by reckart** [comment]
I am already using the Apache Commons Lang [StringEscapeUtils.escapeJava()](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringEscapeUtils.html#escapeJava-java.lang.String-). If read the code correctly, it escapes control characters for which a Java-equivalent exists using the Java escape and all other characters outside of the range `32`-`0x7f` using Unicode escapes. So that should address your comment.

**Comment by amir-zeldes** [comment]
OK, thanks. This means we'll have a slight divergence in how Pepper imports these using https://github.com/korpling/pepperModules-Webannotsvmodules so maybe that's a thing to keep track of. I'll open an issue to make that happen at some point (generally if you change things in the TSV it would be good to put up a reminder issue)

**Comment by reckart** [comment]
> generally if you change things in the TSV it would be good to put up a reminder issue

@amir-zeldes that's why I pinged you so you can decide if you want to do it (and do it) ;)

You can detect TSV files that use Java escapes in the `#Text=` lines by the format String `#FORMAT=WebAnno TSV 3.1` and those without Java escapes by `#FORMAT=WebAnno TSV 3`.

**Comment by amir-zeldes** [comment]
OK, good, it's in the long term planning somewhere, though probably not before end of semester.
