### ISSUE TITLE
Re-Importing project fails

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#454]
Re-importing a project created in WebAnno 3 fails for some reason with the following exception

`Error Importing Project NoResultException: No entity found for query`

Debugging the code shows that, entryName = "source/" and fileName is empty in the following lines

```
String entryName = normalizeEntryName(entry);
if (entryName.startsWith(SOURCE)) {
                String fileName = FilenameUtils.getName(entryName);
```

Checking for empty file name solves the problem

**Comment by reckart** [comment]
Any idea why these empty entries appear at all?
