### ISSUE TITLE
Mark features affected by constraints in UI

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#46]
For various reasons, it would be good to mark features that are affected by constraints in the UI, e.g.:

* because changing the value of such a feature can have side-effects, e.g. adding default slots
* because they reorder tags and it would be good to know when this is to be expected

Likewise, it would be good to use different markers for different special cases, e.g. (marker color in parens):

* **Case 1 (red)** - warning marker if a feature is affected by a constraint but there is no tagset defined on the feature. In such a case the constraints cannot reorder tags and have no effect.
* **Case 2 (yellow)** warning marker if a feature is affected by a constraint but no rule covers the feature value, e.g. `@Lemma.value = "go" -> aFrame = "going"`. Here `aFrame` is affected by a constraint. However, if the actual lemma annotated in the document is `walk` and there is no rule that covers `walk`, then we should also indicate that.
* **Case 3 (green)** for case that a constrained actually applied ok there should be a marker.
* **Case 4 (none)** for the case that no constraints apply to a given feature in a given type, no marker should be displayed

I imagine the marker as a colored dot after the feature name or after the dropdown.

**Comment by reckart** [comment]
I think we should give this issue some priority. Right now, it is hard to see if constraints do not kick in because there are none or because there is a bug.

**Comment by reckart** [comment]
For the moment, I would not expect a marked if a feature in a given type is not affected by a constraint at all even though a feature with the same name in another type might be affected. I have updated the issue description accordingly.

**Comment by aakashysharma** [comment]
There are constraint rules in the project but none of rules can potentially affect "RoleSet" for example. 
Should it be case 2, "yellow" marker (No conditions match) or case 4 "None"?

**Comment by reckart** [comment]
If a feature is not mentioned at all in any rule, then there should be no marker whatsoever.

**Comment by aakashysharma** [comment]
```
boolean isThisAffectedByConstraintRules(FeatureStructure aContext, String aFeature, ParsedConstraints parsedConstraints)
```
is a function in Constraints API #102 which checks whether there are any rules affecting "aFeature" in scope of "aContext" 

The above function returns if current condition (aContext) can affect "aFeature" based on rules in parsedConstraints. 

Should there be function like

```
boolean canThisBeAffected(String aFeature, ParsedConstraints constraints) 
```

which checks irrespective of scope, whether a target can be affected or not?

**Comment by aakashysharma** [comment]
Also, this way it's undermining whether there are constraint rules in project or not. Indicator will only show if it can be affected by any of the constraint rules, whether they kick in at some point or not.

**Comment by reckart** [comment]
The scope must be respected. When I say 

> ... a feature is not mentioned at all in any rule ...

I mean that fully qualified feature that is disambiguated via a scope.

**Comment by reckart** [comment]
Let's tune the yellow down to orange - the bright yellow is hardly visible on the white background.
