### ISSUE TITLE
Set Required Attributes for Layers

### ISSUE THREAD

**Issue by justinsowhat** [webanno/webanno#461]
I'd like to request a functionality to set required attributes for a layer. In other words, when a tag is created and some of its attributes are set to be required, a user won't be allowed to click 'Done' on that annotation without filling out its required attributes. 

For example, currently I can click 'Done' when a file contains a tag that does not have any attributes, which is an undesirable condition for many annotation tasks (see the below). 

<img width="284" alt="screen shot 2017-03-01 at 12 32 26 pm" src="https://cloud.githubusercontent.com/assets/11317666/23472607/706de8e0-fe7b-11e6-9620-385279bbdab2.png">
 
----

- [x] add "required" flag to features (also on import/export)
- [x] add "required" flag in settings UI
- [x] render an error comment/highlight if a required feature is not set
- [ ] check for required features when pressing "Done"

**Comment by reckart** [comment]
I think this "required" flag only makes sense for String features. Do you agree?

**Comment by justinsowhat** [comment]
Sorry for the last response. Yes, I agree with you, and thank you for putting it to work.
