### ISSUE TITLE
Curation page doesn't show created annotation layers (chains)

### ISSUE THREAD

**Issue by timmli** [webanno/webanno#463]
While playing around with the standalone version of WebAnno 3.1.0 (2017-02-26 21:56:12, build a9db4248b0decf9dedf7c4913363ff336727f713), I noticed that I cannot choose to display annotation layers that I've created (i.e. only the standard ones are selectable).

**Comment by reckart** [comment]
You mean that your custom layers do not appear when you click on the "settings" button of the action bar in the annotation page?

**Comment by timmli** [comment]
Yep.

**Comment by reckart** [comment]
Are you sure that your custom layer is actually "enabled" in the project settings?

Mind that chain layers are not supported in "correction" projects and also not on the curation page.

**Comment by timmli** [comment]
> Mind that chain layers are not supported in "correction" projects and also not on the curation page.

Ah, that's why! Yes, relations are indeed shown in the curation page.

**Comment by timmli** [comment]
Hm. Then let me put it as a question: How can I annotate relations between spans and later see them in the curation page? Background: we would like to annotate semantic relations between grammatical functions which may span two or more tokens.

**Comment by reckart** [comment]
Curation supports spans, relations and slot features. 

You can create a custom *span* layer that represents the units between which you want to create relations. Make sure that *Lock to token offsets* is disabled and *Allow multiple tokens* is enabled.

Then you create a custom *relation* layer and configure it to attach to the previously created *span* layer.

In the annotation UI, select your new span layer type from the *layer* dropdown, then mark a piece of text to create a span annotation. Also create a second span annotation. To create the relation, click on one of the span annotations and drag to the other. This will automatically create the relation you just configured in the project settings. Mind that at the moment there can only be a single relation layer attached to a given span layer.

**Comment by timmli** [comment]
Your last comment was really helpful, thanks! I didn't expect "lock tocken offsets" to have such an impact. This solves the issue for me and I'll close it.
