### ISSUE TITLE
Layer names do not get filled in Annotation page.

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#465]
After the commit 5a75c47b95a6846f329ca86878a452cb4824dcae, when opening a document initially, layer names are not filled in the dropdown box. (Never mind about some customized UI elements like intentionally not showing RTL option, etc)

![screen shot 2017-03-06 at 10 30 19 am](https://cloud.githubusercontent.com/assets/1326079/23616563/2e8b20ba-0258-11e7-85c3-1411e6b1731f.png)

**Comment by reckart** [comment]
Oops :) So that line that I removed *did* have an effect after all...

**Comment by kazukisan** [comment]
Thanks fix confirmed.
