### ISSUE TITLE
Ability to view other annotator's work in Annotation Page

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#467]
As discussed in #406, filing a new issue here for a feature request.

This is for being able to view other annotators' work for the currently open document.

- [x] There should be a dropdown box somewhere in the UI, which will list annotator user names, who have edited the annotation document in some way or another.
- [x] After selecting the user name, it will show the version of the annotation of that particular annotator, in read-only mode.
- [x] Display name of the user whose document we see in the document information area above the editor panel, i.e. where the project and document name are also displayed
- [x] When selecting a user, the list of documents should be reloaded depending on what documents that user can access and the coloring should reflect in which state the documents are for that given user

**Comment by kazukisan** [comment]
To add to this if an annotator could view "Curation finished" doc, it will help them compare their work against what was curated. This means the user list should contain curation.

**Comment by reckart** [comment]
@UWinch I have update the description with a few new items after trying out the current state of the PR.

**Comment by UWinch** [comment]
@reckart I have implemented it in a way that other users and their documents can be chosen in the OpenDocumentDialog. However, I'm only showing the documents for the current user if the project is locked (i.e. when the user should not be able to switch between projects). I assumed this was the flag used to adapt the dialog to inception's needs. This way this functionality is only available in webanno and not in inception. Is this what we want or do we want it also in inception?

**Comment by reckart** [comment]
I'd say we want the functionality to be available in both. The "lock project" flag should just lock the project, nothing else.

**Comment by UWinch** [comment]
Ok, I removed the check and this feature would now also show in inception. I finished implementing this issue for the managers. Normal users still cannot see others' work. 
Should we test this for a while now and then implement for normal users with an additional configuration checkbox?
