### ISSUE TITLE
Number of visible sentences not correctly applied when opening/switching documents

### ISSUE THREAD

**Issue by sholschneider** [webanno/webanno#468]
It would be nice if the number of sentences stayed the same when switching to the next file. It is unlikely that an annotator/curator prefers different settings while working with the same project.

**Comment by reckart** [comment]
Actually, it should already remain the same... where does this happen?

**Comment by sholschneider** [comment]
Using WebAnno -- 3.2.0-SNAPSHOT (2017-02-28 09:54:38, build cf39429e24931d253f6b8593e140b18f1d3f43c3) with Chrome on Windows 8.1. Both in annotation and curation mode.

**Comment by reckart** [comment]
Seems like a bug when loading the preferences then. Thanks for reporting, I'll look into it.
