### ISSUE TITLE
Config option for not creating default layers and tagsets

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#469]
Would be good to have a global config so that when creating a new project, some layers and tagsets are not created by default (because they end up being disabled anyway for projects for some people)

Chunk
Coreference
Dependency
Lemma
POS
Named Entity
Surface form

**Comment by reckart** [comment]
I assume that you would also want to suppress the creation of the default tagsets?

**Comment by kazukisan** [comment]
Yes, that is correct.

**Comment by reckart** [comment]
I guess a quick hack to support this would be to add a checkbox on the `ProjectDetailPanel` which would control whether default layers / tagsets are should be created when `Save` is pressed for the first time. Also the checkbox would only be visible as long as the project has not actually been saved once (i.e. created). Maybe using a transient field in the `Project` bean such that the flag doesn't get persisted to the DB... as I said... hack...

**Comment by geniki** [comment]
The option to not have the built-in layers would be great indeed.

As an intermediate step, is it possible to reconsider the default of them being Enabled even if they must exist in the background? Project creators that don't need these layers currently have to untick them one-by-one for every new project.

**Comment by reckart** [comment]
This feature is added in INCEpTION: https://github.com/inception-project/inception/issues/1943
