### ISSUE TITLE
Dependency annotation not accepted in .xmi file

### ISSUE THREAD

**Issue by MeDarina** [webanno/webanno#470]
When loading an .xmi file pre-annotated with a depenency annotation, I get the following error:
"Error while uploading document 0_1.xmi: XCASParsingException: Error parsing XCAS or XMI-CAS from source <unknown> at line 1, column 17461: unknown type: de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.ROOT."

The file is created in a DKPro Pipeline and the error does not occur if the same pipeline is used with an CoNLL Writer and I import the .CoNLL file.

I used an older instance of WebAnno where the error occured, but in also occurs in a current version, namely "WebAnno -- 3.2.0-SNAPSHOT (2017-03-09 11:49:38, build b9afaa211104d6037b50a7f28fb4f840647258c5)", using Safari.

**Comment by reckart** [comment]
WebAnno presently doesn't read XMI files leniently, so it does complain when there are any types in the XMI that it does not know about. I can change that such that WebAnno loads XMI leniently.
