### ISSUE TITLE
Export Dialog does not show progress, breaks the "Projects" view

### ISSUE THREAD

**Issue by eugenso** [webanno/webanno#471]
When I try to export a project (selecting "export the whole project") in WebAnno -- 3.2.0-SNAPSHOT (2017-03-09 11:49:38, build b9afaa211104d6037b50a7f28fb4f840647258c5), the right pane is updated with an empty box. There is no progress bar any more. The download does not show up afterwards. 

When I get back to the "Projects" page, I can select a project in the left pane, but then nothing happens. I get the same empty white box and cannot change settings or export the project.

**Comment by reckart** [comment]
That is already fixed in a more recent build.

**Comment by seyyaw** [comment]
@reckart Good!
@eugenso I will update the testing/experimental instances. You can try that latter.
