### ISSUE TITLE
Could selection for "Attach to layer:" be changed from specific layers to types of layers (span, relation, chain)?

### ISSUE THREAD

**Issue by mforst** [webanno/webanno#473]
I'm defining a bunch of "base" layers for different domains and languages. They are all of type 'span' and vary just wrt. the values for certain features and wrt. "lock to token offsets". On top of these, I'd like a layer of type 'relation'. Ideally, I'd like to use exactly the same specification for this second layer. Unfortunately, though, it seems that I have to create copies of this layer because I have to specify a particular "base" layer for "attach to layer". Wouldn't it be possible to make people specify a type of layer (rather than a specific layer) for "attach to layer" and thereby allow them to combine one "higher" layer with several attachment layers?

**Comment by reckart** [comment]
Unfortunately, we missed the opportunity to "easily" support multiple relations per span and cross-layer relations, etc. layer a long time ago. It is still something on the todo list, but as WebAnno grew, it became more and more complicated to add this feature. At the moment, I am consolidating the code, removing redundancies, cleaning up, etc. Hopefully that will eventually also make it easier again to add this feature. However, it'll be a lot of work. When I implemented the new "link feature" capability on span layer, I allowed linking to arbitrary other span layers by selecting the type "Annotation" from the type dropdown when creating a new feature. You could have a look if that might help you in your setup.

**Comment by reckart** [comment]
See https://github.com/inception-project/inception/issues/1319
