### ISSUE TITLE
File selection for layer import seems buggy

### ISSUE THREAD

**Issue by mforst** [webanno/webanno#474]
Earlier today, I exported four layers. Now, when I try to import one (or several) of them, the result does not correspond to my selection. E.g., I have Entities_charbased and Entities_tokenbased; I select the latter via the dialog; I hit the "Import layer" button, and I end up with the former in my list of layers.

**Comment by reckart** [comment]
When you export a relation layer, it will also export the span layer that it attaches to. Does that explain the effect sufficiently?

**Comment by mforst** [comment]
I don't think so. The two layers that get mixed up are both of type 'span'.

**Comment by reckart** [comment]
Which version of WebAnno are you using?

**Comment by mforst** [comment]
I'm using webanno-standalone-3.1.0.jar so far.

**Comment by reckart** [comment]
Was never able to reproduce this. Closing.
