### ISSUE TITLE
Webanno lands on favicon.ico image after login

### ISSUE THREAD

**Issue by maxxkia** [webanno/webanno#478]
I found a bug in log-in page in webanno-3.2.0-beta-2. Situation is as follows:

1. I open my browser (Chrome). I have the Webanno tab open from the last time I closed my browser.
2. (optional) I refresh the webanno page
3. I log in
4. I land in https://webanno.myserver.org/favicon.ico
5. I enter the url https://webanno.myserver.org/ again and then I successfully enter webanno.
I could easily reproduce this in Firefox as well, it happens the first time I try to log in. If I log out and log in again this doesn't happen.

**Comment by reckart** [comment]
I can reproduce it with Chrome. Probably that is because Chrome tries to pre-load the favicon before loading the actual page and then that is the URL that the login page remembers for redirection.

**Comment by reckart** [comment]
Ok, I think these changes should fix it. Cannot reproduce the effect anymore with Chrome.
