### ISSUE TITLE
TSV3 reader inserts newline between adjacent sentences with no separating whitespace

### ISSUE THREAD

**Issue by adrianeboyd** [webanno/webanno#482]
Even when there is no whitespace between two sentences, the TSV3 reader inserts a newline character, throwing off all the following offsets in the imported file. The annotation display looks garbled as in #447, so I thought it might be related, but character encoding doesn't seem to be the problem.

In addition, the TSV3 writer writes the inserted newline in the token column in the export, completely breaking the export format.

A test case as imported and exported:

[sents-nowhitespace.tsv.txt](https://github.com/webanno/webanno/files/872198/sents-nowhitespace.tsv.txt)
[sents-nowhitespace-exported.tsv.txt](https://github.com/webanno/webanno/files/872199/sents-nowhitespace-exported.tsv.txt)

**Comment by reckart** [comment]
Nice catch. I added a fix that chops off this automatically added LF in case the next sentence starts without any intermediate space.

**Comment by reckart** [comment]
There is a problem with this fix though: it can cause inconsistencies between CASes in existing projects e.g. in the following situation:

* document was imported before fix
* user A started annotating document before fix
* user B starts annotating after fix

In this case, use A will have a CAS created with the extraneous line breaks and user B will have a CAS without them. It would break curation and agreement calculation for this project.

I cannot tell how likely this situation is to occur. Export/import will not fix it either.

To properly address it, I could imagine to

- Finally support exporting/importing the INITIAL_CAS (https://github.com/webanno/webanno/issues/464)
- Adding a migration step on startup that generates INITIAL_CASes for all documents where they are missing so far. The migration step would have to check if all the existing annotator CASes are compatible with the generated INITIAL_CAS and if not, it should either fail or try to recover by using an existing annotator CAS, stripping all annotations, and using that as INITIAL_CAS. However, this could cause an anomaly in projects with pre-annotated documents where the INITIAL_CAS actually does contain annotations...

**Comment by reckart** [comment]
I am considering to push this fix to 3.3.0 and leave it unfixed in 3.2.0 in order to get 3.2.0 out of the door faster. As mentioned in the last comment, fixing the present issue also entails further changes in order to avoid problems down the road.

**Comment by reckart** [comment]
Fixed #464. Not doing the migration step though. I hope that people don't run into this problem.

However, if they do, then the workaround is to export the project using WebAnno 3.2.3 (INITIAL_CAS to be generated on export) and to import it again with WebAnno 3.3.0.
