### ISSUE TITLE
Whole project export does not include in progress curation

### ISSUE THREAD

**Issue by adrianeboyd** [webanno/webanno#483]
An export of the whole project does not include in progress curation. Without those documents, the whole project export does not serve as a complete backup of the project.

**Comment by reckart** [comment]
That was probably an undesired side-effect of #402 ("Curation export: only export documents that are marked as Done").

**Comment by reckart** [comment]
Hm, actually no. #402 affected specifically the `exportCuratedDocuments` method. Looks like this is really a bug / missing feature in the general project export.

**Comment by reckart** [comment]
*sigh* ... yes ... it **is** due to #402.

**Comment by reckart** [comment]
There is a problem with this fix though: it can cause inconsistencies between CASes in existing projects e.g. in the following situation:

* document was imported before fix
* user A started annotating document before fix
* user B starts annotating after fix

In this case, use A will have a CAS created with the extraneous line breaks and user B will have a CAS without them. It would break curation and agreement calculation for this project.

I cannot tell how likely this situation is to occur. Export/import will not fix it either.

To properly address it, I could imagine to

- Finally support exporting/importing the INITIAL_CAS (https://github.com/webanno/webanno/issues/464)
- Adding a migration step on startup that generates INITIAL_CASes for all documents where they are missing so far. The migration step would have to check if all the existing annotator CASes are compatible with the generated INITIAL_CAS and if not, it should either fail or try to recover by using an existing annotator CAS, stripping all annotations, and using that as INITIAL_CAS. However, this could cause an anomaly in projects with pre-annotated documents where the INITIAL_CAS actually does contain annotations...

**Comment by reckart** [comment]
I am considering to push this fix to 3.3.0 and leave it unfixed in 3.2.0 in order to get 3.2.0 out of the door faster. As mentioned in the last comment, fixing the present issue also entails further changes in order to avoid problems down the road.

**Comment by adrianeboyd** [comment]
Did you mean the last two comments for #482?

**Comment by reckart** [comment]
Indeed. To many tabs. I'll move those comments.

**Comment by reckart** [comment]
Still need to verify the fix actually works...

**Comment by reckart** [comment]
Looks good.
