### ISSUE TITLE
Span annotation usability 

### ISSUE THREAD

**Issue by matanox** [webanno/webanno#489]
Hi there,

There seems to be a key usability issue manifesting in the process of annotating a text span, which may be a very common operation for an annotator, thusly one of _the_ most common operations in a running annotation project. May I suggest that addressing this may significantly improve usability and annotation effort along errors by annotators, especially when annotators are not ardent linguistics students but e.g. more regular guys/students/folks.

- as an annotator, when I select a text span, the text lines split in two at the line being annotated, to afford the space for the label. For single words this is fine, but the larger the selected span, the sharp re-rendering of the annotated line and all lines below it ― to a lower position on screen so as to afford the space for the label ― is really too jumpy I find; and the annotator may well feel the urge to make sure they've really selected the right words span let alone that the selected span turns so subtly gray at that point. I find that this really needlessly increases cognitive load on the annotator's part.

Jumpy changes to the vision focus area of the user is kind of a User Interface UX no-no; the graying out of the selection span doubles the cognitive confusion at that sensitive stage of the flow.

I can see three optional ways to alleviate/absolve this:

1. Animate the split so that the text lines going down do not disappear and re-render (very suboptimal for visual cognition and context preservation) but rather gently slide down through some sinusoidal tweening function or similar one (cognitively recommended). With today's graphics processors this can be very smooth on any vanilla machine. I think HTML/CSS has some idioms for tweens even without an animations library but need to confirm.

1. Space out between the rows in the first place, so that no text lines movement is needed; but this might be only desirable for some annotation types not others (with coreference annotation, one might want to see a _lot of text_ on the same page, whereas this would make the text much sparser for them. Maybe this spacing out can be an option in the user's settings along side the choice of fonts etc.

1. At least while annotating, show any annotation's details only upon mouse hover (or touch), on a parallel pane or on top/below the line of text (while graying all but the annotated term or line) so that the text being annotated never moves around while being annotated. While prior to the hover, visually highlighting/boxing the text itself, similarly to how labels are visually emphasized ― to indicate the parts of the text being viewed that bear annotations, so that places that can be hovered are clear and intuitive. I believe in this vein there can be a toggle (button) between this view and the view that shows all annotations in the current expansive form of them, to suit the user's state and preference.

Your thoughts welcome

@matanster

**Comment by reckart** [comment]
WebAnno uses a modified and extended version of the rendering engine of brat. The changes you suggest likely involve deep modifications of the brat rendering code and likely require a significant skill level regarding SVG, JavaScript, and CSS. If you or anybody with sufficient skill has the resources to address this, please drop us a note here.

Meanwhile, I am working on modularizing WebAnno internally such that alternative rendering engines in addition to brat may be included one day.

**Comment by matanster** [comment]
Thanks for letting me know. I doubt I'd be good enough to work within a rendering engine having a rich history like Brat though. Might reconsider after the modularization has been over though...

**Comment by reckart** [comment]
@matanster the feeling of "jumpyness" may be mitigated to some degree by disabling the "Auto-scroll" option in the settings dialog on the annotation page. This option aims at moving the sentence in which the last annotation took place into the center of the screen. Could you try if the "jumpyness" feeling gets better for you if you disable that option?

**Comment by reckart** [comment]
I believe the jumpyness has been sufficiently resolved. Depending on the needs, INCEpTION also has alternative editors to brat that might be more comfortable, e.g. the HTML-based editors for structured documents.
