### ISSUE TITLE
Rendering problem when mixing RTL and LTR in a multi-token annotation

### ISSUE THREAD

**Issue by mabnsr** [webanno/webanno#49]
The red arrow shows the wrong portion of the text highlighted. The red box shows what should be highlighted.

**Comment by reckart** [comment]
Thanks for the report. I am trying to reproduce this on my machine, but so far I cannot. Here I have tried a couple of cases:

**RTL-LTR**

![2015-07-28_21-16-07](https://cloud.githubusercontent.com/assets/1410238/8941162/55e37f58-356e-11e5-8a50-dbe90ba2c12d.png)

**LTR-RTL**

![2015-07-28_21-14-59](https://cloud.githubusercontent.com/assets/1410238/8941166/5fe64b70-356e-11e5-8b2d-53c2a73db4c6.png)

**RTL-LTR-RTL**

![2015-07-28_21-20-42](https://cloud.githubusercontent.com/assets/1410238/8941198/87fc0fbe-356e-11e5-989e-001e1d173ce7.png)

All of these look ok. However, there is a known problem with sub-token annotation of LTR tokens in RTL mode, e.g.:

![2015-07-28_21-17-09](https://cloud.githubusercontent.com/assets/1410238/8941218/a34b9384-356e-11e5-8f02-c02d6b6942da.png)

In the example above, the *20* annotation should be above the *20* text and *01* should be above the *01* text - but they are switched. Currently, I see no way to easily fix this.

However, I believe your problem can be resolved through by pre-processing your data. I assume you imported a plain-text file into WebAnno. The tokenizer in WebAnno makes "22994024-22994022" into a single token. So when you annotate only the "229904022" part, you are creating an annotation that mixes an LTR subtoken with an RTL full token. If you can tokenizer your text externally in such a way that "22994024-22994022" is split into three tokens "22994024" "-" "22994022", then you should be able to make your annotation without a problem. Maybe you also have to make sure that the colon is a separate token from the arabic word before it.

Cf. [Tokenization of languages that are not white space separated?](https://groups.google.com/forum/#!searchin/webanno-user/tokenize/webanno-user/8xqYgFoGzPA/rpUMXyntFhQJ)

**Comment by reckart** [comment]
Btw. I hope these phone numbers are taken either from some publicly accessible source or they are fake. If not, please tell me because then I would remove the image (or you do it yourself if you can/or replace it with something anonymized).

**Comment by mabnsr** [comment]
Thank you for your response, in a simple case, I uploaded plain text file containing:
في 125 شارع محمد علي الواقع في المدينة

I highlighted the portion: "125 شارع محمد علي" for annotation, I got only the number part highlighted, as the attached show. I also tokenized the input text and uploaded as TSV as the following (with tabs before tokens):
1-8	في
2-8	125
3-8	شارع
4-8	محمد
5-8	علي
6-8	الواقع
7-8	في
8-8	المدينة

Still got the same results.

Is it possible that I am not uploading the input correctly or missing some settings, I am using WebAnno 2.2.0. 

Thank you
![screen2](https://cloud.githubusercontent.com/assets/13544017/8945665/63684170-3557-11e5-9888-f06c9f32368f.png)

**Comment by reckart** [comment]
Thanks for the data. I'll check it again. Maybe it is also a browser-specific problem. I was doing my tests with Safari Version 7.1.7 (9537.85.16.12). What browser/version are you using?

**Comment by mabnsr** [comment]
I was using Chrome, but it works better on Safari. I will do more testing tomorrow and let you know if I have any issues. Thank you for your help.

**Comment by reckart** [comment]
Since we do not have the image in the original comment anymore, I simply assume that this issue has been covered by one of the following issues

* #278 
* #265
