### ISSUE TITLE
Document locking not working

### ISSUE THREAD

**Issue by nkrot** [webanno/webanno#492]
In a freshly installed **WebAnno 3.2.0** (through WAR-archive) document locking does not seem to work.

In Monitoring menu I lock a file for a specific user but despite this the user has the ability to see, open and edit the document.

I inspected the state of the locked document in the annotation_document table, it is **IGNORE** before the user start editing the document.

    MariaDB [webanno]> select * from annotation_document;

    +----+--------------+------------------+------------+---------------------+-------------+----------+---------+
    | id | name         | sentenceAccessed | state      | timestamp           | user        | document | project |
    +----+--------------+------------------+------------+---------------------+-------------+----------+---------+
    |  8 | text.004.txt |                0 | IGNORE     | NULL                | test-user-2 |        2 |       1 |

Despite the state being **IGNORE** the user **test-user-2** can edit the document and after the edit the state becomes **INPROGRESS**

    MariaDB [webanno]> select * from annotation_document;

    +----+--------------+------------------+------------+---------------------+-------------+----------+---------+
    | id | name         | sentenceAccessed | state      | timestamp           | user        | document | project |
    +----+--------------+------------------+------------+---------------------+-------------+----------+---------+
    |  8 | text.004.txt |                1 | INPROGRESS | 2017-04-18 19:40:49 | test-user-2 |        2 |       1 |

Or I misunderstand the locking functionality :)

**Comment by reckart** [comment]
If the document is set to IGNORE, it should not appear in the "open" dialog and the user should not be able to edit it. Looks like a but then.

**Comment by reckart** [comment]
Thanks for reporting this problem!
