### ISSUE TITLE
Documentation: more info on Automation mode required

### ISSUE THREAD

**Issue by nkrot** [webanno/webanno#493]
Hi

I have a few, perhaps naïve, questions regarding Automation functionality.

1) Am I right to assume that in Automation mode WebAnno learns annotations from annotated documents and tries to predict labels ("feature values") in a new, unannotated, document(s)? What kind of algorithm is used for learning the model? Can custom learning algorithms be provided?

2) [new feature?] When a new unannotated document has been annotated, curated and approved by the project manager, can this document be added to the set of training documents, learning be rerun and any unopened documents be re-annotated with the newly built model?

3) Is it true that `Project Settings/Automation/Target layer` and `Project Settings/Automation/TAB-SEP` tabs both serve the same purpose: uploading annotated documents used in training, and the difference is only is the format? And that the user can use either method? Can a part of training data be uploaded via `Target layer` and another part via `TAB-SEP`?

Thanks!

**Comment by reckart** [comment]
I'm afraid, I don't know much about the automation functionality, but maybe @seyyaw can answer this question.

**Comment by reckart** [comment]
Btw. questions are usually better posted to the mailing list - not to the issue tracker.

**Comment by nkrot** [comment]
Agree. I will post them to the mailing list
