### ISSUE TITLE
Clearing Annotation fields on page change

### ISSUE THREAD

**Issue by nkrot** [webanno/webanno#494]
Small usability issue. When I have annotated a word and scrolled to another page, the Annotation pane (the one on the right) still holds the most recently edited word. If now I try to change the Annotation/Value, the attempt succeeds: the page is scrolled back to show the page containing the focused word and its annotation is updated.

In my opinion this is wrong. To be on the safe side, the Annotation pane should rather be cleared on page change.

EDIT: In my opinion, the problem is that the annotation of the token that is no longer visible can be updated.

**Comment by reckart** [comment]
Probably this behavior disappears when you go to the "Settings" icon in the action bar of the annotation page and disable "Auto-scroll document while annotating".

I personally don't think that the detail editor pane should be cleared on a page change.

**Comment by reckart** [comment]
What exactly do you think is the problem - the scrolling? that you can still update the selected annotation?

**Comment by reckart** [comment]
Imagine if we did not have paging but instead simple scrolling and you would scroll down such that the selected annotation is no longer visible on the screen - I assume you would not expect here that the detail editor pane clears as soon as you scroll up/down and the selected annotation moves out of the viewport. I consider the paging as a "poor mans" alternative to scrolling, hence I personally think that the detail panel should not change when switching pages.

Actually, if somebody had the skills and time to do it, it would be great to replace the paging with a dynamically loading scrolling - something that actually displays a scroll bar and starts loading and rendering data as soon as it would come into view... a bit like infinite scrolling.

I am leaving this open a bit more in case somebody else wants to comment.

**Comment by reckart** [comment]
One more note: the way to create long-distance relations is to click on a source span, then switch to the page containing the target span, right-clicking on the target span and creating the relation. This would not work if the source span had been cleared from selection on page change.

No further comments, so closing.
