### ISSUE TITLE
Not able to enable Forward Annotation in POS Layer

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#496]
The forward annotation is currently not working.
The code in AnnotationDetailEditorPanel, line 2177 through 2179 disables the functionality

```
if (selectedLayer.getType().equals(WebAnnoConst.SPAN_TYPE)) {
  return false;
}
```
In stead, it should be as `if(!selectedLayer...`
This enables the checkbox but the keyboard-shortcuts are not anymore working then.

**Comment by reckart** [comment]
So that missing `!` is something that got lost without intention in commit 3bd73a4381fa1500473484605e2fdfea28461db9.

**Comment by reckart** [comment]
I added back the `!`. Do you have any idea why the keyboard-shortcuts don't work anymore?
