### ISSUE TITLE
Docker image for WebAnno

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#497]
Build a Docker image for WebAnno and release it to Dockerhub when we run a release.

**Comment by reckart** [comment]
Seems to work ok when as long as MySQL data dir is not mounted on the host. However, when using `-v /my/own/datadir:/var/lib/mysql`, then MySQL doesn't start up anymore:

```
Starting MySQL database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!
```

Maybe it would be better to use H2 by default when running in Docker...

**Comment by bluepuma77** [comment]
If you do provide a Docker solution with 3.3.0, it would be great to have MySQL in a separate container. That should also simplify a lot of the stuff fkuhn tried half a year ago.

Something along the lines of 
```
# store MySQL data externally so it will survive container removal
docker run \
  --name webanno-mysql \
  --hostname mysql \
  --restart=always \
  -v /directory/webanno-database:/var/lib/mysql \
  -e MYSQL_ROOT_PASSWORD=root \
  -e MYSQL_DATABASE=webanno \
  -e MYSQL_USER=webanno \
  -e MYSQL_PASSWORD=t0t4llYSecreT \
  -d mysql:latest

# within webanno you can now access MySQL via `mysql` hostname
docker run \
  --name webanno \
  --restart=always \
  --link webanno-mysql \
  -p 18080:18080 \
  -d webanno:3.3.0
```

**Comment by reckart** [comment]
I would like to have a docker image that runs with a single docker run command. My idea is that it should be similarly easy to use as the WebAnno standalone JAR. 

However, I am starting to think that including MySQL in that image may not be the best idea. It may be better to run WebAnno with the HSQLDB by default. My idea would be that a user of the docker image could put a custom `settings.properties` with a MySQL config into the WebAnno home folder which the user should mount to a path on the host if the user wanted to connect to a MySQL DB.

**Comment by reckart** [comment]
I have been working on a Docker image that is built automatically along with the Maven build.

As discussed before, I would like that image to run as easily as

```
 docker run -v mount/local/path:/webanno-home -p 18080:8080 webanno/webanno
```

or without persistent data possibly even as easy as (maybe even the `-p` can go away?)

```
 docker run -p18080:8080 webanno/webanno
```

without any additional commands and in particular without a second MySQL container.

However, I think it would be very useful to **write documentation** on how to configure that
future official image to run along with a second MySQL container.

* The Docker setup is currently in https://github.com/webanno/webanno/tree/master/webanno-webapp/src/main/docker and (if I remember correctly) it should build the image when WebAnno is built with `mvn clean install -P enable-docker`.
* There is no documentation yet.

From my perspective, the next steps should be
* remove MySQL DB / `settings.properties` from the Docker setup so the image runs by default with HSQLDB
* document how users should mount a host path into the Docker image for persistent storage with HSQLDB
* document how users should place a `settings.properties` file into the mounted host path to configure the MySQL connection
* document how user can start up a second linked MySQL container with persistent storage which WebAnno could use (I don't know atm how to easily create the WebAnno user / database in that container though)

@seyyaw

**Comment by reckart** [comment]
Ok, with the latest commit, the image should now build without MySQL.

Next: documenting how to use persistent storage and how to connect to an external MySQL DB.

**Comment by remstef** [comment]
Hi Richard, I have a single command docker-compose solution for starting separate containers for mysql and webanno, it might be interesting for you. It roughly resembles @bluepuma77's two commands. The command is simply something around

`docker-compose up`

if you're in the same directory as the docker-compose.yml file or something around 

`docker-compose -f <(curl -L 'https://git.io/vHAjh') up`

if you want to download it from the internet in the same command.

WEBANNO_HOME and WEBANNO_PORT environment variables have to be defined beforehand.

you can find details + docker-compose.yml here: https://github.com/remstef/webanno-exmaralda/blob/master/docker-compose.yml

**Comment by reckart** [comment]
I would like to avoid docker-compose because it is much less elegant than `docker run`. Although your approach is kind of appealing, it is not transparent for the user what happens behind your shortened URL. Also, it doesn't work on Windows.

**Comment by reckart** [comment]
Looking at your YAML file, I think we are simply talking past each other and try to solve two different things.

I am focussed on providing the "webanno-server" image from your YAML file. IMHO that is what WebAnno should provide via docker hub. And it should be provided in such a way that it can be started simply using `docker run` (with an embedded database, using `-v` with persistent storage).

You seem to be talking about a second step which takes this "webanno-server" image and combines it with a MySQL server. A docker-compose recipe seems to be a good way of doing that - we could include such a YAML file as an example with the WebAnno documentation. We could even tell advertise the curl-based trick.

What I would like to know at the moment is: 
* How to best build the "webanno-server" image as part of the Maven build?
* Can you use the image that falls out of `mvn clean install -Penable-docker` in the current WebAnno for your docker-compose setup?
* If not, why?

**Comment by remstef** [comment]
> You seem to be talking about ...

Yes, you are right, the compose file creates two containers, mysql and webanno w/o mysql

> How to best build the "webanno-server" image

I just briefly tested it and I never worked with the docker maven plugin before, but I guess the command to issue is 

`mvn -Pdocker clean install docker:build docker:push`

I obviously didn't try to `push`, but `build` works

> Can you use the image...

Yes, works fine, just use the image `webanno/webanno`, but it obviously doesn't talk to the webanno-mysql container because of the wrong settings. Adding a proper `settings.properties` with `mysql` or `webanno-mysql` host (they are aliases) and correct user settings makes it work like a charm.

**Comment by reckart** [comment]
This works. I have just pushed an image to https://hub.docker.com/r/webanno/webanno-snapshots/

```
mvn -Denable-docker -Ddocker.verbose -Ddocker.username=<username> -D=docker.password='<password>' docker:build docker:push
```

So how do you add the `settings.properties`? Do you just throw one into the WebAnno home folder? Do you do it via your docker compose configuration or manually?

Do you think it would be a good idea to push a new image on every Jenkins CI build or just manually once in a while and on releases?

**Comment by reckart** [comment]
@remstef I have added a first throw at documenting the use of WebAnno via Docker here: https://github.com/webanno/webanno/blob/490e6c6b6e038a94a1c0bb9639d711bed4e543cb/webanno-doc/src/main/asciidoc/user-guide/installation.adoc#storing-data-on-the-host 

Could you please have a look if that makes sense to you? Maybe you could add info about starting up the external MySQL via Docker as well?

Mind that unlike in the documentation, the image name presently must be `webanno/webanno-snapshots` instead of `webanno/webanno` since I haven't pushed any release version yet.

**Comment by remstef** [comment]
I just threw a `settings.properties` into the Webanno home folder and restarted the containers. But if this kind of configuration could be supplied as an environment variable, e.g. via `JAVA_OPTS` or so, then it works out-of-the-box . Environment variables can be easily set in a docker-compose file. Is it even already possible to supply this as environment variable, and I just don't know about it?

I'd suggest pushing only on releases. My impression is that in Docker hub people expect a stable version as latest version because often a tag is not supplied in a run command. I see this is what your last commit was about, this sounds like a good solution 😄 

Yes, I will take a look.

**Comment by reckart** [comment]
> Is it even already possible to supply this as environment variable, and I just don't know about it?

Good question. I suppose we could check in the `webanno_initd` if `WEBANNO_HOME` and `WEBANNO_PORT` are already set before setting these variables to the hardcoded/default values. Do you want to have a look at it?

**Comment by remstef** [comment]
the way I see it it's not.

May I suggest stg like 

`JAVA_OPTS=${JAVA_OPTS:-"-Djava.awt.headless=true -Xmx750m -XX:+UseConcMarkSweepGC -Dwebanno.home=$WEBANNO_HOME"}`

in `webanno_initd`

`JAVA_OPTS` is then set to a default string if it is not already defined, otherwise the defined `JAVA_OPTS` is used. This should be safe since webanno runs as the only application in an encapsulated container, I wouldn't suggest that if it were a normal server. 

And `JAVA_OPTS` can then be overridden in a 

`docker run` command, e.g. 

```
docker run ... --env JAVA_OPTS="\
-Djava.awt.headless=true \
-Xmx750m \
-XX:+UseConcMarkSweepGC \
-Dwebanno.home=/export \
-Ddatabase.dialect=org.hibernate.dialect.MySQL5InnoDBDialect \
-Ddatabase.driver=com.mysql.jdbc.Driver \
-Ddatabase.urljdbc:mysql://mysql:3306/webanno?useSSL=false&useUnicode=true&characterEncoding=UTF-8 \
...
" webanno/webanno
```

or similarly in a docker-compose.yml file

This would even offer the chance of providing more memory (I need this actually for webanno-exmaralda 😉 )

**Comment by reckart** [comment]
Can't we do like both? I.e. allow overriding `JAVA_OPTS` for advanced users like you as well as overriding just the `WEBANNO_HOME` / `WEBANNO_PORT`?

**Comment by reckart** [comment]
Btw. did you actually try setting the `database.driver`, etc. via system properties? I just looked up the Spring documentation - I guess it should work out-of-the-box, although I never tried that/thought of that.

**Comment by reckart** [comment]
... sorry, misread. I think it presently does not work, but it should be easy to configure Spring such that it does work.

**Comment by remstef** [comment]
> Can't we do like both? ...

Technically, sure, yes, every parameter could be set like this, but IMHO it doesn't make sense to specify a different port or a different `WEBANNO_HOME` in the dockerized setting because the mapping of the docker container port to a host port is done by the user via the docker run  command. And now that I think about it, it might even be harmful to change these, because in the Dockerfile you have to specify the port that can be exposed to the host via the `EXPOSE` directive. That one is fixed, but if the webanno port changes dynamically, you cannot map it to a host without doing some extra stuff, you can only map exposed ports. Similarly, if you specify the `VOLUME` directive in the Dockerfile to be the webanno home, it should not change in the run command, that might lead to inconsistencies.

If it would work via Spring I think that would be the cleanest solution because we don't have to squash everything into one JAVA_OPTS env variable but in fact we have multiple env variables.

**Comment by reckart** [comment]
Via #538, I have configured Spring such that it prefers database connection details provided via system properties over the built-in defaults and over the `settings.properties` file. However, it still means that these system properties would have to be provided via JAVA_OPTS instead of via environment variables. 

I could also extend enhance that such that the database properties could be obtained form environment variables. However, I would use different names for the environment variables then for the system properties, e.g.

* `WEBANNO_DB_DIALECT` = `database.dialect`
* `WEBANNO_DB_DRIVER` = `database.driver`
* `WEBANNO_DB_URL` = `database.url`
* `WEBANNO_DB_USERNAME` = `database.username`
* `WEBANNO_DB_PASSWORD` = `database.password `

**Comment by reckart** [comment]
Actually if you think using environment variables is a good idea, I would even tend towards reverting #538.

**Comment by remstef** [comment]
Having environment variables like `WEBANNO_DB_DIALECT` ... is a good idea especially when running this with docker. In my opinion the system properties are then not necessary anymore.

**Comment by reckart** [comment]
@remstef ok, environment variable support added via #542

**Comment by remstef** [comment]
Great, thanks! I will test the docker-compose approach and let you know.

**Comment by reckart** [comment]
@remstef so? Did you do your tests? I would tend towards closing this issue.

**Comment by remstef** [comment]
Hi @reckart, I tested it, unfortunately it doesn't work. I'm trying to figure out why, but it seems that the environment variables are not taken into account.

**Comment by reckart** [comment]
According to the `database-context.xml`, they should be

```
        <prop key="database.dialect">#{systemEnvironment['WEBANNO_DB_DIALECT'] ?: 'org.hibernate.dialect.HSQLDialect'}</prop>
        <prop key="database.driver">#{systemEnvironment['WEBANNO_DB_DRIVER'] ?: 'org.hsqldb.jdbc.JDBCDriver'}</prop>
        <prop key="database.url">#{systemEnvironment['WEBANNO_DB_URL'] ?: 'jdbc:hsqldb:file:'.concat(systemProperties['webanno.home'] ?: systemProperties['user.home'].concat('/.webanno')).concat('/db/webanno;hsqldb.default_table_type=cached')}</prop>
        <prop key="database.username">#{systemEnvironment['WEBANNO_DB_USERNAME'] ?: 'sa'}</prop>
        <prop key="database.password">#{systemEnvironment['WEBANNO_DB_PASSWORD'] ?: ''}</prop>
```

**Comment by remstef** [comment]
yes, but it seems they aren't. In the container the environment variables are set, I can see that. 

You can reproduce this, I attached an example docker-compose file (remove the .txt suffix, github doesn't allow .yml suffixes)
[docker-compose.yml.txt](https://github.com/webanno/webanno/files/1204491/docker-compose.yml.txt)

After you built the docker image with `mvn -Pdocker docker:build` run `docker-compose up -d` (in the same directory as the docker-compose.yml file, let's say webanno root). Then check the logs `docker logs webanno_webserver_1` for the database dialect entry (should be mysql, but is hsql). Then attach to the container `docker exec -ti webanno_webserver_1 bash` and print the environment variable `echo $WEBANNO_DB_DIALECT` (that will be mysql).

Maybe the properties are overridden by a default settings.properties file?

**Comment by remstef** [comment]
sorry, better use

`image: "webanno/webanno-snapshots:latest"`

as webserver image in the docker-compose.yml file

**Comment by remstef** [comment]
I forgot to mention `docker-compose down`  in order to remove the containers

**Comment by reckart** [comment]
Last time I tested it in Eclipse, I could nicely set the environment variables in the run configuration (mind really "Environment Variables", not system properties) and they were picked up nicely.

So my suspicion would be that the environment variables you pass into Docker may get lost somewhere between the entry-point script and WebAnno. Maybe they would need to be "exported" in some way to be available to the entry-point scripts or scripts called from it?

**Comment by reckart** [comment]
@remstef btw. since WebAnno is now based on Spring Boot, we could actually drop the Tomcat from the Docker image and start the WebAnno WAR/JAR file using its embedded Tomcat. (`java -jar webanno.war` - mind that now WAR and JAR file are actually identical!)

**Comment by remstef** [comment]
Hm, the variables are passed with the run command, resp.  via the environment tag in docker-compose.yml, that should actually work. I also tried to add them directly to the Dockerfile, but had no success. 

I like the solution with the standalone war/jar file. I briefly tested it, and at least locally it takes environment variables into account, so might be that they get lost in the init script for tomcat or so. If you agree, I would see to change the Dockerfile accordingly.

**Comment by reckart** [comment]
@remstef sure, have a try at the Dockerfile.

**Comment by remstef** [comment]
Works like a charm, also the environment variables :)

**Comment by reckart** [comment]
@remstef Great. Would you like to update the section on Docker (maybe on Docker Compose) in the documentation?: https://github.com/webanno/webanno/blob/master/webanno-doc/src/main/asciidoc/user-guide/installation.adoc#run-using-docker

**Comment by remstef** [comment]
done! :)
