### ISSUE TITLE
Remote API for Automation

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#506]
As we have remote API for annotation, it is better also to have remote API for automation to automatically tag new documents remotely inside WebAnno

**Comment by reckart** [comment]
This feature should be integrated into a separate Remote API controller class that resides in the automation module. To maintain modularity, please do not extend the RemoteApiController or RemoteApiController2 classes.

**Comment by reckart** [comment]
INCEpTION offers the external recommenders API to allow pulling in suggestions from external ML implementations.
