### ISSUE TITLE
Curation mode: color display changed on agreed upon annotations

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#518]
It looks like commit revision (223cefe23e9881d5a2b0def5f52eef4436c5592a or before) contains some change in curation mode, such as that all the agreed upon annotations no longer have the gray color, but instead they have some randomly assigned colors now.

Is this intended change of feature or something else?

**Comment by reckart** [comment]
Are you sure it is that commit that is causing the problem? The files that it changes shouldn't have anything to do with coloring.

**Comment by kazukisan** [comment]
It is not that commit, but I wanted to just say which particular revision of the codebase I was using.
Actually I did git pull of the webanno (unmodified, no local change), and still seeing the same issue.
I am using some random news article to display the issue:

![screen shot 2017-06-07 at 4 27 24 pm](https://user-images.githubusercontent.com/1326079/26899899-95c8798c-4b9e-11e7-9b29-b5f11c0e7703.png)
:

**Comment by reckart** [comment]
I recently pulled the rendering pipeline apart - probably the problem was introduced during that particular refactoring.

**Comment by kazukisan** [comment]
I will report the exact commit that introduced the difference soon.

**Comment by kazukisan** [comment]
6296f933f65c5da3bff2259ff4609b37b37ba2f4 looks like the exact commit that introduced the difference with regard to color of AGREE.
I did checkout each revision close to that commit.
In order to reproduce this, I did need to log out first, then open the curation document (refreshing the page after restarting tomcat wouldn't guarantee showing the difference)

**Comment by reckart** [comment]
That is the commit that pulled apart the rendering pipeline. I didn't expect this to have an effect on the coloring in curation.

**Comment by reckart** [comment]
Thanks for noticing this! I missed completing the refactoring of the rendering when it came to the coloring strategy. Should be fixed now.
