### ISSUE TITLE
List of documents from "Open Document" for Curation does not reflect curation status

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#519]
In Curation, "Open Document" is currently (from git repo, not official release) displaying documents in unexpected ways. The documents listed are not reflecting the true status of curation readiness. For example, curation finished documents should be showing up with red color, but they may appear as black. Curation-Not-ready documents are being shown, etc.

I did revision-by-revision check and I am seeing that from this commit the behavior difference is introduced:
b8da0562a74d1b0ab6f193dc1031fe9dd88f4dfd

**Comment by reckart** [comment]
We are talking about documents, right - not projects? 

I did some refactoring to the project-coloring code, but I didn't actually touch the document-coloring code because I was afraid of breaking it. The method `OpenModalWindowPanel.listDocuments(Map<SourceDocument, String>)` which controls the coloring of documents didn't change. Also the code that actually sets the color in the document list didn't change.

As far as I can see, the *project* color indicates curation-readiness, but the *document* color indicates the curation state (curation-in-progress, curation-finished) in the 3.2.x branch as well as in master.

**Comment by kazukisan** [comment]
Below I have the screen shot of "after" vs "before".

In this example, there should be only one curation-ready document, and because I opened it, it should be having blue color. The image at the bottom of this comment is the properly behaved one. I did notice that this behavior is not reproduced in every project, but I do not know why, but for projects that get affected, yes, it's strange to see this.

![screen shot 2017-06-08 at 10 43 24 am](https://user-images.githubusercontent.com/1326079/26934731-335c4ec8-4c38-11e7-966f-f56195c9023f.png)
![screen shot 2017-06-08 at 10 49 20 am](https://user-images.githubusercontent.com/1326079/26934735-37a15ec4-4c38-11e7-9442-010664eb754a.png)

**Comment by reckart** [comment]
Thanks for the comparison. I'll try to come up with a way to figure out where this is coming from.

**Comment by reckart** [comment]
Ok, I think this one is nailed.

**Comment by kazukisan** [comment]
Thank you for the fix for this "Open Document" issue.

I have one question. I noticed that in curation's open document:
```dsd.setLabel("%s (%s)", sourceDocument.getName(), sourceDocument.getState());```
This lists the document name as well as its (curation status), but in other modes, documents will get listed without (its status) next to it.

This is not an issue, thought, but I thought consistency is something good to have: if annotation document opening dialog shows the status difference by color only, then curation should pursue the same, I feel.

If an extra information, like status indicator, is needed perhaps this may be more of general improvement to have a table-like style for document opening, with one of the columns reserved for indicating the status, perhaps using the same icons seen in monitoring.

**Comment by reckart** [comment]
I added the extra info mainly for debugging purposes and then thought it might be useful to keep. In the other cases, I believe the color code is largely sufficient.

Yep, icons would be great. As usual it is a matter of priorities. Contributions are very welcome! :)

**Comment by kazukisan** [comment]
Thanks for the info, and yes it is more clear for debugging purpose.

In some of annotation projects that I know of within my organization, not all of the annotators need to click Finish. If there are 10 annotators, for example, maybe only 2 people are assigned to that specific document. (And using monitoring to lock documents could be quite slow currently, depending on the number of documents the project contains).

For the curator, when 2 people finish the annotation, it will show in curation open dialog as "document1 (ANNOTATION_INPROGRESS)", for example (and if the doc name is "document1"). 

Developers would be able to understand this dynamic status name, but non-developers may get confused, because they may think the assigned two people didn't click finish.

As soon as those documents are opened, it will become CURATION_INPROGRESS, but it's just one of those UI things :). So I vote for "less is more" style, showing just the document names only.

(And for icons idea, in curation document opening dialog, ANNOTATION_INPROGRESS status have "new" icon, maybe, as it is newly available to be curated).
