### ISSUE TITLE
Perform javascript action on click

### ISSUE THREAD

**Issue by remstef** [webanno/webanno#520]
Allow onClick events on spanannotations and run a defined Javascript action.

**Comment by reckart** [comment]
Do we need the ability to put arbitrary JS there or wouldn't an URL-pattern that could be constructed from a fixed set of parameters (e.g. documentId, projectId, userId, annotation features) be sufficient. I think a URL-pattern would be easier for the typical to understand/configure and less error-prone.

**Comment by remstef** [comment]
Javascript is more flexible in my opinion, e.g. we need to open a particular URL always in the same window/tab. When we supply only a URL pattern, we'd also need an option for a window name and so on. Also this helps a lot for debugging and offers a lot of flexibility.

**Comment by reckart** [comment]
If you want to use JS, then I think the string-substitution in the code-snippet is not a good solution. It introduces special meaning to certain characters not present in JS. For a JS-based solution, it would seem more sensible to pass the parameters as a dictionary, e.g.

```
function handleAction(parameters) {
  // this is where the user-supplied snippet goes and where it can access the "parameters" variable.
}
```

**Comment by reckart** [comment]
Also, I think "doAction" should be renamed to "onClick" then - next you may want to override "onMouseEnter" or something else. Being aligned with the event names in JS would be helpful then.

**Comment by remstef** [comment]
I agree, I named this option "doAction" to be in line with the other options created by other events, e.g. in onDblClick: "createArc", "createSpan"

**Comment by reckart** [comment]
It depends whether taking a Annotation-centric perspective or a JS-centric. I had the impression you were taking an JS-centric perspective since you were aiming for maximal flexibility.

**Comment by remstef** [comment]
> If you want to use JS, then I think the string-substitution in the code-snippet is not a good solution. 

I think the template option is the simplest, we don't want complex Javascript functions here, only things that could be written in a single line, max 2 or three commands. It is still possible to call more complex Javascript functions, but users can then build their parameter objects here too. 

> It depends whether taking a Annotation-centric perspective or a JS-centric.

In the end it's a click on an annotation. But I really don't mind renaming this to "onClick", I'd follow your lead here.

**Comment by reckart** [comment]
The JS option is not the simple one. The simple option would be an URL pattern. If we go to JS and want to avoid trouble further down the road, then the custom JS should be done properly. Introducing substitution patterns always opens a can of potential problems. We have hit these again and again. Here, it is simply not necessary to do it. The approach allowing the user to fill the body of an auto-generated JS function and using a variable to access the necessary is IMHO safer in the long run and not more complex in terms of implementation effort.

**Comment by reckart** [comment]
Actually, even in an URL pattern, it's not that simple - even there it would be necessary to handle escaping, e.g. if the URL should actually contain a verbatim `$` or `{` character. However, this is probably much less likely than in JS. Does you present code handle such cases? I thought it didn't.

**Comment by reckart** [comment]
The reason I am suggesting the body-filling approach is that it avoids any kind of trouble with escaping/unescaping.

**Comment by remstef** [comment]
Hi, I thought about this some time now. I'm not against your suggestion and I absolutely see your point in avoiding executable code in variables/substitutions. On the other hand, and I completely didn't anticipate this use case before, but I kind of like the idea of having the possibility of executable field annotations. E.g. you could annotate (or preannotate) a text with different actions although it's the same layer. You could encode alert boxes / confirm boxes and many more possibilities. Now, I see a lot of problems here too, primarily the ones that you mentioned, in case of errors it is very hard to track down where the error occurs. For that, I would like to suggest to make the escaping optional (activated by default), i.e. as an option next to the javascriptaction box in the layer details panel. I you still see too many security or code safety leaks or so, I'd also go for the parameter object solution.

**Comment by reckart** [comment]
I am thinking more about maintainability than security. From a security perspective, I'd prefer not allowing JS at all. But I see how JS could be a useful feature for some power users (including you). 

I am very concerned about maintainability though and this includes the escaping. In my experience, half-baked solutions with haphazard escaping or no escaping at all are a maintenance nightmare.

I'd really prefer going with the parameter object and in this way precluding the need for escaping/unescaping entirely. It seems to me the best solution.

**Comment by remstef** [comment]
Alright, I can accept that, I'll revise the code.

**Comment by reckart** [comment]
@remstef I changed the parser code such that it works with layers for which there are no JCas cover classes.

Why is it necessary to escape the values in the map separately? When the whole stuff is converted to JSON, aren't the values sufficiently escaped?

Is it really necessary to convert everything to String, even numbers, booleans, etc?

There is a JSONUtil class in WebAnno which would be the preferred way of obtaining an object mapper / converting stuff to JSON.

**Comment by reckart** [comment]
Are you sure it is a good idea to use the UI name of layers and features? The can contain spaces, special characters, etc.

**Comment by remstef** [comment]
> I changed the parser code such that it works with layers for which there are no JCas cover classes.

Thanks

> Why is it necessary to escape the values in the map separately?

it's not, the escapeJavascript method is never called actually, it could be removed

> Is it really necessary to convert everything to String, even numbers, booleans, etc?

it's not actually. The method grew from string substitution where I needed a Map<String, String>, but since we changed that, I probably just forgot about the fact that the json object mapper takes care correct serialization

> There is a JSONUtil class in WebAnno 

Oh, I didn't know about that, then we should change that

**Comment by remstef** [comment]
> Are you sure it is a good idea to use the UI name of layers and features? The can contain spaces, special characters, etc.

My thought was, that it might be easier for the user to enter these names. I didn't think about special chars and spaces etc. So, yes, maybe it's better to leave away.

**Comment by reckart** [comment]
The last commit also changes the layer name in the parameter map from the UI name to the internal name.

**Comment by reckart** [comment]
@remstef the double-click detection code you were using caused every click/double-click even to fire twice. Since an additionally the dblClick event was registered in the dispatcher, all events were even triggered three times. I found a better double-click detection example on SO and was able to fix this. Cancelling the timer was missing.
