### ISSUE TITLE
Feature Request: Project export

### ISSUE THREAD

**Issue by luto65** [webanno/webanno#532]
**Situation in V3.2.1** 
Layers can be exported one at the  time, however one cannot export a whole project configuration in one goal.
**Why is this a problem** 
Transporting projects between different instances and also archive / restore full projects is much more prone to manual errors in handling import / exports
**How it should be** 
In the UI at the same place where one can "Create" project  and "Delete" a project, one should also be able to "Export" a project.

**Comment by reckart** [comment]
This functionality already exists. The entire project can be exported on the last tab of the project settings "Export". The resulting ZIP file can be imported again in another instance.
