### ISSUE TITLE
Dynamic tagset

### ISSUE THREAD

**Issue by luto65** [webanno/webanno#540]
Currently, tag-set are hardcoded in the specific configuration files uploaded or manually created.
This is a problem in cases were the list of key-value pairs be long and/or changing frequently.
A much better approach would be to make those pulldowns dynamic and configurable through a REST service that delivers the needed data.
Typical usage scenario: annotating semantics with e.g. UMLS key/value pairs in medical terminologies.

**Comment by reckart** [comment]
Cf. https://github.com/webanno/webanno/issues/524#issuecomment-307723248

**Comment by reckart** [comment]
INCEpTION has various features addressing this need.

* you can connect to an external SPARQL service to query a knowledge base using a **concept feature**
* you can connect to a simple external web service using a **lookup feature** (available from INCEpTION v27.0) -> https://github.com/inception-project/inception/issues/3598
