### ISSUE TITLE
The annotation labels are not updated according to the annotation constrains

### ISSUE THREAD

**Issue by genimarca** [webanno/webanno#550]
I defined an annotation project in webanno with a constraint, in order to add some properties values to a specific tag of an annotation layer. The constraint works pretty good, but I'm confused with the behavivour of webanno. My annotation scenario is the following:

Annotation layer: I have one annotation layer that is called causal_argument.
The annotation layer has two features: causal_argument_name and causal_argument_polarity
I want that the annotation of the causal_argument_polarity would be only enable in case the value of causal_argument_name would be causing_event. For that I define a constraint file that works fine, as I indicated above. However, when I am annotating, I realized that if I firstly choose CAUSING_EVENT as causal_argument_name and then the polarity, and then I change my mind because I considered that the argument name should be CAUSED_EVENT, the interface does not remove the value of the polarity from the label over the sequence of tokens selected.

Is there any solution for that issue?

**Comment by reckart** [comment]
Presently, the *Hide unconstraint features* only hides the respective features from the UI - it does not reset their value.

**Comment by reckart** [comment]
Part of https://github.com/inception-project/inception/issues/3990
