### ISSUE TITLE
 I couldn't get the listing of the senseId and arguments

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#554]
message from WebAnno user group
=====
I was trying to do the annotation as like your paper "A Web-based Tool for the Integrated Annotation of Semantic and Syntactic Structures", in Figure 1.

I created a Layer "SemArg" with:
- Type "span", Allow stacking, Allow crossing sentence boundary and Allow multiple tokens
- Two features: arguments (Type as webanno.custom.SemArg), senseId (Type as uima.cas.String)

I added a Constraint with the rules:

```
import webanno.custom.SemArg as SemArg;

SemArg {
    @Lemma.value = "ask" -> senseId = "Questioning" | senseId = "Request"; 
    senseId = "Questioning" -> 
    arguments.role = "Addressee" (!) |
    arguments.role = "Message" (!) |
    arguments.role = "Speaker" (!) |
    arguments.role = "Time" |
    arguments.role = "Iterations";
}
```

I managed to do the annotation as like the attached image. But I couldn't get the listing of the senseId and arguments when annotating the text.

Any cue to what i missed to do?
![sempred_annotation](https://user-images.githubusercontent.com/1056051/27768913-5d6899ca-5f1f-11e7-9893-f5ed9ef9a451.jpg)

**Comment by reckart** [comment]
Constraints only work when tagsets are defined on the corresponding features. Since the fields in the annotation detail editor are not dropdowns, I would assume that no tagset has been assigned.

**Comment by reckart** [comment]
User reports on mailing list that it works after setting up tagsets.
