### ISSUE TITLE
Accidental deletion of annotations in read-only layers is possible

### ISSUE THREAD

**Issue by normundsg** [webanno/webanno#555]
- [x] The problem with the warning dialog is that it is not quite clear which layer will be affected by the deletion. **Adding the name of the layer to the dialog would be very helpful.**
- [x] The expected behaviour, however, would be that no action (deletion) is performed after pressing Yes, and a yellow info message would appear in the footer, **stating that this action is not allowed for read-only layers.**

----

I have created a project for FrameNet annotation, with UD and POS annotations in read-only layers:
<img width="864" alt="dependency" src="https://user-images.githubusercontent.com/1726922/27779512-2f8d6bd6-5fcc-11e7-9849-869bdfa91178.png">
<img width="783" alt="pos" src="https://user-images.githubusercontent.com/1726922/27779519-367c7310-5fcc-11e7-94ae-583fb8ea0694.png">

Then I accidentally selected a POS tag (instead of a word) to add a frame annotation:
<img width="1050" alt="selection" src="https://user-images.githubusercontent.com/1726922/27779615-d98c03fe-5fcc-11e7-94ca-666ddd339c90.png">

Since WebAnno alphabetically selects the FE (frame element) layer as the default layer, I tried to change it to the Frame layer, and got this warning:
<img width="1048" alt="warning" src="https://user-images.githubusercontent.com/1726922/27779731-a7d7a600-5fcd-11e7-9a5f-8ce53bda0c4a.png">

By accidentally pressing Yes, the POS tag with the associated dependency links are lost:
<img width="1077" alt="crash" src="https://user-images.githubusercontent.com/1726922/27779855-3a6a2fd8-5fce-11e7-8280-aedbeea90d9c.png">

I'm using WebAnno 3.2.1.

**Comment by reckart** [comment]
Well, yes... that is why there is this warning dialog.

What would be the expected behavior in your opinion?

**Comment by reckart** [comment]
You could try toggling the "Remember layer" option in the annotation settings dialog (reachable via the "Settings" icon in the action bar of the annotation editor.

![2017-07-03_10-26-24](https://user-images.githubusercontent.com/1410238/27784416-33a9b0ae-5fda-11e7-88a6-65809f6a98af.png)

With "Remember layer" enabled, the layer dropdown applies only to newly created annotations. Changing it doesn't affect the presently selected annotation anymore.

If you try it, I would be curious to know what mode you find more intuitive.

**Comment by normundsg** [comment]
Thanks for advice; the "Remember layer" mode seems alright.

The problem with the warning dialog is that it is not quite clear which layer will be affected by the deletion. Adding the name of the layer to the dialog would be very helpful.

The expected behaviour, however, would be that no action (deletion) is performed after pressing Yes, and a yellow info message would appear in the footer, stating that this action is not allowed for read-only layers.

Anyway, an UNDO button would be a universal problem solver in many cases :)

**Comment by reckart** [comment]
Thanks for the feedback.

**Comment by reckart** [comment]
Actually, we have two cases of accidental deletion here: 

* the POS layer is read-only and can be deleted by a type change
* the POS layer is editable, but relations on a read-only dependency layer can be deleted by a type change **or** by a deletion of the POS annotation

**Comment by reckart** [comment]
Incoming links from slot features not counted correctly when showing delete dialog.
