### ISSUE TITLE
Error when annotating span after relation

### ISSUE THREAD

**Issue by mbugert** [webanno/webanno#561]
**Steps to reproduce:**
1. Add an arc between two annotations in some document.
2. Switch to a different document / a different page.
3. Try to add some annotation.

**Expected outcome:** Annotation is added.
**Actual outcome:** Feedback panel says "Error: I don't know how to use [ArcAdapter] in this situation."

**Comment by reckart** [comment]
I assume you don't even have to switch to a different document/page in order to trigger it, right?

**Comment by mbugert** [comment]
Hah indeed. Well then, forget about step 2.

**Comment by reckart** [comment]
Changes break setting features on relation layers.
