### ISSUE TITLE
Customize mouse hover text

### ISSUE THREAD

**Issue by remstef** [webanno/webanno#587]
Customize the information that is shown when moving the mouse pointer over an annotation.

**Comment by remstef** [comment]
finished implementing, new functionality is to customize the content that is shown in the mouse hover box for span annotations. Customization is done via preferences in features and the layer itself (in order to choose not to show the spantext). See screenshots attached:

<img width="300" alt="screen shot 2017-09-11 at 21 53 22" src="https://user-images.githubusercontent.com/5611665/30294311-f1b309e4-973c-11e7-9ac7-b3b1c18fe73e.png">

<img width="300" alt="screen shot 2017-09-11 at 21 55 17" src="https://user-images.githubusercontent.com/5611665/30294395-36019f02-973d-11e7-9015-18fc8a4c10db.png">

<img width="300" alt="screen shot 2017-09-11 at 21 55 27" src="https://user-images.githubusercontent.com/5611665/30294455-697ad452-973d-11e7-99c9-edd273fcf0c8.png">

<img width="300" alt="screen shot 2017-09-11 at 22 01 33" src="https://user-images.githubusercontent.com/5611665/30294515-9c5ce23e-973d-11e7-8609-53513e8b1e19.png">

Quotes with empty content are removed (e.g. for spans with zero length)

<img width="300" alt="screen shot 2017-09-11 at 21 55 04" src="https://user-images.githubusercontent.com/5611665/30294548-c0d9214a-973d-11e7-9bf6-f7001ac917d0.png">

**Comment by reckart** [comment]
@remstef thanks for the screenshots! This really facilitates the discussion.

Is it sufficient to show only the feature value without the feature name? I suppose since there is quite a bit more space in the popup that in the actual annotation label, including the feature names would be useful.

**Comment by remstef** [comment]
That's true, there is indeed more space than in the label text, so we can actually think about having the feature name in there too. But then the tooltip might grow too long for the screen width, e.g. when the tooltip is near the right side. We could make one line per feature to show. But I'm not really convinced that it is necessary. Do you really think it is necessary, or should we just wait for such a feature request :)

**Comment by reckart** [comment]
I think it may be difficult for the user to correlate the values to their features without the feature names, e.g. if there are multiple numeric or boolean values users may have a hard time to remember which position is which feature. Because of the restricted space in the label, it is something one has to accept there. But I can well see people wanting to add a feature to the popup in order to be able to see better which value corresponds to which feature. 

I assume you have a use-case with actual users that motivate you to show this information in the popup. It might be worth trying to get feedback on this question form the actual users.

**Comment by reckart** [comment]
Anyway, whether or not to show feature names is nothing that should block the present PR.

**Comment by remstef** [comment]
Getting back from discussions with actual use-case users, the featurename is not required yet even wanted. If we change the behavior in the future in a different issue we should make the inclusion of the name optional.

**Comment by reckart** [comment]
@remstef The new feature only works on span layers, right? I just saw that VArc doesn't have a hoverFeatures map.

**Comment by reckart** [comment]
Are you still planning to add this for arcs in 3.3.0 or rather disable the configuration of this feature option in the project settings for 3.3.0?

**Comment by reckart** [comment]
I didn't check if the option was already disabled for non-span layers - if that is the case, great.

Btw. `setVisible(SPAN_TYPE.equals(layertype));` would be shorter ;)

**Comment by reckart** [comment]
Hm... keep this issue open or add a separate issue for hover features on arc? I'd tend towards the latter.

**Comment by remstef** [comment]
A new issue is cleaner imo, feel free to assign it to me

**Comment by remstef** [comment]
Please don't close this issue yet, I just realize I need to get back to the feature visibility filtering. I.e. the visibility of a feature value in a span's label shouldn't affect the visibility in the hover text.

**Comment by reckart** [comment]
Does github allow you to edit your comments, in particular the initial comment of this issue? You could add a checklist there what has been done and what remains to be done.

**Comment by remstef** [comment]
The discussion was in a code review for the pull request #642 as far as I remember, I can't find the comment anymore. Anyway, the issue is here:

https://github.com/webanno/webanno/blob/6be4a5b0f23e67e67b68e7baf4383ccf328dcaed/webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRenderer.java#L60

where the list of features is now just a list of visible features (visible in the sense that they are shown in the brat label of the span). See 192d7669e9aee6b76e63b1606f911d10f1ccb99d

But the hover text should be independent of the visibility in the label. I need to refactor 

https://github.com/webanno/webanno/blob/6be4a5b0f23e67e67b68e7baf4383ccf328dcaed/webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/Renderer.java#L60

such that it accepts visible and!! invisible featurelists.

**Comment by reckart** [comment]
How about passing the full unfiltered list of features to render() and filter for visibility inside the render method? It would require replicating the filtering for all three Renderer implementations, but may be preferrable to extending the method signature.

**Comment by remstef** [comment]
Actually something like that is already happening in for each renderer at least in the getFeatures()  method

https://github.com/webanno/webanno/blob/6be4a5b0f23e67e67b68e7baf4383ccf328dcaed/webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/Renderer.java#L72
 
Seems I didn't make myself clear enough regarding the fixme comment here: 192d7669e9aee6b76e63b1606f911d10f1ccb99d  :)

Anyway, I agree, I prefer duplicate filtering over interface changes :) I'll go for that

**Comment by reckart** [comment]
I think you pointed that this would being done redundantly. However, it is not entirely the case. The visibility filtering has to happen still in the same way and set the same field in the renderer implementation, but it can happen inside the renderer implementation.

**Comment by reckart** [comment]
In particular, this call here:

```
            // Render errors if required features are missing
            renderRequiredFeatureErrors(aFeatures, fs, aResponse);
```

needs to receive only enabled features (visibility actually is not relevant).

**Comment by reckart** [comment]
Or its implementation needs to be changed to not consider disabled features.

**Comment by remstef** [comment]
ah, yes, alright, I understand... how about this fix: edcb95a59ac505f8a313f9a4a7e00b35151c08e6

**Comment by reckart** [comment]
All checks here seem to relate only to visibility. Are disabled features filtered out somewhere?

**Comment by remstef** [comment]
right... now? :) (60cc8cfc6531c73adeb0dfc7ae83cf3ac0d5cff3)

**Comment by reckart** [comment]
How about doing a PR, that would allow seeing the aggregate changes instead of having to look at them commit-by-commit.

**Comment by remstef** [comment]
PR:  #665

**Comment by reckart** [comment]
Added a new issue (#679) regarding adding such a feature to arcs as well.

PR merged.

Does this resolve the issue?

**Comment by reckart** [comment]
Well, I guess it is resolved. @remstef if not, please reopen.
