### ISSUE TITLE
Enforce behaviors for Chunk layer

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#60]
The "Chunk" layer should have the following enforced behaviors:

* no crossing of sentence boundary
* no stacking - chunks are typically BIO encoded which does not allow nesting

**Comment by mmev** [comment]
Chunk layers are not necessarily encoded via BIO notation. Thus, I would like to have stacking as an option for Chunks too.

**Comment by reckart** [comment]
Ok. We'll probably need some warning then though, because it wouldn't be possible to export stacked chunks e.g. to CoNLL format. I guess that would be something that needs to be fixed

* in the export filter (DKPro writer component), so that the component produces a decent error message
* in WebAnno so that it picks up that error message and displays it to the user.

**Comment by reckart** [comment]
Closing in favor of #63
