### ISSUE TITLE
Non-primitive types must not be selectable when creating a feature on a relation layer

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#62]
Link features are only allowed on span layers. For features on relation layers, the non-primitive feature types must not be selectable. Right now, uima.tcas.Annotation and all the other span types are selectable even on a feature defined on a relation layer.

**Comment by aakashysharma** [comment]
Questions regarding this.

1. So, only primitive types uima.cas.* should be allowed. Rest everything should be removed/disabled?
2. Should a relation layer have a feature of type "relation layer"? (currently only "span" & "primitive" types are added in dropdown for feature.

**Comment by reckart** [comment]
Only span layers support link non-primitive features. 

The only non-primitied features that a span layer can have are other span layers and "uima.tcas.Annotation" (the latter means that a span can link to arbitrary other spans, not only to a single layer).

All other layer types (relation, chain) can only have primitive features.

**Comment by aakashysharma** [comment]
Just last confirmation before finalizing fix, 

So, if the layer is NOT of type **span**, feature type should be just primitive
uima.cas.String/Integer/Float/Boolean

**Comment by reckart** [comment]
> So, if the layer is *NOT* of type span, feature type should be just primitive
uima.cas.String/Integer/Float/Boolean

Yes.
