### ISSUE TITLE
Focus not working 

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#624]
After selecting an annotation span, focus is supposed to go to the first feature so that we can alternatively use keys to select the tag. Currently, focus is not there and I have to click explicitly. Tested with default NER layer.
Browser: Chrome
Versions: 3.3.x and SNAPSHOT
Tested by: @ChrisBieTUDA

**Comment by reckart** [comment]
Nice catch 👍 

Fixed by restoring a wrapper div on which DefaultFocusBehavior relies atm.

**Comment by normundsg** [comment]
After upgrading to 3.3.0 (from 3.2.1), the focusing does not work anymore...

**Comment by reckart** [comment]
I have opened a new issue for this: https://github.com/webanno/webanno/issues/754
