### ISSUE TITLE
Automation UI crashes

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#625]
The Automation interface do not show the suggestion pane

![image](https://user-images.githubusercontent.com/1056051/29684564-bc7280b2-8912-11e7-946b-21ab1572bd4c.png)
(not sensitive to number of sentences in settings) , What is this subscrolling?

(correction looks a bit better but not really, same subscrolling):
![image](https://user-images.githubusercontent.com/1056051/29684606-e2bb4d9e-8912-11e7-9473-57c69e04ccc5.png)

Browser: Chrome
Versions: 3.3.x and SNAPSHOT

**Comment by reckart** [comment]
Works in Safari but not in Chrome.

**Comment by reckart** [comment]
@seyyaw @ChrisBieTUDA could you please check b1985fae28b2811b6c6eb4fdbebedeb7020a41b2 - the space should now be equally distributed between the two panes. I tested locally in Safari, Firefox and Chrome.

If that is a good solution, I'll also apply it to the correction page. Please let me know.

**Comment by seyyaw** [comment]
Now it shows balanced space Except:
Increasing the number of sentences show starnange suggestion annotations. Example, first it opens 5 sentences as follows:
![screen shot 2017-08-24 at 10 02 06 pm](https://user-images.githubusercontent.com/1056051/29686157-40680004-8918-11e7-9c83-81d21f56c6ba.png)

If we change the sentence number to a larger one:
![screen shot 2017-08-24 at 10 02 44 pm](https://user-images.githubusercontent.com/1056051/29686178-528d0af4-8918-11e7-9a8d-aaf9f5bb5945.png)

May be it is related to the reloading after settings?

**Comment by reckart** [comment]
Can you please explain what problem you are seeing in these screenshots, because unfortunately, I don't understand what I am supposed to see.

**Comment by seyyaw** [comment]
At the bottom, annotations have black bg color, which is wrong...

**Comment by reckart** [comment]
The coloring of annotations is unrelated to the CSS which controls the layout. 

So I take it that the equal distribution between the panes via CSS is now good and I'll apply that CSS to the correction page as well. 

Could you please open a separate issue for the coloring?

**Comment by reckart** [comment]
Layout issue is fixed.

**Comment by reckart** [comment]
Added issue for the coloring here: https://github.com/webanno/webanno/issues/633
