### ISSUE TITLE
Delayed error messages

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#626]
![image](https://user-images.githubusercontent.com/1056051/29684249-941746e4-8911-11e7-93b7-cbca1947bf9d.png)
The red one refers to an attempt of empty document upload, but shows only after the successful upload. This consistent across all views, e.g.:
![image](https://user-images.githubusercontent.com/1056051/29684297-b263f002-8911-11e7-8d9d-4eac812d7654.png)

Browser: Chrome
Versions: 3.3.x and SNAPSHOT
Tested by: @ChrisBieTUDA

**Comment by reckart** [comment]
What do you mean by "across all views"?

**Comment by reckart** [comment]
The feedback panel is now rendered again as part of the import. It had been removed in commit 1ccc1510dc0621f2d006a2adecf4b1a4ee22e7f9 - unfortunately, I have no idea why. Missed that when reviewing the PR.
