### ISSUE TITLE
Bulk import leads to bulk messages

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#628]
Bulk import leads to bulk messages. these do not go away when changing tab and hide everything after.
![image](https://user-images.githubusercontent.com/1056051/29684495-770b43c4-8912-11e7-93a6-bdf1428db760.png)

Browser: Chrome
Versions: 3.3.x and SNAPSHOT
Tested by: @ChrisBieTUDA

**Comment by reckart** [comment]
I think this can be addressed by adding a "bulk close messages" feature. Also, I think it should be quite ok if informative messages only stay for a certain time and then disappear automatically while e.g. warnings and error should require explicit dismissal from the user. WDYT?

**Comment by seyyaw** [comment]
Yes, may be in stead of automatically disappear them, better to collapse them at the bottom right side to expand if required by the user later.

**Comment by reckart** [comment]
I have also been thinking about that, but I don't see a way of implementing this properly with adequate effort. Maybe @mbugert has an idea. In any case, I gather it is ok for the moment and future improvements regarding an "info tray" should be discussed in a separate issue.
