### ISSUE TITLE
user pane annoying message

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#629]
![image](https://user-images.githubusercontent.com/1056051/29684729-4a44b87e-8913-11e7-94de-8047485ddf0a.png)

Since it hides the create button I’d like to use next. 

Versions: 3.3.x and SNAPSHOT
Tested by: @ChrisBieTUDA

**Comment by reckart** [comment]
You notice that there is a "x" to close the notice, right?

**Comment by reckart** [comment]
Would the proposal made in #628 to auto-dismiss info messages after a short time address this?

**Comment by reckart** [comment]
I have added an auto-dismiss of info and success messages after 2 seconds. I think that should address the issue. If not, please re-open and provide additional details.
