### ISSUE TITLE
Remote API version 2 missing support for zip import

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#632]
While it looks like Remote API version 1 supports project create with file import, version 2's project create seems to be just for project creation with project name string.

Is this by design? I don't think the discussion from #455 included project creation API. But I think it is useful to be able to create project with some configuration through API.

**Comment by reckart** [comment]
#445 does include project creation. However, it does not cover importing a previously exported project. Rather a project can be created through the API and then documents can be added to it.

**Comment by kazukisan** [comment]
This might not be something to be covered by API, but how should a developer configure the project through API, such as layer, tagsets, etc, without going through UI?

I am thinking that, In a way, being able to import an existing project allows a project to be created and configured procedurally, if the developer creates a new project config based on an existing project export, but modifying that existing project, so that it is a new project.

(Don't think this is necessarily "issues", but trying to think of ways to do this)

**Comment by reckart** [comment]
You are absolutely right. In fact, there should be an import/export API in the new remote API, but I forgot to implement it. I have reopened #445 and will handle this there. I'm closing this issue here.

**Comment by kazukisan** [comment]
I think you meant #455, but #445

**Comment by reckart** [comment]
Yep ;)
