### ISSUE TITLE
User filtering behaves unexpectedly

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#634]
@bencampbell30  found a bug in the filtering functionality: When you add a new user to the list, they are not immediately removed from the list. They are only removed once you add another new user, and then that user remains in the list until another new user is added and so on. The added user remaining in the list also displaces the users below them in the list such that when you try to add a new user, it's not the one you clicked on:

For Example, if this is the list of users I can add to the project from the dropdown list:

Bob
Fred
James
Steve

If I add Fred, this is what the drop down list looks like the next time I go to add someone:

Bob
Fred
James
Steve

And then if I try to add James, Steve ends up getting added. The list looks like this the next time:

Bob
James
Steve

Also, is there any way an option for "contains" could be added, so that not only users whose username starts with the string typed are matched?

**Comment by reckart** [comment]
@bencampbell30 I atm I don't see an option to enable substring matching in the documentation of the Kendo Multiselect: http://docs.telerik.com/kendo-ui/api/javascript/ui/multiselect

**Comment by reckart** [comment]
Probably substring matching can be achieved by configuring the data source (http://docs.telerik.com/kendo-ui/api/javascript/data/datasource#configuration-filter.operator).

**Comment by reckart** [comment]
Ok, all fixed. Dropdown list updates properly; substring matching is enabled. I also found and set a flag to keep the dropdown open in case the project manager wants to add multiple users in a batch.

**Comment by bencampbell30** [comment]
Thanks!
