### ISSUE TITLE
Delete button does not appear when selecting guidelines, as per documentation

### ISSUE THREAD

**Issue by paulheider** [webanno/webanno#640]
According to [the documentation](https://webanno.github.io/webanno/releases/3.2.2/docs/user-guide.html#_guidelines), a "Delete" button is supposed to appear in the frame when the user selects a guidelines document.  This button doesn't appear with the latest release (full info below) in Chrome, Firefox, or Safari on a Mac OS X.  Functionally, the "Submit" button will delete whatever document is highlighted.  

Version info:  3.2.2 (2017-07-18 23:57:48, build 61cea1f0f7eda3b57d7c548d0577f166ac2830ce)

**Comment by reckart** [comment]
Thanks for the report!
