### ISSUE TITLE
 Is it possible to mark the same words automatically?

### ISSUE THREAD

**Issue by lucianojs** [webanno/webanno#643]
During the annotation jobs I noticed that I have several examples that use the same word. It's possible to do this automatically, without having to inform a Tag one by one.

**Comment by seyyaw** [comment]
@lucianojs The annotation component do not have such facility. There are a couple of ways to make the annotation rapid, though. 
1. **Forward annotation**:  If you are annotating single words and every words are going to be annotated, you can use the forward annotation functionality. This will not work if the annotation layer covers multiple tokens or sub tokens

1. Automation component's **copy annotator**: If you create a project in automation mode, and enable your automation layer for copy annotation, you can annotate the word/s once and it will provide suggestions for the rest of the word/s. But in this case, you need to accept them manually.

Best,

Seid M.
