### ISSUE TITLE
How can I use Constraints for FrameNet? It doesn't' work for me

### ISSUE THREAD

**Issue by hahmyg** [webanno/webanno#645]
Now I'm trying to build environment to annotate FrameNet on WebAnno

I would like to make "Constraints file" for the following task:
1) select the span to annotate Frame
2) WebAnno suggest the proper Frame candidates by following the rules in Constraints file
3) Frame Elements also

So I made _Layers_ and _Features_:
**Layer**: Frame
**Feature 1)** frame_index (type: String)
**Feature 2)** frame_elements (type: webanno.cumstom.Frame)
(and, of course, I add the **tagset** from FrameNet for **frame_index** and **frame_elements** _features_)
_(In this case, if I select the span on text, I can annotate frame and its frame elements slots well)_

And this is my example Constraints file:

**Frame {
  @Lemma.value = "teach" -> frame = "Education_teaching" | frame = "DUMMY";
  frame_index = "Education_teaching" ->     frame_elements = "Course" (!)
}**

As I understand in the documentation (https://webanno.github.io/webanno/releases/3.1.0/docs/user-guide.html#sect_constraints),

**Frame** is a _layer_ to apply my rules,
and if the text has the value "teach" in **value** _feature_ in **Lemma** _layer_, 
WebAnno suggest the "Education_teaching" tag from the tagset in the **frame_index** _feature_ in **Frame** _layer_ .

However, my "Constraints file" doesn't work on the Annotation on the WebAnno,
I means, there are no suggestion for the proper frame candidate, "Education_teaching"
(I select the span on the text "teach", and there is Lemma annotation as "teach", too)

Did I miss something in the documentation?
Or there are some faults in my settings? (Layer or Features)

It would be greatly appreciated if you could help me.

You can contact me freely, if you want to see my screenshot or something else
(hahmyg@kaist.ac.kr)

**Comment by aakashysharma** [comment]
Maybe a missing semicolon in second line?

**Comment by hahmyg** [comment]
[en.txt](https://github.com/webanno/webanno/files/1313723/en.txt)

@aakashysharma Attached file is that I import on WebAnno 

There are two rules, for 'frame_index' and 'frame_elements', 
and both rule doesn't work for me. Thank you for your quick reply.

**Comment by aakashysharma** [comment]
On a quick glance, I can see that you are missing the import statements.

You need to provide fully qualified names (you can view this in settings>layers) as import statements before defining the constraints. 

So, it would be something like (from the guide)
import <fully_qualified_name_of_feature> as <shortName>;

You'd need that for Frame and Lemma (I'm assuming  frame, frame_index and frame_elements are features of Frame. )

Also,
the last line has little typo "fframe_elements ".

**Comment by reckart** [comment]
I assume the question has been answered and the constraints are now working.

Thanks @aakashysharma!
