### ISSUE TITLE
Installation issues on Mac OS 

### ISSUE THREAD

**Issue by aaohmgd** [webanno/webanno#649]
I have followed the WAR installation instructions but I could not use the following command on Mac terminal :
**_aptitude install tomcat8-user authbind_**
So I could not apply all the following instructions in **Dedicated Tomcat instance** section and also **the deployment of WAR file** section
Is there any way to apply these instructions on Mac terminal ?
could you help me to find the best instructions to install the webanno WAR version on tomcat without an embedded database, please
Many thanks in advance

**Comment by reckart** [comment]
The instructions for a Tomcat-based installation are meant for WebAnno running as a service on a server. If you want to do that on OS X try googleing something like "install tomcat as a service on os x". I found e.g. [this tutorial](https://maltronic.io/2016/01/14/easily-install-apache-tomcat-on-mac-os-x-10-11-el-capitan-with-homebrew/).

Another alternative would be you simply run the JAR version and provide a `webanno.home` system property pointing to the directory where you want to store your data and where you keep your `settings.properties` file in which the database configuration is provided. You can use the information about the `settings.properties` file from the WebAnno installation guidelines, but regarding the installation of MySQL on OS X, you have again to google.
