### ISSUE TITLE
Switching project in projects view

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#651]
Switching project to another project does not seem to be working.

Steps to reproduce:

1. Go to the first project, then go to the export tab.
2. Export the whole project. This downloads the zip file of the first project.
3. Stay in the export tab, then choose another project like "second project".
4. Export the whole project, but this still downloads the first project, not the second project.

**Comment by reckart** [comment]
Another good catch!

**Comment by reckart** [comment]
Should be fixed now.

**Comment by reckart** [comment]
Needs still to be fixed for CAS Doctor tab.
