### ISSUE TITLE
How to add a written note linked to a custom annotation layer as a feature 

### ISSUE THREAD

**Issue by aaohmgd** [webanno/webanno#653]
Is it possible on Webanno during the annotation to add a written note as a feature that links to a custom annotation layer? 
Many thanks

**Comment by seyyaw** [comment]
Hi @aaohmgd 
If you mean that to have a custom written note that you can add to an arbitrary custom layer, the answer is no.
But it is possible to add an attribute to the custom layer (a feature) that is dedicated to add a note on the existing annotation. Example, if the Custom layer is called Entity and has a feature called value to add Entity value, you can further add a feature called note.


best

Seid M.
