### ISSUE TITLE
WebAnno does not build on JDK 9

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#656]
WebAnno does not build on JDK 9 due to some outdated Maven plugins.

**Comment by reckart** [comment]
It still doesn't build on JDK9 because even the latest version of the Asciidoctor PDF plugin doesn't yet seem to support JDK9.

**Comment by seyyaw** [comment]
I suggest delaying support of Java 9 until JDK 9 get stable.

**Comment by reckart** [comment]
JDK 9 (stable) has already been released. It is now the standard version of Java. It doesn't mean we should immediately start using Java 9 features, but it would be nice if I didn't always have to switch back to an older JDK before compiling WebAnno on the command line.
