### ISSUE TITLE
Layers and Tagsets in Webanno

### ISSUE THREAD

**Issue by Jona3007** [webanno/webanno#657]
Is there any way to modify the color schema in Webanno? I need a specific set of annotations to be red, others blue and others yellow. and Also, is it possible to be able to see a particular set of annotations without displaying the rest?

Thank you!

**Comment by reckart** [comment]
The colors are hard-coded and can presently not be changed. But since this comes up every once in a while, I'd like to know a bit more about how you imagine to set colors. Do you want that a certain layer has a certain color or that a certain label has a certain color?

You can hide layers either by unchecking the "enabled" checkbox of the respective layer in the project settings or by changing the layer visibility in the "settings" dialog directly on the annotation page.

**Comment by Jona3007** [comment]
Hello Richard,


Thank you for your prompt response, I was thinking on creating 4 different layers for annotation, each one with a primary color, the  labels would match the layers color schema. I noticed that when I annotate I get a certain color but once I uncheck the "enabled" checkbox of a layer, the other layers change their color schema, is there a way to fix this?


Thank you again for you time.


Best regards,

Jonathan


________________________________
De: Richard Eckart de Castilho <notifications@github.com>
Enviado: domingo, 01 de octubre de 2017 03:56 p.m.
Para: webanno/webanno
Cc: Jona3007; Author
Asunto: Re: [webanno/webanno] Layers and Tagsets in Webanno (#657)


The colors are hard-coded and can presently not be changed. But since this comes up every once in a while, I'd like to know a bit more about how you imagine to set colors. Do you want that a certain layer has a certain color or that a certain label has a certain color?

You can hide layers either by unchecking the "enabled" checkbox of the respective layer in the project settings or by changing the layer visibility in the "settings" dialog directly on the annotation page.

**Comment by Jona3007** [comment]
Hello, is this proprietary software? if yes, how much does it cost to acquire?


Thank you!


Jonathan


________________________________
De: Richard Eckart de Castilho <notifications@github.com>
Enviado: domingo, 01 de octubre de 2017 03:56 p.m.
Para: webanno/webanno
Cc: Jona3007; Author
Asunto: Re: [webanno/webanno] Layers and Tagsets in Webanno (#657)


The colors are hard-coded and can presently not be changed. But since this comes up every once in a while, I'd like to know a bit more about how you imagine to set colors. Do you want that a certain layer has a certain color or that a certain label has a certain color?

You can hide layers either by unchecking the "enabled" checkbox of the respective layer in the project settings or by changing the layer visibility in the "settings" dialog directly on the annotation page.

**Comment by reckart** [comment]
It is an open source project - no cost, no promises. Here is the license: https://github.com/webanno/webanno/blob/master/LICENSE.txt

**Comment by Jona3007** [comment]
Thank you for the information!

Sincerely,
Jonathan



Sent from my Sprint Samsung Galaxy S7 edge.


-------- Original message --------

**Comment by reckart** [comment]
> Thank you for your prompt response, I was thinking on creating 4 different layers for annotation, each one with a primary color, the  labels would match the layers color schema. I noticed that when I annotate I get a certain color but once I uncheck the "enabled" checkbox of a layer, the other layers change their color schema, is there a way to fix this?

It can only be fixed in the code. The current coloring code loops through a palette and picks a new color for each *visible* layer.

We had discussed custom coloring per tag in #383 - and it is a bit difficult at the level of tags. However, for entire layers, it should be reasonably easy to add to an upcoming version.

**Comment by reckart** [comment]
* Opened a separate issue for per-layer colors: https://github.com/webanno/webanno/issues/782
* Opened a separate issue for color-change on layer disable: https://github.com/webanno/webanno/issues/783
