### ISSUE TITLE
Pressing Enter or tab keys on multiple feature do not iterate

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#661]
When there are multiple features on a layer, pressing the Enter or Tab key will not proceed to the next text field during annotation. It saves the annotation (from the current field) and return back to the first text field

Version: 3.3.0-SNAPSHOT
browser: chrome

**Comment by reckart** [comment]
@seyyaw I can reproduce the problem over here. It is highly annoying that it appears again and again and it always takes a *lot* of time to debug and fix. Thus, I consider letting this issue slip to a future release, either 3.4.0 or 3.3.1.

**Comment by seyyaw** [comment]
@reckart I really see this a blocking issue. It means we totally disallow annotating on multiple features. If I have time, I can look into it, may be until beginning of November.

**Comment by reckart** [comment]
I just tested - I can use multiple features and I can fill them with values. I just have to use the mouse to click on the fields. It is not as if the user would be completely prevented from using multiple features as you say.

**Comment by seyyaw** [comment]
Ok, I also just test it.
Assume you have three features.

fill textfield one, and click (with mouse) text field two --> cursor comes back to text field one.

Click again text field two--> cursor stays there 

Now fill text field two and click click text field three --> focus goes to text field one

Then click again text field three -- now focus stays

Do you think this is not a problem and we can push it to the next release?

**Comment by reckart** [comment]
It is a problem, but I think it is not so critical, so I'd tend to push it to a bug-fix release.

**Comment by reckart** [comment]
There is a bank holiday here next week - maybe I find some time to have a look at it... but maybe not.
