### ISSUE TITLE
It is possible to add annotation on disabled layers

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#663]
When new span and relation layers and disable both of them. 1) It is possible to see the layers in the settings window of the annotation page 2) It is possible to create annotation both on the span and relation layers. After adding the annotations, the layers are automatically enabled (in the project settings page).

**Comment by remstef** [comment]
Hmmm... I need to test this, I honestly can't remember why I added it. I'll take a look

**Comment by remstef** [comment]
Ok, this code snippet was added because otherwise newly added layers do not appear in the preference dialog. There might a general misconception here, correct me if I'm wrong: If a layer is enabled or not is a user setting right? The enabled option in the project preferences is merely a default option, right? Here

https://github.com/webanno/webanno/blob/60897c125ebc43529436d3959bb95444e82224ff/webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/dialog/AnnotationPreferencesDialogContent.java#L263

a layer gets deactivated or activated in the user preferences. Did I get the concept of `enabled` wrong?

**Comment by reckart** [comment]
The enabled flag on the AnnotationLayer defines whether an administrator enables/disables a layer for all users.

The checkbox in the annotation page preferences settings defines whether a single user wants to see annotations on that layer or not.

If the admin disables a layer for all users, the users should not be able to see that layer at all in the preferences settings.

**Comment by remstef** [comment]
aha... ok, I see. I'll fix that. Hoping the error is related to that.

**Comment by reckart** [comment]
The same fallacy continues in AnnotationPreferencesDialogContent.

**Comment by remstef** [comment]
I fixed the misconception. Disabled layers are now disabled in the preference setting and cannot be annotated. 

However, I realized that something is still not updated properly but I'm not sure if that is actually a different bug. Here is the behavior:
1.) annotate a span with any layer (e.g. NamedEntity)
2.) deselect the layer (NamedEntity) in preferences
3.) annotate a different span
Error: The "Action" window shows a different layer, but the annotation window still has a reference to the NamedEntity Layer, you can see that the features of NamedEntity are provided. By selecting another layer in the "Action" window, the warning says to change the layer *from NamedEntity* to something else.

**Comment by reckart** [comment]
What probably happens right now is that "Named Entity" is still the selected layer, but it is no longer in the list of choices for the dropdown causing some other random layer to be displayed.

That's probably also something that should be handled in the preferences dialog directly or in the callback after it is closed: if the selected layer is no longer visible, then the selection should be updated.

**Comment by remstef** [comment]
Hm, yes... I tried resetting it (see 54b0bd8d828fdd8bf32bead2e4edee6a0db55ba9), but it didn't resolve the issue.

**Comment by reckart** [comment]
Hm. Looking at the code, the best place to catch these kinds of problems is probably `AnnotationFeatureForm.updateLayersDropdown()` which is called e.g. from `AnnotationPage.actionCompletePreferencesChange(AjaxRequestTarget)` - it seems not to be called atm from the other pages though (e.g. Curation, Correction, Automation), which looks like it could be a bug.

Did you see the effect on the annotation page or on one of the other pages?

**Comment by remstef** [comment]
It occurs in the annotation page, not sure about the others

**Comment by reckart** [comment]
@remstef Did you have any opportunity to check this out further? I see two commits in your fork, but no PR - and my understanding is that the commits don't really solve the issue.

**Comment by reckart** [comment]
Found your branch on the subject. I've created a PR now.

**Comment by reckart** [comment]
@remstef I could fix the remaining issue. Thanks! @seyyaw thanks for finding the bug.

**Comment by remstef** [comment]
@reckart, great, thanks a lot :)
