### ISSUE TITLE
Value of Slot features not displayed on the arc

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#664]
For layers with slot features, the value of the slot feature is not displayed on the arc, in stead the name of layer is displayed
Version: 3.3.0-SNAPSHOT
browser:chrome
layers: custom layers with two slot features

**Comment by reckart** [comment]
Actually it seems the label of the span annotation that owns the slot is displayed on the arc. But still a bug.

**Comment by reckart** [comment]
Fixed. Nice catch!
