### ISSUE TITLE
Improved TSV3 reader and writer

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#676]
There are various issues with the existing WebannoTsv3Reader and WebannoTsv3Writer including but not limited to incomplete support for subtoken annotations, slot annotations, and a very slow writing algorithm. Since the existing code is very dense, barely commented, and hard to understand, rewriting the whole thing from scratch based on the existing TSV3 test suite seems to be the best way forward.

**Comment by reckart** [comment]
@seyyaw any comments on this?

**Comment by seyyaw** [comment]
@reckart I will look into this. Thanks for the rework!

**Comment by reckart** [comment]
Mind that the new reader/writer are presently not yet used for import/export - only in unit tests. However, I have locally created a version which on every action a user makes in the annotation UI 1) stores the result as TSV, 2) loads thata again, 3) stores it again 4) compares 1 against 3 and I tested it with many different files (and fixed some more problems). No, the new code seems to very robust.

**Comment by reckart** [comment]
@seyyaw More testing has been done over here now and from my perspective, the new code looks ready now to replace the old one. I'm planning to do that commit in the next couple of days, then to make another beta release and shortly after to make the final release. If you have any comments, please provide them soon.

**Comment by reckart** [comment]
Activated the new implementation.
