### ISSUE TITLE
Batch open/lock/finish per user on monitoring page

### ISSUE THREAD

**Issue by adrianeboyd** [webanno/webanno#696]
It would be useful to have an option on the monitoring page to open/lock/finish all documents for a particular user.

In a project with sparse annotation, going through the "Finish" confirmation can take nearly as much time as the annotation itself, so I've had annotators skip "Finish" entirely and then have manually changed the status in the database by hand. It'd be nice to be able to do this from the monitoring page instead.

Batch open would be useful to have a way to include all documents in a project export even if they were not opened/annotated (see discussion in #693).

**Comment by reckart** [comment]
This is supported by the new workload management pages in INCEpTION.
