### ISSUE TITLE
Document index is off by 1

### ISSUE THREAD

**Issue by adrianeboyd** [webanno/webanno#697]
The document index in the various PositionInfo.text messages starts counting at 0 instead of 1, so it says "document 0 of N" and that you've reached the last document at N-1 of N.

(This seemed trivial so I looked briefly into fixing it, and all I will say is: yeesh.)

**Comment by reckart** [comment]
Do you want to submit a pull request?

**Comment by adrianeboyd** [comment]
No, I don't know how to do it in a sensible way, possibly because I don't know enough about wicket.

**Comment by reckart** [comment]
Ah, sorry - I read "yeesh" as "yes" ;) Never mind - I have committed a fix.
