### ISSUE TITLE
Chrome / Chromium and span annotations result in error

### ISSUE THREAD

**Issue by TFeige** [webanno/webanno#699]
When annotating a span (in arabic) that covers more than one token, the resulting selection ranges from the beginning of the page to the first selection. See attached gif (Annotation No.3 )
![chrome_error](https://user-images.githubusercontent.com/19265315/32553882-5bac1d76-c498-11e7-9992-0d1d58cdae9d.gif)

Used version:  build 8a5a286910e6c34798ba1213d8db715ed2d50bcc

Ubuntu 16.04 w. Chromium 62.0.3202.75
Windows 7 w. Chrome

On Ubuntu with Firefox the error didn't appear, although the "weird" selection shows when moving the span annotation to the next line, but it is possible to finish the annotation the intended way:
![chrome_error-firefox](https://user-images.githubusercontent.com/19265315/32554122-20320a48-c499-11e7-940d-cf6f522b3a1f.gif)

**Comment by TFeige** [comment]
I just tested build 53e043098e7170ad12d26cff943ef8c6754a6ea9. The behaviour is the same.
In addition: 
The error occurs, if I start the annotation at the token boundary. If I start with a space it works.

**Comment by reckart** [comment]
What do you mean by "if I start with a space"?

**Comment by TFeige** [comment]
If I start the annotation including the blank between the previous word and the word I want to annotate. I think it doesn't get included in the annotated span.

**Comment by reckart** [comment]
I think this is a duplicate or at least a variation of #316.

**Comment by reckart** [comment]
@TFeige if you have the opportunity, you might build a WebAnno from the code in PR https://github.com/webanno/webanno/pull/715 and see if that improves the selection behavior for you. Feedback would be appreciated!

**Comment by reckart** [comment]
Both problems also appear in LTR mode. If the mouse passes a part of the screen which is not part of any token or text, then the selection jumps around.

The first issue, namely that the selection jumps to the beginning of the page when dragging the selection inside a row, should be fixed now (cf. issue #316). It should be possible to create annotations in the expected ways. 

The second issue, namely jumping when selecting across rows, is not fixed - is it troublesome?

We should open a separate issue for the jumpyness when selecting across rows.

**Comment by reckart** [comment]
I have opened a separate issue for cross-row jumpyness and close this one.

https://github.com/webanno/webanno/issues/724
