### ISSUE TITLE
SRL annotation with CoNLL 2009 format

### ISSUE THREAD

**Issue by hahmyg** [webanno/webanno#705]
I'm working on the SRL annotation task with WebAnno.

Is there a way to work with the CoNLL 2009 format for SRL annotation?

When I import a SRL annotated CoNLL 2009 file,
there are no annotation about SRL (semanticPredicate, semanticArguments in CoNLL 2009 definition)
(Lemma, POS and dependency only I can see on WebAnno)

I cannot find any information that how to set a layer, and anything.
[conll2009_test.txt](https://github.com/webanno/webanno/files/1473853/conll2009_test.txt)

![webanno](https://user-images.githubusercontent.com/3884429/32825982-1ae54f1e-ca2a-11e7-864e-92c1a92a00ac.PNG)

**Comment by reckart** [comment]
@hahmyg Right... that somehow fell off the agenda for various reasons although it is by now a low-hanging fruit. I think this is something we can still get into the 3.3.0 release.
