### ISSUE TITLE
Tsv3XCasDocumentBuilder creates negative spans for zero-length annotations

### ISSUE THREAD

**Issue by adrianeboyd** [webanno/webanno#710]
The ``beginToken`` for a zero-length annotation in Tsv3XCasDocumentBuilder seems to be the previous token, so it ends up creating a negative span with min() below and then Tsv3XSerializer throws an exception due to a negative substring.

```
TsvSubToken t = beginToken.createSubToken(annotation.getBegin(), 
    min(beginToken.getEnd(), annotation.getEnd()));
```

**Comment by reckart** [comment]
This is a duplicate of #713.
