### ISSUE TITLE
Unable to annotate documents with sentence-final zero-length annotations

### ISSUE THREAD

**Issue by adrianeboyd** [webanno/webanno#712]
Error when opening a document for annotation that has a sentence-final zero-length annotation, such as 
https://github.com/webanno/webanno/blob/7180b9e1c47ae7de72337c41829f19441554a4b4/webanno-io-tsv/src/test/resources/tsv3-suite/testZeroLengthSpansWithoutFeatures/reference.tsv

```
Error: Unable to determine sentences in which the annotation starts/ends: SimpleSpan sofa: _InitialView begin: 16 end: 16
```

I'm not totally sure, but it seems like the annotator won't let me create an empty annotation at the end of a sentence. I can create one at the beginning, but not the end.

**Comment by reckart** [comment]
I remember writing that code. It is a bit tricky to figure out to which sentence zero-width annotations belong that are on the boundary. 

I think the current code can be improved for cases where two sentences are not immediately adjacent, i.e. where there is some whitespace between sentence 1 and sentence 2. However, if two sentences are immediately adjacent without any space between them, there is no way to tell to which sentence a zero-width annotations on the inter-sentence boundary belongs.

**Comment by adrianeboyd** [comment]
I only have zero-length annotations by accident (due to errors in my corpus), so I don't know what a useful solution would like here for projects who use them. (I just wanted to create a test case for #711  and thought the existing ones might be a good place to start.)

**Comment by reckart** [comment]
I'll try to see if I can improve the situation based on `testZeroLengthSpansWithoutFeatures/reference.tsv`.

**Comment by reckart** [comment]
I'm fixing this by treating zero-width annotations that are between two adjacent tokens always to be *at the end of the first token* rather than *at the beginning of the second token*.
