### ISSUE TITLE
CoNLL-U: sent_id annotations

### ISSUE THREAD

**Issue by normundsg** [webanno/webanno#714]
Sentence ID annotations (# sent_id) are lost when importing CoNLL/CoNLL-U files and exporting curated CoNLL/TSV3 files.

It would be also nice see sent_id somewhere in the annotation mode (e.g. on mouse over the line/sentence number).

**Comment by bansp** [comment]
I've just stumbled upon this as well, so I thought I'd give a +1 to this issue.
While I am new to this community and don't know the local customs, let me also mention that I was surprised seeing this marked as "enhancement" -- it seems actually a bit of a stumbling block for scenarios where bits of a corpus are sent to WebAnno for enhancements -- some kludges are needed to incorporate the output back into the corpus, or at least that has to be done manually, to keep track of where the given sentence belongs.

**Comment by bansp** [comment]
@reckart apologies if this wasn't on topic -- my use case was importing CoNLL-U with sent_id and not seeing (any) sent_id in the round-trip export back to CoNNL-U  -- that's how I thought my "+1" made sense. I wasn't aware that some additional conditions were relevant here :-)
