### ISSUE TITLE
Whitespace treated incorrectly at the end of spans in TSV3X exporter, annotator

### ISSUE THREAD

**Issue by adrianeboyd** [webanno/webanno#726]
When a span ends with whitespace (so the last token end is earlier than the span end), TSV3XCasDocumentBuilder chooses the following token as the endToken, creating a subtoken with a negative span under the subcase "Annotation covers only a prefix of the end token".

-----

Moved this part to separate issue: https://github.com/webanno/webanno/issues/727

Possibly related, in the annotation view (tested with 3.3.0-beta-6), if you have a span that's not locked to tokens and you select a token (or tokens) followed by whitespace, the end of the span jumps back to cover just the first letter of the final token. In the example below (with three spaces between each occurrence of "text") I had selected the token plus the whitespace following, but when I release the mouse the final annotation is as shown:

![webanno-whitespace](https://user-images.githubusercontent.com/5794899/33020322-33baaa7a-cdfe-11e7-8500-8eee4b85a5ed.png)

Weirder things happen if you select part of a token followed by whitespace: the annotation jumps to cover earlier characters in the token that weren't selected at all or no annotation is created. If I select 
``t`` plus whitespace, ``ex`` is annotated. If I select ``xt`` plus whitespace, ``e`` is annotated. If I select ``ext`` plus whitespace, nothing (!) is annotated.

**Comment by reckart** [comment]
Thanks for the feedback. I tried various selections as part of the refactoring and they all appeared to work as expected. I'll try to reproduce the effects you describe.

**Comment by reckart** [comment]
I can reproduce the UI issue. But I don't think this is related to the other problem you describe. 

What do you mean "a span ends with whitespace"? There is an assumption that a token span cannot include (start/end with) whitespace.

**Comment by reckart** [comment]
I moved the UI problem to a separate issue. Let's try to nail down the TSV error. Could you please try a different approach to describe to me how to reproduce/trigger the TSV problem?

**Comment by reckart** [comment]
@adrianeboyd I am trying to understand the problem description. Please consider the following example:

```
[   ] <= annotation
This is a test.
```

So the token in this case is "This" and the span of the annotation is "This " (i.e. it includes the whitespace after the token). Does the following example describe the problem you hit?

This kind of annotation can at the moment not be created in WebAnno. Whitespace between tokens cannot be selected and cannot be part of an annotation. 

Actually, with the latest changes to make the selection smoother, the whitespace between tokens can be selected in the browser, but the selection span is truncated to token boundaries before the selection is sent to the server. So no annotations that start or end in whitespace can be created via the UI.

Taking this into account, do you consider it necessary for the TSV3X to support this kind of annotation?

**Comment by adrianeboyd** [comment]
Yes, that's right. I was using the TSV3X writer outside webanno and had some longer span annotations of document sections, some of which ended with whitespace.

I don't think it's necessary to support this, but I guess I'd prefer if it didn't crash in these situations. Ignoring the annotation with a warning (like it does for other annotations that it doesn't support) might be a better option? The TSV3 writer ignored all these kinds of annotations, as far as I remember. (I'd use it instead, except for the memory leak / thrashing problem mentioned in #693.)

**Comment by reckart** [comment]
Thanks for the feedback! Let's keep it on the list of useful enhancements then but do it after 3.3.0.

**Comment by adrianeboyd** [comment]
I'll add that I couldn't get it to crash in the same way within webanno. If I import a binary CAS where a chunk ends with a space, it looks fine in the annotation view and gets exported with a zero-length subtoken like this:

```
#Text=Er gab der Frau nichts
1-1     0-2     Er      _       
1-2     3-6     gab     _       
1-3     7-10    der     NP[1]   
1-4     11-15   Frau    NP[1]   
1-5     16-22   nichts  _       
1-5.1   16-16           NP[1]
```
