### ISSUE TITLE
Text file truncation

### ISSUE THREAD

**Issue by hannahlindsley** [webanno/webanno#731]
When I add a file as .txt to a project and go to edit it, I see that it's been truncated. I'm not exactly sure what's happening here - it could be something to do with multiple line breaks?

**Comment by reckart** [comment]
The code that renders the annotations in the browser tends to get slow for long documents with lots of annotations. Therefore, WebAnno uses a paging approach where only a configurable number of sentences are shown at the same time. You can configure the number via the "Settings" icon in the action bar of the annotation page. You can move between pages via the forward/backward and first/last icons in the action bar.

Does that explain the effect you are observing?

**Comment by reckart** [comment]
I assume that the explanation resolves the question/problem. Should this not be the case, please re-open the issue.
