### ISSUE TITLE
Drawing an arc from a tag to the same tag

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#732]
Trying to draw an arc from a tag to the same tag (circular self-relationship) does not result in any arrow drawn in UI.
If pre-annoated with Governor and Dependent being the same, WebAnno does draw an arrow from a tag to the same tag, though.

**Comment by reckart** [comment]
Creating a self-looping arc requires pressing SHIFT. We tried it without that, but that caused a lot of innocent clicks create a lot of undesired self-looping arcs.

This is documented here: https://webanno.github.io/webanno/releases/3.2.4/docs/user-guide.html#_relations

Does it work if you use the SHIFT key while creating the arc?

**Comment by kazukisan** [comment]
Yes, it works if I press and hold shift before clicking as documented. Thanks for the reference.
