### ISSUE TITLE
Doc clarification: special characters in TSV3

### ISSUE THREAD

**Issue by sanmai-NL** [webanno/webanno#735]
https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/WebAnno%20(GitHub)%20(master)/de.tudarmstadt.ukp.clarin.webanno$webanno-doc/doclinks/1/#_reserved_characters

```
\,[,],|,_,->,;,\t,\n,*
```

So are both `-` and `>` special characters?

**Comment by reckart** [comment]
The way that TSV3 is presently defined/implemented, it kind of considers `->` as a single "character"... and it is also escaped as a single unit, i.e. `->` becomes `\->`. I know this is very odd, but it is way it currently is. It is something to be addressed in the next iteration of the format.
