### ISSUE TITLE
Doc clarification: definition of token

### ISSUE THREAD

**Issue by sanmai-NL** [webanno/webanno#736]
In https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/WebAnno%20(GitHub)%20(master)/de.tudarmstadt.ukp.clarin.webanno$webanno-doc/doclinks/1/#sect_webannotsv, AFAICT there is no definition of ‘token’. I suppose you mean the following:

1. A **token** is the longest sequence of grapheme clusters in which no code point has the Unicode character property `WSpace=Y`. 
2. Each token has an **index** that is an integer ≥ 1.
3. As the **sentence** is read in writing direction, the first token has index 1, whitespace is skipped, then the next token has index 2, and so forth.

Better still, can the grammar of TSV3 be based on a well-defined tokenization algorithm such as word boundaries according to [Unicode Standard Annex #29](http://unicode.org/reports/tr29/#Word_Boundaries)?

**Comment by reckart** [comment]
The format does not define what a token or a sentence actually is. The tokenization and sentence splitting are either performed outside WebAnno and the boundaries already exist upon import - or e.g. in the case of a plaintext import, WebAnno applies the Java BreakIterator to segment text into tokens and sentences. In any case, this is completely independent of the TSV format.

**Comment by reckart** [comment]
For TSV, a token is defined by a line such as this one

```
1-3        9-14        plays
```

I.e. the first column contains only the sentence and token IDs but no sub-token ID. Sentence and token IDs are integer values >= 1. A sentence boundary is detected by an empty line in the TSV file. Unicode are not relevant.

It seems to me that your description assumes a text-tokenization process (as e.g. the Java BreakIterator performs it), not a data-encoding/decoding process (as the TSV reader/writers do it).

**Comment by sanmai-NL** [comment]
@reckart: I'm writing software that produces TSV3. It is important to know how to index tokens, otherwise I cannot be sure the TSV3 files it produces have the intended meaning within WebAnno. Both tokens and indexes occur in TSV3 instances, so the definition of ‘token’ is necessary to define the semantics of TSV3. `BreakIterator` seems strictly compatible with UAX#29, but the latter is just richer. Is it possible to switch over in WebAnno from [`BreakIterator`](https://docs.oracle.com/javase/8/docs/api/java/text/BreakIterator.html) to [`ICUTokenizer`](http://www.solr-start.com/javadoc/solr-lucene/org/apache/lucene/analysis/icu/segmentation/ICUTokenizer.html)? This would allow the TSV3 spec to simply use the definition of ‘token’ as in UAX#29 (or the equivalent term) and be done with it. Another value of it would be that data producers no longer need to care about tokenization as far as punctuation is concerned. E.g. the spaces around the comma and period in 
> A great , great wall .

would become superfluous.

**Comment by reckart** [comment]
As I said, the definition of a token is completely orthogonal to TSV3.

WebAnno internally uses the Java BreakIterator. Switching it to another tokenizer is technically possible but not planned. The internal BreakIterator is just a convenience in case somebody imports a format which does not already contain token and sentence boundaries (e.g. plain text). If there is a good reason to switch to another default tokenizer in WebAnno, please consider opening a separate issue for that. Again, please mind that tokenization is completely independent of the specification of the TSV3 format. However, once tokens and sentences exist, TSV3 will encode them in a specific way.

If a user wants to use WebAnno with a particular tokenization and sentence splitting scheme, then the currently recommended way is to apply this scheme externally to the input data and afterwards import the data into WebAnno. WebAnno and TSV3 do not care what tokenization scheme and sentence splitting scheme is externally applied as long as some basic expectations are not violated, e.g. that tokens may not overlap, that sentences may not overlap, that tokens do not exist outside sentences, that sentences start and end at token boundaries and possibly additional constraints that don't come to my mind right now.

If you want to feed data tokenized with the ICUTokenizer into WebAnno, then pre-process your data with that tokenizer outside of WebAnno and save it e.g. as TSV3 or XMI and import that into WebAnno.

**Comment by reckart** [comment]
Just as a test, I have imported the sentence `A great, great wall.` into WebAnno and exported the result as TSV. Mind that in this example, there is no space before the comma and also non before the period:

```
#FORMAT=WebAnno TSV 3.2


#Text=A great, great wall.
1-1	0-1	A	
1-2	2-7	great	
1-3	7-8	,	
1-4	9-14	great	
1-5	15-19	wall	
1-6	19-20	.
```

The first thing we can see here is that  BreakIterator in this case seems to be splitting the sentence in the correct way.

We can also see that TSV is well able to represent the sentence without the extra spaces.
