### ISSUE TITLE
Clearing 'lock to token offset' box does not enable annotation of partial tokens in 3.2.4

### ISSUE THREAD

**Issue by SJones-Appen** [webanno/webanno#743]
Hello, I am running a project in v3.2.4 and am unable to annotate partial tokens in a custom layer for which the 'lock to token offset' box has been cleared. I have tried undoing and resetting the settings for the layer, but am still unable to annotate partial tokens. Thank you in advance for investigating!

**Comment by reckart** [comment]
Is the "Lock to multiple tokens" checkbox also disabled?

**Comment by SJones-Appen** [comment]
Don't seem to have a box like that. Have "allow multiple tokens," which is enabled.

**Comment by reckart** [comment]
Right, that's the one. Disable that one as well, then you should be able to do sub-token annotations. There is an issue (although I don't have the number handy) to replace these two unintuitive checkboxes with a more sensible dropdown box offering choices like "lock to characters", "lock to tokens", and "lock to multiple tokens" (not necessarily exactly these labels).

**Comment by kazukisan** [comment]
It's this: https://github.com/webanno/webanno/issues/443

**Comment by SJones-Appen** [comment]
Thanks for your quick replies! Do I correctly understand this to mean that multiple token selection is always enabled, and this setting only governs whether a multi-word span's width is locked to the two outermost character offsets?

**Comment by reckart** [comment]
If "Lock to token" is enabled, annotations can only cover exactly one token, not more, not less. The start/end of the annotation must be the start/end of one token.

If "Allow multiple tokens" is enabled, annotations can cover one or more tokens. The start of an annotation must be the start of a token and the end of and annotation must be the end of a token, but it doesn't have to be the same token.

If both options are disabled, annotations can begin and end anywhere. They can also be zero-width annotations if you press shift while clicking on a position.

Mind that whitespace between tokens can never be annotated on its own. Also, mind that the "Allow crossing sentence boundaries" option restricts where annotations can be placed if "Allow multiple tokens" is enabled or if both options are disabled. It is not possible to enable "Allow multiple tokens" and "Lock to token" at the same time.
