### ISSUE TITLE
After upgrading to 3.3.0 (from 3.2.1), the focusing does not work anymore...

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#754]
After upgrading to 3.3.0 (from 3.2.1), the focusing does not work anymore...

Cf. https://github.com/normundsg

**Comment by normundsg** [comment]
Still not working for me... Neither in Chrome nor in Safari.

**Comment by reckart** [comment]
Ok, so I just tested (again) with 3.3.1. The focus works if the first field is a text field. It fails if the field is a combobox (i.e. if there is a tagset).

**Comment by reckart** [comment]
It might be related to https://github.com/webanno/webanno/issues/719 - I'll have another look at it.

**Comment by reckart** [comment]
Actually, this loops back to an old issue and it is due to the way the Kendo ComboBox works (https://github.com/webanno/webanno/issues/146). In retrospective, the things that we tried to fix this only made things worse: highly complex and unintuitive code, erratic behavior when tabbing through fields in the annotation editor panel - very annoying. As far as I can tell at the moment, both #719 and #772 boil down to the same thing.

I have an 1-2 ideas how this might be fixable, but I don't know yet if they will work. I recommend to watch #719 and #772.
