### ISSUE TITLE
Error opening settings dialog in curation mode

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#755]
Error opening settings dialog in curation mode. Was reported on the mailing list.

```
Caused by: java.lang.NullPointerException
        at de.tudarmstadt.ukp.clarin.webanno.ui.annotation.dialog.AnnotationPreferencesDialogContent$1.populateItem(AnnotationPreferencesDialogContent.java:266) ~[webanno-ui-annotation-3.3.0.jar:?]
        at org.apache.wicket.markup.html.list.ListView.onPopulate(ListView.java:523) ~[wicket-core-7.8.0.jar:7.8.0]
        at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:124) ~[wicket-core-7.8.0.jar:7.8.0]
        at org.apache.wicket.Component.internalBeforeRender(Component.java:950) ~[wicket-core-7.8.0.jar:7.8.0]
        at org.apache.wicket.Component.beforeRender(Component.java:1018) ~[wicket-core-7.8.0.jar:7.8.0]
        at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1825) ~[wicket-core-7.8.0.jar:7.8.0]
        ... 166 more
```

WebAnno 3.3.0.

**Comment by reckart** [comment]
@remstef The line which triggers the error was last touched by you in commit  2492fa8e88c12f4642ce800f45f3dfd8d9cbaecb as part of #663. Do you have an idea?

**Comment by reckart** [comment]
Debugging shows that `preferredLayers` is null when this exception is thrown.

```
List<Long> preferredLayers = pref.getAnnotationLayers();
boolean isPreferredToShow = preferredLayers.contains(item.getModelObject().getId());
```

**Comment by reckart** [comment]
Looks like the problem is related to the introduction of the new multi-value features in the per-user settings. The per-user settings are stored in the same preferences file but are prefixed by the `mode`, i.e. annotation, correction, automation, and curation. 

If no file exists or if it cannot be read, then the per-user settings are initialized with defaults. This usually happens in annotation, correction, automation (which are mutually exclusive because a project can only have a single mode).

If a file exists, there is no initialization with defaults.

Thus, when the settings are read in a new mode (i.e. in curation mode), there are no default values. In particular, we get null values for the new multi-value preferences that were introduced with #531 and the code expects that these preferences are never null.

The fix should be to initialize default preferences when a file exists but no preferences for the selected mode are stored there.

**Comment by remstef** [comment]
I'm not able to reproduce this error on the latest 3.3.x branch. Here is what I do:

1. create a project  & add documents
1. annotate documents with 2 users (w/ matching and non matching annotations)
1. finish documents
1. go to curation mode and select the document
1. click on settings
1. change and save settings (a file ${WEBANNO_HOME}/repository/project/{project}/settings/{username}/annotation.properties is created)
1. logout
1. login
1. go to curation mode and select the document
1. click on settings 
1. my saved properties are shown

no Exception is thrown during the process. Second run:

1. create a project  & add documents
1. annotate documents with 2 users (w/ matching and non matching annotations)
1. click on settings in the annotation view (for a particular user)
1. change and save settings (a file ${WEBANNO_HOME}/repository/project/{project}/settings/{username}/annotation.properties is created)
1. finish documents
1. go to curation mode and select the document (w/ same user)
1. document looks weird, only beginning is shown
1. click on settings
1. nullpointer exception is thrown

OK, so the exception is thrown when the file already exists (why? - I don't know yet). As I understand it, there should be independent files, i.e. in the first run the file `${WEBANNO_HOME}/repository/project/{project}/settings/{username}/annotation.properties` shouldn't even have been created, but `${WEBANNO_HOME}/repository/project/{project}/settings/{username}/curation.properties`. But where is that implemented? In `ProjectServiceImpl` I can find a variable `annotationPreferencePropertiesFileName` which is used in `ProjectServiceImpl.loadUserSettings` and `ProjectServiceImpl.saveUserSettings`

**Comment by remstef** [comment]
sorry, mode is prefixed, I see the code now

**Comment by remstef** [comment]
3e5ba2cd18b14e9a73b76dc036b381b02425494e fixes the NullPointerException issue

**Comment by reckart** [comment]
The `no preference found` catch case sets additional defaults - shouldn't all defaults be set if a the preferences in a given mode have not been initialized yet?

**Comment by remstef** [comment]
> document looks weird, only beginning is shown

seems to be a different issue, might be related to 2 different users curating the same document?

**Comment by reckart** [comment]
It should not be a problem if 
* user A enters curation interface,
* curates document X
* A leaves curation interface
* user B enters curation interface,
* curates document X
* B leaves curation interface

However, if A and B open the same document for curation and then A does something (e.g. add/delete an annotation), then what is displayed in the browser of B is no longer in sync with the server. This concurrent curation of a document scenario is presently not supported.

**Comment by reckart** [comment]
Could you post a screenshot of "looks weird"?

**Comment by remstef** [comment]
can't reproduce it, but it was probably related to '...what is displayed in the browser of B is no longer in sync with the server...'

**Comment by reckart** [comment]
@remstef what do you think about https://github.com/webanno/webanno/issues/755#issuecomment-349437085?

**Comment by remstef** [comment]
still testing a bit... sorry just came back to the computer, didn't want to miss the bus ;)

**Comment by remstef** [comment]
>  shouldn't all defaults be set if a the preferences in a given mode have not been initialized yet?

as I see it, only the colors and the layers themselves are initialized with default values here... I can see that most preferences are initialized with a default value in the `AnnotationPreference` class itself. I think that is indeed the best place for that, only that Layers and ColoringStrategies are not known to that object at initialization time. So... I don't have a strong opinion, maybe you have a better opinion, but I think the `PreferencesUtil` should not have the responsibility for "normal" default values that are independent of the project. I'd leave it as it now is.

**Comment by reckart** [comment]
Roger.
