### ISSUE TITLE
Broken UI layout: Constraints tab in Projects Settings

### ISSUE THREAD

**Issue by normundsg** [webanno/webanno#762]
![constraints](https://user-images.githubusercontent.com/1726922/33663958-973aa89a-da9a-11e7-8f31-9b82f56dcba9.png)

**Comment by reckart** [comment]
Which browser?

**Comment by normundsg** [comment]
Google Chrome (Version 62.0.3202.94)

**Comment by reckart** [comment]
Thanks. I can reproduce it. Works on Safari, but broken on Firefox and Chrome.
