### ISSUE TITLE
Luminous POS tags: an option to turn it off

### ISSUE THREAD

**Issue by normundsg** [webanno/webanno#763]
My annotators are complaining about the luminous POS tags in 3.3.0 - it distracts their focus from semantic role annotation. Would be great to have an option to turn this highlighting off.
![pos](https://user-images.githubusercontent.com/1726922/33664940-f3bcffa2-da9d-11e7-9002-665349e5c334.png)

**Comment by reckart** [comment]
Ok. This is an artifact of the "yield" that is shown in the on-mouse-hover-box for POS tags with attached dependency relations. 

I'll see to add a way of including information in that box without triggering the glow.
