### ISSUE TITLE
Question: document state upon opening

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#770]
The version of webanno currently deployed in my environment is a much older version (from June or so), but I wanted to make sure one thing. When an annotator opens the new document, is the annotation state intended to be changed to "in-progress" right away? Or, if the annotator opens, but does nothing about the document, is it intended to retain "new" state ? (I am observing some randomness in this behavior in the currently deployed version, so I wanted to see what the expected behavior is)

**Comment by reckart** [comment]
Checking the 3.3.x code, it looks like the state is changed from NEW to IN_PROGRESS only when the first change is made (i.e. when an annotation is added/removed/updated), but not if the document is just opened.

**Comment by kazukisan** [comment]
Hmmm I seem to get an inconsistent behavior. There is a project that doesn't mark it blue (in progress) when I open a document, but there is also another project that marks it blue as soon as I open a document. A bit random. Let me know if you need more info.

Tried the origin/3.3.x branch.

**Comment by reckart** [comment]
Could you try setting a breakpoint in ` de.tudarmstadt.ukp.clarin.webanno.api.dao.DocumentServiceImpl.writeAnnotationCas(JCas, AnnotationDocument, boolean)` where the document state is set to `IN_PROGRESS` and post the stack trace for the project which switches the document to blue as soon as you open it?

**Comment by reckart** [comment]
Closing as there was no further feedback.
