### ISSUE TITLE
Action buttons placed unintuitively

### ISSUE THREAD

**Issue by normundsg** [webanno/webanno#774]
Example:
![dblclick](https://user-images.githubusercontent.com/1726922/33928897-23190906-dff0-11e7-8e33-927a3ff835b2.png)
When an annotator/curator double clicks a Frame annotation (e.g. "Self_motion"), the Layer under Actions does not change accordingly (e.g. from "LU" to "Frame"). Annotators are confused about this.

(The Annotation pane is generated accordingly.)

**Comment by normundsg** [comment]
P.S. Version 3.3.1.

**Comment by reckart** [comment]
Tried this locally, but so far I cannot reproduce it. What I cannot see from your screenshot is whether your use might have activated the option "remember layer" which causes the dropdown under "Actions" not to change anymore when an annotation is selected. Instead, the type of the selected annotation is shown under "Annotation".

![2017-12-13_10-58-04](https://user-images.githubusercontent.com/1410238/33932975-b530f2f0-dff4-11e7-9b71-66a26c0611d7.png)

**Comment by normundsg** [comment]
Indeed, this is because of the activated "remember layer" option.

But still a bit confusing - because of the co-located Delete and Clear buttons. It seems that these buttons are related to Layer, but they might not be related.

**Comment by reckart** [comment]
Maybe it would be better to have the buttons in the "annotation" part. They are only relevant when an annotation is actually selected.

**Comment by normundsg** [comment]
Yes, that would be the best solution!
