### ISSUE TITLE
Clicking sentence numbers in the curation view does not work

### ISSUE THREAD

**Issue by normundsg** [webanno/webanno#775]
![sentences](https://user-images.githubusercontent.com/1726922/33929615-c9df2020-dff2-11e7-8c2a-fa75dddd8251.png)
When entering the curation mode, clicking on sentence numbers works well. However, when I do something in the annotation pane (e.g. select an annotation), clicking on sentence numbers doesn't work anymore.

WebAnno 3.3.1

**Comment by reckart** [comment]
That is very odd and unexpected - but I can reproduce it. Thanks!
