### ISSUE TITLE
RemoteAPI v2 file export for annotated/curated docs result in cas binary for xmi format

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#785]
Sub URLs could be different for each developer, but because these curations / annotations URL use GET method, I will just paste an example URL:

http://localhost:8080/webanno/api/v2/projects/2/documents/669/annotations/test?format=xmi
(test is the annotation username)

Somehow, even though "xmi" is specified as the format, this downloads a CAS binary file, although it has .xmi at the end. This happens with download of both curation and annotation documents in v2 RemoteAPI.

Downloading the original "source" doc works file with "xmi" file format, though.

Using 3.3.x branch. Is this reproducible?

**Comment by reckart** [comment]
I can(not) reproduce it - kind of... 

`http://localhost:8080/webanno-webapp/api/v2/projects/1/documents/367/annotations/admin?format=xmi`

This is a CoNLL-U document. The filename generated for the downloaded file also has the extension ".conllu" - but in fact it is a ZIP file which contains the XMI. 

Mind that the "read document" action also simply uses the document name as the designated filename - it does also not change the extension.

**Comment by reckart** [comment]
Actually, "read document" **does** change the extension... and **read annotation** seems to have a bug here...

**Comment by kazukisan** [comment]
Thanks, I will give this a try again.
