### ISSUE TITLE
Unable to click tags in Firefox in 3.3.x

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#786]
Hovering over annotated tags does not activate clickable behavior in 3.3.x branch

Firefox 57.0.1, Mac OS 10.10

**Comment by kazukisan** [comment]
Somehow unable to reproduce this myself after a new mvn build + Tomcat restart.
If you cannot reproduce this, please close.

**Comment by reckart** [comment]
You mean that double-clicking a "bubble" does not select the annotation?

**Comment by kazukisan** [comment]
The mouse hover itself isn't working during annotation. I could reproduce this now. (The reason why I couldn't reproduce this last time was because I temporarily tried master branch's visualizer.js )

**Comment by reckart** [comment]
For me the hover popup works in Firefox 57.0.1 on OS X 10.11.6 using 3.3.x (df51984a24537bef7981b3a9b4844f5aff045c73)

![2017-12-30_00-59-09](https://user-images.githubusercontent.com/1410238/34449785-ab5b1458-ecfc-11e7-8637-e80dfc63612f.png)

I can also double-click on annotations to select them and their color changes when I move the mouse over them. Do you see anything unusual in the JS console/log?

**Comment by kazukisan** [comment]
It doesn't happen in all documents, that could be a tricky part. But when it happens it behaves like this:
https://www.youtube.com/watch?v=GpdAppjFLLI

No special log in the console.

Taking some commits from master for files like visualizer.js and annotator-ui.js seems to address this, though. And in Chrome there is no issue.

**Comment by reckart** [comment]
The only changes between 3.3.x and master that I can see are in visualizer.js and they relate to the differential update that I pushed to master yesterday. Otherwise, the files you mentioned seem to be in sync between master and 3.3.x. Which commits are you referring to?

**Comment by kazukisan** [comment]
When I do 
```git diff master..3.3.x ./webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js```

I am seeing differences related to #724 in my environment:
```
diff --git a/webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js b/webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
index 146624515..c80691f0f 100644
--- a/webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
+++ b/webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
@@ -216,7 +216,12 @@ var Visualizer = (function($, window, undefined) {
     };

     var Row = function(svg) {
+// BEGIN WEBANNO EXTENSION - #724 - Cross-row selection is jumpy
+/*
       this.group = svg.group();
+ */
+      this.group = svg.group({ 'class': 'row' });
+// END WEBANNO EXTENSION - #724 - Cross-row selection is jumpy
```

**Comment by reckart** [comment]
I assume this means that your master includes these lines, but your 3.3.x branch does not.

But it looks like the "official" 3.3.x branch includes the respective lines:

https://github.com/webanno/webanno/blob/bc5f920fef9c186f75f5ad2bf737aae6c5e3eeea/webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js#L218-L224

When I locally compare 3.3.x to master, I see changes related to the following issues in master only:

* #709 - Optimize render data size for annotations without labels (~line 1093 + ~line 2757)
* #790 - Differential updates for brat view (~line 3831 + ~line 4346)

**Comment by kazukisan** [comment]
Thanks for the info and sorry for confusion on my part. There was something that went wrong with pull from upstream on my end.

**Comment by kazukisan** [comment]
And yes it works fine in Firefox. Sorry for this once again.
