### ISSUE TITLE
Curation: after picking annotator's tag, annotation view moves to top

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#788]
The annotation content is large enough that seeing people's annotation requires scrolling down. That is fine but when picking some tags from some annotator in the bottom or so, the curation view gets refreshed and annotator view also gets re-rendered to assign new colors, etc. However, the annotator view scrolls back to the top.

It would be better for productivity if the content being viewed could stay where it has been, instead of moving all the way back to the top.

(Tried this in 3.3.x branch)

**Comment by reckart** [comment]
This is the same as https://github.com/webanno/webanno/issues/418 right?

**Comment by kazukisan** [comment]
Yes, and #418 was filed in January 11 of 2017, I completely forgot about what I filed. Actually, this behavior is working with code from June 2017, much before Bootstrap UI update.

A long story but that's the version of tool we've been still using because IT department decided to firewall maven dependencies in August and it took this long to sort out the issues, (nothing I could do for a long time). New security policy requires artifacts built by internal Bamboo process within this firewall.

The reason why you've seen some new issues opened by me recently is because I am trying to deploy 3.3.x branch internally, now that Nexus firewall issue seems partially resolved.

Anyway, this curation annotation picking somehow seems to works fine in June 2017 version. But eventually they are the same issues in terms of usability. I will close this one.

**Comment by reckart** [comment]
@kazukisan June 2017 would be a 3.2.x version or a 3.3.x version from that time?

**Comment by kazukisan** [comment]
The specific commit used was e6449e1dde33208f32bbdf0579cf39b70131e962 , and this is from 3.3.0 SNAPSHOT. (I was always using master branch instead of officially "released" versions)

If you try that commit, picking user annotation in curation works very well, and the viewport correctly moves back to the location of the picked annotation upon content view refresh.
