### ISSUE TITLE
Remote API response body's curation state does not reflect the actual state

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#801]
After successfully changing the curation state to "CURATION-COMPLETE", the response body still returns state "NEW", although I can confirm it indeed changed the curation state to complete. This happens also when setting the document to "CURATION-IN-PROGRESS". (Also, it doesn't look like "NEW" is supported for curation state via API???)

Tried this via swagger-ui.html.

CURL
```
curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: application/json' {"type":"formData"} 'http://localhost:8080/webanno/api/v2/projects/2/documents/668/curation?format=xmi&state=CURATION-COMPLETE'
```

Request URL
```
http://localhost:8080/webanno/api/v2/projects/2/documents/668/curation?format=xmi&state=CURATION-COMPLETE
```

Request Headers
```
{
  "Accept": "application/json;charset=UTF-8"
}
```

Response Body
```
{
  "messages": [],
  "content": {
    "user": "CURATION_USER",
    "state": "NEW",
    "timestamp": "2018-01-04T10:37:04-0500"
  }
}
```

Response Code
```
201
```

**Comment by reckart** [comment]
@kazukisan actually, that response is kind of correct. 

When you upload a curation for a document, then you can optionally set the **source document status**.

However, the status that is returned from the POST call is the status of the **annotation document** (of the `CURATION_USER`).

Looks like we need another parameter to also allow setting the status of the **annotation document** (of the `CURATION_USER`).

**Comment by reckart** [comment]
Or we use the `state` parameter here to only set the state of the **annotation document** and adjust the state of the **source document** accordingly:

* if there is no state parameter, set the source document state to **CURATION-IN-PROGRESS**.
* do the same if the state parameter is set to **IN-PROGRESS**.
* if the state parameter is **COMPLETE**, then set the source document state to **CURATION-FINISHED**.

**Comment by reckart** [comment]
The way that annotation state and document state are presently managed in WebAnno is a bit error-prone since the document state is usually updated explicitly instead of being updated implicitly when the annotation/curation status changes. I have opened a separate issue for that: #819

**Comment by kazukisan** [comment]
If no state param is given, I think setting it to CURATION-IN-PROGRESS sounds good. And in the end, it is a /curation/ endpoint, so limiting the acceptable states to just what curation document can have sounds good.
