### ISSUE TITLE
Remote API's curation deletion results in a weird state

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#803]
To reproduce:

-Finish annotation of a document in GUI so that it will be available for curation.
-Finish curation of the document
-Use API's DELETE to delete the curation
-By "open"ing the window dialog to see available curation, that document is still colored "red"
-But after opening the document, there is no curation document available (the top panel is empty), although the document state is still "Finished".

Desired behavior:
When curation deletion API removes the CURATION_USER's document, it should also adjust the state from "CURATION-COMPLETE" to something else.

**Comment by reckart** [comment]
I guess the state should be set back to ANNOTATION_IN_PROGRESS.
