### ISSUE TITLE
Being able to see document ID from curation

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#812]
While doing annotation, it is easy to see the document ID now, because it can be found in the URL.
However, I wonder if there would be an easier way to retrieve the document ID during curation because the document ID is not shown in URL or anywhere, currently.

One idea:
At the right side, there would be string like "Showing 1-44 of 44 sentences [document 44 of 46]"
This could add document ID info like "Showing 1-44 of 44 sentences [document 44 of 46, ID: 12345]"

**Comment by reckart** [comment]
@kazukisan Do you need this for development or for production?

**Comment by kazukisan** [comment]
This would be for production but I realize this may be too specific to some environment.
It is good to see the document ID, if there is a suspicious curation which needs to be re-opened, but done via API rather than through monitoring. If there is a project with 1000+ documents with 15 annotators, it is just quite slow to be able to re-open documents for curation / annotation, etc.

So, it is ultimately better for the long term to address the speed concerns of monitoring page. I would like to close this, if fine, I think this benefits only certain users using certain workflow.

**Comment by reckart** [comment]
Your call. Some pages already show database IDs in developer mode - that is why I was asking. In production mode, it may just clutter the UI with IDs that normal users normally cannot make any use of.

**Comment by kazukisan** [comment]
I don't know how useful this would be for development mode. If needed, I think this could be either re-opened or new issue. Thanks for the response!
