### ISSUE TITLE
Refreshing the curation page doesn't result in correct state after changing state in API

### ISSUE THREAD

**Issue by kazukisan** [webanno/webanno#816]
From 3.3.x branch.

To reproduce:
* Go to curation document that is already marked Finish, or click Finish if curation is not done yet
* Keep this curation page open
* Use remote API to mark the document back to CURATION-IN-PROGRESS
* Go to the curation page still open, and it should still show "Finish" being checked.
* Refresh the webpage
* Now "Finish" is no longer checked with green color check mark, but trying to modify the curation results in "Error: This document is already closed. Please ask your project manager to re-open it via the Monitoring page". This means WebAnno still thinks the curation is locked, although state is "CURATION-IN-PROGRESS".

Workaround:
After the state is changed after using API, rather than refresh, click "Next" document, then "Prev" document to come back to the same document, then the CURATION-IN-PROGRESS state is indeed reflected.

**Comment by reckart** [comment]
It is not related to the remote API. The code which checked whether a document is done or not in curation mode used a stale value stored in the UI state. The same effect could be achieved when changing the curation document state via the monitoring page.

For curiosity: how did you change the (curation) document state via the remote API... I didn't find any call that would allow that (short of uploading a new document).

**Comment by kazukisan** [comment]
Right, the change of state was achieved by uploading a new document, but with a new state in the API call's parameter.
