### ISSUE TITLE
Add orthography layer into TCF reader

### ISSUE THREAD

**Issue by seyyaw** [webanno/webanno#825]
Dear all,

i wanted to tokenize and add some annotations by using the DTA::CAB tools. The tool automatically makes a tokenization and adds pos and lemma annotations as well als orthography corrections for each token (if necessary). The output format is tcf.

The POS and LEMMA layer is directly visible after importing the TCF-File to webanno, but anyway I am not able to see the orthography/correction annotations. I was not able to find the correct settings to create a layer which shows these annotations.

Can anyone give me an idea what to do to get these annotations shown in webanno? :)  

Here you can see a selection of the tcf-file:
```
    <orthography>
      <correction tokenIDs="w1" operation="replace">ANDREAE</correction>
      <correction tokenIDs="w5" operation="replace">Freuden-Spiel</correction>
      <correction tokenIDs="w7" operation="replace">auf</correction>
...
    </orthography>
 ```

Thanks a lot in advance
Marcel

**Comment by reckart** [comment]
@seyyaw there is are some problems implementing this feature at this time: 

- the corresponding types in DKPro Core is SofaChangeAnnotation or Anomaly - but both are not fully equivalent with the TCF orthography layer. SofaChangeAnnotation would be closest.

- WebAnno has no concept of the `tokenIDs` property of TCF orthography annotations (cf. https://github.com/weblicht/tcf-spec/blob/master/src/main/rnc-schema/textcorpus_0_4.rnc#L60)

If you wish to investigate this, please do it on a feature branch and do a pull request. Please do not modify the code in 3.3.x or master directly. Also, please outline here in which way you indent to address this request.

**Comment by reckart** [comment]
Before I replied to Marcel's mail, I had a look at the TCF specification for the orthography layer to see if it is a low-hanging fruit. However, it doesn't seem to be really.

First a suitable DKPro Core type needs to be identified to which this layer can be mapped. Most closest would be the SofaChangeAnnotation. But the "operations" supported by DKPro Core SofaChangeAnnotation and TCF orthography are different.
DKPro Core SofaChangeAnnotation supports "insert", but TCF orthography supports "insert-before" and "insert-after".
The DKPro Core annotation is offset-based while the TCF annotation is token-based. It may be possible to harmonize this over some time.

The second and probably more difficult problem is that neither WebAnno nor DKPro Core have any suitable concept to support the "tokenIDs" property of TCF:

       # reference to token/tokens that are corrected
       attribute tokenIDs { xsd:IDREFS }?,

https://github.com/weblicht/tcf-spec/blob/master/src/main/rnc-schema/textcorpus_0_4.rnc#L60

Hence, at the moment, I do not think that TCF orthography can be properly supported with a clean and neat implementation. Hacks should be avoided.
