### ISSUE TITLE
Feature details not completely transferred while exporting/importing a project

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#83]
If a Layer has more than one Feature, while exporting/importing a project, only the first Feature's tagset setting is retained.
The second feature's tagset configuration is missing.

![bug 82_1](https://cloud.githubusercontent.com/assets/1897100/9302182/e6624e22-44d4-11e5-9f65-7f41584148b3.png)
![bug 82_2](https://cloud.githubusercontent.com/assets/1897100/9302183/e6650982-44d4-11e5-9b77-1e8526bc955d.png)

**Comment by aakashysharma** [comment]
Currently, in AnnotationLayer.java, it has space for only one AnnotationFeature. 

private AnnotationFeature attachFeature;

Is this design intentional? A layer can have more than 1 feature I believe.

**Comment by seyyaw** [comment]
No, a layer can have multiple features
The column has ManyToOne relationship

    @ManyToOne
    @ForeignKey(name = "none")
    @JoinColumn(name = "annotation_feature")
    private AnnotationFeature attachFeature;

**Comment by reckart** [comment]
There is some documentation on the data(base) model for layers here:

https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/WebAnno%20(GitHub)%20(master)/de.tudarmstadt.ukp.clarin.webanno$webanno-doc/doclinks/3/#_layers

**Comment by aakashysharma** [comment]
Checked code and tested with different combinations and different layers and projects.
Only happens with the above case. 
Even created similar features in a new layer and exported them and imported. 

Putting the issue on hold for now.
