### ISSUE TITLE
User may accidentally shut down WebAnno during startup

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#830]
When webanno is started (not headless), after some time it puts up a little
window with a "Shutdown" button.

On Windows, the box and the button are "selected".

This has an unfortunate consequence.  If while waiting for webanno to
initialize, you have another window open (like an email composition window) and
are typing, then what happens is that in the middle of typing some word, the
WebAnno dialog box/buttom appear and become selected, and the next keystroke
goes to that window / button, essentially "pushing" (by accident) the shutdown
button, which then shuts things down!

**Comment by mbugert** [comment]
> On Windows, the box and the button are "selected".
I'm having the same issue on Ubuntu.

**Comment by mbugert** [comment]
See pull request #848.

**Comment by reckart** [comment]
I wonder actually why the window pops to the front at all.... does this happen with all new windows that are opened by a "background" application?

**Comment by reckart** [comment]
Seems to be a thing of JDialog:  https://stackoverflow.com/questions/823795/jdialog-lets-main-application-lose-focus

**Comment by reckart** [comment]
Actually, it might help to simply make the dialog **not** modal...
