### ISSUE TITLE
Error: Unable to determine sentences in which the annotation starts/ends: POS sofa: _InitialView begin: 166 end: 169 PosValue: "NOUN"

### ISSUE THREAD

**Issue by adindabudi** [webanno/webanno#856]
I have imported tsv like this in my webanno docker version 3.3.0. 
`#FORMAT=WebAnno TSV 3.2
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS|PosValue

#Text=Bila kamu termasuk salah satu pengguna Instagram yang hobi berburu kuliner, aplikasi pencarian makanan Qraved baru saja menunjuk top 10 akun Instagram kuliner Tanah Air
1-1	0-4	Bila	ADP
1-2	5-9	kamu	PRON
1-3	10-18	termasuk	VERB
1-4	19-29	salah satu	DET
1-5	30-38	pengguna	NOUN
1-6	39-48	Instagram	PROPN
1-7	49-53	yang	PRON
1-8	54-58	hobi	NOUN
1-9	59-66	berburu	VERB
1-10	67-74	kuliner	NOUN
1-11	75-76	,	SYM
1-12	77-85	aplikasi	NOUN
1-13	86-95	pencarian	NOUN
1-14	96-103	makanan	NOUN
1-15	104-110	Qraved	PROPN
1-16	111-115	baru	PROPN
1-17	116-120	saja	ADV
1-18	121-129	menunjuk	VERB
1-19	130-133	top	NOUN
1-20	134-136	10	NUM
1-21	137-141	akun	NOUN
1-22	142-151	Instagram	PROPN
1-23	152-159	kuliner	NOUN
1-24	160-165	Tanah	NOUN
1-25	166-169	Air	NOUN`

I successfully import file but i cannot open it. Here are the error message in logs:
2018-02-19 07:52:50 ERROR [adindabudi] ApplicationPageBase - adindabudi: Error: Unable to determine sentences in which the annotation starts/ends: POS
   sofa: _InitialView
   begin: 166
   end: 169
   PosValue: "NOUN"

Error: Unable to determine sentences in which the annotation starts/ends: POS sofa: _InitialView begin: 166 end: 169 PosValue: "NOUN"

**Comment by reckart** [comment]
@adindabudi Did you find/fix a problem in your data?

**Comment by adindabudi** [comment]
yes, i miscalculated the offset of tokens when creating the tsv file
