### ISSUE TITLE
Cannot Export Curated Documents or Export to TSV 3 in Annotation/Curation

### ISSUE THREAD

**Issue by adindabudi** [webanno/webanno#859]
I successfully import tsv file that created programatically by script to Webanno 3.3.0. Text and tokens in tsv file is already annotated programmatically also. And then, i edited some annotations with Webanno, But I cannot export again my tsv file. 

I get the exception like this in logs:
```
2018-02-20 05:22:11 ERROR [adindabudi] ApplicationPageBase - adindabudi: Error: Aborting due to unrecoverable error while exporting!
2018-02-20 05:22:11 ERROR [adindabudi] ApplicationPageBase - adindabudi: Unable to export curated documents because of exception while processing.
```

```
Caused by: java.lang.NullPointerException
2018-02-20 05:22:11 ERROR [adindabudi] ProjectPage - Error: de.tudarmstadt.ukp.clarin.webanno.ui.project.export.ProjectExportPanel$ProjectExportForm$5 failed to retrieve a File object from model
java.lang.IllegalStateException: de.tudarmstadt.ukp.clarin.webanno.ui.project.export.ProjectExportPanel$ProjectExportForm$5 failed to retrieve a File object from model
```

**Comment by reckart** [comment]
Please go to the project settings of your project and look for a tab titled "CAS Doctor". Use it to check your data for known inconsistencies.

**Comment by reckart** [comment]
Btw. I would recommend upgrading to WebAnno 3.3.3. Check the release notes from 3.3.1 to 3.3.3 here: https://github.com/webanno/webanno/releases

**Comment by adindabudi** [comment]
I have upgraded my webanno version to 3.3.3, but i got the same Error. I've also tried to check and active repairs with CAS doctor, but still cannot export to TSV3, But I can export to another format.

**Comment by reckart** [comment]
If you could export the entire project and select "Binary CAS" during the export and send it to me privately (or attach it here if there is no problem in making the data public), I could try having a look at the issue.

**Comment by reckart** [comment]
@adindabudi Looks like there is a problem with offsets in your data. E.g. look at the XMI export of `01.tsv`. The NullPointerException in the TSV export happens in the last sentence. Below we see the last tokens of the last sentence from the XMI export: the sentence ends before the last Token ends. All tokens must be inside sentences.

```
    <type4:Token xmi:id="240542" sofa="12" begin="68456" end="68460" pos="240551"/>
    <type4:Token xmi:id="240561" sofa="12" begin="68461" end="68466" pos="240570"/>

    <type4:Sentence xmi:id="240366" sofa="12" begin="68409" end="68465"/>
```

So looks like you may have a bug in the code which generates the TSV format for you.

If you are not using Java to generate your TSV files but e.g. Python, please check out the notes on offsets in TSV (https://webanno.github.io/webanno/releases/3.3.4/docs/user-guide.html#_encoding_and_offsets)

This case is not yet covered by a CAS Doctor check, but there already is an issue to also check for this case (https://github.com/webanno/webanno/issues/217).

**Comment by reckart** [comment]
Closing this issue as it could be tracked down to bad input data.
