### ISSUE TITLE
Default coloring strategy is static --> making color scheme configurable

### ISSUE THREAD

**Issue by GiantEnemyCrab** [webanno/webanno#861]
Not sure this is an issue or not, but I believe all tags are expected to have different colors by default? (dynamic coloring). If so, ``` private boolean staticColor = true;``` from ```AnnotationPreference.java``` is making the best initial default to be static, though it states about backward compatibility. I think seeing different colors (dynamic) is a good default but this may be more of personal preference.

By the way, I think "pastelle" should become "pastel" in the text.

-----

- [ ] "pastelle" should become "pastel"
- [ ] "dynamic" vs "static" difficult to understand
- [ ] default coloring scheme configurable via project settings

**Comment by reckart** [comment]
The default is that every layer has its color (except for the chain layers where every chain has a color). 

When you open a document, all of the layers are by default visible. If every tag gets its own color on a document with multiple layers I'm afraid it would look like a confetti explosion.

**Comment by kazukisan** [comment]
I see, thanks for the response. And that explains it if the expectation is that people set up projects with multiple layers.

On my end, there hasn't been many projects that utilized multiple layers, but instead we normally have just one layer, and in that case, it is nice to see different colors for different tags.
This has been completely customizable on my end, and I think that's fine because this is more of a preferential matter. So I don't know if there is a need for code change then?

Another note while on this topic. There doesn't seem to be any difference between "dynamic" vs "dynamic pastelle", or "static" vs "static pastelle". They fall into the same case statement, so I wondered about these existence.

**Comment by reckart** [comment]
> This has been completely customizable on my end, and I think that's fine because this is more of a preferential matter. So I don't know if there is a need for code change then?

Well, we could consider defaulting to a color-per-tag scheme if a document is opened in a project with only a single enabled layer... might be confusing though.

We could also consider making the default coloring scheme configurable in the project settings to allow project managers to set up a suitable default scheme for their annotators and to avoid some overhead.

> Another note while on this topic. There doesn't seem to be any difference between "dynamic" vs "dynamic pastelle", or "static" vs "static pastelle". They fall into the same case statement, so I wondered about these existence.

Good question. Looking at the comment "ignore for the moment and fall through", it seems to me as if the code is incomplete. Probably there should be cases using the PALETTE_NORMAL for the non-pastel cases.

**Comment by kazukisan** [comment]
I think coloring scheme configurable in project settings is a good way to go.

**Comment by kazukisan** [comment]
Another question. I find it rather difficult to interpret the difference between "static" vs "dynamic". "static" is for one color per layer and "dynamic" is for one color per tag?

**Comment by reckart** [comment]
We could use "Color per tag" instead of "dynamic" - any suggestions for an alternative for "static"?

**Comment by kazukisan** [comment]
I had an impression that "static" was "one color per layer". Is that true?

**Comment by reckart** [comment]
Indeed, but wouldn't it look kind of strange to have "one color per layer" in a table such as:

| Layer        | Coloring  |
|--------------|-----------|
| POS          | per tag   |
| Named Entity | per layer |

... I mean there are not multiple layers "under" Named Entity, so "per layer" might be a bit off ... but maybe that's just me.

**Comment by kazukisan** [comment]
I see!
"one color" or "single color", then?
(wish I was a UIUX / wordsmith expert)

**Comment by reckart** [comment]
I would believe this is sufficiently addressed by the modularized and configurable coloring #1603.
