### ISSUE TITLE
Auto-logout broken

### ISSUE THREAD

**Issue by mbugert** [webanno/webanno#864]
In WebAnno 3.3.4, commit dc8a4e574b1c649740d62a2a380c023fad956a97, this happened when the auto logout feature was supposed to kick me out:
![webanno_logout_failure](https://user-images.githubusercontent.com/23331603/36554556-e00cf6e8-17ff-11e8-9ef7-e12056787062.gif)

I checked the log, it doesn't mention anything related to the issue.

**Comment by reckart** [comment]
dc8a4e5 is just the release commit - no changes to the code.

That said, I have an idea what may cause this problem: the timer that reloads the page does not seem to stop when the timeout period is over. Instead it continues to "tick" every second. So if the page-reload takes longer than a second, we see this effect. The solution should be to actually stop the timer once the reload triggers.
