### ISSUE TITLE
Copy annotator not working

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#87]
Reported on mailing list:

> Are annotation suggestions broken in 2.3.0?
I'm a happy user of the feature that suggests previously annotated words (WebAnno 2.2.0 on Linux, without providing training files).
Unfortunately, I could not make this feature work with the newest release of WebAnno. I have even deleted all files in /tmp and ~/.webanno. So I wanted to know, whether other users can confirm this behaviour.

**Comment by reckart** [comment]
@seyyaw I believe it is fixed, right?

**Comment by seyyaw** [comment]
yes, fixed
