### ISSUE TITLE
While opening a document for annotation, it doesn't show which project is selected

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#88]
If you go from home screen to Annotation, it'd open projects/documents panel, however there's no indication of which project is selected and which project those documents belong to.

Issue exist in other parts of webanno such as Curation too. Attached screenshot.

![issue88](https://cloud.githubusercontent.com/assets/1897100/9415596/bc6a6d2e-4840-11e5-98e1-dac37e5e6f3b.PNG)

**Comment by reckart** [comment]
I guess that no project or document is selected at the start. If you press "open", I would expect that nothing happens. What kind of improvement do you suggest?

**Comment by aakashysharma** [comment]
But it's showing documents of first project. At least it should show that these documents are of first project.

**Comment by reckart** [comment]
Fixed as part of #1547.
