### ISSUE TITLE
Example Projects

### ISSUE THREAD

**Issue by samhavens** [webanno/webanno#885]
Hi! Thank you to the developers and maintainers of this project, it looks great.

As a new user, I have to admit it is a bit hard to get started with this. Docker makes it _really_ easy to boot, but I think having example projects would be amazing. If there are examples that I missed, I'm sorry.

**Comment by reckart** [comment]
@samhavens we have examples on our downloads page: https://webanno.github.io/webanno/downloads/

**Comment by reckart** [comment]
@samhavens btw, I have also just pushed the latest version (3.3.4) to Dockerhub:

https://hub.docker.com/r/webanno/webanno/tags/
