### ISSUE TITLE
export as webanno tsv 3 and reimport breaks relations

### ISSUE THREAD

**Issue by Pils19** [webanno/webanno#886]
I mentioned a bug with the webanno tsv 3  export.
When i'm going to export a file with relation annotations in webanno tsv 3 format, all relations with direction from left to right going to break. This means the start point will also be the endpoint in the tsv file and after reimport the relation starts and ends at the same word.  For if i annotate "This is a simple test sentence ." in the same way as in the image below and export it - I get the fellowing tsv. 
![bug_image](https://user-images.githubusercontent.com/11837585/37347509-48eeb54e-26d2-11e8-9434-66020fee45bd.png)

```
#T_SP=de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS|PosValue
#T_RL=de.tudarmstadt.ukp.dkpro.core.api.syntax.type.dependency.Dependency|DependencyType|flavor|BT_de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS


#Text=This is a simple test sentence .
1-1	0-4	This	DET	nsubj	basic	1-1	
1-2	5-7	is	_	_	_	_	
1-3	8-9	a	_	_	_	_	
1-4	10-16	simple	_	_	_	_	
1-5	17-21	test	_	_	_	_	
1-6	22-30	sentence	NOUN	_	_	_	
1-7	31-32	.	_	_	_	_	
```

Reimporting this will lead to an relation from "This" to "This". See the image below.
![bug_image_2](https://user-images.githubusercontent.com/11837585/37348937-8b46f642-26d5-11e8-97f4-817597fc990d.png)

I used a fresh new webanno instance from docker hub (3.3.4) to reproduce this bug.
This Bug also turns up in 3.3.0.

**Comment by reckart** [comment]
Thanks, will look into this!

**Comment by reckart** [comment]
@Pils19 good catch. The TSV3 test suite was written following the DKPro Core conventions for relations, namely that the offsets of the relation should match that of the dependent. However, WebAnno does not follow this convention. For the moment (3.3.x), I am fixing the TSV3 test suite and the writer code.
