### ISSUE TITLE
Option to display stack trace instead of simply "Internal Error"

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#91]
Option to display stack trace instead of simply "Internal Error" - will be helpful for feedback with testers.

**Comment by mmev** [comment]
The stack trace is ok, please add the "Return to the main page" additionally.
(I do not remember, how the "return" line was named.)

**Comment by reckart** [comment]
It's a built-in page. We could eventually replace it with a custom page that has additional links and information (e.g. also shows the exact build, WebAnno version and potentially more stuff that could be useful to report) - however, for the moment, the trace is all I can offer.
