### ISSUE TITLE
Annotate part of word

### ISSUE THREAD

**Issue by futurespy** [webanno/webanno#912]
I don't know if there's already a way to do that, but when manually creating a WebAnno TSV3 I can specify where a token begins and end, but for documents already in the project, I cannot change where the token begins and end. Being able to annotate a prefix or suffix without having to export and import the document again would be useful sometimes (I mean, being able to redefine a token boundary).

**Comment by reckart** [comment]
Go to the the "layers" tab in the project settings. Locate the layer where you want to make sub-token spans. Uncheck all of the following options:

* Lock to token
* Allow multiple tokens

Now you should be able to mark arbitrary spans of test including token suffixes/prefixes on the chosen layer.

Mind that you cannot make an annotation consisting only of whitespace between tokens.

**Comment by reckart** [comment]
The above only allows you to create annotations at arbitrary locations and only works for custom layers. Most of the built-in layers are locked to token positions.

The approach does not allow you to redefine token or sentence boundaries. These boundaries are not editable in WebAnno.

**Comment by futurespy** [comment]
Nice. I've recreated the default layers and worked like a charm! Thanks!
