### ISSUE TITLE
(relations vs Link features) + constraints

### ISSUE THREAD

**Issue by jrouces** [webanno/webanno#917]
Hi,

I am starting to use WebAnno and I am having problems understanding which of two possible ways of modeling my data I should use, as well as how I can use constraints with each. Maybe I am missing something.

My use case is the following: I want to annotate texts spans bearing sentiment, and for each of these spans, I want to have the option of link other two spans in the same sentence representing targets and sources of sentiment. It is a sort of "single-frame two-role" frame annotation. I also want to add coreference info for the cases where the source or target are pronouns.

1/ One way I see of modeling this is creating 
- a layer Concept of type span
- a layer SentimentTerm of type span with a feature of type String for the sentiment and a feature of type Concept which I can use to add roles Source and Target.

I suspect this is the intended way because what I am doing is a kind of semantic predicate and this is the example use for the use of "Link features" with roles (the name role even is the same as the one used for semantic role). However, it requires a significant amount of work for the annotator. Unless I am missing something, the annotator has to type "Target" and "Source" every time, there is no drop-down menu. I have tried to use constraints to reduce the options to Target and Source:

import webanno.custom.Concept as Concept;
import webanno.custom.SentimentTerm as SentimentTerm;
SentimentTerm {
  sentiment = "5" -> arguments.role = "Target" | arguments.role = "Source";
}

The condition sentiment = "5" is because I was not sure if an empty condition would be accepted.

However, it seems that the annotator still has the write Target and Source. Also, I am not sure how the validation works, there seems to be a very small icon of a red exclamation sign when it is not validated, but this is very easy for the annotator to miss or ignore. Am I missing something here? I thought the CAS Doctor had something to do with constraint validation but it seems not to be the case.

I am omitting the corref part in this version because it would make my illustration more complex.

2/ Another way I see of modeling this is creating 
- a layer Span of type span with a feature of type Integer for the sentiment and 
- a layer Relation of type relation attached to Span, with a feature of type String with possible values {Target, Source, Corref}. 

This is a much simpler model, and requires less clicking and typing for the annotator (something that imo is critical for large annotation efforts), but because relations can only connect spans of the same layer, all spans have the attribute of type Integer for the sentiment. This is not a big problem but it is redundant and semantically unclear and has the potential to confuse annotators. I have tried to solve it with constraints but I haven't found how.

In general I think Webanno is very good because it seems to be the only opensource annotation software that supports a complex flexible model and is actively maintained. However, I find the documentation difficult to follow at several points. Maybe one or two use cases as running examples would help.

Best,
Jacobo.

**Comment by reckart** [comment]
@jrouces check out the screenshots in #918

**Comment by jrouces** [comment]
Thanks.

I had misread "mandatory or common" for just "mandatory" in the documentation, and since in my case they can be left blank, I was not using the (!). Now that I see that it doesn't make them mandatory it works for me.

For the condition, I just made a copy for each of the possible 5 values of sentiment. That seems to work although if you have other ideas for dummy tautological conditions it could be interesting for other people, and for me too since for the coreference I would need that (otherwise maybe I can use a layer of type relation for that one).

I was also wondering if there is some way to avoid the confirmation pop-up that says: "You are about to replace an annotation of type SentimentTerm with a new annotation of type Concept. This action will discard all feature values and delete 0 relation(s)/link(s) attached to current SentimentTerm annotation. Are you sure?"

It adds a new click for every "frame" when using this method with different span layer types. I understand that it is dangerous to delete information, but when that happens is only for the set of annotations connected to that one, which should normally not be too large, so the possibility of trade-off with speed could be good for some users.

**Comment by reckart** [comment]
> I was also wondering if there is some way to avoid the confirmation pop-up that says: "You are about to replace an annotation of type SentimentTerm with a new annotation of type Concept. This action will discard all feature values and delete 0 relation(s)/link(s) attached to current SentimentTerm annotation. Are you sure?"

Open the "settings" dialog on the annotation page and enable **Remember layer**. In that mode, the dialog only appears if you really delete an annotation. However, you cannot change the type of an existing annotation anymore. You'd have to delete/re-create.
