### ISSUE TITLE
Upgrade 3.2.1 to 3.3.5, unable to open some documents

### ISSUE THREAD

**Issue by Quadrocompile** [webanno/webanno#921]
I'm currently in the process of upgrading our WebAnno isntallation from 3.2.1 to 3.3.5. However, there is an issue with the project file attached. The project contains 10 documents, however only 7 can be opened after the project has been imported into the new WebAnno installation. KERN2021_NN_von_Wesen.tsv, KERN2021_ein-NN-von-einem-NN-SICHTUNG.tsv and KERN2021_ein-NN-wie-ein-NN-gesichtet.tsv fail to load with the following error:

Error: The reader for format [ctsv3] is unable to digest data: Line 18: Expected sentence header or token but got [SUBTOKEN]

I verified that these documents can be opened with the still running WebAnno version 3.2.1. I used the tsv3 export option and repeated the whole export/import process just to make sure, but it yields the same result.

Any help would be appreciated!

(On a sidenote: is there a hidden feature to bulk-export all projects from a current installation? We have about 50 project files and exporting all one-by-one is quite tedious, especially since the export of larger projects takes forever. The export of our biggest project file (42mb on disk) took nearly two hours...)

[NN_von_NN_2018-04-21_2123.zip](https://github.com/webanno/webanno/files/1934913/NN_von_NN_2018-04-21_2123.zip)

**Comment by reckart** [comment]
I'd recommend you *make a backup* of your WebAnno home folder and of your MySQL database and then do an *in-place upgrade* of WebAnno. WebAnno 3.3.0 comes with completely rewritten TSV3 code and WebAnno versions prior to 3.3.0 are known to have a significant number of bugs in TSV3.

**Comment by Quadrocompile** [comment]
Well, the guide recommends the exporting/importing method so I tried that. We are moving the instance to another server, so with the mysql data already loaded to the database of version 3.3.5, should it suffice for the "in-place upgrade" to just copy the /srv/webanno folder from the old 3.2.1 version to the new server?

**Comment by reckart** [comment]
yep

**Comment by reckart** [comment]
After the upgrade, I'd recommend you go through each project with the CAS Doctor on the project settings page and run a diagnosis. If you see trouble, try the repair with the default settings. Before activating any repairs that are not enabled by default, I'd recommend [reading them up](https://webanno.github.io/webanno/releases/3.3.5/docs/developer-guide.html#sect_casdoctor).

**Comment by Quadrocompile** [comment]
I moved the files from the old installations /srv/webanno folder to the 3.3.5 installations server but now there is not a single document in either project that can be loaded

Error reading initial CAS for [KERN2021_NN_von_Gestalt.tsv]: Source file [KERN2021_NN_von_Gestalt.tsv] not found in [/srv/webanno/repository/project/75/document/125/source/KERN2021_NN_von_Gestalt.tsv]

The files are neither in the directory of the 3.2.1 version, nor in the directory of the 3.3.5 version. However, when searchign for the .tsv file in the 3.2.1 directory it can be found under another path:

/srv/webanno/repository/project/80/document/346/source/KERN2021_NN_von_Gestalt.tsv

Do you have an idea why WebAnno searches for the projects in the wrong location? I'll try to drop the webanno database and reinitialize it next.

**Comment by reckart** [comment]
@Quadrocompile make sure you copy the WebAnno database contents and WebAnno home folder **as is** from the original installation before starting the new WebAnno version for the first time. If you have already started importing data into the new WebAnno and then try to copy the DB or home folder, you'll run into an inconsistent state (DB does not match home folder content).

Btw. could it be you have the file in two different projects?

**Comment by Quadrocompile** [comment]
I think the problem was caused by an inconsistent database state. I removed WebAnno completely from the system and with the fresh installation and a complete dump of the old database everything seems to be running fine now. Thank you very much for your assistance!
