### ISSUE TITLE
Potential for Question-Answer annotation (eg SQuAD)

### ISSUE THREAD

**Issue by nmstoker** [webanno/webanno#922]
Hello,

This looks like a really interesting annotation tool, so thank you to the authors for the effort put in.

I have a question about how feasible it might be to use WebAnno to annotate "Question and Answer"-style datasets, such as something in the style of SQuAD (https://rajpurkar.github.io/SQuAD-explorer/)

I'm only just figuring out my way round WebAnno, so I apologise if this is obvious (_either obviously possible or obviously not possible!_)  The general way it works with SQuAD datasets is the document (typically a paragraph) has several questions added to it and then the spans within the document that correspond to the answer are marked up by people to form the ground truth.

Is this feasible with WebAnno?  I see I can create a custom Layer (eg "Question") and then create a tagset that uses a string primitive, so users could select a span and add an open ended question, but ideally I'd have the questions be added first and then pass those round for annotation - the way described before would need the annotator to also enter the question at the point they annotate it.

Another way I suppose might be to just prepend the questions in a visually obvious way to the paragraph documents, numbering them and then create a custom Layer that let's people select a span and give it a feature of 1,2,3,4 etc corresponding to the question it answers. Then the data could be exported and processed into the desired format.

Any thoughts/recommendations on the best approach to take with this?

Many thanks
Neil

**Comment by reckart** [comment]
So I understand that you annotate answers with questions, right? I.e. the question is the label to the annotated answer span. So how about you define a tagset which includes all the questions you want to have, create a span layer "Answer" with a String feature "question" to which you assign your question tagset. That way, when users mark up a piece of text and annotate it as "answer, they can choose from one of the pre-existing questions.

The only "problem" is that tagsets are not per document but rather per project. Not sure if that is a problem.

**Comment by nmstoker** [comment]
Thanks for the quick follow up @reckart

Effectively yes it is annotating answers with questions, so your method could work.

You mention the tagset is per project - I'll have to see how it works with a practice. Sounds like I'd just have to deal with it, but ideally the questions would be per document (since each document could be on a slightly diffident topic and would therefore be helpful to avoid people annotating a question that was really meant for another document)

My second approach might be more practical with regard to linking the questions to a specific document. I'll give both a go and see how they compare.

Many thanks,
Neil
