### ISSUE TITLE
Add .gitattributes file

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#94]
Add .gitattributes file to avoid whitespace problem on commit. 

Cf. https://help.github.com/articles/dealing-with-line-endings/

**Comment by reckart** [comment]
@seyyaw @aakashysharma @sholschneider - All committers, please make sure to update your local clones with the proper line endings as described here:

https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings

**Comment by aakashysharma** [comment]
I did that, no changes detected. Probably because when I set up .gitattributes file, it detected and changed 24 files in the commit. https://github.com/webanno/webanno/commit/a2132c2de96ebdbfa7205052b2e7c896d05e82ed

**Comment by reckart** [comment]
I've just updated to the latest changes and immediately after the update, git marked the ProjectConstraintsPanel that was touched in c80b002b030f8f641c13c5f19e7a977f9089ed64  as dirty - no changes, apparently only line endings. I used a hex editor to investigate and some reason git appears to have converted it to Windows line endings on checkout (0D 0A).

**Comment by reckart** [comment]
I have changed a global setting as recommended in https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings 

    $ git config --global core.autocrlf input
    # Configure Git on OS X to properly handle line endings

After that I refreshed the local files

    git rm --cached -r .
    git reset --hard

That seems to have fixed it for me.
