### ISSUE TITLE
"Concurrency" issues between project admin and annotators

### ISSUE THREAD

**Issue by jrouces** [webanno/webanno#952]
Hi,

I have a huge number of documents (10k) and annotators (11), so going through the lock-unlock table in monitoring mode takes a while (I am making a JS script for this but still can take some time). Is there some way to prevent the users from starting to annotate from the time when I upload the documents until the time I have finished my pass over the table? It seems like if someone logs in and opens a document,  I can no longer block that document for that user.

If I unassign a user for the project, then he does not show up in the table and I cannot make the assignment. So I am thinking about something like preventing them from logging in, but not modify the user account per se.

I could use some ip filtering but I am not the admin of the machine so it would be very cumbersome and complicated. I wonder if there is an easier way.

Best,
Jacobo.

**Comment by reckart** [comment]
Related to https://github.com/webanno/webanno/issues/90

**Comment by jrouces** [comment]
Hi,

I am trying to do what you suggested, but when adding documents, the table annotation_document is not updated. I am not sure under which circumstances they are added. When I open one with a user, the row for that document and user appears, but I also have rows for documents from previous upload batches that I have never opened, so I guess there may be other process updating the table.

I could try to create the rows myself but I think it is easy that I don't do it exactly the same way webanno does, which could mess up something.

Is there a deterministic rule to know how and when the table is updated with rows for every document,user pair?

**Comment by reckart** [comment]
Adding a document does not trigger adding entries to the `annotation_document` table. The `annotation_document` table tracks the status of a particular user's work. It would not be sufficient to add entries when a document is added/removed, but also when annotators are added/removed.

For that reason, I'm afraid the entries in the annotation document table are created lazily and different parts of the code force the creation of an entry while others do not. 

In theory, an entry is created whenever an annotator starts working on a document or when the document is locked for a particular user.

**Comment by jrouces** [comment]
Hi,

Ok thanks.

Then I will try to create the rows myself, but could you tell me if you think this can mess up something, or if there is some sort of redundancy that I should update too?

The field sentenceAccessed seems to be always zero, is that correct?

What is the difference between timestamp and updated?

I assume I can obtain the annotation_document.document int from source_document.id and that source_document is updated when docs are uploaded, but please tell me if I am missing something.

Thanks in advance.

/Jacobo.

**Comment by jrouces** [comment]
Or if you could point out to the portion of the Java code that does edits the SQL when the server side receives a command from the front-end when you use the GUI table in Monitoring. I guess I just have to replicate that.

Otherwise would it be a better idea that I go back to plan A and I try to mess with the front end, but injecting some javascript in the browser console instead of the too-hig-end simulation of the click that needed to wait for the table to reload?

**Comment by reckart** [comment]
The following fields are mandatory in `annotation_document`.

* `id` (actually this is auto-generated - do not fill it in)
* `name`
* `state`
* `user`
* `document` (points to `source_document` table)
* `project` (points to `project` table and must match the ID of the project which is associated with the `document` in `source_document`)

The other fields are purely informational (at least for the time being).

**Comment by reckart** [comment]
A future WebAnno version will likely drop the `project` column in `annotation_document` because it is redundant.

**Comment by jrouces** [comment]
Ok, thanks. It seems it worked, although at the end I used the update because the NEW rows had appeared. I guess I did something in the way that created them (I suspect it is because I manually locked each doc for a single user).

**Comment by reckart** [comment]
Glad it works for you now. Closing the issue then.
