### ISSUE TITLE
Constraints reading/writing should use UTF-8

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#96]
With issue #95 we figured out there was problem if the constraint files were not encoded with ANSI, it'd cause an error while uploading.

Hence, for reading(importing) /writing(exporting) constraint files should be done in UTF-8.

**Comment by aakashysharma** [comment]
@reckart For ANSI encoded files, they are passed as it is. ANSI encoding usually doesn't clash with UTF-8 encoding. I believe if user can see that contents are correct in file, I'm sure it'd work in constraints (unless you deliberately encode a UTF-8 file into ANSI and make "diamond" characters).

The constraints are always read as "UTF-8" from repository. While importing, they are simply copied (if no errors occur in parsing, it can happen if you force German characters into ANSI encoding)

```
@Override
    public String readConstrainSet(ConstraintSet aSet)
        throws IOException
    {
        String constraintRulesPath = dir.getAbsolutePath() + PROJECT + aSet.getProject().getId()
                + CONSTRAINTS;
        String filename = aSet.getId() + ".txt";
        String data = FileUtils.readFileToString(new File(constraintRulesPath, filename), "UTF-8");

```

I am worried that forcing might end up as weird characters like this http://www.mkyong.com/java/how-to-write-utf-8-encoded-data-into-a-file-java/

Currently I don't see a problem scenario. Please explain if you have one.

**Comment by reckart** [comment]
If I choose to import an UTF-8 encoded constraints file containing e.g. umlauts in a comment or feature value, then I should be able to do that. 
The file should display the umlauts properly in the UI. 
When the constraints are evaluated, umlauts in the feature values should be properly compared against. When I export it again, the exported file should still have the same umlauts.

WebAnno should expect UTF-8 everywhere and enforce its use everywhere.

Also, in general anything that WebAnno talks to should be configured for UTF-8:

The browser we use should correctly detect that the page is in UTF-8 and expects UTF-8 data. I believe the latter is something that might have to be configured in the settings of the servlet container (e.g. Tomcat), but it is possibly the default there anyway. Also, the database schema should be configured to use UTF-8 as a default encoding.

**Comment by reckart** [comment]
I didn't quite understand your comment with regards to http://www.mkyong.com/java/how-to-write-utf-8-encoded-data-into-a-file-java/

**Comment by aakashysharma** [comment]
I meant, characters turning into different ones while transforming them into UTF-8. Like "??" turned into some weird characters. 

"If I choose to import an UTF-8 encoded constraints file containing e.g. umlauts in a comment or feature value, then I should be able to do that. The file should display the umlauts properly in the UI. "
This works in current version.

Question: Should it throw an error/reject completely if a [constraint] file [while importing through Constraints tab in project settings] is in something other than UTF-8?

**Comment by reckart** [comment]
> I meant, characters turning into different ones while transforming them into UTF-8. Like "??" turned into some weird characters.

I understood it such that the  ?? he used in the example are placeholders for Asian characters. In the screenshots, he used actual characters.

> Question: Should it throw an error/reject completely if a [constraint] file [while importing through Constraints tab in project settings] is in something other than UTF-8?

If Java encounters a sequence that it illegal in UTF-8 and it thinks it should throw an exception, we should let it, catch it, and display it properly. Otherwise, I don't think we need to do any special checking at the moment.

**Comment by aakashysharma** [comment]
Constraints use UTF-8 for storing files. If a file is damaged outside Webanno, Webanno will not try to repair it. The import may fail!
