### ISSUE TITLE
remote-api for webanno document import /export.

### ISSUE THREAD

**Issue by Anupam02** [webanno/webanno#960]
Hi , Just wanted to check for the remote api's for document  import / export ,  I am looking for an automatic import / export for the documents , in webanno server instead of manually importing the document or manually exporting the documenting after finish .
I have referred to https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/  , but I am not getting any remote api calls for docment import export.

**Comment by reckart** [comment]
For the "source documents":

* https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/#_create_document
* https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/#_read_document

For the annotations per user:

* https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/#_create_annotations
* https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/#_read_annotations

For the curated annotations:

* https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/#_create_curations
* https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/#_read_curations

**Comment by Anupam02** [comment]
Thanks @reckart  :)  one more query regarding remote api for webook for status change .. I have gone through https://github.com/webanno/webanno/issues/792 , and didn't find it here (https://github.com/webanno/webanno/issues/455 )

**Comment by reckart** [comment]
You need to add something like this to the `settings.properties` file:

```
webhooks.globalHooks[0].url=http://host/your-notification-rest-service
webhooks.globalHooks[0].topics[0]=DOCUMENT_STATE
webhooks.globalHooks[0].topics[1]=ANNOTATION_STATE
webhooks.globalHooks[0].topics[2]=PROJECT_STATE
```

If you use https, you may also have to add

```
webhooks.globalHooks[0].verify-certificates=false
```

**Comment by Anupam02** [comment]
Thannks @reckart  for the info,  could you please let me know if value of webhooks.globalHooks[0].url  will be my own rest service notification api, if you could provide me an example that would be great.
webhooks.globalHooks[0].url=http://host/your-notification-rest-service

**Comment by reckart** [comment]
See the unit test for the webhooks:

https://github.com/webanno/webanno/blob/ee661681d858e1ea78340753d1f85361b189d8c9/webanno-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookServiceTest.java#L112-L158

**Comment by Anupam02** [comment]
thanks @reckart   , got it  :+1:
