### ISSUE TITLE
description The request sent by the client was syntactically incorrect.

### ISSUE THREAD

**Issue by Anupam02** [webanno/webanno#968]
HI , 
  while going for login page , after providing credentials , getting a HTTP status code 400 , for webanno .
the url is going to /login.html?-1.IFormSubmitListener-loginForm  , 
by searching for the error ( http://forum.spring.io/forum/spring-projects/web/90910-spring-the-request-sent-by-the-client-was-syntactically-incorrect , https://stackoverflow.com/questions/17792274/spring-mvc-error-400-the-request-sent-by-the-client-was-syntactically-incorrect )  it seems like this error is coming from the code.

Just wanted to check if there is any chance there is any problem from the code side as in the error seaches I could see a lot of spring mvc reference.
Below is the errror , I am getting .
Thanks in advance.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
HTTP Status 400 - Origin does not correspond to request
type Status report

message Origin does not correspond to request

description The request sent by the client was syntactically incorrect.

Apache Tomcat/8.0.32 (Ubuntu)
+++++++++++++++++++++++++++++++++++++++++++++

**Comment by tmandekic** [comment]
We deployed webanno inside Docker container. Added ssl certificate. It throws the same error as above. When we remove ssl,  it works. 
Do you have any solution for that?

**Comment by reckart** [comment]
No idea... if you find a solution, please let us know,

**Comment by cyplas** [comment]
I'm also getting this error, in a thereby failed attempt to upgrade WA from 3.2.4 to 3.3.0.

In catalina.out, I'm getting:

```
2019-02-22 11:32:51 ERROR [SYSTEM] ErrorPageFilter - Cannot forward to error page for request [/login.html] as the response has already been committed. As a result, the response may have the wrong status code. If your application is running on WebSphere Application Server you may be able to resolve this problem by setting com.ibm.ws.webcontainer.invokeFlushAfterService to false
```

Initial googling suggests the problem may be at Java level (https://stackoverflow.com/questions/37240513/o-s-boot-context-web-errorpage-cannot-forward-to-error-page-for-request-as). I wonder why this doesn't seem to be affecting all users ... Our server is dedicated to webanno and set up according to your admin guide (and without websphere). Any tips would be appreciated.

**Comment by reckart** [comment]
Please try clearing your browser cache.

If you are using the JAR version, did you clear out the Winstone folder before starting the new version as described in the upgrade instructions?

----
### Clean working folder

clean up the temporary installation before running the new version:

* On OS X: `rm -R "$TMPDIR/winstoneEmbeddedWAR"`
* On Linux: `rm -R /tmp/winstoneEmbeddedWAR`
* On Windows: `remove the winstoneEmbeddedWAR that should be somewhere under C:\Users\<username>\AppData\Local\Temp`

start the new version

**Comment by reckart** [comment]
@cyplas which Tomcat and Java version are you using?

**Comment by cyplas** [comment]
Thanks for the quick reply. Unfortunately, clearing the cache (or trying another browser) didn't help.

We're using the WAR version, on ubuntu 16.04, java 1.8.0_44, tomcat 8.0.32. I've been following the upgrade installations in your docs (delete, wait, stop, replace, start).

**Comment by reckart** [comment]
Hm. Should work. Maybe try upgrading to Tomcat 8.5.x?

**Comment by reckart** [comment]
Also wouldn't hurt upgrading to the latest Java 8 bugfix release.

**Comment by cyplas** [comment]
Upgrading Ubuntu to 18.04 and with it tomcat and java didn't help. But it seems like we've gotten past our problem, so I'm reporting here, in case it is of wider use:

The problem seems to have been due to some subtle combination of factors, such that the error would get triggered when using WA 3.3 and proxy and khtml-based browser (so, ironically, chrome or safari, but not firefox, lynx or w3m). (And maybe ssl, I'm not sure.)

My colleague solved this by cutting out one "step" in the configs:

```
# on webanno server
<         ProxyPassReverse http://localhost/webanno
---
>         ProxyPassReverse http://www.clarin.si/webanno
>           Header set Access-Control-Allow-Origin "*"
>           Header set Access-Control-Allow-Credentials "true"

```

```
# on proxy server
<         ProxyPass         /webanno http://cl-webanno.ijs.si/webanno                                                                                                                                                                                                          
---                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
>       ProxyPass         /webanno ajp://cl-webanno.ijs.si:18009/webanno timeout=1200
```

**Comment by cyplas** [comment]
> @cyplas would you like to create a PR adding this to the documentation?

I don't think that's a great idea, because I don't fully understand the solution. :) It was my colleague's magic.

**Comment by reckart** [comment]
@cyplas Let us know if your colleague cares to contribute an update to the documentation :)
