### ISSUE TITLE
llegalArgumentException: CAS type [webanno.custom.MetaData] does not have a feature called [Clause_name]

### ISSUE THREAD

**Issue by Anupam02** [webanno/webanno#971]
HI ,
While uploading documents I am  getting llegalArgumentException: CAS type [webanno.custom.MetaData] does not have a feature called [Clause_name] , 
just upgraded it from 3.2 to 3.4 and did project import, is it because of the way we did imported project?

**Comment by reckart** [comment]
How did you do the import?

**Comment by Anupam02** [comment]
I exported the projects and then did project import from on the webanno 3.4.1 , it imported everything from layers and tagsets that was there before on webanno 3.2.x

**Comment by reckart** [comment]
Closing since no further information has been provided.
