### ISSUE TITLE
Sending Post Request.

### ISSUE THREAD

**Issue by Demirrr** [webanno/webanno#972]
Hello,
I would like to send a simple post request in order to create  a new project with a given project name. 
First try:

```
URL = 'http://localhost:8080/api/v2/projects'
dataa={
  "messages": [],
  "body": {
    "name": "Dummy_Name2"
  }
}

r = requests.post(URL, data = dataa,auth=('admin', 'admin'))
```

Output:

```
{'timestamp': 1528204046959, 'status': 415, 'error': 'Unsupported Media Type', 'exception': 'org.springframework.web.HttpMediaTypeNotSupportedException', 'message': "Content type 'application/x-www-form-urlencoded' not supported", 'path': '/api/v2/projects'}
```

Any opinion is appreciated.

**Comment by reckart** [comment]
Content type must be `application/json;charset=UTF-8`.

**Comment by reckart** [comment]
Forget it. Did you have a look at this issue: https://github.com/webanno/webanno/issues/966

Otherwise: access the `<your-webanno-url>/swagger-ui.html` and test-drive the remote API calls from there. It even generates curl commands like this for you:

`curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: application/json' {"type":"formData"} 'https://<host>/webanno/api/v2/projects?name=test%20project'`

**Comment by Demirrr** [comment]
Firstly, @reckart thank you for quick respond. I am familiar with swagger. However curl which is created by swagger does not help me as well. Please consider the follow scenario.

![screenshot from 2018-06-05 15-54-44](https://user-images.githubusercontent.com/13405667/40980812-a369577e-68d9-11e8-9910-da1cc8789a93.png)

It works pretty well. As you see in the image that Dummy_Project is created. 
Thereafter, please look at the image below.
![screenshot from 2018-06-05 16-02-53](https://user-images.githubusercontent.com/13405667/40980954-0326db8c-68da-11e8-9d30-0e2f6179c721.png)

Ps: All get requests work like a charm.

**Comment by reckart** [comment]
The `Content-Type` header needs to specify a multipart boundary, e.g.

```
curl -u username:password -X POST --header 'Content-Type: multipart/form-data; boundary=---multipart-boundary-RANDOMSTRING'  --header 'Accept: application/json' 'http://localhost:8080/webanno-webapp/api/v2/projects?name=test'
```

then you get sensible output:

```
{"messages":[],"body":{"id":260,"name":"test"}}
```

**Comment by reckart** [comment]
Btw. the better alternative would be this

> curl -u username:password -F name=test  --header 'Accept: application/json' 'http://localhost:8080/webanno-webapp/api/v2/projects'

Swagger UI unfortunately doesn't generate good curl commands for these form posts.

**Comment by reckart** [comment]
I'm going to upgrade Swagger/Springfox in WebAnno 3.5.0, but the problem with the badly generated curl commands remains.

**Comment by reckart** [comment]
Turns out I can tweak the metadata for the Swagger UI so that it generates better curl.

**Comment by rbhambriiit** [comment]
Working Python solution:

```
import requests
project_name = 'api_project1'
create_project_url = "http://??.??.???:?????/api/v2/projects?name=" + project_name
headers = { "content-type": "multipart/form-data; boundary=---multipart-boundary-RANDOMSTRING" }
response = requests.post(create_project_url, auth=('???', '???'), headers=headers)
create_project = response.json()

```
