### ISSUE TITLE
webanno.constraints.grammar folder missing

### ISSUE THREAD

**Issue by j-lnaddef** [webanno/webanno#981]
I get compilations error when trying to compile from the sources, I get the following import error at several places : `package de.tudarmstadt.ukp.clarin.webanno.constraints.grammar does not exist`, and indeed I cannot see any grammar folder in the sources.
Am I missing something?

**Comment by reckart** [comment]
Try a "mvn clean install" on the command line and/or make sure you IDE supports the ph-javacc-maven-plugin. If you use Eclipse, it should normally offer to install the required plugins when you import the project.

**Comment by j-lnaddef** [comment]
I was using Netbeans but I just tried Eclipse just to be sure. I get the same errors just by importing the project : 
![webanno_comp_error](https://user-images.githubusercontent.com/9340154/41180968-ef90e26e-6b24-11e8-8df8-fa21da8a929a.png)

Is `de.tudarmstadt.ukp.clarin.webanno.constraints.grammar` an external dependency? I was expecting to see a `grammar` folder in the `webanno-constraints` project, next to the `evaluator`, `model` and `visitor` folders

**Comment by reckart** [comment]
The files are generated by the ph-javacc-maven-plugin and the build-helper-maven-plugin adds the folders with the generated files as source folders. If your IDE does not support these Maven plugins, you may run "mvn clean install" on the command line to generate the files and then manually add the respective folders as source folders in your IDE. For details, see the pom.xml file in the constraints module.

**Comment by j-lnaddef** [comment]
It worked using `mvn clean install` from the command line, thank you for your help!
