### ISSUE TITLE
Automation - process new documents

### ISSUE THREAD

**Issue by j-lnaddef** [webanno/webanno#987]
I cannot say if this is a missing feature or if I just could not find it.

When I start a new automation, it makes the predictions for all the documents already added to the project : this is working fine. What I do not find is **how to have the predictions made for new documents** I want to add after training the automation?

The only solution I have found until now is re-training the classifier each time I add a new document, which is obviously wrong.
What am I missing?

**Comment by seyyaw** [comment]
@j-lnaddef Yes, you are right.  We need to have a possibility to (auto) tag new documents. I will address this issue as soon as I have time.
Thanks

**Comment by reckart** [comment]
No further updates to the automation code are planned.
