### ISSUE TITLE
Cannot create chain layer

### ISSUE THREAD

**Issue by camielcolruyt** [webanno/webanno#989]
When I try to 'Create' a layer of type chain, the following error message pops up and the layer is not created: 

`Error: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : de.tudarmstadt.ukp.clarin.webanno.model.AnnotationFeature.layer -> de.tudarmstadt.ukp.clarin.webanno.model.AnnotationLayer; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : de.tudarmstadt.ukp.clarin.webanno.model.AnnotationFeature.layer -> de.tudarmstadt.ukp.clarin.webanno.model.AnnotationLayer`

See also screenshot below. There is no problem creating span or relation layers. This happens on the standalone version 3.4.2. Deleting the .webanno folder and allowing the application to rebuild it did not help, nor did restarting the computer.

Maybe I'm missing something, but I am effectively locked out of using chain layers.

Exact build: 3.4.2 (2018-06-04 19:36:56, build 756461b3251e8cfd7a086464cdc8a560479852c2), Windows 10.

![webanno_error_ss](https://user-images.githubusercontent.com/40267220/41410886-348077da-6fdb-11e8-9fc8-f07f22d5650f.png)

**Comment by reckart** [comment]
From the error message, it looks like a bug. Will look into it.
