### ISSUE TITLE
Constraints for Link features

### ISSUE THREAD

**Issue by czulo** [webanno/webanno#994]
Hi,

I have set up a frame annotation project with the frame layer as central layer. This frame layer has, amongst others, the following features:

- String: N_Inc
- Link: FE

The Link feature links to the type webanno.custom.FE which has no further features, it is basically just a span annotation. Both features are assigned the same Tagset which lists all possible frame elements from the FrameNet database. I can use the Constraint mechanism to set core values for the N_Inc feature successfully by means of such constraints as

Name = "Reading_activity" -> N_Inc = "Reader";

But when I use the exact same syntax for the FE feature, nothing happens. How do I address the Tagset for the Link feature FE correctly?

Many thanks,
Oliver

**Comment by reckart** [comment]
Can you say in human language what constraint you want to express?

**Comment by czulo** [comment]
For each frame, a number of frame elements are described. For the frame Reading_activity (invoked by the "semantic predicate"), the core elements ("arguments") are Reader, Text and Topic. Potentially, however, frame elements such as Time, Means etc. can also appear. So my constraint should push the core elements to the top of the list.

I can do this for the String feature N_Inc, but for the Link feature FE which is assigned the exact same Tagset (i.e. the list of all potential frame element names), this does not seem to work.

Hope this helps!

**Comment by reckart** [comment]
I believe your case is covered by the current [functionality](https://webanno.github.io/webanno/releases/3.4.2/docs/user-guide.html#_constraints_for_slot_features).

I guess, it should look something like this in your case:

```
SemPred {
  senseId = "Reading_activity" ->
    // core roles (slots for them appear automatically)
    arguments.role = "Reader" (!) | arguments.role = "Text" (!) | arguments.role = "Topic" (!) |
    // non-core roles (shown at the top of the list, but no slots are added automatically)
    arguments.role = "Time" | arguments.role = "Means";
  // .. other senses
}
```

**Comment by czulo** [comment]
Hi Ricardo,

in fact it does! The problem was in the way Link features are defined and the documentation wasn't explicit about that, I had to infer it from there. So, for a string feature it is enough to say 

Name = "Reading_activity" -> N_Inc = "Reader";

but for the Link feature FE you have to say

Name = "Reading_activity" -> FE.role = "Reader";

i.e. I had to add the ".role" at the end of the feature to address the tagset. Maybe you could make this explicit somewhere in the documentation? Reading through the example, I thought that "role" was just another feature explicitely defined on the "argument" level...

But it works now! :)

- Oliver

**Comment by reckart** [comment]
@czulo I have added a note to the documentation :) Thanks! Great it works for you now.
