### ISSUE TITLE
role_remote not coming in webanno 3.4.2

### ISSUE THREAD

**Issue by Anupam02** [webanno/webanno#999]
Hello, I just upgraded to webanno 3.4.2 and in roles role_remote is not coming..
can someone please help me,
I have upgraded it from webanno 3.3.5 , 
and upgraded 3.3.5 from 3.3.2

**Comment by reckart** [comment]
The system property `webanno.remote-api.enable` needs to be set to `true`. Mind that this setting is not made in the `settings.properties` file but e.g. at the level of your Tomcat starting script (usually `JAVA_OPTS`) if your are using the WAR version on on the command line using `-Dwebanno.remote-api.enable=true` if you are using the JAR version.

**Comment by reckart** [comment]
Btw. WebAnno 3.4.3 has just been released and fixes a bug which sometimes renders the curation page inaccessible. So best upgrade again ;)

**Comment by reckart** [comment]
Since there has been no further feedback on this question, I assume it has been resolved.

**Comment by Anupam02** [comment]
Thanks Richard, it has been resolved, sorry for not acknowledging.
